import { Injectable } from "@nestjs/common";
import { Prisma } from "../generated/prisma/client.js";
import type { TrustedCompanyActorContext } from "../core-controls/trusted-context.js";
import { DatabaseService } from "../database/database.service.js";

type Kind = "SALE" | "PURCHASE" | "EXPENSE" | "OBLIGATION" | "OTHER";
type Query = Readonly<{ from?: Date; to?: Date; businessMonths: readonly string[]; kinds: readonly Kind[]; supplierIds: readonly string[]; categoryIds: readonly string[]; statuses: readonly ("POSTED" | "CANCELLED")[]; q?: string }>;
const PAGE_SIZE = 500;
@Injectable()
export class InvoiceRegisterService {
  constructor(private readonly db: DatabaseService) {}
  async workspace(context: TrustedCompanyActorContext, query: Query) {
    return this.db.inTenantTransaction(context.tenantId, async (tx) => {
      const where: Prisma.FinanceJournalEntryWhereInput = { tenantId: context.tenantId, companyId: context.companyId, status: "POSTED", sourceType: { not: "vault_transfer" }, ...(dateFilter(query) ? { businessDate: dateFilter(query)! } : {}), ...(query.q ? { OR: [{ sourceReference: { contains: query.q, mode: "insensitive" } }, { description: { contains: query.q, mode: "insensitive" } }] } : {}) };
      const [entries, suppliers, categories] = await Promise.all([
        tx.financeJournalEntry.findMany({ where, orderBy: [{ businessDate: "desc" }, { postedAt: "desc" }], take: PAGE_SIZE + 1, select: { id: true, sourceType: true, sourceReference: true, businessDate: true, description: true, postedAt: true, lines: { select: { debitAmount: true } }, outflowDocument: { select: { id: true, documentNumber: true, kind: true, settlementKind: true, status: true, supplierInvoiceDate: true, grossAmount: true, netAmount: true, vatAmount: true, notes: true, recurringExpenseProfileId: true, batch: { select: { batchNumber: true } }, supplier: { select: { id: true, nameAr: true, nameEn: true } }, category: { select: { id: true, nameAr: true, nameEn: true } } } }, dailySalesClosing: { select: { id: true, documentNumber: true, status: true, grossAmount: true, netAmount: true, vatAmount: true, notes: true } }, supplierDuePayment: { select: { id: true, amount: true, due: { select: { supplier: { select: { id: true, nameAr: true, nameEn: true } }, category: { select: { id: true, nameAr: true, nameEn: true, kind: true } } } } } }, inclusiveLoan: { select: { id: true, originalAmount: true, notes: true } }, inclusiveLoanPayment: { select: { id: true, amount: true, loan: { select: { sourceDocumentNumber: true, notes: true } } } } } }),
        tx.financeSupplier.findMany({ where: { tenantId: context.tenantId, companyId: context.companyId, status: "ACTIVE" }, orderBy: { nameAr: "asc" }, take: 1000, select: { id: true, nameAr: true, nameEn: true } }),
        tx.financeCategory.findMany({ where: { tenantId: context.tenantId, companyId: context.companyId, status: "ACTIVE", isPosting: true }, orderBy: { nameAr: "asc" }, take: 500, select: { id: true, nameAr: true, nameEn: true } }),
      ]);
      const records = entries.map((entry) => mapEntry(entry)).filter((item) => (!query.kinds.length || query.kinds.includes(item.kind)) && (!query.supplierIds.length || (item.supplier !== null && query.supplierIds.includes(item.supplier.id))) && (!query.categoryIds.length || (item.category !== null && query.categoryIds.includes(item.category.id))) && (!query.statuses.length || query.statuses.includes(item.status)));
      const summary = records.reduce((total, item) => ({ documentCount: total.documentCount + 1, salesCount: total.salesCount + Number(item.kind === "SALE"), purchaseCount: total.purchaseCount + Number(item.kind === "PURCHASE"), expenseCount: total.expenseCount + Number(item.kind === "EXPENSE"), obligationCount: total.obligationCount + Number(item.kind === "OBLIGATION"), otherCount: total.otherCount + Number(item.kind === "OTHER"), paidCount: total.paidCount + Number(item.settlementKind === "PAID"), payableCount: total.payableCount + Number(item.settlementKind === "PAYABLE"), gross: total.gross.plus(item.grossAmount), net: total.net.plus(item.netAmount), vat: total.vat.plus(item.vatAmount) }), { documentCount: 0, salesCount: 0, purchaseCount: 0, expenseCount: 0, obligationCount: 0, otherCount: 0, paidCount: 0, payableCount: 0, gross: new Prisma.Decimal(0), net: new Prisma.Decimal(0), vat: new Prisma.Decimal(0) });
      return { companyId: context.companyId, appliedPeriod: { fromBusinessDate: query.from ? dateValue(query.from) : null, toBusinessDate: query.to ? dateValue(query.to) : null, businessMonths: [...query.businessMonths] }, summary: { documentCount: summary.documentCount, salesCount: summary.salesCount, purchaseCount: summary.purchaseCount, expenseCount: summary.expenseCount, obligationCount: summary.obligationCount, otherCount: summary.otherCount, paidCount: summary.paidCount, payableCount: summary.payableCount, grossAmount: summary.gross.toFixed(4), netAmount: summary.net.toFixed(4), vatAmount: summary.vat.toFixed(4) }, filters: { suppliers, categories }, records: records.slice(0, PAGE_SIZE), hasMore: entries.length > PAGE_SIZE };
    });
  }
}
function mapEntry(entry: any) {
  const movement = entry.lines.reduce((total: Prisma.Decimal, line: { debitAmount: Prisma.Decimal }) => total.plus(line.debitAmount), new Prisma.Decimal(0)); const outflow = entry.outflowDocument; const sales = entry.dailySalesClosing; const duePayment = entry.supplierDuePayment;
  if (outflow) return { id: outflow.id, source: "OUTFLOW_DOCUMENT" as const, sourceType: entry.sourceType, documentNumber: outflow.documentNumber, businessDate: entry.businessDate, supplierInvoiceDate: outflow.supplierInvoiceDate, kind: outflow.kind as Kind, settlementKind: outflow.settlementKind, status: outflow.status, supplier: outflow.supplier, category: outflow.category, grossAmount: outflow.grossAmount.toFixed(4), netAmount: outflow.netAmount.toFixed(4), vatAmount: outflow.vatAmount.toFixed(4), journalEntryId: entry.id, batchNumber: outflow.batch?.batchNumber ?? null, notes: outflow.notes, recurring: outflow.recurringExpenseProfileId !== null, createdAt: entry.postedAt };
  if (sales) return { id: sales.id, source: "DAILY_SALES" as const, sourceType: entry.sourceType, documentNumber: sales.documentNumber, businessDate: entry.businessDate, supplierInvoiceDate: null, kind: "SALE" as Kind, settlementKind: "PAID" as const, status: sales.status === "POSTED" ? "POSTED" as const : "CANCELLED" as const, supplier: null, category: null, grossAmount: sales.grossAmount.toFixed(4), netAmount: sales.netAmount.toFixed(4), vatAmount: sales.vatAmount.toFixed(4), journalEntryId: entry.id, batchNumber: null, notes: sales.notes, recurring: false, createdAt: entry.postedAt };
  if (duePayment) return { id: duePayment.id, source: "SUPPLIER_DUE_PAYMENT" as const, sourceType: entry.sourceType, documentNumber: entry.sourceReference, businessDate: entry.businessDate, supplierInvoiceDate: null, kind: duePayment.due.category?.kind === "PURCHASE" ? "PURCHASE" as Kind : "EXPENSE" as Kind, settlementKind: "PAID" as const, status: "POSTED" as const, supplier: duePayment.due.supplier, category: duePayment.due.category, grossAmount: duePayment.amount.toFixed(4), netAmount: duePayment.amount.toFixed(4), vatAmount: "0.0000", journalEntryId: entry.id, batchNumber: null, notes: entry.description, recurring: false, createdAt: entry.postedAt };
  if (entry.inclusiveLoan) return generic(entry, "LOAN_OPENING", "OBLIGATION", entry.inclusiveLoan.originalAmount, entry.inclusiveLoan.notes);
  if (entry.inclusiveLoanPayment) return generic(entry, "LOAN_REPAYMENT", "OBLIGATION", entry.inclusiveLoanPayment.amount, entry.inclusiveLoanPayment.loan.notes);
  return generic(entry, "JOURNAL", "OTHER", movement, entry.description);
}
function generic(entry: any, source: "LOAN_OPENING" | "LOAN_REPAYMENT" | "JOURNAL", kind: Kind, value: Prisma.Decimal, notes: string | null) { return { id: entry.id, source, sourceType: entry.sourceType, documentNumber: entry.sourceReference, businessDate: entry.businessDate, supplierInvoiceDate: null, kind, settlementKind: null, status: "POSTED" as const, supplier: null, category: null, grossAmount: value.toFixed(4), netAmount: value.toFixed(4), vatAmount: "0.0000", journalEntryId: entry.id, batchNumber: null, notes, recurring: false, createdAt: entry.postedAt }; }
function dateFilter(query: Query): Prisma.DateTimeFilter | undefined { if (query.businessMonths.length) return { in: query.businessMonths.flatMap((month) => { const [year, value] = month.split("-").map(Number); const count = new Date(Date.UTC(year!, value!, 0)).getUTCDate(); return Array.from({ length: count }, (_, index) => new Date(Date.UTC(year!, value! - 1, index + 1))); }) }; return query.from || query.to ? { ...(query.from ? { gte: query.from } : {}), ...(query.to ? { lte: query.to } : {}) } : undefined; }
function dateValue(value: Date) { return value.toISOString().slice(0, 10); }
