-- HR data is tenant-owned even when it also belongs to a company.  Keep the
-- database boundary aligned with DatabaseService.inTenantTransaction so an
-- omitted application predicate cannot cross a tenant boundary.
ALTER TABLE "HrEmployee" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployee" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeePromotion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeePromotion" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeLeave" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeLeave" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeDocumentBlob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeDocumentBlob" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeDocument" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeDocument" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeDocumentVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeDocumentVersion" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeLetter" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeLetter" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeService" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeService" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeFinancialMovement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeFinancialMovement" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrFinalSettlement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrFinalSettlement" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrFinalSettlementRecovery" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrFinalSettlementRecovery" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrFinalSettlementPayment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrFinalSettlementPayment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrFinalSettlementPaymentAllocation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrFinalSettlementPaymentAllocation" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeAdvance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeAdvance" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeAdvancePayoutAllocation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeAdvancePayoutAllocation" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeAdvanceSettlement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeAdvanceSettlement" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeAdvanceDeferral" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeAdvanceDeferral" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeAdministrativeDeduction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeAdministrativeDeduction" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeAdministrativeDeductionAction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeAdministrativeDeductionAction" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeCompensationProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrEmployeeCompensationProfile" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrCompensationPolicy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrCompensationPolicy" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrCompensationPolicyVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrCompensationPolicyVersion" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrPayrollRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrPayrollRun" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrPayrollLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrPayrollLine" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrPayrollAdvanceApplication" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrPayrollAdvanceApplication" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrPayrollAdministrativeDeductionApplication" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrPayrollAdministrativeDeductionApplication" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrPayrollPayment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrPayrollPayment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "HrPayrollPaymentAllocation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HrPayrollPaymentAllocation" FORCE ROW LEVEL SECURITY;

CREATE POLICY "HrEmployee_tenant_isolation" ON "HrEmployee" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrEmployeePromotion_tenant_isolation" ON "HrEmployeePromotion" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrEmployeeLeave_tenant_isolation" ON "HrEmployeeLeave" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrEmployeeDocumentBlob_tenant_isolation" ON "HrEmployeeDocumentBlob" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrEmployeeDocument_tenant_isolation" ON "HrEmployeeDocument" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrEmployeeDocumentVersion_tenant_isolation" ON "HrEmployeeDocumentVersion" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrEmployeeLetter_tenant_isolation" ON "HrEmployeeLetter" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrEmployeeService_tenant_isolation" ON "HrEmployeeService" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrEmployeeFinancialMovement_tenant_isolation" ON "HrEmployeeFinancialMovement" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrFinalSettlement_tenant_isolation" ON "HrFinalSettlement" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrFinalSettlementRecovery_tenant_isolation" ON "HrFinalSettlementRecovery" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrFinalSettlementPayment_tenant_isolation" ON "HrFinalSettlementPayment" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrFinalSettlementPaymentAllocation_tenant_isolation" ON "HrFinalSettlementPaymentAllocation" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrEmployeeAdvance_tenant_isolation" ON "HrEmployeeAdvance" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrEmployeeAdvancePayoutAllocation_tenant_isolation" ON "HrEmployeeAdvancePayoutAllocation" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrEmployeeAdvanceSettlement_tenant_isolation" ON "HrEmployeeAdvanceSettlement" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrEmployeeAdvanceDeferral_tenant_isolation" ON "HrEmployeeAdvanceDeferral" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrEmployeeAdministrativeDeduction_tenant_isolation" ON "HrEmployeeAdministrativeDeduction" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrEmployeeAdministrativeDeductionAction_tenant_isolation" ON "HrEmployeeAdministrativeDeductionAction" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrEmployeeCompensationProfile_tenant_isolation" ON "HrEmployeeCompensationProfile" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrCompensationPolicy_tenant_isolation" ON "HrCompensationPolicy" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrCompensationPolicyVersion_tenant_isolation" ON "HrCompensationPolicyVersion" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrPayrollRun_tenant_isolation" ON "HrPayrollRun" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrPayrollLine_tenant_isolation" ON "HrPayrollLine" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrPayrollAdvanceApplication_tenant_isolation" ON "HrPayrollAdvanceApplication" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrPayrollAdministrativeDeductionApplication_tenant_isolation" ON "HrPayrollAdministrativeDeductionApplication" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrPayrollPayment_tenant_isolation" ON "HrPayrollPayment" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY "HrPayrollPaymentAllocation_tenant_isolation" ON "HrPayrollPaymentAllocation" USING ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid) WITH CHECK ("tenantId" = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
