const modules = [
  {id:'command',icon:'⌘',color:'#08744d',ar:'مركز القيادة',en:'Command center',arDescription:'صورة تنفيذية وقرارات اليوم.',enDescription:'Executive view and today’s decisions.',arItems:['النظرة التنفيذية','الأولويات','التنبيهات','موجز النشاط'],enItems:['Executive overview','Priorities','Alerts','Activity brief']},
  {id:'operations',icon:'◫',color:'#176e9e',ar:'العمليات',en:'Operations',arDescription:'المبيعات والمشتريات والمخزون.',enDescription:'Sales, purchasing, and inventory.',arItems:['نظرة التشغيل','المبيعات','المشتريات','الموردون','المخزون والمستودعات','الطلبات'],enItems:['Operations overview','Sales','Purchasing','Suppliers','Inventory & warehouses','Requests']},
  {id:'finance',icon:'▣',color:'#a3532e',ar:'المالية والمحاسبة',en:'Finance & accounting',arDescription:'الفواتير والخزائن والمصروفات.',enDescription:'Invoices, treasury, and expenses.',arItems:['نظرة المالية','الفواتير والمدفوعات','الخزائن والبنوك','المصروفات','الالتزامات والقروض','الحسابات والسجل'],enItems:['Finance overview','Invoices & payments','Treasury & banks','Expenses','Liabilities & loans','Accounts & ledger']},
  {id:'hr',icon:'♙',color:'#bd4778',ar:'الموارد البشرية',en:'Human resources',arDescription:'الموظفون والرواتب والخدمات.',enDescription:'Employees, payroll, and services.',arItems:['نظرة HR','الموظفون','الإجازات والعودة','الرواتب','السلف والخصومات','الإقامات والخدمات'],enItems:['HR overview','Employees','Leave & return','Payroll','Advances & deductions','Residencies & services']},
  {id:'reports',icon:'▥',color:'#876422',ar:'التقارير',en:'Reports',arDescription:'التقارير والضريبة والطباعة.',enDescription:'Reports, tax, printing.',arItems:['نظرة التقارير','التقارير المالية','التقرير الضريبي','Hajri Tax','الطباعة والتصدير'],enItems:['Reports overview','Financial reports','VAT report','Hajri Tax','Print & export']},
  {id:'admin',icon:'⚙',color:'#536b63',ar:'الإدارة',en:'Administration',arDescription:'الشركات والمستخدمون والإعدادات.',enDescription:'Companies, users, and settings.',arItems:['نظرة الإدارة','الشركات','المستخدمون','الأدوار والصلاحيات','الهوية والثيم','النسخ الاحتياطي'],enItems:['Administration overview','Companies','Users','Roles & permissions','Identity & theme','Backup']},
];
const state={language:'ar',theme:'green',step:'modules',moduleId:'command',section:0,lastFocus:null};
const q=(selector)=>document.querySelector(selector); const current=()=>modules.find((module)=>module.id===state.moduleId); const local=(module,suffix='')=>module[`${state.language}${suffix}`];
function updateText(){document.documentElement.lang=state.language;document.documentElement.dir=state.language==='ar'?'rtl':'ltr';q('#language').textContent=state.language==='ar'?'EN':'ع';q('#app-language').textContent=state.language==='ar'?'EN':'ع';document.querySelectorAll('[data-ar]').forEach((element)=>{element.textContent=element.dataset[state.language];});q('#search').placeholder=state.step==='modules'?(state.language==='ar'?'ابحث عن موديول…':'Search a module…'):(state.language==='ar'?'ابحث عن قسم…':'Search a section…');}
function toggleTheme(){state.theme=state.theme==='green'?'classic':'green';document.body.classList.toggle('is-classic',state.theme==='classic');}
function moduleChoice(module){const button=document.createElement('button');button.type='button';button.className='module-card';button.style.setProperty('--module',module.color);button.innerHTML=`<span class="module-icon" aria-hidden="true">${module.icon}</span><span class="module-copy"><strong>${local(module)}</strong><span>${local(module,'Description')}</span></span><span class="module-arrow" aria-hidden="true">←</span>`;button.addEventListener('click',()=>{state.moduleId=module.id;state.step='sections';q('#search').value='';renderLauncher();});return button;}
function sectionChoice(name,index,module){const button=document.createElement('button');button.type='button';button.className='section-choice';button.style.setProperty('--module',module.color);button.innerHTML=`<span class="section-order">${String(index+1).padStart(2,'0')}</span><span><strong>${name}</strong><small>${state.language==='ar'?'فتح القسم':'Open section'}</small></span><span class="section-arrow" aria-hidden="true">←</span>`;button.addEventListener('click',()=>openSection(module.id,index));return button;}
function renderRecent(){const recent=JSON.parse(localStorage.getItem('baseer-shell-recent')||'[]');const items=recent.map((key)=>{const [id,index]=key.split(':');const module=modules.find((entry)=>entry.id===id);return module?{module,index:Number(index)}:null;}).filter(Boolean).slice(0,4);q('#recent').hidden=state.step!=='modules'||items.length===0;if(!items.length)return;q('#recent-list').replaceChildren(...items.map(({module,index})=>{const button=document.createElement('button');button.type='button';button.textContent=`${local(module)} · ${local(module,'Items')[index]}`;button.addEventListener('click',()=>openSection(module.id,index));return button;}));}
function renderLauncher(){const module=current();const sections=local(module,'Items');const query=q('#search').value.trim().toLowerCase();const isModules=state.step==='modules';q('#launcher-path').textContent=isModules?'Baseer ERP':`Baseer ERP ← ${local(module)}`;q('#launcher-title').textContent=isModules?(state.language==='ar'?'ماذا تريد أن تنجز؟':'What do you want to do?'):(state.language==='ar'?`اختر القسم داخل ${local(module)}`:`Choose a section in ${local(module)}`);q('#launcher-intro').textContent=isModules?(state.language==='ar'?'اختر الموديول الذي تريد العمل فيه. تشترك الموديولات في نفس الشركة والبيانات والصلاحيات.':'Choose the module you want to work in. All modules share the same company, data, and permissions.'):(state.language==='ar'?`${local(module,'Description')} بعد الاختيار ستجد الأقسام دائمًا في القائمة الجانبية.`:`${local(module,'Description')} After choosing, sections stay in the module sidebar.`);q('#launcher-back').hidden=isModules;q('#launcher-note').textContent=isModules?(state.language==='ar'?'تظهر الموديولات وفق الصلاحيات.':'Modules are shown according to permissions.'):(state.language==='ar'?'هذه الأقسام ستكون في القائمة الجانبية بعد الدخول، وليست تبويبات.':'These sections become the sidebar after entry, not tabs.');const choices=isModules?modules.filter((entry)=>`${entry.ar} ${entry.en} ${entry.arDescription} ${entry.enDescription}`.toLowerCase().includes(query)):sections.map((name,index)=>({name,index})).filter((entry)=>entry.name.toLowerCase().includes(query));q('#count').textContent=isModules?`${choices.length} / ${modules.length}`:`${choices.length} / ${sections.length}`;q('#choices').replaceChildren(...choices.map((entry)=>isModules?moduleChoice(entry):sectionChoice(entry.name,entry.index,module)));q('#empty').hidden=choices.length!==0;renderRecent();}
function renderSidebar(){const module=current();const items=local(module,'Items');q('#sidebar-title').textContent=local(module);q('#drawer-title').textContent=local(module);const create=(item,index)=>{const button=document.createElement('button');button.type='button';button.className=`nav-item${index===state.section?' active':''}`;button.innerHTML=`<span class="nav-dot" aria-hidden="true"></span><span>${item}</span>`;button.addEventListener('click',()=>openSection(module.id,index));return button;};q('#side-nav').replaceChildren(...items.map(create));q('#drawer-nav').replaceChildren(...items.map(create));q('#crumb').textContent=`Baseer ERP / ${local(module)}`;q('#section-title').textContent=items[state.section];q('#section-description').textContent=local(module,'Description');q('#module-label').textContent=local(module);q('#hero-title').textContent=state.language==='ar'?`مرحبًا بك في ${items[state.section]}`:`Welcome to ${items[state.section]}`;q('#hero-copy').textContent=state.language==='ar'?'الانتقال الرئيسي بين الأقسام هنا، من القائمة الجانبية الخاصة بالموديول.':'Primary section navigation lives here, in the module-specific sidebar.';}
function remember(id,section){const key=`${id}:${section}`;const old=JSON.parse(localStorage.getItem('baseer-shell-recent')||'[]').filter((entry)=>entry!==key);localStorage.setItem('baseer-shell-recent',JSON.stringify([key,...old].slice(0,4)));}
function setRoute(){location.hash=`module=${state.moduleId}&section=${state.section}`;}
function openSection(id,index){state.moduleId=id;state.section=index;remember(id,index);q('#launcher-view').hidden=true;q('#app-view').hidden=false;closeDrawer();renderSidebar();setRoute();}
function startLauncher(){state.step='modules';q('#search').value='';q('#launcher-view').hidden=false;q('#app-view').hidden=true;renderLauncher();}
function parseRoute(){const params=new URLSearchParams(location.hash.slice(1));const id=params.get('module');const index=Number(params.get('section'));if(modules.some((module)=>module.id===id)&&Number.isInteger(index)&&index>=0&&index<current().arItems.length){state.moduleId=id;state.section=index;q('#launcher-view').hidden=true;q('#app-view').hidden=false;renderSidebar();}else startLauncher();}
function openDrawer(){q('#mobile-drawer').classList.add('is-open');q('#mobile-drawer').setAttribute('aria-hidden','false');}function closeDrawer(){q('#mobile-drawer').classList.remove('is-open');q('#mobile-drawer').setAttribute('aria-hidden','true');}
function toggleLanguage(){state.language=state.language==='ar'?'en':'ar';updateText();if(q('#app-view').hidden)renderLauncher();else renderSidebar();}
q('#launcher-back').addEventListener('click',()=>{state.step='modules';q('#search').value='';renderLauncher();});q('#search').addEventListener('input',renderLauncher);q('#language').addEventListener('click',toggleLanguage);q('#app-language').addEventListener('click',toggleLanguage);q('#theme').addEventListener('click',toggleTheme);q('#app-theme').addEventListener('click',toggleTheme);q('#open-modules').addEventListener('click',startLauncher);q('#side-modules').addEventListener('click',startLauncher);q('#hero-modules').addEventListener('click',startLauncher);q('#app-home').addEventListener('click',(event)=>{event.preventDefault();startLauncher();});q('#brand-home').addEventListener('click',(event)=>{event.preventDefault();startLauncher();});q('#mobile-sections').addEventListener('click',openDrawer);q('#close-drawer').addEventListener('click',closeDrawer);q('#drawer-backdrop').addEventListener('click',closeDrawer);window.addEventListener('hashchange',parseRoute);document.addEventListener('keydown',(event)=>{if(event.key==='Escape')closeDrawer();});updateText();parseRoute();
