const modules=[
  {id:'command',icon:'⌘',color:'#08744d',ar:'مركز القيادة',en:'Command center',arDescription:'صورة تنفيذية وقرارات اليوم.',enDescription:'Executive view and today’s decisions.',arItems:['النظرة التنفيذية','الأولويات','التنبيهات','موجز النشاط'],enItems:['Executive overview','Priorities','Alerts','Activity brief']},
  {id:'operations',icon:'◫',color:'#176e9e',ar:'العمليات',en:'Operations',arDescription:'المبيعات والمشتريات والمخزون.',enDescription:'Sales, purchasing, and inventory.',arItems:['نظرة التشغيل','المبيعات','المشتريات','الموردون','المخزون والمستودعات','الطلبات'],enItems:['Operations overview','Sales','Purchasing','Suppliers','Inventory & warehouses','Requests']},
  {id:'finance',icon:'▣',color:'#a3532e',ar:'المالية والمحاسبة',en:'Finance & accounting',arDescription:'الفواتير والخزائن والمصروفات.',enDescription:'Invoices, treasury, and expenses.',arItems:['نظرة المالية','الفواتير والمدفوعات','الخزائن والبنوك','المصروفات','الالتزامات والقروض','الحسابات والسجل'],enItems:['Finance overview','Invoices & payments','Treasury & banks','Expenses','Liabilities & loans','Accounts & ledger']},
  {id:'hr',icon:'♙',color:'#bd4778',ar:'الموارد البشرية',en:'Human resources',arDescription:'الموظفون والرواتب والخدمات.',enDescription:'Employees, payroll, and services.',arItems:['نظرة HR','الموظفون','الإجازات والعودة','الرواتب','السلف والخصومات','الإقامات والخدمات'],enItems:['HR overview','Employees','Leave & return','Payroll','Advances & deductions','Residencies & services']},
  {id:'reports',icon:'▥',color:'#876422',ar:'التقارير',en:'Reports',arDescription:'التقارير والضريبة والطباعة.',enDescription:'Reports, tax, printing.',arItems:['نظرة التقارير','التقارير المالية','التقرير الضريبي','Hajri Tax','الطباعة والتصدير'],enItems:['Reports overview','Financial reports','VAT report','Hajri Tax','Print & export']},
  {id:'admin',icon:'⚙',color:'#536b63',ar:'الإدارة',en:'Administration',arDescription:'الشركات والمستخدمون والإعدادات.',enDescription:'Companies, users, and settings.',arItems:['نظرة الإدارة','الشركات','المستخدمون','الأدوار والصلاحيات','الهوية والثيم','النسخ الاحتياطي'],enItems:['Administration overview','Companies','Users','Roles & permissions','Identity & theme','Backup']},
];
const state={language:'ar',theme:'green',moduleId:'command',section:0};const q=(s)=>document.querySelector(s);const current=()=>modules.find((m)=>m.id===state.moduleId);const local=(m,s='')=>m[`${state.language}${s}`];
function updateLanguage(){document.documentElement.lang=state.language;document.documentElement.dir=state.language==='ar'?'rtl':'ltr';q('#language').textContent=state.language==='ar'?'EN':'ع';q('#app-language').textContent=state.language==='ar'?'EN':'ع';document.querySelectorAll('[data-ar]').forEach((el)=>el.textContent=el.dataset[state.language]);q('#search').placeholder=state.language==='ar'?'ابحث عن موديول…':'Search a module…';if(q('#app-view').hidden)renderLauncher();else renderApp();}
function toggleTheme(){state.theme=state.theme==='green'?'classic':'green';document.body.classList.toggle('is-classic',state.theme==='classic');}
function moduleCard(module){const b=document.createElement('button');b.type='button';b.className='module-card';b.style.setProperty('--module',module.color);b.innerHTML=`<span class="module-icon">${module.icon}</span><span class="module-copy"><strong>${local(module)}</strong><span>${local(module,'Description')}</span></span><span class="module-arrow">←</span>`;b.addEventListener('click',()=>openSection(module.id,0));return b;}
function renderLauncher(){const term=q('#search').value.trim().toLowerCase();const list=modules.filter((m)=>`${m.ar} ${m.en} ${m.arDescription} ${m.enDescription}`.toLowerCase().includes(term));q('#count').textContent=`${list.length} / ${modules.length}`;q('#choices').replaceChildren(...list.map(moduleCard));q('#empty').hidden=list.length>0;renderRecent();}
function renderRecent(){const keys=JSON.parse(localStorage.getItem('baseer-shell-recent-v4')||'[]');const entries=keys.map((key)=>{const [id,index]=key.split(':');const m=modules.find((entry)=>entry.id===id);return m?{m,index:Number(index)}:null;}).filter(Boolean);q('#recent').hidden=entries.length===0;q('#recent-list').replaceChildren(...entries.map(({m,index})=>{const b=document.createElement('button');b.type='button';b.textContent=`${local(m)} · ${local(m,'Items')[index]}`;b.addEventListener('click',()=>openSection(m.id,index));return b;}));}
function remember(id,index){const key=`${id}:${index}`;const old=JSON.parse(localStorage.getItem('baseer-shell-recent-v4')||'[]').filter((v)=>v!==key);localStorage.setItem('baseer-shell-recent-v4',JSON.stringify([key,...old].slice(0,4)));}
function setHash(){location.hash=`module=${state.moduleId}&section=${state.section}`;}
function navButton(name,index,module){const b=document.createElement('button');b.type='button';b.className=`nav-item${state.section===index?' active':''}`;b.innerHTML=`<span class="nav-dot"></span><span>${name}</span>`;b.addEventListener('click',()=>openSection(module.id,index));return b;}
function renderApp(){const module=current(),items=local(module,'Items'),section=items[state.section];q('#sidebar-title').textContent=local(module);q('#drawer-title').textContent=local(module);q('#side-nav').replaceChildren(...items.map((n,i)=>navButton(n,i,module)));q('#drawer-nav').replaceChildren(...items.map((n,i)=>navButton(n,i,module)));q('#crumb').textContent=`Baseer ERP / ${local(module)}`;q('#section-title').textContent=section;q('#section-description').textContent=local(module,'Description');q('#module-label').textContent=local(module);q('#hero-title').textContent=state.language==='ar'?`مرحبًا بك في ${section}`:`Welcome to ${section}`;q('#hero-copy').textContent=state.language==='ar'?'تنتقل بين أقسام هذا الموديول من القائمة الجانبية فقط.':'Navigate this module’s sections only from its sidebar.';}
function openSection(id,index){state.moduleId=id;state.section=index;remember(id,index);q('#launcher-view').hidden=true;q('#app-view').hidden=false;closeDrawer();renderApp();setHash();}
function showModules(){q('#launcher-view').hidden=false;q('#app-view').hidden=true;q('#search').value='';renderLauncher();}
function closeDrawer(){q('#mobile-drawer').classList.remove('is-open');q('#mobile-drawer').setAttribute('aria-hidden','true');}function openDrawer(){q('#mobile-drawer').classList.add('is-open');q('#mobile-drawer').setAttribute('aria-hidden','false');}
function parseHash(){const p=new URLSearchParams(location.hash.slice(1)),id=p.get('module'),index=Number(p.get('section')),module=modules.find((m)=>m.id===id);if(module&&Number.isInteger(index)&&index>=0&&index<module.arItems.length){state.moduleId=id;state.section=index;q('#launcher-view').hidden=true;q('#app-view').hidden=false;renderApp();}else showModules();}
q('#search').addEventListener('input',renderLauncher);q('#language').addEventListener('click',()=>{state.language=state.language==='ar'?'en':'ar';updateLanguage();});q('#app-language').addEventListener('click',()=>{state.language=state.language==='ar'?'en':'ar';updateLanguage();});q('#theme').addEventListener('click',toggleTheme);q('#app-theme').addEventListener('click',toggleTheme);q('#open-modules').addEventListener('click',showModules);q('#side-modules').addEventListener('click',showModules);q('#hero-modules').addEventListener('click',showModules);q('#brand-home').addEventListener('click',(e)=>{e.preventDefault();showModules();});q('#app-home').addEventListener('click',(e)=>{e.preventDefault();showModules();});q('#mobile-sections').addEventListener('click',openDrawer);q('#close-drawer').addEventListener('click',closeDrawer);q('#drawer-backdrop').addEventListener('click',closeDrawer);window.addEventListener('hashchange',parseHash);document.addEventListener('keydown',(e)=>{if(e.key==='Escape')closeDrawer();});updateLanguage();parseHash();
