import { defineLocalizedCopy, type BaseerLanguage } from "./baseer-ui-copy";

export const administrationCopy = defineLocalizedCopy({
  ar: {
    administration: "الإدارة",
    basiraMark: "ب",
    companies: "الشركات",
    users: "المستخدمون",
    roles: "الأدوار والصلاحيات",
    addEmployee: "إضافة مستخدم",
    showDisabledUsers: "إظهار المعطّلين",
    hideDisabledUsers: "إخفاء المعطّلين",
    hiddenDisabledUsers: (count: number) => `المعطّلون مخفيون (${count})`,
    systemOwner: "مالك النظام",
    activeUserCount: "نشط",
    disabledUserCount: "مُعطّل",
    systemOwnerCount: "مالك",
    addRole: "إضافة دور",
    displayName: "الاسم الظاهر",
    loginName: "اسم الدخول",
    access: "الوصول والصلاحية",
    interface: "الواجهة",
    arabic: "العربية",
    english: "English",
    status: "الحالة",
    noCompany: "غير مرتبط بشركة",
    active: "نشط",
    disabled: "مُعطّل",
    domain: "النطاق",
    password: "كلمة المرور",
    show: "إظهار",
    hide: "إخفاء",
    newPassword: "كلمة مرور جديدة",
    saveEmployee: "حفظ الموظف",
    saveChanges: "حفظ التغييرات",
    disableUser: "تعطيل المستخدم",
    enableUser: "تفعيل المستخدم",
    companiesLegend: "الشركات",
    avatar: "الصورة الرمزية",
    initials: "حرف الاسم",
    male: "رجل",
    female: "امرأة",
    close: "إغلاق",
    checkRequiredFields: "تحقق من الحقول المطلوبة.",
    createEmployee: "إضافة موظف",
    preferredLanguage: "لغة الواجهة المفضلة",
    role: "الدور",
    arabicName: "الاسم الظاهر بالعربية",
    englishName: "الاسم الظاهر بالإنجليزية",
    permissions: "صلاحية", defaultRole: "دور افتراضي", customRole: "دور مخصص", editPermissions: "تعديل الصلاحيات", roleCode: "رمز الدور", createRole: "إضافة دور", editRole: "تعديل دور", selectedPermissions: "الصلاحيات المحددة", returnToRoles: "العودة إلى الأدوار", deleteRole: "حذف الدور", sensitive: "حساس", activeCompanies: "الشركات النشطة", activeUsers: "المستخدمون النشطون", approvedPermissions: "صلاحيات معتمدة", administrationRules: "قواعد الإدارة", printExport: "الطباعة والتصدير", archived: "مؤرشفة", showArchived: "عرض المؤرشفة", addCompany: "إضافة شركة", companyNumber: (count: number) => `شركة #${count}`, viewEdit: "عرض وتعديل", noCompanies: "لا توجد شركات ضمن هذا العرض.", companyManagement: "إدارة الشركات", createCompany: "إنشاء الشركة", updateCompany: "تعديل الشركة", archiveCompany: "أرشفة الشركة", reactivateCompany: "إعادة التفعيل", companyArabicName: "اسم الشركة بالعربية", companyEnglishName: "اسم الشركة بالإنجليزية", companyLogo: "شعار الشركة", changeReason: "سبب التغيير", shortReason: "اكتب سبباً مختصراً", newCompany: "شركة جديدة", activeCompany: "شركة نشطة", archivedCompany: "شركة مؤرشفة", saveCompany: "حفظ الشركة", edit: "تعديل", optional: "اختياري", refresh: "تحديث", cancel: "إلغاء", saving: "جارٍ الحفظ…", usersManagement: "إدارة المستخدمين", usersTable: "جدول المستخدمين", editRoleName: (name: string) => `تعديل دور: ${name}`, rolePermissionCount: "صلاحية", companyLogoHint: "PNG أو JPG أو WebP · حتى 512 كيلوبايت", archiveCompanyAction: "أرشفة الشركة", reactivateCompanyAction: "إعادة التفعيل", ownerOnly: "يمكنك العرض فقط؛ تغييرات الإدارة تحتاج مالك النظام.", loadingAdministration: "جارٍ تحميل الإدارة…", administrationCommandFailed: "تعذر تنفيذ أمر الإدارة.", noAdministrationAccess: "لا تملك حالياً صلاحية الإدارة المركزية.", companiesAndAccess: "إدارة الشركات والوصول", avatarMale: "صورة رمزية: رجل", avatarFemale: "صورة رمزية: امرأة", avatarNamed: (name: string) => `صورة رمزية: ${name}`, invalidVatRate: "أدخل نسبة بين 0 و100 وبحد أقصى منزلتين عشريتين.",
  },
  en: {
    administration: "Administration",
    basiraMark: "B",
    companies: "Companies",
    users: "Users",
    roles: "Roles & permissions",
    addEmployee: "Add user",
    showDisabledUsers: "Show disabled",
    hideDisabledUsers: "Hide disabled",
    hiddenDisabledUsers: (count: number) => `${count} disabled hidden`,
    systemOwner: "System owner",
    activeUserCount: "Active",
    disabledUserCount: "Disabled",
    systemOwnerCount: "Owners",
    addRole: "Add role",
    displayName: "Display name",
    loginName: "Login name",
    access: "Access & role",
    interface: "Interface",
    arabic: "Arabic",
    english: "English",
    status: "Status",
    noCompany: "No company access",
    active: "Active",
    disabled: "Disabled",
    domain: "Domain",
    password: "Password",
    show: "Show",
    hide: "Hide",
    newPassword: "New password",
    saveEmployee: "Save employee",
    saveChanges: "Save changes",
    disableUser: "Disable user",
    enableUser: "Enable user",
    companiesLegend: "Companies",
    avatar: "Avatar",
    initials: "Initials",
    male: "Male",
    female: "Female",
    close: "Close",
    checkRequiredFields: "Check the required fields.",
    createEmployee: "Add employee",
    preferredLanguage: "Preferred interface language",
    role: "Role",
    arabicName: "Arabic display name",
    englishName: "English display name",
    permissions: "permissions", defaultRole: "System role", customRole: "Custom role", editPermissions: "Edit permissions", roleCode: "Role code", createRole: "Add role", editRole: "Edit role", selectedPermissions: "Selected permissions", returnToRoles: "Back to roles", deleteRole: "Delete role", sensitive: "Sensitive", activeCompanies: "Active companies", activeUsers: "Active users", approvedPermissions: "Approved permissions", administrationRules: "Administration rules", printExport: "Print & export", archived: "Archived", showArchived: "Show archived", addCompany: "Add company", companyNumber: (count: number) => `Company #${count}`, viewEdit: "View & edit", noCompanies: "No companies in this view.", companyManagement: "Company management", createCompany: "Create company", updateCompany: "Update company", archiveCompany: "Archive company", reactivateCompany: "Reactivate", companyArabicName: "Arabic company name", companyEnglishName: "English company name", companyLogo: "Company logo", changeReason: "Change reason", shortReason: "Enter a short reason", newCompany: "New company", activeCompany: "Active company", archivedCompany: "Archived company", saveCompany: "Save company", edit: "Edit", optional: "Optional", refresh: "Refresh", cancel: "Cancel", saving: "Saving…", usersManagement: "User management", usersTable: "Users table", editRoleName: (name: string) => `Edit role: ${name}`, rolePermissionCount: "permissions", companyLogoHint: "PNG, JPG or WebP · up to 512 KB", archiveCompanyAction: "Archive company", reactivateCompanyAction: "Reactivate", ownerOnly: "You can view only; changes require the system owner.", loadingAdministration: "Loading administration…", administrationCommandFailed: "Administration command failed.", noAdministrationAccess: "Tenant administration access is not available.", companiesAndAccess: "Companies & access", avatarMale: "Avatar: male", avatarFemale: "Avatar: female", avatarNamed: (name: string) => `Avatar: ${name}`, invalidVatRate: "Enter a rate from 0 to 100 with at most two decimal places.",
  },
});

export function administrationText(language: BaseerLanguage) {
  return administrationCopy[language];
}
