import { useState, type FormEvent } from "react";

import { createAdministrationRole, deleteAdministrationRole, updateAdministrationRole } from "./administration-client";
import type { AdministrationOverview } from "./administration-types";
import type { ActiveSession } from "./daily-sales-client";

type Props = { session: ActiveSession; overview: AdministrationOverview; owner: boolean; onDone: () => Promise<void>; onError: (error: unknown) => void };
type Permission = AdministrationOverview["permissions"][number];
type Role = AdministrationOverview["roles"][number];
type PermissionSection = { title: string; match: (code: string) => boolean };
const permissionModules: ReadonlyArray<{ key: string; title: string; sections: readonly PermissionSection[] }> = [
  { key: "administration", title: "الإدارة", sections: [{ title: "الشركات", match: (code) => code.startsWith("administration.companies") }, { title: "المستخدمون", match: (code) => code.startsWith("administration.users") }, { title: "الأدوار والصلاحيات", match: (code) => code.startsWith("administration.roles") }] },
  { key: "finance", title: "المالية", sections: [{ title: "التهيئة والبيانات الأساسية", match: (code) => /finance\.(setup|configuration|foundation)/.test(code) }, { title: "الفترات والخزائن", match: (code) => /finance\.(periods|vaults)/.test(code) }, { title: "الموردون والالتزامات", match: (code) => /finance\.(suppliers|supplier_dues)/.test(code) }, { title: "القروض", match: (code) => code.startsWith("finance.loans") }] },
  { key: "operations", title: "العمليات والمبيعات", sections: [{ title: "سجل المبيعات", match: (code) => /finance\.daily_sales\.(read|history)/.test(code) }, { title: "تقفيل المبيعات", match: (code) => /finance\.daily_sales\.(create|correct|reverse|write)/.test(code) }, { title: "تقويم التشغيل", match: (code) => code.startsWith("finance.operational_calendar") }] },
  { key: "platform", title: "المنصة", sections: [{ title: "الملفات والمستندات", match: (code) => code.startsWith("platform.files") }, { title: "التشغيل والتاريخ", match: (code) => /platform\.(business-date|observability)/.test(code) }, { title: "الطباعة والتصدير", match: (code) => code.startsWith("platform.output") }] },
  { key: "ai", title: "بصيرة والذكاء", sections: [{ title: "استخدام بصيرة", match: (code) => code === "platform.ai.use" }, { title: "مزود الذكاء", match: (code) => /platform\.ai\.(configuration|provider)/.test(code) }, { title: "هوية بصيرة", match: (code) => /platform\.ai\.(identity|system_identity)/.test(code) }] },
];

export function AdministrationRolesPanel({ session, overview, owner, onDone, onError }: Props) {
  const [editing, setEditing] = useState(false); const [editingRole, setEditingRole] = useState<Role | null>(null); const [nameAr, setNameAr] = useState(""); const [nameEn, setNameEn] = useState(""); const [code, setCode] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [busy, setBusy] = useState(false);
  const reset = () => { setEditing(false); setEditingRole(null); setNameAr(""); setNameEn(""); setCode(""); setSelected([]); };
  const startEdit = (role: Role) => { setEditingRole(role); setNameAr(role.nameAr); setNameEn(role.nameEn); setCode(role.code); setSelected(role.permissionCodes); setEditing(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!owner) return; setBusy(true); try { if (editingRole) await updateAdministrationRole(session, editingRole.id, { nameAr, nameEn, permissionCodes: selected }); else await createAdministrationRole(session, { code, nameAr, nameEn, permissionCodes: selected }); await onDone(); reset(); } catch (error) { onError(error); } finally { setBusy(false); } };
  const remove = async () => { if (!owner || !editingRole || !window.confirm(`حذف دور «${editingRole.nameAr}»؟ لا يمكن الحذف إذا كان مستخدم مرتبطاً به.`)) return; setBusy(true); try { await deleteAdministrationRole(session, editingRole.id); await onDone(); reset(); } catch (error) { onError(error); } finally { setBusy(false); } };
  const toggle = (permissionCode: string, checked: boolean) => setSelected((current) => checked ? [...new Set([...current, permissionCode])] : current.filter((item) => item !== permissionCode));
  if (editing) return <section className="administration-section administration-role-editor"><header className="administration-section-heading"><div><p className="eyebrow">الأدوار والصلاحيات</p><h3>{editingRole ? `تعديل دور: ${editingRole.nameAr}` : "إضافة دور"}</h3></div><button className="daily-sales-secondary" type="button" onClick={reset} disabled={busy}>← العودة إلى الأدوار</button></header><form className="administration-role-form" onSubmit={(event) => void submit(event)}><div className="administration-role-basics"><label>رمز الدور<input required disabled={Boolean(editingRole)} pattern="[A-Z][A-Z0-9_]*" value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} placeholder="CUSTOM_SALES_ROLE" /></label><label>الاسم بالعربية<input required value={nameAr} onChange={(event) => setNameAr(event.target.value)} /></label><label>الاسم بالإنجليزية<input required value={nameEn} onChange={(event) => setNameEn(event.target.value)} /></label></div><fieldset className="administration-permission-picker"><legend>الصلاحيات المحددة <small>{selected.length}</small></legend>{permissionModules.map((module) => <PermissionModule key={module.key} title={module.title} sections={module.sections} permissions={overview.permissions} selected={selected} onToggle={toggle} />)}</fieldset><footer className="administration-role-editor__footer"><button className="daily-sales-secondary" type="button" onClick={reset} disabled={busy}>إلغاء</button>{editingRole && <button className="daily-sales-danger" type="button" onClick={() => void remove()} disabled={busy}>حذف الدور</button>}<button className="daily-sales-primary" disabled={busy || !selected.length}>{busy ? "جارٍ الحفظ…" : editingRole ? "حفظ التعديلات" : "حفظ الدور"}</button></footer></form></section>;
  return <section className="administration-section administration-roles-section"><header className="administration-section-heading"><div><h3>الأدوار والصلاحيات</h3></div>{owner && <button className="daily-sales-primary" type="button" onClick={() => { reset(); setEditing(true); }}>+ إضافة دور</button>}</header><div className="administration-role-cards">{overview.roles.map((role) => <article key={role.id}><span className={role.isSystem ? "administration-role-card__system" : "administration-role-card__custom"}>{role.isSystem ? "دور افتراضي" : "دور مخصص"}</span><strong>{role.nameAr}</strong><small>{role.nameEn}</small><p>{role.permissionCodes.length} صلاحية مفعلة</p>{owner && <button className="daily-sales-secondary" type="button" onClick={() => startEdit(role)}>تعديل الصلاحيات</button>}</article>)}</div></section>;
}
function PermissionModule({ title, sections, permissions, selected, onToggle }: { title: string; sections: readonly PermissionSection[]; permissions: Permission[]; selected: string[]; onToggle: (permissionCode: string, checked: boolean) => void }) { const visible = sections.map((section) => ({ ...section, permissions: permissions.filter((permission) => section.match(permission.code)) })).filter((section) => section.permissions.length > 0); if (!visible.length) return null; const count = visible.reduce((total, section) => total + section.permissions.length, 0); return <section className="administration-permission-module"><header><h5>{title}</h5><span>{count} صلاحية</span></header><div className="administration-permission-sections">{visible.map((section) => <section className="administration-permission-section" key={section.title}><h6>{section.title}</h6><div>{section.permissions.map((permission) => <label key={permission.code} className={permission.risk === "sensitive" ? "is-sensitive" : ""}><input type="checkbox" checked={selected.includes(permission.code)} onChange={(event) => onToggle(permission.code, event.target.checked)} /><span>{permission.nameAr}</span>{permission.risk === "sensitive" && <small>حساس</small>}</label>)}</div></section>)}</div></section>; }