import { useState, type FormEvent, type ReactNode, type RefObject } from "react";

import { createAdministrationUser, replaceAdministrationUserAccess, resetAdministrationUserPassword, updateAdministrationUserStatus } from "./administration-client";
import { AdministrationUserAvatar, type UserAvatarKind } from "./administration-user-avatar";
import { DataTable } from "./data-table";
import type { AdministrationOverview } from "./administration-types";
import type { ActiveSession } from "./daily-sales-client";
import { useDialogFocusTrap } from "./use-dialog-focus-trap";

type Props = { session: ActiveSession; overview: AdministrationOverview; owner: boolean; onDone: () => Promise<void>; onError: (error: unknown) => void };
type User = AdministrationOverview["users"][number];
type DialogMode = "create" | "manage" | null;
const activeCompanies = (overview: AdministrationOverview) => overview.companies.filter((company) => company.status === "ACTIVE");

export function AdministrationUsersPanel({ session, overview, owner, onDone, onError }: Props) {
  const [mode, setMode] = useState<DialogMode>(null); const [selectedUserId, setSelectedUserId] = useState<string | null>(null);
  const selectedUser = overview.users.find((user) => user.id === selectedUserId) ?? null;
  const close = () => { setMode(null); setSelectedUserId(null); }; const openUser = (user: User) => { setSelectedUserId(user.id); setMode("manage"); };
  return <section className="administration-section administration-users-section"><header className="administration-section-heading"><div><h3>المستخدمون</h3><p>اختر اسم المستخدم لإدارة دوره والشركات التي يستطيع الدخول إليها.</p></div>{owner && <button className="daily-sales-primary" type="button" onClick={() => setMode("create")}>+ إضافة موظف</button>}</header><DataTable ariaLabel="جدول المستخدمين" caption="المستخدمون" rowKey={(row) => row.key} columns={[{ id: "user", header: "المستخدم", cell: (row) => row.cells.user }, { id: "login", header: "اسم الدخول", cell: (row) => row.cells.login }, { id: "access", header: "الوصول والصلاحية", cell: (row) => row.cells.access }, { id: "language", header: "الواجهة", cell: (row) => row.cells.language }, { id: "status", header: "الحالة", cell: (row) => row.cells.status }]} rows={overview.users.map((user) => ({ key: user.id, cells: { user: <button className="administration-table-user" type="button" onClick={() => openUser(user)}><AdministrationUserAvatar name={user.nameAr} kind={user.avatarKind} /><span><strong>{user.nameAr}</strong><small>{user.nameEn}</small></span></button>, login: user.login, access: user.memberships.length ? <span className="administration-table-access">{user.memberships.map((membership) => <span key={membership.companyId}><strong>{membership.companyNameAr}</strong><small>{membership.roleNameAr}</small></span>)}</span> : "غير مرتبط بشركة", language: user.preferredLanguage === "ar" ? "العربية" : "English", status: <span className={user.status === "ACTIVE" ? "administration-status-pill is-active" : "administration-status-pill is-disabled"}>{user.status === "ACTIVE" ? "نشط" : "مُعطّل"}</span> } }))} />{mode === "create" && <CreateUserDialog session={session} overview={overview} onDone={onDone} onError={onError} onClose={close} />}{mode === "manage" && selectedUser && <ManageUserDialog session={session} user={selectedUser} overview={overview} owner={owner} onDone={onDone} onError={onError} onClose={close} />}</section>;
}

function CompanyCheckboxes({ overview, value, onChange, disabled }: { overview: AdministrationOverview; value: string[]; onChange: (value: string[]) => void; disabled: boolean }) { const toggle = (companyId: string) => onChange(value.includes(companyId) ? value.filter((id) => id !== companyId) : [...value, companyId]); return <fieldset className="administration-access-list administration-company-checkboxes"><legend>الشركات</legend>{activeCompanies(overview).map((company) => <label key={company.id}><input type="checkbox" checked={value.includes(company.id)} disabled={disabled} onChange={() => toggle(company.id)} /><span>{company.nameAr}</span></label>)}</fieldset>; }

function CreateUserDialog({ session, overview, onDone, onError, onClose }: Pick<Props, "session" | "overview" | "onDone" | "onError"> & { onClose: () => void }) {
  const companies = activeCompanies(overview); const [login, setLogin] = useState(""); const [nameAr, setNameAr] = useState(""); const [nameEn, setNameEn] = useState(""); const [password, setPassword] = useState(""); const [preferredLanguage, setPreferredLanguage] = useState<"ar" | "en">("ar"); const [companyIds, setCompanyIds] = useState<string[]>(companies[0] ? [companies[0].id] : []); const [roleId, setRoleId] = useState(overview.roles[0]?.id ?? ""); const [avatarKind, setAvatarKind] = useState<UserAvatarKind>("INITIALS"); const [busy, setBusy] = useState(false); const dialogRef = useDialogFocusTrap({ open: true, saving: busy, onClose });
  const save = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await createAdministrationUser(session, { login, nameAr, nameEn, password, preferredLanguage, companyIds, roleId, avatarKind }); await onDone(); onClose(); } catch (error) { onError(error); } finally { setBusy(false); } };
  return <Dialog title="إضافة موظف" intro="اختر دوراً واحداً، ثم علّم الشركات التي يدخل إليها الموظف." busy={busy} dialogRef={dialogRef} onClose={onClose}><form className="administration-dialog-form" onSubmit={(event) => void save(event)}><AvatarPicker value={avatarKind} onChange={setAvatarKind} previewName={nameAr || "الموظف"} /><label>اسم المستخدم أو البريد الإلكتروني<input required value={login} onChange={(event) => setLogin(event.target.value)} placeholder="ahmed أو ahmed@example.com" autoComplete="username" /></label><label>الاسم بالعربية<input required value={nameAr} onChange={(event) => setNameAr(event.target.value)} /></label><label>الاسم بالإنجليزية<input required value={nameEn} onChange={(event) => setNameEn(event.target.value)} /></label><label>لغة الواجهة المفضلة<select value={preferredLanguage} onChange={(event) => setPreferredLanguage(event.target.value as "ar" | "en")}><option value="ar">العربية</option><option value="en">English</option></select></label><label>كلمة المرور الأولية<input type="password" required minLength={6} value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password" /><small>6 خانات على الأقل، بأي مزيج تختاره.</small></label><label>الدور<select value={roleId} onChange={(event) => setRoleId(event.target.value)}>{overview.roles.map((role) => <option key={role.id} value={role.id}>{role.nameAr}</option>)}</select></label><CompanyCheckboxes overview={overview} value={companyIds} onChange={setCompanyIds} disabled={busy} /><footer><button className="daily-sales-secondary" type="button" onClick={onClose} disabled={busy}>إلغاء</button><button className="daily-sales-primary" disabled={busy || !companyIds.length}>{busy ? "جارٍ الحفظ…" : "حفظ الموظف"}</button></footer></form></Dialog>;
}

function ManageUserDialog({ session, user, overview, owner, onDone, onError, onClose }: { session: ActiveSession; user: User; overview: AdministrationOverview; owner: boolean; onDone: () => Promise<void>; onError: (error: unknown) => void; onClose: () => void }) {
  const [reason, setReason] = useState(""); const [replacementPassword, setReplacementPassword] = useState(""); const [companyIds, setCompanyIds] = useState<string[]>(user.memberships.map((membership) => membership.companyId)); const [roleId, setRoleId] = useState(user.memberships[0]?.roleId ?? overview.roles[0]?.id ?? ""); const [busy, setBusy] = useState(false); const dialogRef = useDialogFocusTrap({ open: true, saving: busy, onClose });
  const run = async (action: () => Promise<unknown>) => { if (!owner || reason.trim().length < 3) return; setBusy(true); try { await action(); setReason(""); setReplacementPassword(""); await onDone(); } catch (error) { onError(error); } finally { setBusy(false); } };
  return <Dialog title={user.nameAr} intro="دور واحد للشركات المحددة، مثل إعداد المستخدم في نوركس. الحفظ يطبق الاختيارات دفعة واحدة." busy={busy} dialogRef={dialogRef} onClose={onClose}><section className="administration-user-profile"><AdministrationUserAvatar name={user.nameAr} kind={user.avatarKind} large /><div><strong>{user.nameAr}</strong><span>{user.login}</span><small>{user.preferredLanguage === "ar" ? "واجهة عربية" : "English interface"}</small><em className={user.status === "ACTIVE" ? "is-active" : "is-disabled"}>{user.status === "ACTIVE" ? "نشط" : "مُعطّل"}</em></div></section><div className="administration-dialog-form"><label>سبب التغيير<input minLength={3} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="مثال: تعديل تكليف العمل" autoComplete="off" /></label><label>الدور<select value={roleId} disabled={!owner || busy} onChange={(event) => setRoleId(event.target.value)}>{overview.roles.map((role) => <option key={role.id} value={role.id}>{role.nameAr} · {role.permissionCodes.length} صلاحية</option>)}</select></label><CompanyCheckboxes overview={overview} value={companyIds} onChange={setCompanyIds} disabled={!owner || busy} />{owner && <button className="daily-sales-primary" disabled={busy || reason.trim().length < 3 || !companyIds.length} type="button" onClick={() => void run(() => replaceAdministrationUserAccess(session, user.id, { roleId, companyIds, reason }))}>{busy ? "جارٍ الحفظ…" : "حفظ الوصول"}</button>} {owner && <section className="administration-sensitive-actions"><button className="daily-sales-secondary" disabled={busy || reason.trim().length < 3} type="button" onClick={() => void run(() => updateAdministrationUserStatus(session, user.id, user.status === "ACTIVE" ? "DISABLED" : "ACTIVE", reason))}>{user.status === "ACTIVE" ? "تعطيل المستخدم" : "تفعيل المستخدم"}</button>{user.status === "ACTIVE" && <><label>كلمة مرور جديدة<input type="password" minLength={6} value={replacementPassword} onChange={(event) => setReplacementPassword(event.target.value)} placeholder="6 خانات على الأقل" /></label><button className="daily-sales-secondary" disabled={busy || reason.trim().length < 3 || replacementPassword.length < 6} type="button" onClick={() => void run(() => resetAdministrationUserPassword(session, user.id, replacementPassword, reason))}>إعادة ضبط كلمة المرور</button></>}</section>}<footer><button className="daily-sales-secondary" type="button" onClick={onClose} disabled={busy}>إغلاق</button></footer></div></Dialog>;
}
function AvatarPicker({ value, onChange, previewName }: { value: UserAvatarKind; onChange: (value: UserAvatarKind) => void; previewName: string }) { return <fieldset className="administration-avatar-picker"><legend>الصورة الرمزية</legend><div>{(["INITIALS", "MALE", "FEMALE"] as const).map((kind) => <button className={value === kind ? "is-selected" : ""} key={kind} type="button" onClick={() => onChange(kind)}><AdministrationUserAvatar name={previewName} kind={kind} large /><span>{kind === "INITIALS" ? "حرف الاسم" : kind === "MALE" ? "رجل" : "امرأة"}</span></button>)}</div></fieldset>; }
function Dialog({ title, intro, busy, dialogRef, onClose, children }: { title: string; intro: string; busy: boolean; dialogRef: RefObject<HTMLElement | null>; onClose: () => void; children: ReactNode }) { const close = () => { if (!busy) onClose(); }; return <div className="daily-sales-dialog-backdrop" role="presentation" onMouseDown={close}><section ref={dialogRef} className="daily-sales-dialog administration-user-dialog" role="dialog" aria-modal="true" aria-label={title} onMouseDown={(event) => event.stopPropagation()}><header className="daily-sales-dialog__header"><div><p className="eyebrow">إدارة المستخدمين</p><h3>{title}</h3><p>{intro}</p></div><button className="dialog-icon-button" type="button" aria-label="إغلاق" onClick={close} disabled={busy}>×</button></header>{children}</section></div>; }