import { useState, type FormEvent } from "react";

import { createAdministrationRole, deleteAdministrationRole, updateAdministrationRole } from "./administration-client";
import { BaseerConfirmDialog } from "./baseer-confirm-dialog";
import type { AdministrationOverview } from "./administration-types";
import type { ActiveSession } from "./daily-sales-client";
import { displayName } from "./baseer-localization";
import { administrationText } from "./administration-copy";

type Props = { language: "ar" | "en"; session: ActiveSession; overview: AdministrationOverview; owner: boolean; onDone: () => Promise<void>; onError: (error: unknown) => void };
type Permission = AdministrationOverview["permissions"][number];
type Role = AdministrationOverview["roles"][number];
type PermissionSection = { titleAr: string; titleEn: string; match: (code: string) => boolean };
const permissionModules: ReadonlyArray<{ key: string; titleAr: string; titleEn: string; sections: readonly PermissionSection[] }> = [
  { key: "administration", titleAr: "الإدارة", titleEn: "Administration", sections: [{ titleAr: "الشركات", titleEn: "Companies", match: (code) => code.startsWith("administration.companies") }, { titleAr: "المستخدمون", titleEn: "Users", match: (code) => code.startsWith("administration.users") }, { titleAr: "الأدوار والصلاحيات", titleEn: "Roles & permissions", match: (code) => code.startsWith("administration.roles") }] },
  { key: "finance", titleAr: "المالية", titleEn: "Finance", sections: [{ titleAr: "التهيئة والبيانات الأساسية", titleEn: "Setup & master data", match: (code) => /finance\.(setup|configuration|foundation)/.test(code) }, { titleAr: "الفترات والخزائن", titleEn: "Periods & vaults", match: (code) => /finance\.(periods|vaults)/.test(code) }, { titleAr: "الموردون والالتزامات", titleEn: "Suppliers & dues", match: (code) => /finance\.(suppliers|supplier_dues)/.test(code) }, { titleAr: "القروض", titleEn: "Loans", match: (code) => code.startsWith("finance.loans") }] },
  { key: "operations", titleAr: "العمليات والمبيعات", titleEn: "Operations & sales", sections: [{ titleAr: "سجل المبيعات", titleEn: "Sales register", match: (code) => /finance\.daily_sales\.(read|history)/.test(code) }, { titleAr: "تقفيل المبيعات", titleEn: "Sales closing", match: (code) => /finance\.daily_sales\.(create|correct|reverse|write)/.test(code) }, { titleAr: "تقويم التشغيل", titleEn: "Operating calendar", match: (code) => code.startsWith("finance.operational_calendar") }] },
  { key: "platform", titleAr: "المنصة", titleEn: "Platform", sections: [{ titleAr: "الملفات والمستندات", titleEn: "Files & documents", match: (code) => code.startsWith("platform.files") }, { titleAr: "التشغيل والتاريخ", titleEn: "Operations & business date", match: (code) => /platform\.(business-date|observability)/.test(code) }, { titleAr: "الطباعة والتصدير", titleEn: "Print & export", match: (code) => code.startsWith("platform.output") }] },
  { key: "ai", titleAr: "بصيرة والذكاء", titleEn: "Basira & AI", sections: [{ titleAr: "استخدام بصيرة", titleEn: "Use Basira", match: (code) => code === "platform.ai.use" }, { titleAr: "مزود الذكاء", titleEn: "AI provider", match: (code) => /platform\.ai\.(configuration|provider)/.test(code) }, { titleAr: "هوية بصيرة", titleEn: "Basira identity", match: (code) => /platform\.ai\.(identity|system_identity)/.test(code) }] },
];

export function AdministrationRolesPanel({ language, session, overview, owner, onDone, onError }: Props) { const text = administrationText(language);
  const [editing, setEditing] = useState(false); const [editingRole, setEditingRole] = useState<Role | null>(null); const [nameAr, setNameAr] = useState(""); const [nameEn, setNameEn] = useState(""); const [code, setCode] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [confirmDelete, setConfirmDelete] = useState(false);
  const reset = () => { setEditing(false); setEditingRole(null); setNameAr(""); setNameEn(""); setCode(""); setSelected([]); };
  const startEdit = (role: Role) => { setEditingRole(role); setNameAr(role.nameAr); setNameEn(role.nameEn); setCode(role.code); setSelected(role.permissionCodes); setEditing(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!owner) return; setBusy(true); try { if (editingRole) await updateAdministrationRole(session, editingRole.id, { nameAr, nameEn, permissionCodes: selected }); else await createAdministrationRole(session, { code, nameAr, nameEn, permissionCodes: selected }); await onDone(); reset(); } catch (error) { onError(error); } finally { setBusy(false); setConfirmDelete(false); } };
  const remove = async () => { if (!owner || !editingRole) return; setBusy(true); try { await deleteAdministrationRole(session, editingRole.id); await onDone(); reset(); } catch (error) { onError(error); } finally { setBusy(false); setConfirmDelete(false); } };
  const toggle = (permissionCode: string, checked: boolean) => setSelected((current) => checked ? [...new Set([...current, permissionCode])] : current.filter((item) => item !== permissionCode));
  if (editing) return <>{<section className="administration-section administration-role-editor"><header className="administration-section-heading"><div><p className="eyebrow">{text.roles}</p><h3>{editingRole ? text.editRoleName(displayName(language, editingRole)) : text.createRole}</h3></div><button className="daily-sales-secondary" type="button" onClick={reset} disabled={busy}>← {text.returnToRoles}</button></header><form className="administration-role-form" onSubmit={(event) => void submit(event)}><div className="administration-role-basics"><label>{text.roleCode}<input required disabled={Boolean(editingRole)} pattern="[A-Z][A-Z0-9_]*" value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} placeholder="CUSTOM_SALES_ROLE" /></label><label>{text.arabicName}<input required value={nameAr} onChange={(event) => setNameAr(event.target.value)} /></label><label>{text.englishName}<input required value={nameEn} onChange={(event) => setNameEn(event.target.value)} /></label></div><fieldset className="administration-permission-picker"><legend>{text.selectedPermissions} <small>{selected.length}</small></legend>{permissionModules.map((module) => <PermissionModule key={module.key} language={language} title={language === "ar" ? module.titleAr : module.titleEn} sections={module.sections} permissions={overview.permissions} selected={selected} onToggle={toggle} />)}</fieldset><footer className="administration-role-editor__footer"><button className="daily-sales-secondary" type="button" onClick={reset} disabled={busy}>{text.cancel}</button>{editingRole && <button className="daily-sales-danger" type="button" onClick={() => setConfirmDelete(true)} disabled={busy}>{text.deleteRole}</button>}<button className="daily-sales-primary" disabled={busy || !selected.length}>{busy ? text.saving : editingRole ? text.saveChanges : text.createRole}</button></footer></form></section>}<BaseerConfirmDialog open={confirmDelete} title={text.deleteRole} message={`${text.deleteRole}: ${editingRole ? displayName(language, editingRole) : ""}`} confirmLabel={text.deleteRole} language={language} destructive busy={busy} onCancel={() => setConfirmDelete(false)} onConfirm={() => void remove()} /></>;
  return <section className="administration-section administration-roles-section"><header className="administration-section-heading"><div><h3>{text.roles}</h3></div>{owner && <button className="daily-sales-primary" type="button" onClick={() => { reset(); setEditing(true); }}>+ {text.addRole}</button>}</header><div className="administration-role-cards">{overview.roles.map((role) => <article key={role.id}><span className={role.isSystem ? "administration-role-card__system" : "administration-role-card__custom"}>{role.isSystem ? text.defaultRole : text.customRole}</span><strong>{displayName(language, role)}</strong><small>{language === "ar" ? role.nameEn : role.nameAr}</small><p>{role.permissionCodes.length} {text.permissions}</p>{owner && <button className="daily-sales-secondary" type="button" onClick={() => startEdit(role)}>{text.editPermissions}</button>}</article>)}</div></section>;
}
function PermissionModule({ language, title, sections, permissions, selected, onToggle }: { language: "ar" | "en"; title: string; sections: readonly PermissionSection[]; permissions: Permission[]; selected: string[]; onToggle: (permissionCode: string, checked: boolean) => void }) { const text = administrationText(language); const visible = sections.map((section) => ({ ...section, permissions: permissions.filter((permission) => section.match(permission.code)) })).filter((section) => section.permissions.length > 0); if (!visible.length) return null; const count = visible.reduce((total, section) => total + section.permissions.length, 0); return <section className="administration-permission-module"><header><h5>{title}</h5><span>{count} {text.permissions}</span></header><div className="administration-permission-sections">{visible.map((section) => <section className="administration-permission-section" key={section.titleAr}><h6>{language === "ar" ? section.titleAr : section.titleEn}</h6><div>{section.permissions.map((permission) => <label key={permission.code} className={permission.risk === "sensitive" ? "is-sensitive" : ""}><input type="checkbox" checked={selected.includes(permission.code)} onChange={(event) => onToggle(permission.code, event.target.checked)} /><span>{displayName(language, permission)}</span>{permission.risk === "sensitive" && <small>{text.sensitive}</small>}</label>)}</div></section>)}</div></section>; }