import { lazy, Suspense, useCallback, useState, type ComponentType } from "react";

import { createAdministrationRole, deleteAdministrationRole, updateAdministrationRole } from "./administration-client";
import { BaseerButton } from "./baseer-button";
import { BaseerConfirmDialog } from "./baseer-confirm-dialog";
import { BaseerCheckbox, BaseerTextInput } from "./baseer-form-fields";
import type { AdministrationOverview } from "./administration-types";
import type { ActiveSession } from "./daily-sales-client";
import { displayName } from "./baseer-localization";
import { administrationText } from "./administration-copy";
import type { BaseerValidatedFormFieldProps, BaseerValidatedFormSchemaFactory } from "./baseer-validated-form-field";

type Props = { language: "ar" | "en"; session: ActiveSession; overview: AdministrationOverview; owner: boolean; onDone: () => Promise<void>; onError: (error: unknown) => void };
type Permission = AdministrationOverview["permissions"][number];
type Role = AdministrationOverview["roles"][number];
type PermissionSection = { titleAr: string; titleEn: string; match: (code: string) => boolean };
type RoleForm = { code: string; nameAr: string; nameEn: string; permissionCodes: string[] };
const LazyBaseerValidatedFormField = lazy(async () => ({ default: (await import("./baseer-validated-form-field")).BaseerValidatedFormField }));
function BaseerValidatedFormField<Values extends Record<string, unknown>>(props: BaseerValidatedFormFieldProps<Values>) {
  const Form = LazyBaseerValidatedFormField as unknown as ComponentType<BaseerValidatedFormFieldProps<Values>>;
  return <Suspense fallback={<form id={props.id} className={props.className} data-baseer-rhf-form aria-busy="true" onSubmit={(event) => event.preventDefault()} />}><Form {...props} /></Suspense>;
}
const permissionModules: ReadonlyArray<{ key: string; titleAr: string; titleEn: string; sections: readonly PermissionSection[] }> = [
  { key: "administration", titleAr: "الإدارة", titleEn: "Administration", sections: [{ titleAr: "الشركات", titleEn: "Companies", match: (code) => code.startsWith("administration.companies") }, { titleAr: "المستخدمون", titleEn: "Users", match: (code) => code.startsWith("administration.users") }, { titleAr: "الأدوار والصلاحيات", titleEn: "Roles & permissions", match: (code) => code.startsWith("administration.roles") }] },
  { key: "finance", titleAr: "المالية", titleEn: "Finance", sections: [{ titleAr: "التهيئة والبيانات الأساسية", titleEn: "Setup & master data", match: (code) => /finance\.(setup|configuration|foundation)/.test(code) }, { titleAr: "الفترات والخزائن", titleEn: "Periods & vaults", match: (code) => /finance\.(periods|vaults)/.test(code) }, { titleAr: "الموردون والالتزامات", titleEn: "Suppliers & dues", match: (code) => /finance\.(suppliers|supplier_dues)/.test(code) }, { titleAr: "القروض", titleEn: "Loans", match: (code) => code.startsWith("finance.loans") }] },
  { key: "operations", titleAr: "العمليات والمبيعات", titleEn: "Operations & sales", sections: [{ titleAr: "سجل المبيعات", titleEn: "Sales register", match: (code) => /finance\.daily_sales\.(read|history)/.test(code) }, { titleAr: "تقفيل المبيعات", titleEn: "Sales closing", match: (code) => /finance\.daily_sales\.(create|correct|reverse|write)/.test(code) }, { titleAr: "تقويم التشغيل", titleEn: "Operating calendar", match: (code) => code.startsWith("finance.operational_calendar") }, { titleAr: "كتالوج العمليات والتحويلات", titleEn: "Operations catalogue & conversions", match: (code) => code.startsWith("operations.catalog") || code.startsWith("operations.conversions") }, { titleAr: "الرسبي والطلبات والعهدة", titleEn: "Recipes, purchase requests & custody", match: (code) => code.startsWith("operations.recipe") || code.startsWith("operations.purchase_request") || code.startsWith("operations.custody") || code.startsWith("operations.inventory") }] },
  { key: "hr", titleAr: "الموارد البشرية", titleEn: "Human resources", sections: [{ titleAr: "الموظفون والخدمات", titleEn: "Employees & services", match: (code) => code.startsWith("hr.employees") }, { titleAr: "الإجازات", titleEn: "Leaves", match: (code) => code.startsWith("hr.leaves") }, { titleAr: "الرواتب", titleEn: "Payroll", match: (code) => code.startsWith("hr.payroll") }, { titleAr: "السلف والخصومات", titleEn: "Advances & deductions", match: (code) => /hr\.(advances|deductions)/.test(code) }, { titleAr: "ملف الموظف", titleEn: "Employee file", match: (code) => /hr\.employee_(documents|letters)/.test(code) }, { titleAr: "نهاية الخدمة", titleEn: "Final settlements", match: (code) => code.startsWith("hr.final_settlements") }] },
  { key: "platform", titleAr: "المنصة", titleEn: "Platform", sections: [{ titleAr: "الملفات والمستندات", titleEn: "Files & documents", match: (code) => code.startsWith("platform.files") }, { titleAr: "التشغيل والتاريخ", titleEn: "Operations & business date", match: (code) => /platform\.(business-date|observability)/.test(code) }, { titleAr: "الطباعة والتصدير", titleEn: "Print & export", match: (code) => code.startsWith("platform.output") }] },
  { key: "ai", titleAr: "بصيرة والذكاء", titleEn: "Basira & AI", sections: [{ titleAr: "استخدام بصيرة", titleEn: "Use Basira", match: (code) => code === "platform.ai.use" }, { titleAr: "مزود الذكاء", titleEn: "AI provider", match: (code) => /platform\.ai\.(configuration|provider)/.test(code) }, { titleAr: "هوية بصيرة", titleEn: "Basira identity", match: (code) => /platform\.ai\.(identity|system_identity)/.test(code) }] },
];

export function AdministrationRolesPanel({ language, session, overview, owner, onDone, onError }: Props) { const text = administrationText(language);
  const [editing, setEditing] = useState(false); const [editingRole, setEditingRole] = useState<Role | null>(null); const [values, setValues] = useState<RoleForm>({ code: "", nameAr: "", nameEn: "", permissionCodes: [] }); const [busy, setBusy] = useState(false); const [confirmDelete, setConfirmDelete] = useState(false);
  const roleSchemaFactory = useCallback<BaseerValidatedFormSchemaFactory>(({ z }) => z.object({ code: z.string().regex(/^[A-Z][A-Z0-9_]*$/, language === "ar" ? "استخدم أحرفاً كبيرة وشرطة سفلية فقط." : "Use uppercase letters, numbers and underscores only."), nameAr: z.string().trim().min(1, language === "ar" ? "أدخل الاسم بالعربية." : "Enter the Arabic name."), nameEn: z.string().trim().min(1, language === "ar" ? "أدخل الاسم بالإنجليزية." : "Enter the English name."), permissionCodes: z.array(z.string()).min(1, language === "ar" ? "اختر صلاحية واحدة على الأقل." : "Choose at least one permission.") }), [language]);
  const reset = () => { setEditing(false); setEditingRole(null); setValues({ code: "", nameAr: "", nameEn: "", permissionCodes: [] }); };
  const startEdit = (role: Role) => { if (role.isSystem) return; setEditingRole(role); setValues({ code: role.code, nameAr: role.nameAr, nameEn: role.nameEn, permissionCodes: role.permissionCodes }); setEditing(true); };
  const submit = async (next: RoleForm) => { if (!owner) return; setBusy(true); try { if (editingRole) await updateAdministrationRole(session, editingRole.id, { nameAr: next.nameAr, nameEn: next.nameEn, permissionCodes: next.permissionCodes }); else await createAdministrationRole(session, { code: next.code, nameAr: next.nameAr, nameEn: next.nameEn, permissionCodes: next.permissionCodes }); await onDone(); reset(); } catch (error) { onError(error); } finally { setBusy(false); setConfirmDelete(false); } };
  const remove = async () => { if (!owner || !editingRole) return; setBusy(true); try { await deleteAdministrationRole(session, editingRole.id); await onDone(); reset(); } catch (error) { onError(error); } finally { setBusy(false); setConfirmDelete(false); } };
  const toggle = (permissionCode: string, checked: boolean) => setValues((current) => ({ ...current, permissionCodes: checked ? [...new Set([...current.permissionCodes, permissionCode])] : current.permissionCodes.filter((item) => item !== permissionCode) }));
  if (editing) return <>{<section className="administration-section administration-role-editor"><header className="administration-section-heading"><div><p className="eyebrow">{text.roles}</p><h3>{editingRole ? text.editRoleName(displayName(language, editingRole)) : text.createRole}</h3></div><BaseerButton variant="secondary" type="button" onClick={reset} disabled={busy}>← {text.returnToRoles}</BaseerButton></header><BaseerValidatedFormField<RoleForm> id="administration-role" className="administration-role-form" values={values} schemaFactory={roleSchemaFactory} onValid={(next) => void submit(next)} errorSummaryLabel={text.checkRequiredFields}>{({ errors }) => <><div className="administration-role-basics"><label>{text.roleCode}<BaseerTextInput disabled={Boolean(editingRole)} aria-invalid={Boolean(errors.code)} value={values.code} onChange={(event) => setValues((current) => ({ ...current, code: event.target.value.toUpperCase() }))} placeholder="CUSTOM_SALES_ROLE" />{errors.code ? <small role="alert">{errors.code.message}</small> : null}</label><label>{text.arabicName}<BaseerTextInput aria-invalid={Boolean(errors.nameAr)} value={values.nameAr} onChange={(event) => setValues((current) => ({ ...current, nameAr: event.target.value }))} />{errors.nameAr ? <small role="alert">{errors.nameAr.message}</small> : null}</label><label>{text.englishName}<BaseerTextInput aria-invalid={Boolean(errors.nameEn)} value={values.nameEn} onChange={(event) => setValues((current) => ({ ...current, nameEn: event.target.value }))} />{errors.nameEn ? <small role="alert">{errors.nameEn.message}</small> : null}</label></div><fieldset className="administration-permission-picker" aria-invalid={Boolean(errors.permissionCodes)}><legend>{text.selectedPermissions} <small>{values.permissionCodes.length}</small></legend>{permissionModules.map((module) => <PermissionModule key={module.key} moduleKey={module.key} language={language} title={language === "ar" ? module.titleAr : module.titleEn} sections={module.sections} permissions={overview.permissions} selected={values.permissionCodes} onToggle={toggle} />)}{errors.permissionCodes ? <small role="alert">{errors.permissionCodes.message}</small> : null}</fieldset><footer className="administration-role-editor__footer"><BaseerButton variant="secondary" type="button" onClick={reset} disabled={busy}>{text.cancel}</BaseerButton>{editingRole && <BaseerButton variant="danger" type="button" onClick={() => setConfirmDelete(true)} disabled={busy}>{text.deleteRole}</BaseerButton>}<BaseerButton disabled={busy}>{busy ? text.saving : editingRole ? text.saveChanges : text.createRole}</BaseerButton></footer></>}</BaseerValidatedFormField></section>}<BaseerConfirmDialog open={confirmDelete} title={text.deleteRole} message={`${text.deleteRole}: ${editingRole ? displayName(language, editingRole) : ""}`} confirmLabel={text.deleteRole} language={language} destructive busy={busy} onCancel={() => setConfirmDelete(false)} onConfirm={() => void remove()} /></>;
  return <section className="administration-section administration-roles-section"><header className="administration-section-heading"><div><h3>{text.roles}</h3></div>{owner && <BaseerButton type="button" onClick={() => { reset(); setEditing(true); }}>+ {text.addRole}</BaseerButton>}</header><div className="administration-role-cards">{overview.roles.map((role) => <article key={role.id}><span className={role.isSystem ? "administration-role-card__system" : "administration-role-card__custom"}>{role.isSystem ? text.defaultRole : text.customRole}</span><strong>{displayName(language, role)}</strong><small>{language === "ar" ? role.nameEn : role.nameAr}</small><p>{role.permissionCodes.length} {text.permissions}</p>{owner && !role.isSystem && <BaseerButton variant="secondary" type="button" onClick={() => startEdit(role)}>{text.editPermissions}</BaseerButton>}</article>)}</div></section>;
}
function PermissionModule({ moduleKey, language, title, sections, permissions, selected, onToggle }: { moduleKey: string; language: "ar" | "en"; title: string; sections: readonly PermissionSection[]; permissions: Permission[]; selected: string[]; onToggle: (permissionCode: string, checked: boolean) => void }) { const text = administrationText(language); const visible = sections.map((section) => ({ ...section, permissions: permissions.filter((permission) => section.match(permission.code)) })).filter((section) => section.permissions.length > 0); const classified = new Set(visible.flatMap((section) => section.permissions.map((permission) => permission.code))); const remaining = permissions.filter((permission) => permission.module === moduleKey && !classified.has(permission.code)); if (remaining.length) visible.push({ titleAr: "صلاحيات إضافية", titleEn: "Additional capabilities", match: () => false, permissions: remaining }); if (!visible.length) return null; const count = visible.reduce((total, section) => total + section.permissions.length, 0); return <section className="administration-permission-module"><header><h4>{title}</h4><span>{count} {text.permissions}</span></header><div className="administration-permission-sections">{visible.map((section) => <section className="administration-permission-section" key={section.titleAr}><h5>{language === "ar" ? section.titleAr : section.titleEn}</h5><div>{section.permissions.map((permission) => <label key={permission.code} className={permission.risk === "sensitive" ? "is-sensitive" : ""}><BaseerCheckbox checked={selected.includes(permission.code)} onChange={(event) => onToggle(permission.code, event.target.checked)} /><span>{displayName(language, permission)}</span>{permission.risk === "sensitive" && <small>{text.sensitive}</small>}</label>)}</div></section>)}</div></section>; }
