import { defineLocalizedCopy, type BaseerLanguage } from "./baseer-ui-copy";

export const backupRecoveryCopy = defineLocalizedCopy({
  ar: {
    eyebrow: "Baseer ERP / الإدارة",
    title: "النسخ الاحتياطي والاستعادة",
    description: "متابعة أرشيفات الشركات وجودتها وتحضير الاستعادة الآمنة. تصدير الأرشيف وتنزيله المشفّر موجودان في الخادم؛ هذه الشاشة لا تعرض إلا بيانات خادمة موثوقة بعد ربطها.",
    gate: "بوابة البناء 2",
    gateStatus: "بانتظار ربط metadata الموثوقة",
    noApiTitle: "الأرشيف الحالي إعدادات جزئية فقط",
    noApiDescription: "يغطي الأرشيف الحالي إعدادات مالية مختارة فقط (PARTIAL_CONFIGURATION_ONLY)، وليس نسخة كاملة قابلة للاستعادة. قيمة restoreEligible هي false؛ لا يجوز تنزيله أو عرضه كنسخة تعافٍ كاملة. يظل التنزيل معطلاً هنا حتى تصل metadata متحققة تشمل الاسم والحجم والبصمة والصيغة وحالة التحقق.",
    healthTitle: "صحة الحماية",
    healthDescription: "تظهر هذه المؤشرات من العامل الخلفي بعد إتاحته، وليست تقديرات من المتصفح.",
    lastVerifiedBackup: "آخر نسخة متحقق منها",
    recoveryPoint: "أقدم نقطة قابلة للاستعادة",
    storage: "التخزين المحلي",
    restoreTest: "آخر اختبار استعادة",
    unavailable: "غير متاح",
    waitingForApi: "بانتظار ربط بيانات الخادم",
    backupTitle: "النسخ المؤرشفة",
    backupDescription: "ستظهر النسخ المعتمدة فقط بعد اكتمال التصدير والتشفير وفحص البصمات.",
    noBackupsTitle: "لا توجد metadata موثوقة للعرض",
    noBackupsDescription: "توجد واجهات خادمة للتصدير والتنزيل المشفّر، لكن قائمة الوظائف وmetadata الأرشيف لم تُربطا بهذه الشاشة بعد. لن يُفعّل التنزيل قبل وصول الاسم الآمن والحجم وبصمة SHA-256 والصيغة ووقت التحقق من عقد الخادم.",
    qualityTitle: "فحص جودة النسخة",
    qualityDescription: "لا تصبح النسخة صالحة إلا بعد اكتمال الملفات، وفحص SHA-256، وفك الضغط والتشفير، ومطابقة الأعداد والمرفقات.",
    qualityCheckArchive: "سلامة الأرشيف والبنية",
    qualityCheckChecksums: "بصمات الملفات والمرفقات",
    qualityCheckConsistency: "اتساق بيانات الشركة",
    qualityCheckRecoverability: "تقرير قابل للاستعادة",
    restoreTitle: "مسار الاستيراد والاستعادة",
    restoreDescription: "سيظهر التقدم الحقيقي من العامل الخلفي عند اكتمال واجهات الاستيراد. لا تستعيد الواجهة أي بيانات بنفسها.",
    restorePending: "بانتظار واجهة الاستيراد",
    restoreUpload: "رفع الملف القابل للاستكمال",
    restoreVerify: "فحص سلامة الملف والتوافق",
    restoreDiscover: "استكشاف الشركات واختيار الشركة",
    restoreStage: "تجهيز البيانات في منطقة آمنة",
    restoreValidate: "التحقق من العلاقات والأرصدة",
    restoreApply: "التأكيد والتطبيق والتحقق النهائي",
    auditTitle: "سجل التدقيق",
    auditDescription: "سيسجل العامل الخلفي عمليات الإنشاء والتحميل والفحص والاستيراد والنتيجة. لا توجد أحداث محملة من الخادم حالياً.",
    noAuditTitle: "لا توجد أحداث تدقيق معروضة",
    noAuditDescription: "بعد الربط، يظهر هنا المستخدم، الوقت، نوع العملية، الحالة، الشركة، ومعرّف الدعم دون إظهار مفاتيح أو روابط حساسة.",
    dataBoundaryTitle: "حدود هذه الشاشة",
    dataBoundaryDescription: "هذه الصفحة مخصصة لأرشيفات بصير والشركات فقط. لا تعرض أو تنزّل النسخة الكاملة للسيرفر، لأنها قد تحتوي على تطبيقات وإعدادات أخرى.",
  },
  en: {
    eyebrow: "Baseer ERP / Administration",
    title: "Backup & recovery",
    description: "Track company archives and their quality, and prepare safe recovery. Server-side archive export and encrypted download exist; this screen shows only trusted server data after it is connected.",
    gate: "Build gate 2",
    gateStatus: "Waiting for trusted metadata connection",
    noApiTitle: "The current archive covers partial configuration only",
    noApiDescription: "The current archive contains only selected finance configuration (PARTIAL_CONFIGURATION_ONLY); it is not a complete recovery backup. restoreEligible is false, so it must not be presented or downloaded here as a full recovery archive. Download remains disabled until verified metadata supplies the safe filename, size, hash, format, and verification state.",
    healthTitle: "Protection health",
    healthDescription: "These indicators will come from the background worker when available; they are never browser estimates.",
    lastVerifiedBackup: "Last verified backup",
    recoveryPoint: "Oldest recoverable point",
    storage: "Local storage",
    restoreTest: "Last restore test",
    unavailable: "Unavailable",
    waitingForApi: "Waiting for server-data connection",
    backupTitle: "Archived backups",
    backupDescription: "Only approved archives will appear after export, encryption, and checksum verification complete.",
    noBackupsTitle: "No trusted archive metadata to show",
    noBackupsDescription: "Server endpoints for export and encrypted download exist, but job listing and archive metadata are not connected to this screen yet. Download will stay disabled until the server contract supplies a safe name, size, SHA-256 hash, format, and verification time.",
    qualityTitle: "Backup quality verification",
    qualityDescription: "An archive cannot be marked usable until its contents, SHA-256 checksums, compression and encryption, counts, and attachments have been verified.",
    qualityCheckArchive: "Archive and structure integrity",
    qualityCheckChecksums: "File and attachment checksums",
    qualityCheckConsistency: "Company data consistency",
    qualityCheckRecoverability: "Recoverability report",
    restoreTitle: "Import & recovery path",
    restoreDescription: "Actual progress will arrive from the background worker once import interfaces are complete. The UI never restores data itself.",
    restorePending: "Waiting for import interface",
    restoreUpload: "Resumable file upload",
    restoreVerify: "File integrity and compatibility check",
    restoreDiscover: "Discover and select a company",
    restoreStage: "Prepare data in a safe staging area",
    restoreValidate: "Validate references and balances",
    restoreApply: "Confirm, apply, and verify the result",
    auditTitle: "Audit trail",
    auditDescription: "The background worker will log create, download, verify, import, and outcome events. No events are loaded from the server yet.",
    noAuditTitle: "No audit events are displayed",
    noAuditDescription: "After connection, this will show the user, time, action, status, company, and support ID without exposing keys or sensitive links.",
    dataBoundaryTitle: "Screen boundary",
    dataBoundaryDescription: "This screen is for Baseer and company archives only. It does not expose or download the full server backup, which can contain other apps and settings.",
  },
});

export function backupRecoveryText(language: BaseerLanguage) {
  return backupRecoveryCopy[language];
}
