import { defineLocalizedCopy } from "./baseer-ui-copy";

export const baseerLoginCopy = defineLocalizedCopy({
  ar: {
    welcome: "مرحباً بك في بصير",
    secureAccess: "دخول آمن ومباشر إلى مساحة عملك",
    login: "البريد الإلكتروني أو اسم المستخدم",
    password: "كلمة المرور",
    show: "إظهار",
    hide: "إخفاء",
    submit: "تسجيل الدخول",
    loading: "جارٍ التحقق…",
    choose: "اختر الشركة",
    noCompanies: "لا توجد شركة متاحة لهذا المستخدم.",
    other: "استخدام حساب آخر",
    activateOwner: "تفعيل المالك العام لأول مرة",
    activationDescription: "أدخل رمز التفعيل مرة واحدة واختر كلمة مرورك الجديدة.",
    activationCode: "رمز التفعيل لمرة واحدة",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور",
    activate: "تفعيل الحساب",
    backToSignIn: "العودة للدخول",
    passwordTooShort: "يجب أن تكون كلمة المرور 6 خانات على الأقل.",
    passwordMismatch: "كلمتا المرور غير متطابقتين.",
    activationComplete: "تم تفعيل الحساب. سجّل الدخول بكلمة المرور الجديدة.",
    failed: "تعذر تسجيل الدخول. تحقق من بياناتك ثم أعد المحاولة.",
    sessionSetupFailed: "تم التحقق من بيانات الدخول، لكن تعذر فتح مساحة العمل. أعد المحاولة لاحقاً.",
    serviceUnavailable: "الخدمة غير متاحة حالياً. أعد المحاولة لاحقاً.",
    switchLanguage: "English",
  },
  en: {
    welcome: "Welcome to Baseer",
    secureAccess: "Secure, direct access to your workspace",
    login: "Email or username",
    password: "Password",
    show: "Show",
    hide: "Hide",
    submit: "Sign in",
    loading: "Verifying…",
    choose: "Choose a company",
    noCompanies: "No company is available for this user.",
    other: "Use another account",
    activateOwner: "Activate general owner",
    activationDescription: "Enter the one-time activation code and choose a new password.",
    activationCode: "One-time activation code",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    activate: "Activate account",
    backToSignIn: "Back to sign in",
    passwordTooShort: "Password must be at least 6 characters.",
    passwordMismatch: "Passwords do not match.",
    activationComplete: "Your account is active. Sign in with the new password.",
    failed: "Could not sign in. Check your details and try again.",
    sessionSetupFailed: "Your sign-in was verified, but the workspace could not be opened. Please try again shortly.",
    serviceUnavailable: "The service is temporarily unavailable. Please try again shortly.",
    switchLanguage: "العربية",
  },
});
