import { defineLocalizedCopy } from "./baseer-ui-copy";

export const baseerLoginCopy = defineLocalizedCopy({
  ar: {
    welcome: "مرحباً بك في بصير",
    secureAccess: "دخول آمن ومباشر إلى مساحة عملك",
    login: "البريد الإلكتروني أو اسم المستخدم",
    password: "كلمة المرور",
    show: "إظهار",
    hide: "إخفاء",
    submit: "تسجيل الدخول",
    loading: "جارٍ التحقق…",
    choose: "اختر الشركة",
    noCompanies: "لا توجد شركة متاحة لهذا المستخدم.",
    other: "استخدام حساب آخر",
    failed: "تعذر تسجيل الدخول. تحقق من بياناتك ثم أعد المحاولة.",
    sessionSetupFailed: "تم التحقق من بيانات الدخول، لكن تعذر فتح مساحة العمل. أعد المحاولة لاحقاً.",
    serviceUnavailable: "الخدمة غير متاحة حالياً. أعد المحاولة لاحقاً.",
    switchLanguage: "English",
  },
  en: {
    welcome: "Welcome to Baseer",
    secureAccess: "Secure, direct access to your workspace",
    login: "Email or username",
    password: "Password",
    show: "Show",
    hide: "Hide",
    submit: "Sign in",
    loading: "Verifying…",
    choose: "Choose a company",
    noCompanies: "No company is available for this user.",
    other: "Use another account",
    failed: "Could not sign in. Check your details and try again.",
    sessionSetupFailed: "Your sign-in was verified, but the workspace could not be opened. Please try again shortly.",
    serviceUnavailable: "The service is temporarily unavailable. Please try again shortly.",
    switchLanguage: "العربية",
  },
});
