import { defineLocalizedCopy, type BaseerLanguage } from "./baseer-ui-copy";

const categoryCopy = defineLocalizedCopy({
  ar: {
    title: "الفئات والتصنيفات", nameAr: "الاسم بالعربية", nameEn: "الاسم بالإنجليزية", refresh: "تحديث", description: "شجرة البنود المالية المرتبطة بالسجل المحاسبي.", addCategory: "إضافة فئة", editCategory: "تعديل الفئة", archiveCategory: "أرشفة الفئة", archiveTitle: "أرشفة الفئة", archiveMessage: "لن تُحذف الحركات السابقة؛ ستتوقف الفئة عن الاستخدام الجديد.", search: "ابحث بالاسم أو الكود", allKinds: "كل الأنواع", groups: "المجموعات", posting: "قابلة للترحيل", archived: "مؤرشفة", active: "نشطة", code: "الكود", category: "الفئة", kind: "النوع", parent: "المجموعة الرئيسية", noParent: "بدون مجموعة", suggestedSupplier: "المورد المقترح", noSuggestedSupplier: "بدون مورد مقترح", acceptsPosting: "تقبل الترحيل", groupOnly: "مجموعة تنظيمية فقط", save: "حفظ الفئة", add: "إضافة الفئة", clear: "مسح الفلاتر", noResults: "لا توجد فئات مطابقة.", action: "الإجراء", edit: "تعديل", archive: "أرشفة", categorySaved: "تم حفظ الفئة وربطها بحسابها المالي.", categoryArchived: "تمت الأرشفة مع الاحتفاظ بالسجل السابق.", loading: "جارٍ تحميل الفئات…", categoriesCount: "إجمالي الفئات", activeCategories: "الفئات النشطة", postingCategories: "فئات الترحيل", groupCategories: "المجموعات", archivedCategories: "المؤرشفة", status: "الحالة", showArchived: "إظهار المؤرشف", accountingTypeFixed: "النوع المحاسبي لا يتغير بعد الإنشاء.", tableCaption: "شجرة الفئات والتصنيفات المالية", requiredNames: "أدخل الاسم بالعربية والإنجليزية والكود.",
  },
  en: {
    title: "Categories & classifications", nameAr: "Arabic name", nameEn: "English name", refresh: "Refresh", description: "Financial item tree linked to the accounting ledger.", addCategory: "Add category", editCategory: "Edit category", archiveCategory: "Archive category", archiveTitle: "Archive category", archiveMessage: "Prior movements remain intact; the category will stop being available for new activity.", search: "Search by name or code", allKinds: "All types", groups: "Groups", posting: "Posting", archived: "Archived", active: "Active", code: "Code", category: "Category", kind: "Type", parent: "Parent group", noParent: "No parent", suggestedSupplier: "Suggested supplier", noSuggestedSupplier: "No suggested supplier", acceptsPosting: "Accepts posting", groupOnly: "Organizational group only", save: "Save category", add: "Add category", clear: "Clear filters", noResults: "No matching categories.", action: "Action", edit: "Edit", archive: "Archive", categorySaved: "The category and linked financial account were saved.", categoryArchived: "Archived; prior activity remains intact.", loading: "Loading categories…", categoriesCount: "Total categories", activeCategories: "Active categories", postingCategories: "Posting categories", groupCategories: "Groups", archivedCategories: "Archived", status: "Status", showArchived: "Show archived", accountingTypeFixed: "The accounting type is fixed after creation.", tableCaption: "Financial categories and classifications tree", requiredNames: "Enter the Arabic name, English name, and code.",
  },
});

export function categoryText(language: BaseerLanguage) { return categoryCopy[language]; }
