import { defineLocalizedCopy } from "./baseer-ui-copy";

export type DailySalesLanguage = "ar" | "en";

export const dailySalesText = defineLocalizedCopy({
  ar: {
    eyebrow: "المبيعات اليومية",
    title: "ملخص المبيعات اليومي",
    subtitle:
      "انقل في نهاية اليوم ملخص المبيعات من نظام نقاط البيع الخارجي حسب خزائن التحصيل. الضريبة والقيود تثبت في الخادم فقط.",
    noSession: "سجّل الدخول واختر الشركة أولًا",
    noSessionDetail:
      "هذه الشاشة لا تحفظ رمز الدخول أو الشركة يدويًا، ولا تعرض أرقامًا تجريبية. تظهر البيانات بعد إنشاء جلسة الشركة من تسجيل الدخول.",
    refresh: "تحديث",
    date: "تاريخ الملخص",
    dateHint: "اختر تاريخ العمل. لا يقبل النظام تاريخًا بعد اليوم.",
    scope: "الفترة",
    morning: "صباح",
    evening: "مساء",
    all: "كل اليوم",
    customers: "عدد العملاء",
    channels: "قنوات التحصيل",
    addChannel: "إضافة قناة",
    amount: "الإجمالي شامل الضريبة",
    enterAmount: "أدخل مبلغًا موجبًا في خزنة تحصيل واحدة على الأقل.",
    cashHandover: "تسليم كاش للمحاسب",
    cashVault: "خزنة التسليم",
    scopeHint:
      "اختر شفتًا واحدًا أو «كل اليوم» فقط؛ لا يجتمع كل اليوم مع شفتين.",
    notes: "ملاحظات اختيارية",
    create: "إدخال ملخص",
    saveAndSend: "حفظ وإرسال الملخص",
    entryIntro:
      "انقل أرقام ملخص نقاط البيع الخارجي: مبلغ كل خزنة مستخدمة وعدد العملاء. الخادم يتحقق ويحفظ الأثر المحاسبي.",
    entryMode: "نوع الإدخال",
    dayOffAction: "بدون عمل اليوم",
    dayOffTitle: "تسجيل يوم بدون عمل",
    dayOffIntro:
      "سجّل سبب عدم العمل فقط. لا تظهر مبالغ أو خزائن، ولا ينشأ قيد مالي.",
    dayOffNoMoney: "هذا اليوم لا يحتوي ملخص مبيعات.",
    dayOffNoMoneyHint:
      "يُستبعد من متوسط أيام التشغيل، ويبقى ظاهرًا بسببه في التقويم والتقارير.",
    dayOffReason: "سبب عدم العمل",
    dayOffFromDate: "من تاريخ",
    dayOffToDate: "إلى تاريخ",
    dayOffRangeHint: "اختر نطاقًا متصلًا حتى 31 يومًا. يحفظ النظام النطاق كاملًا أو لا يحفظ شيئًا.",
    dayOffNote: "ملاحظة إضافية",
    dayOffNoteRequired: "أضف ملاحظة تشرح سبب عدم العمل.",
    saveDayOff: "حفظ أيام بدون عمل",
    dayOffSuccess: "تم توثيق أيام بدون عمل. لم ينشأ أي قيد مالي.",
    dayOff: "بدون عمل",
    dayOffExcluded: "مستبعد من معدل التشغيل",
    WEEKLY_CLOSURE: "إغلاق أسبوعي",
    EID: "عيد",
    HOLIDAY: "عيد أو عطلة",
    MAINTENANCE: "صيانة",
    EMERGENCY: "طارئ",
    OTHER: "سبب آخر",
    closeDialog: "إغلاق",
    entryTotal: "إجمالي الإدخال",
    entryTotalHint: "قيمة خادمية بعد التحقق من مبالغ الخزائن والضريبة.",
    previewLoading: "جارٍ التحقق…",
    correct: "حفظ التعديل",
    cancelEdit: "إلغاء",
    edit: "تعديل",
    reverse: "إلغاء الملخص",
    reverseTitle: "إلغاء الملخص",
    reverseIntro: "هل تريد إلغاء هذا الملخص؟",
    reverseRecord: "السجل المحدد",
    reverseReason: "سبب الإلغاء",
    reverseConfirm: "إلغاء",
    calendar: "التقويم التشغيلي",
    closings: "سجل المبيعات",
    shiftReport: "تقرير الشفتات للشهر",
    cashHandoverReport: "إجمالي تسليم الكاش للمحاسب",
    cashHandoverShort: "تسليم الكاش",
    handoverRecords: "سجل تسليم",
    actions: "إجراءات",
    notAvailable: "غير متاح",
    noClosings: "لا يوجد ملخص مبيعات محفوظ خلال هذه الفترة.",
    noClosing: "لا يوجد ملخص",
    pending: "بيانات ناقصة",
    recorded: "تم الحفظ",
    closed: "مغلق",
    open: "عمل",
    partial: "جزئي",
    net: "الصافي",
    vat: "الضريبة",
    gross: "الإجمالي",
    version: "الإصدار",
    status: "الحالة",
    loaded: "تم التحديث من الخادم",
    loadMore: "تحميل المزيد",
    saving: "جارٍ الحفظ…",
    error:
      "تعذر إتمام العملية. تحقق من الصلاحية والفترة المالية ثم أعد المحاولة.",
    success: "تم حفظ وإرسال ملخص المبيعات للتحقق منه في الخادم.",
    dateRange: "عرض الشهر الحالي",
    calendarHint:
      "يوم العمل المفتوح بلا ملخص مبيعات هو بيانات ناقصة. اختر بدون عمل لتوثيق الإجازة أو الإغلاق واستبعاده من معدل التشغيل.",
    emptyChannels:
      "لا توجد خزائن بيع نشطة للشركة. يجب تجهيز خزائن قنوات التحصيل من إعداد الشركة أولًا.",
    selectVault: "اختر الخزنة",
    setDay: "تحديث حالة اليوم",
    dayStatus: "حالة اليوم",
    saveDay: "حفظ حالة اليوم",
    reason: "سبب الإغلاق/الملاحظة",
    recordedHint:
      "يُجمع للمتابعة الشهرية فقط؛ لا يدخل خزينة ولا ينشئ قيدًا أو يغيّر الإيراد أو الرصيد.",
    serverOnly: "كل الأرقام أدناه نتائج خادمية موثقة.",
    reversalHint: "تظهر العمليات الملغاة بوضوح في السجل.",
    historyLimited: "بحسب صلاحيتك: تظهر آخر {count} ملخصات فقط.",
    POSTED: "مثبت",
    REVERSED: "ملغى",
    tenantCode: "رمز المؤسسة",
    login: "اسم المستخدم أو البريد الإلكتروني",
    password: "كلمة المرور",
    signIn: "تسجيل الدخول",
    signingIn: "جارٍ التحقق…",
    signInError: "تعذر تسجيل الدخول أو لا توجد شركة متاحة.",
    chooseCompany: "اختر الشركة",
    sessionOnly:
      "تنتهي جلسة العرض عند إغلاق المتصفح. لا يُحفظ رمز الدخول في ملفات النظام أو الكود.",
    CASH: "نقد",
    BANK: "بنك",
    APP: "تطبيقات",
  },
  en: {
    eyebrow: "Sales operations",
    title: "Daily sales closing",
    subtitle:
      "Record a daily sales summary by collection vault. VAT, journals, and summaries are calculated and sealed by the server only.",
    noSession: "Sign in and select a company first",
    noSessionDetail:
      "This screen does not accept or store a token or company manually, and it shows no demo figures. Data appears only after the company session is created by sign-in.",
    refresh: "Refresh",
    date: "Closing date",
    dateHint: "Choose the business date. Future dates are not accepted.",
    scope: "Scope",
    morning: "Morning",
    evening: "Evening",
    all: "Whole day",
    customers: "Customer count",
    channels: "Collection channels",
    addChannel: "Add channel",
    amount: "Gross amount incl. VAT",
    enterAmount: "Enter a positive amount for at least one collection vault.",
    cashHandover: "Cash handover to accountant",
    cashVault: "Handover vault",
    scopeHint:
      "Choose one shift or Whole day only; Whole day cannot be combined with shifts.",
    notes: "Optional notes",
    create: "Add summary",
    saveAndSend: "Save and send summary",
    entryIntro:
      "Enter only the closing summary and collection channels. The server verifies and calculates balances, VAT, and journals.",
    entryMode: "Entry type",
    dayOffAction: "No work today",
    dayOffTitle: "Record a day off",
    dayOffIntro:
      "Record only why the business did not operate. No amounts or vaults are shown and no journal is created.",
    dayOffNoMoney: "This day has no sales summary.",
    dayOffNoMoneyHint:
      "It is excluded from the operating-day average and remains visible with its reason in calendar and reports.",
    dayOffReason: "No-work reason",
    dayOffFromDate: "From date",
    dayOffToDate: "To date",
    dayOffRangeHint: "Choose one continuous range of up to 31 days. It saves completely or not at all.",
    dayOffNote: "Additional note",
    dayOffNoteRequired: "Add a note explaining the no-work reason.",
    saveDayOff: "Save days off",
    dayOffSuccess:
      "The day off was documented. No financial journal was created.",
    dayOff: "Day off",
    dayOffExcluded: "Excluded from operating average",
    WEEKLY_CLOSURE: "Weekly closure",
    EID: "Eid",
    HOLIDAY: "Holiday",
    MAINTENANCE: "Maintenance",
    EMERGENCY: "Emergency",
    OTHER: "Other",
    closeDialog: "Close",
    entryTotal: "Entry total",
    entryTotalHint: "Server value after validating vault amounts and VAT.",
    previewLoading: "Verifying…",
    correct: "Save correction",
    cancelEdit: "Cancel",
    edit: "Edit",
    reverse: "Cancel summary",
    reverseTitle: "Confirm summary cancellation",
    reverseIntro: "Cancel this summary?",
    reverseRecord: "Selected record",
    reverseReason: "Cancellation reason",
    reverseConfirm: "Cancel",
    calendar: "Operational calendar",
    closings: "Sales register",
    shiftReport: "Monthly shift report",
    cashHandoverReport: "Cash handed to accountant",
    cashHandoverShort: "Cash handover",
    handoverRecords: "handover records",
    actions: "Actions",
    notAvailable: "N/A",
    noClosings: "No closings in this period.",
    noClosing: "No closing",
    pending: "Pending",
    recorded: "Recorded",
    closed: "Closed",
    open: "Operating",
    partial: "Partial",
    net: "Net",
    vat: "VAT",
    gross: "Gross",
    version: "Version",
    status: "Status",
    loaded: "Updated from the server",
    loadMore: "Load more",
    saving: "Saving…",
    error:
      "The operation could not be completed. Check access and the financial period, then try again.",
    success: "The operation was saved and verified by the server.",
    dateRange: "Current month",
    calendarHint:
      "An open day without a closing is incomplete data. Use Day off to document a closure and exclude it from the operating average.",
    emptyChannels:
      "There are no active sales vaults for this company. Set up collection vaults first.",
    selectVault: "Select a vault",
    setDay: "Update day status",
    dayStatus: "Day status",
    saveDay: "Save day status",
    reason: "Closure reason / note",
    recordedHint:
      "It is tracked only in the monthly handover report; it never enters a vault, creates a journal, or changes revenue or balance.",
    serverOnly: "All figures below are server-owned, traceable results.",
    reversalHint: "Cancelled operations remain clearly visible in the register.",
    historyLimited: "Your access shows the latest {count} closings only.",
    POSTED: "Posted",
    REVERSED: "Cancelled",
    tenantCode: "Tenant code",
    login: "Username or email",
    password: "Password",
    signIn: "Sign in",
    signingIn: "Verifying…",
    signInError: "Sign-in failed or no company is available.",
    chooseCompany: "Choose company",
    sessionOnly:
      "The viewing session ends when the browser closes. No sign-in token is stored in system files or source code.",
    CASH: "Cash",
    BANK: "Bank",
    APP: "App",
  },
});
