import { useCallback, useEffect, useMemo, useState } from "react";

import { presentBaseerApiError } from "./baseer-api-error";
import { BaseerButton } from "./baseer-button";
import { BaseerCard } from "./baseer-card";
import { BaseerDialog } from "./baseer-dialog";
import { DataTable } from "./data-table";
import { activeSession, requestId } from "./daily-sales-client";
import { approveHrCompensationPolicyVersion, createHrCompensationPolicy, createHrCompensationPolicyVersion, listHrCompensationPolicies, type HrCompensationPolicy, type HrCompensationPolicyVersion } from "./hr-client";

type Language = "ar" | "en";
const today = () => new Date().toISOString().slice(0, 10);
const month = () => today().slice(0, 7);
type PolicyForm = { code: string; nameAr: string; nameEn: string; effectiveFrom: string };
const emptyPolicy = (): PolicyForm => ({ code: "", nameAr: "", nameEn: "", effectiveFrom: `${month()}-01` });

/** Policy administration deliberately exposes no coefficients: formulas remain server-controlled. */
export function HrCompensationPoliciesDialog({ open, language, onClose, onError, onChanged }: { open: boolean; language: Language; onClose: () => void; onError: (message: string) => void; onChanged: () => Promise<void> }) {
  const ar = language === "ar";
  const [policies, setPolicies] = useState<HrCompensationPolicy[]>([]);
  const [loading, setLoading] = useState(false);
  const [busy, setBusy] = useState(false);
  const [createOpen, setCreateOpen] = useState(false);
  const [versionPolicy, setVersionPolicy] = useState<HrCompensationPolicy | null>(null);
  const [form, setForm] = useState<PolicyForm>(emptyPolicy());
  const [versionDate, setVersionDate] = useState(`${month()}-01`);
  const load = useCallback(async () => { const session = activeSession(); if (!session) return; setLoading(true); try { setPolicies((await listHrCompensationPolicies(session)).policies); } catch (error) { onError(presentBaseerApiError(error, language, ar ? "تحميل السياسات" : "Loading policies")); } finally { setLoading(false); } }, [ar, language, onError]);
  useEffect(() => { if (open) void load(); }, [load, open]);
  const create = async (event: React.FormEvent) => { event.preventDefault(); const session = activeSession(); if (!session || busy) return; setBusy(true); try { await createHrCompensationPolicy(session, { code: form.code.trim().toUpperCase(), nameAr: form.nameAr, nameEn: form.nameEn || undefined, effectiveFrom: form.effectiveFrom, idempotencyKey: requestId() }); setCreateOpen(false); setForm(emptyPolicy()); await load(); await onChanged(); } catch (error) { onError(presentBaseerApiError(error, language, ar ? "إنشاء السياسة" : "Creating policy")); } finally { setBusy(false); } };
  const createVersion = async (event: React.FormEvent) => { event.preventDefault(); const session = activeSession(); if (!session || busy || !versionPolicy) return; setBusy(true); try { await createHrCompensationPolicyVersion(session, { policyId: versionPolicy.id, effectiveFrom: versionDate, idempotencyKey: requestId() }); setVersionPolicy(null); await load(); await onChanged(); } catch (error) { onError(presentBaseerApiError(error, language, ar ? "إنشاء إصدار" : "Creating version")); } finally { setBusy(false); } };
  const approve = async (version: HrCompensationPolicyVersion) => { const session = activeSession(); if (!session || busy) return; setBusy(true); try { await approveHrCompensationPolicyVersion(session, { policyVersionId: version.id, idempotencyKey: requestId() }); await load(); await onChanged(); } catch (error) { onError(presentBaseerApiError(error, language, ar ? "اعتماد الإصدار" : "Approving version")); } finally { setBusy(false); } };
  const rows = useMemo(() => policies.flatMap((policy) => policy.versions.map((version) => ({ policy, version }))), [policies]);
  const columns = [{ id: "policy", header: ar ? "السياسة" : "Policy", cell: (row: { policy: HrCompensationPolicy; version: HrCompensationPolicyVersion }) => `${row.policy.code} · ${ar ? row.policy.nameAr : row.policy.nameEn ?? row.policy.nameAr}` }, { id: "version", header: ar ? "الإصدار" : "Version", cell: (row: { version: HrCompensationPolicyVersion }) => `v${row.version.versionNumber}`, width: "7rem" }, { id: "from", header: ar ? "السريان" : "Effective", cell: (row: { version: HrCompensationPolicyVersion }) => row.version.effectiveFrom, width: "10rem" }, { id: "formula", header: ar ? "المعادلة" : "Formula", cell: () => ar ? "قياسية سعودية" : "Saudi standard", width: "12rem" }, { id: "status", header: ar ? "الحالة" : "Status", cell: (row: { version: HrCompensationPolicyVersion }) => ({ DRAFT: ar ? "مسودة" : "Draft", APPROVED: ar ? "معتمد" : "Approved", SUPERSEDED: ar ? "مستبدل" : "Superseded" })[row.version.status], width: "9rem" }, { id: "action", header: ar ? "الإجراء" : "Action", cell: (row: { version: HrCompensationPolicyVersion }) => row.version.status === "DRAFT" ? <BaseerButton type="button" variant="secondary" disabled={busy} onClick={() => void approve(row.version)}>{ar ? "اعتماد" : "Approve"}</BaseerButton> : "—", width: "10rem" }];
  return <><BaseerDialog open={open} title={ar ? "سياسات التعويض" : "Compensation policies"} language={language} busy={busy} onClose={onClose} footer={<><BaseerButton type="button" variant="secondary" onClick={onClose}>{ar ? "إغلاق" : "Close"}</BaseerButton><BaseerButton type="button" onClick={() => { setForm(emptyPolicy()); setCreateOpen(true); }}>{ar ? "إضافة سياسة" : "Add policy"}</BaseerButton></>}><BaseerCard><p>{ar ? "المعادلة قياسية ومحكومة من الخادم. لا يمكن إدخال معاملات أو نسب قانونية من الواجهة." : "The formula is standard and server-governed. Legal coefficients cannot be entered in the interface."}</p></BaseerCard>{loading ? <BaseerCard>{ar ? "جارٍ تحميل السياسات…" : "Loading policies…"}</BaseerCard> : rows.length ? <DataTable ariaLabel={ar ? "إصدارات سياسات التعويض" : "Compensation policy versions"} caption={ar ? "إصدارات سياسات التعويض" : "Compensation policy versions"} rows={rows} columns={columns} rowKey={(row) => row.version.id} /> : <BaseerCard>{ar ? "لا توجد سياسات تعويض بعد." : "No compensation policies yet."}</BaseerCard>}{policies.length ? <div className="baseer-inline-actions">{policies.map((policy) => <BaseerButton key={policy.id} type="button" variant="quiet" onClick={() => { setVersionDate(`${month()}-01`); setVersionPolicy(policy); }}>{ar ? `إصدار جديد: ${policy.nameAr}` : `New version: ${policy.nameEn ?? policy.nameAr}`}</BaseerButton>)}</div> : null}</BaseerDialog>
    <BaseerDialog open={createOpen} title={ar ? "إضافة سياسة تعويض" : "Add compensation policy"} language={language} busy={busy} onClose={() => setCreateOpen(false)} footer={<><BaseerButton type="button" variant="secondary" onClick={() => setCreateOpen(false)}>{ar ? "إلغاء" : "Cancel"}</BaseerButton><BaseerButton type="submit" form="hr-policy-create" disabled={busy}>{ar ? "حفظ السياسة" : "Save policy"}</BaseerButton></>}><form id="hr-policy-create" className="administration-form" onSubmit={(event) => void create(event)}><label>{ar ? "الكود" : "Code"}<input required value={form.code} onChange={(event) => setForm((value) => ({ ...value, code: event.target.value.toUpperCase() }))} /></label><label>{ar ? "الاسم بالعربية" : "Arabic name"}<input required value={form.nameAr} onChange={(event) => setForm((value) => ({ ...value, nameAr: event.target.value }))} /></label><label>{ar ? "الاسم بالإنجليزية" : "English name"}<input value={form.nameEn} onChange={(event) => setForm((value) => ({ ...value, nameEn: event.target.value }))} /></label><label>{ar ? "شهر أول إصدار" : "First version effective month"}<input required type="month" value={form.effectiveFrom.slice(0, 7)} onChange={(event) => setForm((value) => ({ ...value, effectiveFrom: `${event.target.value}-01` }))} /></label></form></BaseerDialog>
    <BaseerDialog open={Boolean(versionPolicy)} title={ar ? "إنشاء إصدار سياسة" : "Create policy version"} language={language} busy={busy} onClose={() => setVersionPolicy(null)} footer={<><BaseerButton type="button" variant="secondary" onClick={() => setVersionPolicy(null)}>{ar ? "إلغاء" : "Cancel"}</BaseerButton><BaseerButton type="submit" form="hr-policy-version" disabled={busy}>{ar ? "إنشاء مسودة" : "Create draft"}</BaseerButton></>}><form id="hr-policy-version" className="administration-form" onSubmit={(event) => void createVersion(event)}><label>{ar ? "شهر السريان" : "Effective month"}<input required type="month" value={versionDate.slice(0, 7)} onChange={(event) => setVersionDate(`${event.target.value}-01`)} /></label><p>{ar ? "سيُنشأ الإصدار كمسودة ويحتاج اعتماداً منفصلاً قبل أن يظهر في اتفاقات الموظفين." : "The version is created as a draft and must be approved before it appears in employee agreements."}</p></form></BaseerDialog></>;
}
