import { useBaseerForm, z } from "./baseer-form-state";
import { useCallback, useEffect, useMemo, useState } from "react";

import { presentBaseerApiError, presentBaseerLoadError } from "./baseer-api-error";
import { BaseerButton } from "./baseer-button";
import { BaseerCard } from "./baseer-card";
import { BaseerDialog } from "./baseer-dialog";
import { BaseerFormDialog } from "./baseer-form-dialog";
import { BaseerMonthPicker, BaseerTextInput } from "./baseer-form-fields";
import { BaseerFormGrid, BaseerFormSection } from "./baseer-form-section";
import { BaseerDataGridField as BaseerDataGrid } from "./baseer-data-grid-field";
import { activeSession, requestId } from "./daily-sales-client";
import { approveHrCompensationPolicyVersion, createHrCompensationPolicy, createHrCompensationPolicyVersion, listHrCompensationPolicies, type HrCompensationPolicy, type HrCompensationPolicyVersion } from "./hr-client";

type Language = "ar" | "en";
const today = () => new Date().toISOString().slice(0, 10);
const month = () => today().slice(0, 7);
type PolicyForm = { code: string; nameAr: string; nameEn: string; effectiveMonth: string };
const emptyPolicy = (): PolicyForm => ({ code: "", nameAr: "", nameEn: "", effectiveMonth: month() });
const policySchema = (language: Language) => z.object({ code: z.string().trim().min(2, language === "ar" ? "الكود مطلوب." : "Code is required."), nameAr: z.string().trim().min(2, language === "ar" ? "الاسم العربي مطلوب." : "Arabic name is required."), nameEn: z.string(), effectiveMonth: z.string().regex(/^\d{4}-\d{2}$/, language === "ar" ? "اختر شهر السريان." : "Choose an effective month.") });
const versionSchema = (language: Language) => z.object({ effectiveMonth: z.string().regex(/^\d{4}-\d{2}$/, language === "ar" ? "اختر شهر السريان." : "Choose an effective month.") });

/** Policy administration deliberately exposes no coefficients: formulas remain server-controlled. */
export function HrCompensationPoliciesDialog({ open, language, onClose, onError, onChanged }: { open: boolean; language: Language; onClose: () => void; onError: (message: string) => void; onChanged: () => Promise<void> }) {
  const ar = language === "ar";
  const [policies, setPolicies] = useState<HrCompensationPolicy[]>([]);
  const [loading, setLoading] = useState(false);
  const [busy, setBusy] = useState(false);
  const [createOpen, setCreateOpen] = useState(false);
  const [versionPolicy, setVersionPolicy] = useState<HrCompensationPolicy | null>(null);
  const policyForm = useBaseerForm<PolicyForm>({ schema: policySchema(language), defaultValues: emptyPolicy() });
  const versionForm = useBaseerForm<{ effectiveMonth: string }>({ schema: versionSchema(language), defaultValues: { effectiveMonth: month() } });
  const load = useCallback(async () => { const session = activeSession(); if (!session) return; setLoading(true); try { setPolicies((await listHrCompensationPolicies(session)).policies); } catch (error) { onError(presentBaseerLoadError(error, language, { ar: "سياسات التعويض", en: "compensation policies" })); } finally { setLoading(false); } }, [ar, language, onError]);
  useEffect(() => { if (open) void load(); }, [load, open]);
  const create = policyForm.handleSubmit(async (form) => { const session = activeSession(); if (!session || busy) return; setBusy(true); try { await createHrCompensationPolicy(session, { code: form.code.trim().toUpperCase(), nameAr: form.nameAr.trim(), nameEn: form.nameEn.trim() || undefined, effectiveFrom: `${form.effectiveMonth}-01`, idempotencyKey: requestId() }); setCreateOpen(false); policyForm.reset(emptyPolicy()); await load(); await onChanged(); } catch (error) { onError(presentBaseerApiError(error, language, ar ? "إنشاء السياسة" : "Creating policy")); } finally { setBusy(false); } });
  const createVersion = versionForm.handleSubmit(async ({ effectiveMonth }) => { const session = activeSession(); if (!session || busy || !versionPolicy) return; setBusy(true); try { await createHrCompensationPolicyVersion(session, { policyId: versionPolicy.id, effectiveFrom: `${effectiveMonth}-01`, idempotencyKey: requestId() }); setVersionPolicy(null); await load(); await onChanged(); } catch (error) { onError(presentBaseerApiError(error, language, ar ? "إنشاء إصدار" : "Creating version")); } finally { setBusy(false); } });
  const approve = async (version: HrCompensationPolicyVersion) => { const session = activeSession(); if (!session || busy) return; setBusy(true); try { await approveHrCompensationPolicyVersion(session, { policyVersionId: version.id, idempotencyKey: requestId() }); await load(); await onChanged(); } catch (error) { onError(presentBaseerApiError(error, language, ar ? "اعتماد الإصدار" : "Approving version")); } finally { setBusy(false); } };
  const rows = useMemo(() => policies.flatMap((policy) => policy.versions.map((version) => ({ policy, version }))), [policies]);
  const columns = [{ id: "policy", header: ar ? "السياسة" : "Policy", cell: (row: { policy: HrCompensationPolicy; version: HrCompensationPolicyVersion }) => `${row.policy.code} · ${ar ? row.policy.nameAr : row.policy.nameEn ?? row.policy.nameAr}` }, { id: "version", header: ar ? "الإصدار" : "Version", cell: (row: { version: HrCompensationPolicyVersion }) => `v${row.version.versionNumber}`, width: "7rem" }, { id: "from", header: ar ? "السريان" : "Effective", cell: (row: { version: HrCompensationPolicyVersion }) => row.version.effectiveFrom, width: "10rem" }, { id: "formula", header: ar ? "المعادلة" : "Formula", cell: () => ar ? "قياسية سعودية" : "Saudi standard", width: "12rem" }, { id: "status", header: ar ? "الحالة" : "Status", cell: (row: { version: HrCompensationPolicyVersion }) => ({ DRAFT: ar ? "مسودة" : "Draft", APPROVED: ar ? "معتمد" : "Approved", SUPERSEDED: ar ? "مستبدل" : "Superseded" })[row.version.status], width: "9rem" }, { id: "action", header: ar ? "الإجراء" : "Action", cell: (row: { version: HrCompensationPolicyVersion }) => row.version.status === "DRAFT" ? <BaseerButton type="button" variant="secondary" disabled={busy} onClick={() => void approve(row.version)}>{ar ? "اعتماد" : "Approve"}</BaseerButton> : "—", width: "10rem" }];
  return <><BaseerDialog open={open} title={ar ? "سياسات التعويض" : "Compensation policies"} language={language} busy={busy} onClose={onClose} footer={<><BaseerButton type="button" variant="secondary" onClick={onClose}>{ar ? "إغلاق" : "Close"}</BaseerButton><BaseerButton type="button" onClick={() => { policyForm.reset(emptyPolicy()); setCreateOpen(true); }}>{ar ? "إضافة سياسة" : "Add policy"}</BaseerButton></>}><BaseerCard><p>{ar ? "المعادلة قياسية ومحكومة من الخادم. لا يمكن إدخال معاملات أو نسب قانونية من الواجهة." : "The formula is standard and server-governed. Legal coefficients cannot be entered in the interface."}</p></BaseerCard>{loading ? <BaseerCard>{ar ? "جارٍ تحميل السياسات…" : "Loading policies…"}</BaseerCard> : rows.length ? <BaseerDataGrid ariaLabel={ar ? "إصدارات سياسات التعويض" : "Compensation policy versions"} caption={ar ? "إصدارات سياسات التعويض" : "Compensation policy versions"} rows={rows} columns={columns} rowKey={(row) => row.version.id} /> : <BaseerCard>{ar ? "لا توجد سياسات تعويض بعد." : "No compensation policies yet."}</BaseerCard>}{policies.length ? <div className="baseer-inline-actions">{policies.map((policy) => <BaseerButton key={policy.id} type="button" variant="quiet" onClick={() => { versionForm.reset({ effectiveMonth: month() }); setVersionPolicy(policy); }}>{ar ? `إصدار جديد: ${policy.nameAr}` : `New version: ${policy.nameEn ?? policy.nameAr}`}</BaseerButton>)}</div> : null}</BaseerDialog>
    <BaseerFormDialog open={createOpen} title={ar ? "إضافة سياسة تعويض" : "Add compensation policy"} language={language} busy={busy} size="standard" formId="hr-policy-create" submitLabel={ar ? "حفظ السياسة" : "Save policy"} onClose={() => setCreateOpen(false)}><form id="hr-policy-create" className="baseer-form" data-baseer-rhf-form="true" noValidate onSubmit={(event) => void create(event)}><BaseerFormSection title={ar ? "هوية السياسة" : "Policy identity"}><BaseerFormGrid><label>{ar ? "الكود" : "Code"}<BaseerTextInput aria-invalid={Boolean(policyForm.formState.errors.code)} {...policyForm.register("code", { onChange: (event) => policyForm.setValue("code", event.target.value.toUpperCase(), { shouldValidate: true }) })} />{policyForm.formState.errors.code ? <small role="alert">{policyForm.formState.errors.code.message}</small> : null}</label><label>{ar ? "الاسم بالعربية" : "Arabic name"}<BaseerTextInput aria-invalid={Boolean(policyForm.formState.errors.nameAr)} {...policyForm.register("nameAr")} />{policyForm.formState.errors.nameAr ? <small role="alert">{policyForm.formState.errors.nameAr.message}</small> : null}</label><label>{ar ? "الاسم بالإنجليزية" : "English name"}<BaseerTextInput {...policyForm.register("nameEn")} /></label><label>{ar ? "شهر أول إصدار" : "First version effective month"}<BaseerMonthPicker aria-invalid={Boolean(policyForm.formState.errors.effectiveMonth)} {...policyForm.register("effectiveMonth")} />{policyForm.formState.errors.effectiveMonth ? <small role="alert">{policyForm.formState.errors.effectiveMonth.message}</small> : null}</label></BaseerFormGrid></BaseerFormSection></form></BaseerFormDialog>
    <BaseerFormDialog open={Boolean(versionPolicy)} title={ar ? "إنشاء إصدار سياسة" : "Create policy version"} language={language} busy={busy} size="compact" formId="hr-policy-version" submitLabel={ar ? "إنشاء مسودة" : "Create draft"} onClose={() => setVersionPolicy(null)}><form id="hr-policy-version" className="baseer-form" data-baseer-rhf-form="true" noValidate onSubmit={(event) => void createVersion(event)}><BaseerFormSection title={ar ? "سريان الإصدار" : "Version effective date"}><BaseerFormGrid columns="one"><label>{ar ? "شهر السريان" : "Effective month"}<BaseerMonthPicker aria-invalid={Boolean(versionForm.formState.errors.effectiveMonth)} {...versionForm.register("effectiveMonth")} />{versionForm.formState.errors.effectiveMonth ? <small role="alert">{versionForm.formState.errors.effectiveMonth.message}</small> : null}</label></BaseerFormGrid></BaseerFormSection></form></BaseerFormDialog></>;
}
