import { api, baseerApiBaseUrl, type ActiveSession } from "./daily-sales-client";
import { parseBaseerApiResponse } from "./baseer-api-error";

export type HrEmployeeStatus = "ACTIVE" | "ON_LEAVE" | "TERMINATED" | "ARCHIVED";
export type HrEmployee = { id: string; employeeNumber: string; nameAr: string; nameEn: string | null; jobTitle: string | null; phone: string | null; email: string | null; iqamaNumber: string | null; workSchedule: string | null; hireDate: string; currentMonthlyGross: string | null; profilePhotoVersionId: string | null; status: HrEmployeeStatus; terminatedAt: string | null; notes: string | null };
export type HrEmployeePromotion = { id: string; employeeId: string; effectiveDate: string; previousJobTitle: string | null; newJobTitle: string; decisionReference: string; reason: string | null; createdAt: string };
export type HrEmployeePromotionsReceipt = { promotions: HrEmployeePromotion[]; hasMore: boolean; nextCursor: string | null };
export type HrEmployeeCompensationHistoryReceipt = { compensationHistory: HrCompensationProfile[]; hasMore: boolean; nextCursor: string | null };
export type HrService = { id: string; employeeId: string; serviceType: "IQAMA_ISSUANCE" | "IQAMA_RENEWAL" | "SPONSORSHIP_TRANSFER" | "EXIT_REENTRY_VISA" | "FLIGHT_TICKET" | "MEDICAL_INSURANCE" | "HEALTH_CERTIFICATE" | "OTHER"; referenceNumber: string | null; issueDate: string | null; expiryDate: string | null; supplier: { id: string; nameAr: string; nameEn: string | null } | null; category: { id: string; nameAr: string; nameEn: string } | null; outflowDocumentId: string | null; costStatus: "NOT_ISSUED" | "POSTED" | "REVERSED"; status: "DRAFT" | "ISSUED" | "CANCELLED"; complianceStatus: "ACTIVE" | "RENEWED" | "CANCELLED"; notes: string | null };
export type HrMovement = { id: string; journalEntryId: string; movementType: "SERVICE_COST" | "PAYROLL_ACCRUAL" | "PAYROLL_PAYMENT" | "ADVANCE_ISSUED" | "ADVANCE_SETTLEMENT" | "FINAL_SETTLEMENT_ACCRUAL" | "FINAL_SETTLEMENT_PAYMENT"; businessDate: string; amount: string; sourceReference: string; description: string | null };
export type HrCompensationProfile = { id: string; employeeId: string; effectiveFrom: string; effectiveTo: string | null; monthlyGross: string; policyVersionId: string | null; compensationMethod: HrCompensationMethod; foodAllowance: string; housingAllowance: string; transportAllowance: string; otherAllowance: string; scheduledHoursPerDay: number | null; scheduledWorkDays: number | null; notes: string | null };
export type HrCompensationPolicyVersion = { id: string; policyId: string; policyCode: string; policyNameAr: string; policyNameEn: string | null; versionNumber: number; effectiveFrom: string; effectiveTo: string | null; status: "DRAFT" | "APPROVED" | "SUPERSEDED"; formulaCode: "STANDARD_MONTHLY_V1" };
export type HrCompensationPolicy = { id: string; code: string; nameAr: string; nameEn: string | null; versions: HrCompensationPolicyVersion[] };
export type HrCompensationPoliciesReceipt = { policies: HrCompensationPolicy[] };
export type HrCompensationPolicySnapshot = { policyId: string; policyVersionId: string; policyCode: string; policyNameAr: string; policyNameEn: string | null; versionNumber: number; effectiveFrom: string; formulaCode: "STANDARD_MONTHLY_V1" };
export type HrDetail = { employee: HrEmployee; compensation: HrCompensationProfile | null; compensationHistory: HrCompensationProfile[]; compensationHistoryCount: number; services: HrService[]; serviceCount: number; servicesHasMore: boolean; movements: HrMovement[]; movementCount: number; hasMoreMovements: boolean; nextMovementCursor: string | null };
export type HrEmployeesReceipt = { employees: HrEmployee[]; hasMore: boolean; nextCursor: string | null; summary: { activeEmployees: number; employeesOnLeave: number; openAdvances: number; openAdministrativeDeductions: number } };
export type HrAdvance = { id: string; employeeId: string; employeeNameAr: string; employeeNameEn: string | null; advanceNumber: string; businessDate: string; originalAmount: string; settledAmount: string; remainingAmount: string; status: "ISSUED" | "PARTIALLY_SETTLED" | "SETTLED" | "REVERSED"; nextSettlementDate: string | null; notes: string | null; journalEntryId: string; allocations: Array<{ vaultId: string; vaultNameAr: string; vaultNameEn: string; paymentMethod: "CASH" | "BANK_TRANSFER" | "BANK_CARD" | "BANK_PAYMENT" | "APP"; amount: string }> };
export type HrAdvancesReceipt = { advances: HrAdvance[]; hasMore: boolean; nextCursor: string | null };
export type HrAdvanceDetail = { advance: HrAdvance; settlements: Array<{ id: string; source: "PAYROLL" | "MANUAL_RECEIPT" | "FINAL_SETTLEMENT"; businessDate: string; amount: string; journalEntryId: string | null; sourceReference: string | null }>; hasMoreSettlements: boolean; nextSettlementCursor: string | null; deferrals: Array<{ id: string; businessDate: string; deferredUntil: string; reason: string }>; hasMoreDeferrals: boolean; nextDeferralCursor: string | null };
export type HrAdministrativeDeduction = { id: string; employeeId: string; employeeNameAr: string; employeeNameEn: string | null; deductionNumber: string; businessDate: string; originalAmount: string; appliedAmount: string; remainingAmount: string; status: "OPEN" | "PARTIALLY_APPLIED" | "APPLIED" | "DEFERRED" | "CANCELLED"; plannedPayrollDate: string | null; description: string; cancellationReason: string | null };
export type HrAdministrativeDeductionsReceipt = { deductions: HrAdministrativeDeduction[]; hasMore: boolean; nextCursor: string | null };
export type HrAdministrativeDeductionDetail = { deduction: HrAdministrativeDeduction; actions: Array<{ id: string; actionType: "CREATED" | "DEFERRED" | "CANCELLED" | "APPLIED" | "REVERSED"; businessDate: string; amount: string | null; plannedPayrollDate: string | null; reason: string | null }>; hasMoreActions: boolean; nextActionCursor: string | null };
export type HrPayrollStatus = "DRAFT" | "APPROVED" | "PARTIALLY_PAID" | "PAID" | "REVERSED";
export type HrCompensationMethod = "FIXED_MONTHLY" | "INCLUSIVE_OVERTIME";
export type HrPayrollRun = { id: string; runNumber: string; payrollMonth: string; businessDate: string; status: HrPayrollStatus; employeeCount: number; grossAmount: string; advanceSettlementAmount: string; administrativeDeductionAmount: string; netPayableAmount: string; paidAmount: string; notes: string | null; accrualJournalEntryId: string | null };
export type HrPayrollCalculationSnapshot = { formulaCode: "FULL_MONTH_V1" | "PRORATED_NEW_HIRE_V1"; calculationPeriodStart: string; calculationPeriodEnd: string; eligibleDays: number; calendarDaysInMonth: number; prorationRatio: string; monthlyGrossAmount: string };
export type HrPayment = { id: string; paymentNumber: string; businessDate: string; amount: string; journalEntryId: string; status: "POSTED" | "REVERSED"; reversedAt: string | null; reversalJournalEntryId: string | null };
export type HrPayrollDetail = { payrollRun: HrPayrollRun; lines: Array<{ id: string; employeeId: string; employeeNumber: string; employeeNameAr: string; employeeNameEn: string | null; grossSalary: string; compensationMethod: HrCompensationMethod; eligibilityCode: "FULL_MONTH_V1" | "FULL_MONTH_ON_LEAVE_EXCEPTION_V1" | "PRORATED_NEW_HIRE_V1"; basicSalary: string; foodAllowance: string; housingAllowance: string; transportAllowance: string; otherAllowance: string; overtimeAmount: string; overtimeHours: string; scheduledHoursPerDay: number | null; scheduledWorkDays: number | null; compensationPolicySnapshot: HrCompensationPolicySnapshot | null; payrollCalculationSnapshot: HrPayrollCalculationSnapshot | null; advanceSettlementAmount: string; administrativeDeductionAmount: string; netPayableAmount: string; paidAmount: string; advances: Array<{ id: string; sourceId: string; amount: string; referenceNumber: string }>; administrativeDeductions: Array<{ id: string; sourceId: string; amount: string; referenceNumber: string }> }>; payments: HrPayment[]; hasMoreLines: boolean; nextLineCursor: string | null; hasMorePayments: boolean; nextPaymentCursor: string | null };
export type HrPayrollRunsReceipt = { payrollRuns: HrPayrollRun[]; hasMore: boolean; nextCursor: string | null; summary: { count: number; cancelledCount: number; grossAmount: string; advanceSettlementAmount: string; administrativeDeductionAmount: string; netPayableAmount: string } };
export type HrPayrollPreviewApplication = { id: string; referenceNumber: string; remainingAmount: string };
export type HrPayrollPreviewReason = "ACTIVE_WITH_VALID_COMPENSATION" | "ACTIVE_NEW_HIRE_PRORATED" | "ACTIVE_MISSING_COMPENSATION" | "COMPENSATION_DOES_NOT_COVER_PAYROLL_PERIOD" | "HIRED_AFTER_BUSINESS_DATE" | "ON_LEAVE_EXPLICITLY_INCLUDED" | "ON_LEAVE_REQUIRES_EXPLICIT_INCLUSION" | "ON_LEAVE_MISSING_COMPENSATION";
export type HrPayrollPreviewEmployee = { id: string; employeeNumber: string; nameAr: string; nameEn: string | null; status: "ACTIVE" | "ON_LEAVE"; included: boolean; reason: HrPayrollPreviewReason; eligibilityCode: "FULL_MONTH_V1" | "FULL_MONTH_ON_LEAVE_EXCEPTION_V1" | "PRORATED_NEW_HIRE_V1" | null; calculationPeriodStart: string | null; calculationPeriodEnd: string | null; eligibleDays: number | null; calendarDaysInMonth: number | null; prorationRatio: string | null; monthlyGrossAmount: string | null; estimatedGrossAmount: string | null; advances: HrPayrollPreviewApplication[]; advanceCount: number; hasMoreAdvances: boolean; administrativeDeductions: HrPayrollPreviewApplication[]; administrativeDeductionCount: number; hasMoreAdministrativeDeductions: boolean };
export type HrPayrollPreviewReceipt = { companyId: string; counts: { active: number; onLeave: number; included: number; excluded: number; exceptions: number }; totals: { employeeCount: number; grossAmount: string; advanceSettlementAmount: string; administrativeDeductionAmount: string; netPayableAmount: string }; exceptions: Array<{ employeeId: string; employeeNumber: string; employeeNameAr: string; reason: "ACTIVE_MISSING_COMPENSATION" | "ON_LEAVE_MISSING_COMPENSATION" | "COMPENSATION_DOES_NOT_COVER_PAYROLL_PERIOD" | "HIRED_AFTER_BUSINESS_DATE" }>; employees: HrPayrollPreviewEmployee[]; hasMore: boolean; nextCursor: string | null };
export type HrEmployeeLeaveType = "ANNUAL" | "SICK" | "UNPAID" | "OTHER";
export type HrEmployeeLeaveStatus = "APPROVED" | "RETURNED";
export type HrEmployeeLeave = {
  id: string;
  employeeId: string;
  employeeNumber: string;
  employeeNameAr: string;
  employeeNameEn: string | null;
  leaveType: HrEmployeeLeaveType;
  status: HrEmployeeLeaveStatus;
  startDate: string;
  endDate: string;
  actualReturnDate: string | null;
  notes: string | null;
};
export type HrEmployeeLeavesReceipt = { leaves: HrEmployeeLeave[]; hasMore: boolean; nextCursor: string | null; summary: { count: number; onLeaveNow: number; upcoming: number; returned: number } };
export type HrEmployeeLeaveDetail = { leave: HrEmployeeLeave };
export type HrEmployeeDocumentType = "NATIONAL_ID" | "IQAMA" | "PASSPORT" | "EMPLOYMENT_CONTRACT" | "MEDICAL_INSURANCE" | "HEALTH_CERTIFICATE" | "QUALIFICATION" | "OTHER";
export type HrEmployeeDocumentStatus = "ACTIVE" | "REVOKED";
export type HrEmployeeDocumentBlobStatus = "STAGED" | "READY" | "QUARANTINED" | "REVOKED";
export type HrEmployeeDocumentComplianceStatus = "NOT_APPLICABLE" | "VALID" | "EXPIRING" | "EXPIRED";
export type HrEmployeeDocument = { id: string; employeeId: string; documentType: HrEmployeeDocumentType; status: HrEmployeeDocumentStatus; title: string; referenceNumber: string | null; issueDate: string | null; expiryDate: string | null; notes: string | null; linkedServiceId: string | null; retentionUntil: string | null; legalHold: boolean; complianceStatus: HrEmployeeDocumentComplianceStatus; currentVersion: { id: string; version: number; blobStatus: HrEmployeeDocumentBlobStatus; mimeType: string; byteSize: string; sha256: string; createdAt: string } | null; createdAt: string; updatedAt: string; revokedAt: string | null; revokedReason: string | null };
export type HrEmployeeDocumentsReceipt = { companyId: string; documents: HrEmployeeDocument[]; hasMore: boolean; nextCursor: string | null };
export type HrEmployeeLetterType = "SALARY_CERTIFICATE" | "SERVICE_CERTIFICATE";
export type HrEmployeeLetterStatus = "ISSUED" | "REVOKED";
export type HrEmployeeLetter = { id: string; employeeId: string; letterType: HrEmployeeLetterType; status: HrEmployeeLetterStatus; letterNumber: string; locale: "ar" | "en"; recipient: string | null; issuedAt: string; revokedAt: string | null; revokedReason: string | null; outputReportCode: "hr.employee-letter" };
export type HrEmployeeLettersReceipt = { companyId: string; letters: HrEmployeeLetter[]; hasMore: boolean; nextCursor: string | null };
export type HrAdvanceEntryReferences = {
  companyId: string;
  employees: Array<Pick<HrEmployee, "id" | "employeeNumber" | "nameAr" | "nameEn" | "status">>;
  vaults: Array<{ id: string; nameAr: string; nameEn: string; paymentMethod: "CASH" | "BANK_TRANSFER" | "BANK_CARD" | "BANK_PAYMENT" | "APP"; paymentMethods: Array<"CASH" | "BANK_TRANSFER" | "BANK_CARD" | "BANK_PAYMENT" | "APP"> }>;
};
export type HrFinalSettlementReason = "EMPLOYER_TERMINATION" | "RESIGNATION" | "ARTICLE_80" | "ARTICLE_81" | "FORCE_MAJEURE" | "MATERNITY" | "OTHER_LEGAL_REVIEW";
export type HrFinalSettlementStatus = "DRAFT" | "APPROVED" | "PARTIALLY_PAID" | "PAID" | "REVERSED" | "CANCELLED";
export type HrFinalSettlementReasonVerificationStatus = "PENDING" | "VERIFIED" | "REJECTED";
export type HrFinalSettlementRecovery = { recoveryType: "ADVANCE" | "ADMINISTRATIVE_DEDUCTION"; sourceId: string; amount: string };
export type HrFinalSettlementPreview = { employeeId: string; terminationDate: string; terminationReason: HrFinalSettlementReason; reasonEvidenceReference: string; reasonVerificationStatus: HrFinalSettlementReasonVerificationStatus; serviceDays: number; eosWage: string; fullAwardAmount: string; entitlementFactor: string; eosAmount: string; otherCreditsAmount: string; recoveryAmount: string; netPayableAmount: string; calculationPolicyVersion: "SA-EOS-V1" };
export type HrFinalSettlement = HrFinalSettlementPreview & { id: string; settlementNumber: string; status: HrFinalSettlementStatus; paidAmount: string; createdAt: string; approvedAt: string | null; outputReportCode: "hr.final-settlement" };
export type HrFinalSettlementsReceipt = { companyId: string; settlements: HrFinalSettlement[]; hasMore: boolean; nextCursor: string | null };
export type HrFinalSettlementDetail = { companyId: string; settlement: HrFinalSettlement; payments: HrPayment[]; hasMorePayments: boolean; nextPaymentCursor: string | null };
export type HrOverviewReceipt = {
  companyId: string;
  businessDate: string;
  workforce: { activeEmployees: number; employeesOnLeave: number } | null;
  financial: { openAdvances: number | null; openAdministrativeDeductions: number | null } | null;
  payroll: { draftCount: number; awaitingPaymentCount: number; recentRuns: Array<Pick<HrPayrollRun, "id" | "runNumber" | "payrollMonth" | "status">> } | null;
  services: { expiredCount: number; expiringCount: number; attentionItems: Array<{ id: string; employeeId: string; employeeNameAr: string; employeeNameEn: string | null; serviceType: HrService["serviceType"]; expiryDate: string }> } | null;
  leaves: { openCount: number; actionItems: Array<{ id: string; employeeId: string; employeeNameAr: string; employeeNameEn: string | null; leaveType: HrEmployeeLeaveType; startDate: string; endDate: string }> } | null;
  finalSettlements: { openCount: number; actionItems: Array<Pick<HrFinalSettlement, "id" | "settlementNumber" | "terminationDate" | "status">> } | null;
};

function withQuery(path: string, query: Record<string, string | number | undefined>) { const parameters = new URLSearchParams(); for (const [key, value] of Object.entries(query)) if (value !== undefined && value !== "") parameters.set(key, String(value)); return `${path}${parameters.size ? `?${parameters}` : ""}`; }
export function getHrOverview(session: ActiveSession, signal?: AbortSignal) { return api<HrOverviewReceipt>(session, "/hr/overview", { signal }); }
export function listHrEmployees(session: ActiveSession, query: { status?: HrEmployeeStatus; search?: string; cursor?: string; pageSize?: number } = {}, options?: Pick<RequestInit, "signal">) { return api<HrEmployeesReceipt>(session, withQuery("/hr/employees", query), options); }
export function onboardHrEmployee(session: ActiveSession, payload: unknown) { return api<{ id: string; compensationId: string; replayed: boolean }>(session, "/hr/employees/onboard", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function updateHrEmployee(session: ActiveSession, payload: unknown) { return api(session, "/hr/employees/update", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function listHrEmployeePromotions(session: ActiveSession, employeeId: string, query: { cursor?: string; pageSize?: number } = {}) { return api<HrEmployeePromotionsReceipt>(session, withQuery(`/hr/employees/${encodeURIComponent(employeeId)}/promotions`, query)); }
export function listHrEmployeeCompensationHistory(session: ActiveSession, employeeId: string, query: { cursor?: string; pageSize?: number } = {}) { return api<HrEmployeeCompensationHistoryReceipt>(session, withQuery(`/hr/employees/${encodeURIComponent(employeeId)}/compensation-history`, query)); }
export function createHrEmployeePromotion(session: ActiveSession, employeeId: string, payload: { effectiveDate: string; newJobTitle: string; decisionReference: string; reason?: string; idempotencyKey: string }) { return api<{ id: string; replayed: boolean }>(session, `/hr/employees/${encodeURIComponent(employeeId)}/promotions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function listHrAdvances(session: ActiveSession, query: { employeeId?: string; status?: HrAdvance["status"]; search?: string; cursor?: string; pageSize?: number } = {}) { return api<HrAdvancesReceipt>(session, withQuery("/hr/advances", query)); }
export function getHrAdvanceEntryReferences(session: ActiveSession, options?: Pick<RequestInit, "signal">) { return api<HrAdvanceEntryReferences>(session, "/hr/advances/entry-references", options); }
export function getHrAdvance(session: ActiveSession, advanceId: string, query: { settlementCursor?: string; settlementPageSize?: number; deferralCursor?: string; deferralPageSize?: number } = {}) { return api<HrAdvanceDetail>(session, withQuery(`/hr/advances/${encodeURIComponent(advanceId)}`, query)); }
export function listHrAdministrativeDeductions(session: ActiveSession, query: { employeeId?: string; status?: HrAdministrativeDeduction["status"]; search?: string; cursor?: string; pageSize?: number } = {}) { return api<HrAdministrativeDeductionsReceipt>(session, withQuery("/hr/deductions", query)); }
export function getHrAdministrativeDeduction(session: ActiveSession, deductionId: string, query: { actionCursor?: string; actionPageSize?: number } = {}) { return api<HrAdministrativeDeductionDetail>(session, withQuery(`/hr/deductions/${encodeURIComponent(deductionId)}`, query)); }
export function issueHrEmployeeAdvance(session: ActiveSession, payload: unknown) { return api(session, "/hr/advances", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function reverseHrEmployeeAdvanceIssue(session: ActiveSession, payload: unknown) { return api(session, "/hr/advances/reverse", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function settleHrEmployeeAdvanceDirectly(session: ActiveSession, payload: unknown) { return api(session, "/hr/advances/settle-directly", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function deferHrEmployeeAdvance(session: ActiveSession, payload: unknown) { return api(session, "/hr/advances/defer", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function createHrEmployeeAdministrativeDeduction(session: ActiveSession, payload: unknown) { return api(session, "/hr/deductions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function deferHrEmployeeAdministrativeDeduction(session: ActiveSession, payload: unknown) { return api(session, "/hr/deductions/defer", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function cancelHrEmployeeAdministrativeDeduction(session: ActiveSession, payload: unknown) { return api(session, "/hr/deductions/cancel", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function getHrEmployee(session: ActiveSession, employeeId: string, cursor?: string) { return api<HrDetail>(session, `/hr/employees/${encodeURIComponent(employeeId)}${cursor ? `?cursor=${encodeURIComponent(cursor)}` : ""}`); }
export type HrEmployeePayrollHistoryLine = HrPayrollDetail["lines"][number] & { payrollRunId: string; runNumber: string; payrollMonth: string; businessDate: string; payrollStatus: HrPayrollStatus };
export type HrEmployeePayrollHistoryReceipt = { lines: HrEmployeePayrollHistoryLine[]; hasMore: boolean; nextCursor: string | null };
export function listHrEmployeePayrollHistory(session: ActiveSession, employeeId: string, query: { cursor?: string; pageSize?: number } = {}) { return api<HrEmployeePayrollHistoryReceipt>(session, withQuery(`/hr/employees/${encodeURIComponent(employeeId)}/payroll`, query)); }
export function listHrEmployeeLeaves(session: ActiveSession, query: { employeeId?: string; status?: HrEmployeeLeaveStatus; leaveType?: HrEmployeeLeaveType; periodFrom?: string; periodTo?: string; search?: string; cursor?: string; pageSize?: number; sortDirection?: 'asc' | 'desc' } = {}) { return api<HrEmployeeLeavesReceipt>(session, withQuery("/hr/leaves", query)); }
export function getHrEmployeeLeave(session: ActiveSession, leaveId: string) { return api<HrEmployeeLeaveDetail>(session, `/hr/leaves/${encodeURIComponent(leaveId)}`); }
export function createHrEmployeeLeave(session: ActiveSession, payload: unknown) { return api(session, "/hr/leaves", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function recordHrEmployeeReturn(session: ActiveSession, payload: unknown) { return api(session, "/hr/leaves/return", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function listHrEmployeeDocuments(session: ActiveSession, employeeId: string, query: { cursor?: string; pageSize?: number; documentType?: HrEmployeeDocumentType; status?: HrEmployeeDocumentStatus; expiry?: "VALID" | "EXPIRING" | "EXPIRED" | "NONE" } = {}) { return api<HrEmployeeDocumentsReceipt>(session, withQuery(`/hr/employees/${encodeURIComponent(employeeId)}/documents`, query)); }
export function createHrEmployeeDocument(session: ActiveSession, employeeId: string, payload: unknown) { return api<{ id: string; versionId: string; replayed: boolean }>(session, `/hr/employees/${encodeURIComponent(employeeId)}/documents`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function replaceHrEmployeeDocument(session: ActiveSession, documentId: string, payload: unknown) { return api<{ id: string; versionId: string; replayed: boolean }>(session, `/hr/employee-documents/${encodeURIComponent(documentId)}/versions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function revokeHrEmployeeDocument(session: ActiveSession, documentId: string, payload: unknown) { return api<{ id: string; replayed: boolean }>(session, `/hr/employee-documents/${encodeURIComponent(documentId)}/revoke`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
/** Download is authenticated and produces an in-memory Blob; document storage URLs never reach the browser. */
export async function downloadHrEmployeeDocumentVersion(session: ActiveSession, versionId: string) {
  const response = await fetch(`${baseerApiBaseUrl}/hr/employee-document-versions/${encodeURIComponent(versionId)}/download`, { cache: "no-store", headers: { Accept: "application/pdf,image/jpeg,image/png", Authorization: `Bearer ${session.accessToken}`, "X-Baseer-Company-Id": session.companyId } });
  if (!response.ok) await parseBaseerApiResponse<never>(response);
  const disposition = response.headers.get("content-disposition") ?? "";
  const fileName = /filename="?([^";]+)"?/i.exec(disposition)?.[1] ?? "employee-document";
  return { blob: await response.blob(), fileName };
}
export function listHrEmployeeLetters(session: ActiveSession, employeeId: string, query: { cursor?: string; pageSize?: number } = {}) { return api<HrEmployeeLettersReceipt>(session, withQuery(`/hr/employees/${encodeURIComponent(employeeId)}/letters`, query)); }
export function issueHrEmployeeLetter(session: ActiveSession, employeeId: string, payload: unknown) { return api<{ id: string; letterNumber: string; outputReportCode: "hr.employee-letter"; replayed: boolean }>(session, `/hr/employees/${encodeURIComponent(employeeId)}/letters/issue`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function revokeHrEmployeeLetter(session: ActiveSession, letterId: string, payload: unknown) { return api<{ id: string; replayed: boolean }>(session, `/hr/employee-letters/${encodeURIComponent(letterId)}/revoke`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function previewHrFinalSettlement(session: ActiveSession, payload: { employeeId: string; terminationDate: string; terminationReason: HrFinalSettlementReason; reasonEvidenceReference: string; reasonEvidenceNote?: string; recoveries: HrFinalSettlementRecovery[] }) { return api<HrFinalSettlementPreview>(session, "/hr/final-settlements/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function listHrFinalSettlements(session: ActiveSession, query: { cursor?: string; pageSize?: number; employeeId?: string; status?: HrFinalSettlementStatus; search?: string } = {}) { return api<HrFinalSettlementsReceipt>(session, withQuery("/hr/final-settlements", query)); }
export function getHrFinalSettlement(session: ActiveSession, settlementId: string, query: { paymentCursor?: string; pageSize?: number } = {}) { return api<HrFinalSettlementDetail>(session, withQuery(`/hr/final-settlements/${encodeURIComponent(settlementId)}`, query)); }
export function createHrFinalSettlement(session: ActiveSession, payload: unknown) { return api<{ id: string; settlementNumber: string; replayed: boolean }>(session, "/hr/final-settlements", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function verifyHrFinalSettlementReason(session: ActiveSession, payload: { settlementId: string; verificationNote: string; idempotencyKey: string }) { return api<{ id: string; settlementNumber: string; replayed: boolean }>(session, "/hr/final-settlements/verify-reason", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function approveHrFinalSettlement(session: ActiveSession, payload: unknown) { return api<{ id: string; settlementNumber: string; replayed: boolean }>(session, "/hr/final-settlements/approve", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function payHrFinalSettlement(session: ActiveSession, payload: unknown) { return api<{ id: string; settlementNumber: string; replayed: boolean }>(session, "/hr/final-settlements/pay", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function reverseHrFinalSettlement(session: ActiveSession, payload: unknown) { return api<{ id: string; settlementNumber: string; replayed: boolean }>(session, "/hr/final-settlements/reverse", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function reverseHrFinalSettlementPayment(session: ActiveSession, payload: unknown) { return api(session, "/hr/final-settlement-payments/reverse", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function listHrPayrollRuns(session: ActiveSession, query: { status?: HrPayrollStatus; search?: string; cursor?: string; pageSize?: number } = {}) { return api<HrPayrollRunsReceipt>(session, withQuery("/hr/payroll-runs", query)); }
export function getHrPayrollRun(session: ActiveSession, payrollRunId: string, query: { lineCursor?: string; linePageSize?: number; paymentCursor?: string; paymentPageSize?: number } = {}) { return api<HrPayrollDetail>(session, withQuery(`/hr/payroll-runs/${encodeURIComponent(payrollRunId)}`, query)); }
export function setHrEmployeeCompensation(session: ActiveSession, payload: unknown) { return api(session, "/hr/compensation", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function listHrCompensationPolicies(session: ActiveSession) { return api<HrCompensationPoliciesReceipt>(session, "/hr/compensation-policies"); }
export function createHrCompensationPolicy(session: ActiveSession, payload: unknown) { return api(session, "/hr/compensation-policies", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function createHrCompensationPolicyVersion(session: ActiveSession, payload: unknown) { return api(session, "/hr/compensation-policies/version", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function approveHrCompensationPolicyVersion(session: ActiveSession, payload: unknown) { return api(session, "/hr/compensation-policies/approve", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function createHrPayrollRun(session: ActiveSession, payload: unknown) { return api(session, "/hr/payroll-runs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function updateHrPayrollRun(session: ActiveSession, payload: unknown) { return api(session, "/hr/payroll-runs/update", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function previewHrPayrollRun(session: ActiveSession, payload: { payrollMonth: string; businessDate: string; includeOnLeaveEmployeeIds?: string[]; lines?: Array<{ employeeId: string; advances: Array<{ id: string; amount: string }>; administrativeDeductions: Array<{ id: string; amount: string }> }>; cursor?: string; pageSize?: number }, signal?: AbortSignal) { return api<HrPayrollPreviewReceipt>(session, "/hr/payroll-runs/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload), signal }); }
export function approveHrPayrollRun(session: ActiveSession, payload: unknown) { return api(session, "/hr/payroll-runs/approve", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function discardHrPayrollRun(session: ActiveSession, payload: unknown) { return api(session, "/hr/payroll-runs/discard", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function payHrPayrollRun(session: ActiveSession, payload: unknown) { return api(session, "/hr/payroll-runs/pay", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function reverseHrPayrollRun(session: ActiveSession, payload: unknown) { return api(session, "/hr/payroll-runs/reverse", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function reverseHrPayrollPayment(session: ActiveSession, payload: unknown) { return api(session, "/hr/payroll-payments/reverse", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
