import { api, type ActiveSession } from "./daily-sales-client";

export type HrEmployeeStatus = "ACTIVE" | "ON_LEAVE" | "TERMINATED" | "ARCHIVED";
export type HrEmployee = { id: string; employeeNumber: string; nameAr: string; nameEn: string | null; jobTitle: string | null; phone: string | null; email: string | null; hireDate: string; status: HrEmployeeStatus; terminatedAt: string | null; notes: string | null };
export type HrService = { id: string; employeeId: string; serviceType: "IQAMA_ISSUANCE" | "IQAMA_RENEWAL" | "SPONSORSHIP_TRANSFER" | "EXIT_REENTRY_VISA" | "FLIGHT_TICKET" | "MEDICAL_INSURANCE" | "HEALTH_CERTIFICATE" | "OTHER"; referenceNumber: string | null; issueDate: string | null; expiryDate: string | null; supplier: { id: string; nameAr: string; nameEn: string | null } | null; category: { id: string; nameAr: string; nameEn: string } | null; outflowDocumentId: string | null; status: "DRAFT" | "ISSUED" | "CANCELLED"; complianceStatus: "ACTIVE" | "RENEWED" | "CANCELLED"; notes: string | null };
export type HrMovement = { id: string; journalEntryId: string; movementType: "SERVICE_COST" | "PAYROLL_ACCRUAL" | "PAYROLL_PAYMENT" | "ADVANCE_ISSUED" | "ADVANCE_SETTLEMENT"; businessDate: string; amount: string; sourceReference: string; description: string | null };
export type HrCompensationProfile = { id: string; employeeId: string; effectiveFrom: string; effectiveTo: string | null; monthlyGross: string; policyVersionId: string | null; compensationMethod: HrCompensationMethod; foodAllowance: string; otherAllowance: string; scheduledHoursPerDay: number | null; scheduledWorkDays: number | null; notes: string | null };
export type HrCompensationPolicyVersion = { id: string; policyId: string; policyCode: string; policyNameAr: string; policyNameEn: string | null; versionNumber: number; effectiveFrom: string; effectiveTo: string | null; status: "DRAFT" | "APPROVED" | "SUPERSEDED"; formulaCode: "STANDARD_MONTHLY_V1" };
export type HrCompensationPolicy = { id: string; code: string; nameAr: string; nameEn: string | null; versions: HrCompensationPolicyVersion[] };
export type HrCompensationPoliciesReceipt = { policies: HrCompensationPolicy[] };
export type HrCompensationPolicySnapshot = { policyId: string; policyVersionId: string; policyCode: string; policyNameAr: string; policyNameEn: string | null; versionNumber: number; effectiveFrom: string; formulaCode: "STANDARD_MONTHLY_V1" };
export type HrDetail = { employee: HrEmployee; compensation: HrCompensationProfile | null; services: HrService[]; movements: HrMovement[]; hasMoreMovements: boolean; nextMovementCursor: string | null };
export type HrEmployeesReceipt = { employees: HrEmployee[]; hasMore: boolean; nextCursor: string | null; summary: { activeEmployees: number; employeesOnLeave: number; openAdvances: number; openAdministrativeDeductions: number } };
export type HrAdvance = { id: string; employeeId: string; employeeNameAr: string; employeeNameEn: string | null; advanceNumber: string; businessDate: string; originalAmount: string; settledAmount: string; remainingAmount: string; status: "ISSUED" | "PARTIALLY_SETTLED" | "SETTLED" | "REVERSED"; nextSettlementDate: string | null; notes: string | null; journalEntryId: string; allocations: Array<{ vaultId: string; vaultNameAr: string; vaultNameEn: string; paymentMethod: "CASH" | "BANK_TRANSFER" | "BANK_CARD" | "BANK_PAYMENT" | "APP"; amount: string }> };
export type HrAdvancesReceipt = { advances: HrAdvance[]; hasMore: boolean; nextCursor: string | null };
export type HrAdvanceDetail = { advance: HrAdvance; settlements: Array<{ id: string; source: "PAYROLL" | "MANUAL_RECEIPT"; businessDate: string; amount: string; journalEntryId: string | null; sourceReference: string | null }>; deferrals: Array<{ id: string; businessDate: string; deferredUntil: string; reason: string }> };
export type HrAdministrativeDeduction = { id: string; employeeId: string; employeeNameAr: string; employeeNameEn: string | null; deductionNumber: string; businessDate: string; originalAmount: string; appliedAmount: string; remainingAmount: string; status: "OPEN" | "PARTIALLY_APPLIED" | "APPLIED" | "DEFERRED" | "CANCELLED"; plannedPayrollDate: string | null; description: string; cancellationReason: string | null };
export type HrAdministrativeDeductionsReceipt = { deductions: HrAdministrativeDeduction[]; hasMore: boolean; nextCursor: string | null };
export type HrAdministrativeDeductionDetail = { deduction: HrAdministrativeDeduction; actions: Array<{ id: string; actionType: "CREATED" | "DEFERRED" | "CANCELLED" | "APPLIED" | "REVERSED"; businessDate: string; amount: string | null; plannedPayrollDate: string | null; reason: string | null }> };
export type HrPayrollStatus = "DRAFT" | "APPROVED" | "PARTIALLY_PAID" | "PAID" | "REVERSED";
export type HrCompensationMethod = "FIXED_MONTHLY" | "INCLUSIVE_OVERTIME";
export type HrPayrollRun = { id: string; runNumber: string; payrollMonth: string; businessDate: string; status: HrPayrollStatus; employeeCount: number; grossAmount: string; advanceSettlementAmount: string; administrativeDeductionAmount: string; netPayableAmount: string; paidAmount: string; notes: string | null; accrualJournalEntryId: string | null };
export type HrPayrollDetail = { payrollRun: HrPayrollRun; lines: Array<{ id: string; employeeId: string; employeeNumber: string; employeeNameAr: string; employeeNameEn: string | null; grossSalary: string; compensationMethod: HrCompensationMethod; eligibilityCode: "FULL_MONTH_V1" | "FULL_MONTH_ON_LEAVE_EXCEPTION_V1" | "FULL_MONTH_NEW_HIRE_EXCEPTION_V1"; basicSalary: string; foodAllowance: string; otherAllowance: string; overtimeAmount: string; overtimeHours: string; scheduledHoursPerDay: number | null; scheduledWorkDays: number | null; compensationPolicySnapshot: HrCompensationPolicySnapshot | null; advanceSettlementAmount: string; administrativeDeductionAmount: string; netPayableAmount: string; paidAmount: string; advances: Array<{ id: string; amount: string; referenceNumber: string }>; administrativeDeductions: Array<{ id: string; amount: string; referenceNumber: string }> }>; payments: Array<{ id: string; paymentNumber: string; businessDate: string; amount: string; journalEntryId: string }> };
export type HrPayrollRunsReceipt = { payrollRuns: HrPayrollRun[]; hasMore: boolean; nextCursor: string | null };
export type HrPayrollPreviewApplication = { id: string; referenceNumber: string; remainingAmount: string };
export type HrPayrollPreviewReason = "ACTIVE_WITH_VALID_COMPENSATION" | "ACTIVE_MISSING_COMPENSATION" | "NEW_HIRE_REQUIRES_FULL_MONTH_EXCEPTION" | "HIRED_AFTER_BUSINESS_DATE" | "ON_LEAVE_EXPLICITLY_INCLUDED" | "ON_LEAVE_REQUIRES_EXPLICIT_INCLUSION" | "ON_LEAVE_MISSING_COMPENSATION";
export type HrPayrollPreviewEmployee = { id: string; employeeNumber: string; nameAr: string; nameEn: string | null; status: "ACTIVE" | "ON_LEAVE"; included: boolean; reason: HrPayrollPreviewReason; advances: HrPayrollPreviewApplication[]; administrativeDeductions: HrPayrollPreviewApplication[] };
export type HrPayrollPreviewReceipt = { companyId: string; counts: { active: number; onLeave: number; included: number; excluded: number; exceptions: number }; totals: { employeeCount: number; grossAmount: string; advanceSettlementAmount: string; administrativeDeductionAmount: string; netPayableAmount: string }; exceptions: Array<{ employeeId: string; employeeNumber: string; employeeNameAr: string; reason: "ACTIVE_MISSING_COMPENSATION" | "ON_LEAVE_MISSING_COMPENSATION" | "NEW_HIRE_REQUIRES_FULL_MONTH_EXCEPTION" | "HIRED_AFTER_BUSINESS_DATE" }>; employees: HrPayrollPreviewEmployee[]; hasMore: boolean; nextCursor: string | null };
export type HrEmployeeLeaveType = "ANNUAL" | "SICK" | "UNPAID" | "OTHER";
export type HrEmployeeLeaveStatus = "APPROVED" | "RETURNED";
export type HrEmployeeLeave = {
  id: string;
  employeeId: string;
  employeeNumber: string;
  employeeNameAr: string;
  employeeNameEn: string | null;
  leaveType: HrEmployeeLeaveType;
  status: HrEmployeeLeaveStatus;
  startDate: string;
  endDate: string;
  actualReturnDate: string | null;
  notes: string | null;
};
export type HrEmployeeLeavesReceipt = { leaves: HrEmployeeLeave[]; hasMore: boolean; nextCursor: string | null };
export type HrEmployeeLeaveDetail = { leave: HrEmployeeLeave };

function withQuery(path: string, query: Record<string, string | number | undefined>) { const parameters = new URLSearchParams(); for (const [key, value] of Object.entries(query)) if (value !== undefined && value !== "") parameters.set(key, String(value)); return `${path}${parameters.size ? `?${parameters}` : ""}`; }
export function listHrEmployees(session: ActiveSession, query: { status?: HrEmployeeStatus; search?: string; cursor?: string; pageSize?: number } = {}) { return api<HrEmployeesReceipt>(session, withQuery("/hr/employees", query)); }
export function updateHrEmployee(session: ActiveSession, payload: unknown) { return api(session, "/hr/employees/update", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function listHrAdvances(session: ActiveSession, query: { employeeId?: string; status?: HrAdvance["status"]; cursor?: string; pageSize?: number } = {}) { return api<HrAdvancesReceipt>(session, withQuery("/hr/advances", query)); }
export function getHrAdvance(session: ActiveSession, advanceId: string) { return api<HrAdvanceDetail>(session, `/hr/advances/${encodeURIComponent(advanceId)}`); }
export function listHrAdministrativeDeductions(session: ActiveSession, query: { employeeId?: string; status?: HrAdministrativeDeduction["status"]; cursor?: string; pageSize?: number } = {}) { return api<HrAdministrativeDeductionsReceipt>(session, withQuery("/hr/deductions", query)); }
export function getHrAdministrativeDeduction(session: ActiveSession, deductionId: string) { return api<HrAdministrativeDeductionDetail>(session, `/hr/deductions/${encodeURIComponent(deductionId)}`); }
export function issueHrEmployeeAdvance(session: ActiveSession, payload: unknown) { return api(session, "/hr/advances", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function settleHrEmployeeAdvanceDirectly(session: ActiveSession, payload: unknown) { return api(session, "/hr/advances/settle-directly", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function deferHrEmployeeAdvance(session: ActiveSession, payload: unknown) { return api(session, "/hr/advances/defer", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function createHrEmployeeAdministrativeDeduction(session: ActiveSession, payload: unknown) { return api(session, "/hr/deductions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function deferHrEmployeeAdministrativeDeduction(session: ActiveSession, payload: unknown) { return api(session, "/hr/deductions/defer", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function cancelHrEmployeeAdministrativeDeduction(session: ActiveSession, payload: unknown) { return api(session, "/hr/deductions/cancel", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function getHrEmployee(session: ActiveSession, employeeId: string, cursor?: string) { return api<HrDetail>(session, `/hr/employees/${encodeURIComponent(employeeId)}${cursor ? `?cursor=${encodeURIComponent(cursor)}` : ""}`); }
export type HrEmployeePayrollHistoryLine = HrPayrollDetail["lines"][number] & { payrollRunId: string; runNumber: string; payrollMonth: string; businessDate: string; payrollStatus: HrPayrollStatus };
export type HrEmployeePayrollHistoryReceipt = { lines: HrEmployeePayrollHistoryLine[]; hasMore: boolean; nextCursor: string | null };
export function listHrEmployeePayrollHistory(session: ActiveSession, employeeId: string, query: { cursor?: string; pageSize?: number } = {}) { return api<HrEmployeePayrollHistoryReceipt>(session, withQuery(`/hr/employees/${encodeURIComponent(employeeId)}/payroll`, query)); }
export function listHrEmployeeLeaves(session: ActiveSession, query: { employeeId?: string; status?: HrEmployeeLeaveStatus; leaveType?: HrEmployeeLeaveType; periodFrom?: string; periodTo?: string; cursor?: string; pageSize?: number } = {}) { return api<HrEmployeeLeavesReceipt>(session, withQuery("/hr/leaves", query)); }
export function getHrEmployeeLeave(session: ActiveSession, leaveId: string) { return api<HrEmployeeLeaveDetail>(session, `/hr/leaves/${encodeURIComponent(leaveId)}`); }
export function createHrEmployeeLeave(session: ActiveSession, payload: unknown) { return api(session, "/hr/leaves", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function recordHrEmployeeReturn(session: ActiveSession, payload: unknown) { return api(session, "/hr/leaves/return", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function listHrPayrollRuns(session: ActiveSession, query: { status?: HrPayrollStatus; cursor?: string; pageSize?: number } = {}) { return api<HrPayrollRunsReceipt>(session, withQuery("/hr/payroll-runs", query)); }
export function getHrPayrollRun(session: ActiveSession, payrollRunId: string) { return api<HrPayrollDetail>(session, `/hr/payroll-runs/${encodeURIComponent(payrollRunId)}`); }
export function setHrEmployeeCompensation(session: ActiveSession, payload: unknown) { return api(session, "/hr/compensation", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function listHrCompensationPolicies(session: ActiveSession) { return api<HrCompensationPoliciesReceipt>(session, "/hr/compensation-policies"); }
export function createHrCompensationPolicy(session: ActiveSession, payload: unknown) { return api(session, "/hr/compensation-policies", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function createHrCompensationPolicyVersion(session: ActiveSession, payload: unknown) { return api(session, "/hr/compensation-policies/version", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function approveHrCompensationPolicyVersion(session: ActiveSession, payload: unknown) { return api(session, "/hr/compensation-policies/approve", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function createHrPayrollRun(session: ActiveSession, payload: unknown) { return api(session, "/hr/payroll-runs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function previewHrPayrollRun(session: ActiveSession, payload: { payrollMonth: string; businessDate: string; includeOnLeaveEmployeeIds?: string[]; includeFullMonthNewHireEmployeeIds?: string[]; lines?: Array<{ employeeId: string; advances: Array<{ id: string; amount: string }>; administrativeDeductions: Array<{ id: string; amount: string }> }>; cursor?: string; pageSize?: number }) { return api<HrPayrollPreviewReceipt>(session, "/hr/payroll-runs/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function approveHrPayrollRun(session: ActiveSession, payload: unknown) { return api(session, "/hr/payroll-runs/approve", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function payHrPayrollRun(session: ActiveSession, payload: unknown) { return api(session, "/hr/payroll-runs/pay", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
export function reverseHrPayrollRun(session: ActiveSession, payload: unknown) { return api(session, "/hr/payroll-runs/reverse", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
