export type HrCopy = Record<string, string>;

export const hrCopy = {
  ar: {
    title: "الموارد البشرية", employees: "الموظفون", services: "الإقامات والخدمات", employeeFile: "ملف الموظف", addEmployee: "إضافة موظف", addService: "إضافة خدمة", loading: "جارٍ تحميل بيانات الموارد البشرية…", noEmployees: "لا يوجد موظفون مسجلون لهذه الشركة.", noServices: "لا توجد خدمات مسجلة.", noMovements: "لا توجد حركات مالية لهذا الموظف.", employeeNumber: "رقم الموظف", employeeName: "اسم الموظف", jobTitle: "المسمى الوظيفي", status: "الحالة", hireDate: "تاريخ التعيين", email: "البريد الإلكتروني", phone: "الجوال", notes: "ملاحظات", save: "حفظ", cancel: "إلغاء", active: "نشط", onLeave: "في إجازة", terminated: "منتهٍ", archived: "مؤرشف", serviceType: "نوع الخدمة", referenceNumber: "الرقم المرجعي", issueDate: "تاريخ الإصدار", expiryDate: "تاريخ الانتهاء", supplier: "المورد", financialCategory: "البند المالي", serviceSaved: "تم حفظ خدمة الموظف.", employeeSaved: "تم حفظ الموظف.", employeeUpdated: "تم تحديث ملف الموظف.", financialRecord: "السجل المالي للموظف", movementType: "نوع الحركة", date: "التاريخ", amount: "المبلغ", sourceReference: "مرجع العملية", loadMore: "تحميل المزيد", personalDetails: "بيانات الموظف", createEmployee: "إنشاء موظف", createService: "إنشاء خدمة", issueServiceCost: "إصدار تكلفة الخدمة", serviceCostIssued: "تم إصدار تكلفة الخدمة وقيدها.", selectEmployee: "اختر الموظف", selectSupplier: "اختر المورد", selectCategory: "اختر البند", selectVault: "اختر الخزينة", invoiceNumber: "رقم فاتورة المورد", invoiceMissingReason: "سبب عدم وجود الفاتورة", taxable: "خاضعة للضريبة", overview: "نظرة الموارد البشرية", payrollPending: "هذا المسار سيبنى بعد اعتماد سياسة الرواتب؛ لا يُسجل كخدمة موظف.", iqama: "تجديد إقامة", transfer: "نقل كفالة", visa: "تأشيرة خروج وعودة", ticket: "تذكرة سفر", medical: "تأمين طبي", health: "شهادة صحية", other: "خدمة أخرى", draft: "مسودة", issued: "صادرة", cancelled: "ملغاة", serviceCost: "تكلفة خدمة", payrollAccrual: "استحقاق راتب", payrollPayment: "سداد راتب", advanceIssued: "سلفة موظف", advanceSettlement: "تسوية سلفة", employeeServiceHint: "تسجل الخدمة أولاً، ثم تصدر تكلفتها كمصروف مستقل مرتبط بملف الموظف.", advances: "السلف", deductions: "الخصومات", addAdvance: "إصدار سلفة", advanceNumber: "رقم السلفة", originalAmount: "مبلغ السلفة", remainingAmount: "الرصيد المتبقي", advanceSaved: "تم إصدار السلفة وقيدها كذمة على الموظف.", advancePolicy: "السلفة ذمة على الموظف؛ الخصم الإداري أو التأديبي ليس تسويةً للسلفة.", advancePending: "تسوية السلفة عبر مسير الراتب أو السداد المباشر ستضاف في مسار مستقل بعد بناء الرواتب.",
  },
  en: {
    title: "Human resources", employees: "Employees", services: "Residencies & services", employeeFile: "Employee file", addEmployee: "Add employee", addService: "Add service", loading: "Loading HR data…", noEmployees: "No employees are registered for this company.", noServices: "No services are recorded.", noMovements: "No financial movements exist for this employee.", employeeNumber: "Employee no.", employeeName: "Employee", jobTitle: "Job title", status: "Status", hireDate: "Hire date", email: "Email", phone: "Phone", notes: "Notes", save: "Save", cancel: "Cancel", active: "Active", onLeave: "On leave", terminated: "Terminated", archived: "Archived", serviceType: "Service type", referenceNumber: "Reference no.", issueDate: "Issue date", expiryDate: "Expiry date", supplier: "Supplier", financialCategory: "Financial category", serviceSaved: "Employee service saved.", employeeSaved: "Employee saved.", employeeUpdated: "Employee file updated.", financialRecord: "Employee financial record", movementType: "Movement type", date: "Date", amount: "Amount", sourceReference: "Source reference", loadMore: "Load more", personalDetails: "Employee details", createEmployee: "Create employee", createService: "Create service", issueServiceCost: "Issue service cost", serviceCostIssued: "Service cost was issued and posted.", selectEmployee: "Select employee", selectSupplier: "Select supplier", selectCategory: "Select category", selectVault: "Select vault", invoiceNumber: "Supplier invoice no.", invoiceMissingReason: "Invoice missing reason", taxable: "Taxable", overview: "HR overview", payrollPending: "This workflow will be built after the payroll policy is approved; it is not an employee service.", iqama: "Iqama renewal", transfer: "Sponsorship transfer", visa: "Exit/re-entry visa", ticket: "Flight ticket", medical: "Medical insurance", health: "Health certificate", other: "Other service", draft: "Draft", issued: "Issued", cancelled: "Cancelled", serviceCost: "Service cost", payrollAccrual: "Payroll accrual", payrollPayment: "Payroll payment", advanceIssued: "Employee advance", advanceSettlement: "Advance settlement", employeeServiceHint: "Record the service first, then issue its cost as a separate expense linked to the employee file.", advances: "Advances", deductions: "Deductions", addAdvance: "Issue advance", advanceNumber: "Advance no.", originalAmount: "Advance amount", remainingAmount: "Remaining balance", advanceSaved: "The employee advance was issued and posted as a receivable.", advancePolicy: "An advance is receivable from the employee; an administrative or disciplinary deduction never settles it.", advancePending: "Payroll and direct-receipt settlement will be added as separate workflows after payroll is built.",
  },
} as const;

export function hrText(language: "ar" | "en"): HrCopy { return hrCopy[language]; }
