import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import { BaseerButton } from "./baseer-button";
import { BaseerCard } from "./baseer-card";
import { BaseerComboboxField } from "./baseer-combobox-field";
import { BaseerNotice } from "./baseer-workspace";
import { activeSession } from "./daily-sales-client";
import { getAttendanceEmployeeCompliance, type AttendanceEmployeeCompliance, type AttendanceEmployeeComplianceScope } from "./attendance-client";

import "./hr-employee-attendance-compliance-card.css";

type Language = "ar" | "en";
type CompliancePeriod = AttendanceEmployeeCompliance["currentMonth"];

const clampPercent = (value: number) => Math.max(0, Math.min(100, Number.isFinite(value) ? value : 0));
function minutes(value: number, language: Language) { const safe = Math.max(0, Math.round(value || 0)); const hours = Math.floor(safe / 60); const remainder = safe % 60; if (!hours) return language === "ar" ? `${remainder} د` : `${remainder}m`; if (!remainder) return language === "ar" ? `${hours} س` : `${hours}h`; return language === "ar" ? `${hours} س ${remainder} د` : `${hours}h ${remainder}m`; }
function periodLabel(scope: AttendanceEmployeeComplianceScope, language: Language) { const labels: Record<AttendanceEmployeeComplianceScope, [string, string]> = { MONTH: ["الشهر الحالي", "Current month"], YEAR: ["من بداية السنة", "Year to date"], LAST_6_MONTHS: ["آخر 6 أشهر", "Last 6 months"], LAST_12_MONTHS: ["آخر 12 شهراً", "Last 12 months"], EMPLOYMENT: ["من تاريخ التعيين", "Since hire date"], CUSTOM: ["فترة مخصصة", "Custom range"] }; return labels[scope][language === "ar" ? 0 : 1]; }
function toneFor(rate: number): "success" | "warning" | "danger" { return rate >= 95 ? "success" : rate >= 85 ? "warning" : "danger"; }
function RateRing({ rate, language, hasMeasurement = true }: { rate: number; language: Language; hasMeasurement?: boolean }) { const safeRate = clampPercent(rate); const tone = hasMeasurement ? toneFor(safeRate) : "neutral"; return <div className={`hr-attendance-compliance__ring hr-attendance-compliance__ring--${tone}`} role="img" aria-label={hasMeasurement ? (language === "ar" ? `مؤشر الالتزام ${safeRate}%` : `Attendance compliance ${safeRate}%`) : (language === "ar" ? "لا توجد أيام دوام مقيمة بعد" : "No evaluated workdays yet")}><div><strong dir="ltr">{hasMeasurement ? `${safeRate}%` : "—"}</strong><span>{language === "ar" ? "التزام" : "Compliance"}</span></div></div>; }
function PeriodSummary({ period, language, compact = false }: { period: CompliancePeriod; language: Language; compact?: boolean }) {
  const ar = language === "ar"; const rate = clampPercent(period.ratePercent); const hasMeasurement = period.plannedMinutes > 0 || period.eligibleWorkDays > 0; const needsReview = period.status === "NEEDS_REVIEW"; const canPublishRate = hasMeasurement && !needsReview; const statusSuffix = period.status === "NEEDS_REVIEW" ? (ar ? " · بحاجة مراجعة" : " · Needs review") : period.status === "PROVISIONAL" ? (ar ? " · مبدئي" : " · Provisional") : "";
  return <section className={compact ? "hr-attendance-compliance__aggregate" : "hr-attendance-compliance__current"}><div className="hr-attendance-compliance__period-header">{compact ? <><strong>{ar ? "الالتزام التراكمي" : "Aggregate compliance"}</strong><span dir="ltr">{period.from} — {period.to}</span></> : <><div><h4>{ar ? "التزام الشهر الحالي" : "Current-month compliance"}</h4><p>{ar ? `محسوب حتى ${period.to}${statusSuffix}` : `Calculated through ${period.to}${statusSuffix}`}</p></div><RateRing rate={rate} language={language} hasMeasurement={canPublishRate} /></>}</div>{compact ? <div className="hr-attendance-compliance__aggregate-rate"><span className={`hr-attendance-compliance__tone hr-attendance-compliance__tone--${canPublishRate ? toneFor(rate) : "neutral"}`}>{needsReview ? (ar ? "بحاجة مراجعة" : "Needs review") : (ar ? "نسبة الالتزام" : "Compliance rate")}</span><strong dir="ltr">{canPublishRate ? `${rate}%` : "—"}</strong></div> : null}<dl className="hr-attendance-compliance__metrics"><div><dt>{ar ? "المخطط" : "Planned"}</dt><dd>{minutes(period.plannedMinutes, language)}</dd></div><div><dt>{ar ? "المغطى" : "Covered"}</dt><dd>{minutes(period.coveredPlannedMinutes, language)}</dd></div><div className={period.shortageMinutes ? "hr-attendance-compliance__metric--attention" : undefined}><dt>{ar ? "غير المغطى" : "Not covered"}</dt><dd>{minutes(period.shortageMinutes, language)}</dd></div><div><dt>{ar ? "أيام مقيمة" : "Evaluated days"}</dt><dd>{period.eligibleWorkDays}</dd></div></dl>{!compact ? <div className="hr-attendance-compliance__breakdown">{needsReview ? <span>{ar ? "السجل يحتاج مراجعة قبل إصدار نسبة التزام نهائية." : "This record needs review before a final compliance rate is shown."}</span> : hasMeasurement ? <><span>{ar ? `تأخير ${minutes(period.lateMinutes, language)}` : `Late ${minutes(period.lateMinutes, language)}`}</span><span>{ar ? `خروج مبكر ${minutes(period.earlyLeaveMinutes, language)}` : `Early leave ${minutes(period.earlyLeaveMinutes, language)}`}</span><span>{ar ? `وقت زائد ${minutes(period.extraMinutes, language)} للمراجعة` : `Extra ${minutes(period.extraMinutes, language)} for review`}</span></> : <span>{ar ? "لا توجد أيام دوام مكتملة قابلة للتقييم في هذه الفترة." : "There are no completed workdays to evaluate in this period."}</span>}</div> : null}</section>;
}

/** Attendance quality is separate from payroll: coverage never exceeds 100%, and no card action can change a salary. */
export function HrEmployeeAttendanceComplianceCard({ employeeId, language }: { employeeId: string; language: Language }) {
  const ar = language === "ar"; const [scope, setScope] = useState<AttendanceEmployeeComplianceScope>("YEAR"); const [receipt, setReceipt] = useState<AttendanceEmployeeCompliance | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const requestVersion = useRef(0);
  const load = useCallback(async () => { const version = ++requestVersion.current; const session = activeSession(); if (!session) { if (version === requestVersion.current) { setReceipt(null); setError(true); setLoading(false); } return; } setLoading(true); setError(false); try { const value = await getAttendanceEmployeeCompliance(session, employeeId, { scope }); if (version === requestVersion.current) setReceipt(value); } catch { if (version === requestVersion.current) { setReceipt(null); setError(true); } } finally { if (version === requestVersion.current) setLoading(false); } }, [employeeId, scope]);
  useEffect(() => { void load(); }, [load]);
  const scopeOptions = useMemo(() => (["YEAR", "LAST_6_MONTHS", "LAST_12_MONTHS", "EMPLOYMENT"] as const).map((value) => ({ id: value, label: periodLabel(value, language) })), [language]);
  return <BaseerCard className="hr-attendance-compliance" aria-busy={loading}><header className="hr-attendance-compliance__header"><div><span>{ar ? "الحضور والانصراف" : "Attendance"}</span><h3>{ar ? "مؤشر الالتزام بالدوام" : "Attendance compliance"}</h3><p>{ar ? "يقيس تغطية وقت الدوام المخطط؛ لا يرتبط بالراتب أو احتساب الأوفر تايم." : "Measures scheduled-time coverage; it is not linked to payroll or overtime calculation."}</p></div>{receipt ? <BaseerComboboxField label={ar ? "فترة الالتزام التراكمي" : "Aggregate period"} searchable={false} value={scope} options={scopeOptions} onChange={(value) => setScope(value as AttendanceEmployeeComplianceScope)} /> : null}</header>{loading ? <p className="hr-attendance-compliance__loading">{ar ? "جارٍ احتساب الالتزام من سجل الحضور المعتمد…" : "Calculating compliance from approved attendance…"}</p> : error ? <BaseerNotice tone="warning">{ar ? "تعذر تحميل مؤشر الالتزام الآن." : "The compliance indicator could not be loaded."}<BaseerButton type="button" variant="quiet" onClick={() => void load()}>{ar ? "إعادة المحاولة" : "Try again"}</BaseerButton></BaseerNotice> : receipt ? <><div className="hr-attendance-compliance__periods"><PeriodSummary period={receipt.currentMonth} language={language} /><PeriodSummary period={receipt.aggregate} language={language} compact /></div><footer>{ar ? "الوقت الزائد مرجع للمراجعة فقط، ولا يرفع المؤشر عن 100% أو يغيّر أي راتب." : "Extra time is a review reference only; it never raises the rate above 100% or changes salary."}</footer></> : null}</BaseerCard>;
}
