import { Fragment, lazy, Suspense, type ReactNode, useEffect, useState } from "react";

import "./hr-employee-profile-dialog.css";

import { BaseerBatchPanel, BaseerWorkspaceTabs } from "./baseer-batch-layout";
import { BaseerButton } from "./baseer-button";
import { BaseerCard } from "./baseer-card";
import { BaseerDialog } from "./baseer-dialog";
import { BaseerMoney } from "./baseer-money";
import { BaseerStatusBadge } from "./baseer-status-badge";
import { BaseerEmptyState, BaseerNotice } from "./baseer-workspace";
import { DataTable } from "./data-table";
import { activeSession } from "./daily-sales-client";
import { HrEmployeePhoto } from "./hr-employee-photo";
import { listHrAdministrativeDeductions, listHrAdvances, listHrEmployeeLeaves, listHrEmployeePayrollHistory, listHrFinalSettlements, type HrAdministrativeDeduction, type HrAdvance, type HrDetail, type HrEmployeeLeave, type HrEmployeePayrollHistoryLine, type HrFinalSettlement } from "./hr-client";

type Language = "ar" | "en";
type ProfileTab = "overview" | "employment" | "compensation" | "payroll" | "time" | "compliance" | "documents" | "financial";
type LedgerRow = { id: string; reference: ReactNode; date: string; description: ReactNode; gross: ReactNode; adjustments: ReactNode; balance: ReactNode; status: ReactNode };
type LedgerSection = { id: string; title: string; empty: string; rows: readonly LedgerRow[] };
const HrPayrollDetailDialog = lazy(async () => ({ default: (await import("./hr-payroll-detail-dialog")).HrPayrollDetailDialog }));
const HrEmployeeDocumentsPanel = lazy(async () => ({ default: (await import("./hr-employee-documents-panel")).HrEmployeeDocumentsPanel }));
const HrEmployeeLettersPanel = lazy(async () => ({ default: (await import("./hr-employee-letters-panel")).HrEmployeeLettersPanel }));
const HrEmployeePromotionsPanel = lazy(async () => ({ default: (await import("./hr-employee-promotions-panel")).HrEmployeePromotionsPanel }));
const HrFinalSettlementWorkspace = lazy(async () => ({ default: (await import("./hr-final-settlement-panel")).HrFinalSettlementWorkspace }));
const HrSalaryAdjustmentDialog = lazy(async () => ({ default: (await import("./hr-salary-adjustment-dialog")).HrSalaryAdjustmentDialog }));

const employeeStatus = (language: Language, status: HrDetail["employee"]["status"]) => ({ ACTIVE: language === "ar" ? "نشط" : "Active", ON_LEAVE: language === "ar" ? "في إجازة" : "On leave", TERMINATED: language === "ar" ? "منتهٍ" : "Terminated", ARCHIVED: language === "ar" ? "مؤرشف" : "Archived" })[status];
const payrollTone = (status: string) => status === "PAID" ? "success" as const : status === "REVERSED" ? "danger" as const : status === "DRAFT" ? "warning" as const : "info" as const;

/** The employee file is the HR workspace. Salary history stays internal while the UI stays simple. */
export function HrEmployeeProfileDialog({ detail, language, onClose, onEdit, onManageCompensation, onLoadMoreMovements, onError, onChanged }: { detail: HrDetail; language: Language; onClose: () => void; onEdit: () => void; onManageCompensation: () => void; onLoadMoreMovements: () => Promise<void>; onError: (message: string) => void; onChanged: () => Promise<void> }) {
  const ar = language === "ar";
  const employeeId = detail.employee.id;
  const [tab, setTab] = useState<ProfileTab>("overview");
  const [loading, setLoading] = useState(true);
  const [payroll, setPayroll] = useState<HrEmployeePayrollHistoryLine[]>([]);
  const [payrollCursor, setPayrollCursor] = useState<string | null>(null);
  const [advances, setAdvances] = useState<HrAdvance[]>([]);
  const [deductions, setDeductions] = useState<HrAdministrativeDeduction[]>([]);
  const [leaves, setLeaves] = useState<HrEmployeeLeave[]>([]);
  const [leaveCursor, setLeaveCursor] = useState<string | null>(null);
  const [settlements, setSettlements] = useState<HrFinalSettlement[]>([]);
  const [payrollRunId, setPayrollRunId] = useState<string | null>(null);
  const [finalSettlementOpen, setFinalSettlementOpen] = useState(false);
  const [salaryAdjustment, setSalaryAdjustment] = useState<"INCREASE" | "DECREASE" | null>(null);

  useEffect(() => { setTab("overview"); }, [employeeId]);
  useEffect(() => {
    const session = activeSession();
    if (!session) { setLoading(false); return; }
    setLoading(true);
    void Promise.all([listHrEmployeePayrollHistory(session, employeeId, { pageSize: 25 }), listHrAdvances(session, { employeeId, pageSize: 50 }), listHrAdministrativeDeductions(session, { employeeId, pageSize: 50 }), listHrEmployeeLeaves(session, { employeeId, pageSize: 50 }), listHrFinalSettlements(session, { employeeId, pageSize: 25 })])
      .then(([payrollReceipt, advanceReceipt, deductionReceipt, leaveReceipt, settlementReceipt]) => { setPayroll(payrollReceipt.lines); setPayrollCursor(payrollReceipt.nextCursor); setAdvances(advanceReceipt.advances); setDeductions(deductionReceipt.deductions); setLeaves(leaveReceipt.leaves); setLeaveCursor(leaveReceipt.nextCursor); setSettlements(settlementReceipt.settlements); })
      .catch(() => onError(ar ? "تعذر تحميل ملف الموظف المتكامل." : "The complete employee file could not be loaded."))
      .finally(() => setLoading(false));
  }, [ar, employeeId, onError]);

  const name = ar ? detail.employee.nameAr : detail.employee.nameEn ?? detail.employee.nameAr;
  const salary = detail.compensation;
  const tabs: readonly { id: ProfileTab; label: string }[] = [{ id: "overview", label: ar ? "نظرة 360" : "360 overview" }, { id: "employment", label: ar ? "المسار والتعويض" : "Employment & compensation" }, { id: "payroll", label: ar ? "الرواتب والتسويات" : "Payroll & settlements" }, { id: "time", label: ar ? "الإجازات" : "Leaves" }, { id: "compliance", label: ar ? "الخدمات والامتثال" : "Services & compliance" }, { id: "documents", label: ar ? "المستندات والخطابات" : "Documents & letters" }, { id: "financial", label: ar ? "السجل المالي" : "Financial record" }];
  const leaveColumns = [{ id: "type", header: ar ? "النوع" : "Type", cell: (row: HrEmployeeLeave) => row.leaveType }, { id: "period", header: ar ? "الفترة" : "Period", cell: (row: HrEmployeeLeave) => `${row.startDate} — ${row.endDate}` }, { id: "return", header: ar ? "العودة" : "Return", cell: (row: HrEmployeeLeave) => row.actualReturnDate ?? "—" }, { id: "status", header: ar ? "الحالة" : "Status", cell: (row: HrEmployeeLeave) => <BaseerStatusBadge tone={row.status === "RETURNED" ? "success" : "warning"}>{row.status === "RETURNED" ? (ar ? "عاد للعمل" : "Returned") : (ar ? "معتمدة" : "Approved")}</BaseerStatusBadge> }];
  const serviceColumns = [{ id: "type", header: ar ? "الخدمة" : "Service", cell: (row: HrDetail["services"][number]) => row.serviceType }, { id: "reference", header: ar ? "المرجع" : "Reference", cell: (row: HrDetail["services"][number]) => row.referenceNumber ?? "—" }, { id: "expiry", header: ar ? "الانتهاء" : "Expiry", cell: (row: HrDetail["services"][number]) => row.expiryDate ?? "—" }, { id: "status", header: ar ? "الحالة" : "Status", cell: (row: HrDetail["services"][number]) => <BaseerStatusBadge tone={row.status === "ISSUED" ? "success" : row.status === "CANCELLED" ? "neutral" : "warning"}>{row.status}</BaseerStatusBadge> }];
  const movementColumns = [{ id: "date", header: ar ? "التاريخ" : "Date", cell: (row: HrDetail["movements"][number]) => row.businessDate }, { id: "type", header: ar ? "العملية" : "Operation", cell: (row: HrDetail["movements"][number]) => row.movementType }, { id: "reference", header: ar ? "المرجع" : "Reference", cell: (row: HrDetail["movements"][number]) => row.sourceReference }, { id: "amount", header: ar ? "المبلغ" : "Amount", numeric: true, align: "end" as const, cell: (row: HrDetail["movements"][number]) => <BaseerMoney value={row.amount} language={language} /> }];
  const salaryHistory = detail.compensationHistory.map((row, index) => { const previous = detail.compensationHistory[index + 1]; const difference = previous ? Number(row.monthlyGross) - Number(previous.monthlyGross) : 0; const changeLabel = row.notes?.startsWith("ترقية") ? (ar ? "ترقية وزيادة راتب" : "Promotion and salary increase") : difference > 0 ? (ar ? "زيادة راتب" : "Salary increase") : difference < 0 ? (ar ? "تخفيض راتب" : "Salary decrease") : (ar ? "الراتب الأول / تعديل" : "Initial salary / edit"); return { ...row, changeLabel, changeAmount: previous ? Math.abs(difference).toFixed(4) : null }; });
  const salaryHistoryColumns = [{ id: "effective", header: ar ? "بداية التطبيق" : "Effective from", cell: (row: typeof salaryHistory[number]) => row.effectiveFrom }, { id: "change", header: ar ? "التغيير" : "Change", cell: (row: typeof salaryHistory[number]) => <span>{row.changeLabel}{row.changeAmount ? <> · <BaseerMoney value={row.changeAmount} language={language} /></> : null}</span> }, { id: "salary", header: ar ? "إجمالي الراتب" : "Monthly salary", numeric: true, align: "end" as const, cell: (row: typeof salaryHistory[number]) => <BaseerMoney value={row.monthlyGross} language={language} /> }, { id: "reason", header: ar ? "السبب / الملاحظة" : "Reason / note", cell: (row: typeof salaryHistory[number]) => row.notes ?? "—" }];
  const openAdvanceCount = advances.filter((item) => item.status === "ISSUED" || item.status === "PARTIALLY_SETTLED").length;
  const sections: readonly LedgerSection[] = [
    { id: "payroll", title: ar ? "مسيرات الرواتب" : "Payroll runs", empty: ar ? "لا توجد مسيرات لهذا الموظف." : "No payroll runs for this employee.", rows: payroll.map((row) => ({ id: row.id, reference: <BaseerButton type="button" variant="quiet" onClick={() => setPayrollRunId(row.payrollRunId)}>{row.runNumber}</BaseerButton>, date: row.payrollMonth, description: ar ? "راتب الشهر" : "Monthly payroll", gross: <BaseerMoney value={row.grossSalary} language={language} />, adjustments: <span className="hr-payroll-settlements__adjustments"><span>{ar ? "سلف" : "Advances"} <BaseerMoney value={row.advanceSettlementAmount} language={language} /></span><span>{ar ? "خصومات" : "Deductions"} <BaseerMoney value={row.administrativeDeductionAmount} language={language} /></span></span>, balance: <BaseerMoney value={row.netPayableAmount} language={language} />, status: <BaseerStatusBadge tone={payrollTone(row.payrollStatus)}>{row.payrollStatus}</BaseerStatusBadge> })) },
    { id: "settlements", title: ar ? "مخالصات نهاية الخدمة" : "End-of-service settlements", empty: ar ? "لا توجد مخالصات نهاية خدمة." : "No end-of-service settlements.", rows: settlements.map((row) => ({ id: row.id, reference: row.settlementNumber, date: row.terminationDate, description: ar ? "مخالصة نهاية الخدمة" : "End-of-service settlement", gross: <BaseerMoney value={row.fullAwardAmount} language={language} />, adjustments: <BaseerMoney value={row.recoveryAmount} language={language} />, balance: <BaseerMoney value={row.netPayableAmount} language={language} />, status: <BaseerStatusBadge tone={payrollTone(row.status)}>{row.status}</BaseerStatusBadge> })) },
    { id: "advances", title: ar ? "السلف" : "Advances", empty: ar ? "لا توجد سلف." : "No advances.", rows: advances.map((row) => ({ id: row.id, reference: row.advanceNumber, date: row.businessDate, description: row.notes || (ar ? "سلفة موظف" : "Employee advance"), gross: <BaseerMoney value={row.originalAmount} language={language} />, adjustments: <BaseerMoney value={row.settledAmount} language={language} />, balance: <BaseerMoney value={row.remainingAmount} language={language} />, status: <BaseerStatusBadge tone={row.status === "SETTLED" ? "success" : row.status === "REVERSED" ? "danger" : "warning"}>{row.status}</BaseerStatusBadge> })) },
    { id: "deductions", title: ar ? "الخصومات الإدارية" : "Administrative deductions", empty: ar ? "لا توجد خصومات إدارية." : "No administrative deductions.", rows: deductions.map((row) => ({ id: row.id, reference: row.deductionNumber, date: row.businessDate, description: row.description, gross: <BaseerMoney value={row.originalAmount} language={language} />, adjustments: <BaseerMoney value={row.appliedAmount} language={language} />, balance: <BaseerMoney value={row.remainingAmount} language={language} />, status: <BaseerStatusBadge tone={row.status === "APPLIED" ? "success" : row.status === "CANCELLED" ? "neutral" : "info"}>{row.status}</BaseerStatusBadge> })) },
  ];

  return <><BaseerDialog open title={name} size="wide" language={language} onClose={onClose}><section className="hr-employee-profile"><header className="hr-employee-profile__hero"><div className="hr-employee-profile__identity"><HrEmployeePhoto employeeId={employeeId} name={name} language={language} onError={onError} onChanged={onChanged} /><div><div className="hr-employee-profile__name"><h2>{name}</h2><BaseerStatusBadge tone={detail.employee.status === "ACTIVE" ? "success" : detail.employee.status === "ON_LEAVE" ? "warning" : "neutral"}>{employeeStatus(language, detail.employee.status)}</BaseerStatusBadge></div><p>{detail.employee.employeeNumber} · {detail.employee.jobTitle ?? (ar ? "دون مسمى وظيفي" : "No job title")}</p></div></div><div className="hr-employee-profile__actions"><BaseerButton type="button" disabled={!salary} onClick={() => setSalaryAdjustment("INCREASE")}>{ar ? "زيادة راتب" : "Increase salary"}</BaseerButton><BaseerButton type="button" variant="secondary" disabled={!salary} onClick={() => setSalaryAdjustment("DECREASE")}>{ar ? "تخفيض راتب" : "Decrease salary"}</BaseerButton><BaseerButton type="button" variant="secondary" onClick={onManageCompensation}>{ar ? "تعديل الراتب" : "Edit salary"}</BaseerButton><BaseerButton type="button" variant="secondary" disabled={detail.employee.status !== "TERMINATED"} title={detail.employee.status !== "TERMINATED" ? (ar ? "يُتاح بعد إنهاء الموظف وتسجيل تاريخ الإنهاء." : "Available after terminating the employee and recording the termination date.") : undefined} onClick={() => setFinalSettlementOpen(true)}>{ar ? "نهاية الخدمة" : "End of service"}</BaseerButton><BaseerButton type="button" variant="secondary" onClick={onEdit}>{ar ? "تعديل البيانات" : "Edit employee"}</BaseerButton></div></header><BaseerWorkspaceTabs ariaLabel={ar ? "أقسام ملف الموظف" : "Employee file sections"} idPrefix="hr-employee-profile" tabs={tabs} activeId={tab} onChange={(value) => setTab(value as ProfileTab)} /><BaseerBatchPanel id={`hr-employee-profile-panel-${tab}`} labelledBy={`hr-employee-profile-${tab}`}>{loading ? <BaseerNotice tone="info">{ar ? "جارٍ جمع سجل الموظف من المصادر الموثقة…" : "Collecting the employee record from governed sources…"}</BaseerNotice> : null}
    {tab === "overview" ? <div className="hr-employee-profile__overview"><div className="hr-employee-profile__facts"><BaseerCard><h3>{ar ? "بيانات العمل" : "Employment details"}</h3><dl><div><dt>{ar ? "تاريخ التعيين" : "Hire date"}</dt><dd>{detail.employee.hireDate}</dd></div><div><dt>{ar ? "رقم الإقامة" : "Iqama number"}</dt><dd dir="ltr">{detail.employee.iqamaNumber ?? "—"}</dd></div><div><dt>{ar ? "الجوال" : "Phone"}</dt><dd>{detail.employee.phone ?? "—"}</dd></div><div><dt>{ar ? "البريد" : "Email"}</dt><dd>{detail.employee.email ?? "—"}</dd></div></dl></BaseerCard><BaseerCard><h3>{ar ? "الراتب الحالي" : "Current salary"}</h3>{salary ? <dl><div><dt>{ar ? "الإجمالي الشهري" : "Monthly total"}</dt><dd><BaseerMoney value={salary.monthlyGross} language={language} /></dd></div><div><dt>{ar ? "طريقة الاحتساب" : "Calculation method"}</dt><dd>{salary.compensationMethod === "INCLUSIVE_OVERTIME" ? (ar ? "شامل الأوفر تايم" : "Inclusive overtime") : (ar ? "راتب ثابت" : "Fixed monthly")}</dd></div><div><dt>{ar ? "يسري من" : "Applies from"}</dt><dd>{salary.effectiveFrom}</dd></div></dl> : <BaseerEmptyState title={ar ? "لم يُحدد راتب بعد" : "Salary not set"} action={<BaseerButton type="button" onClick={onManageCompensation}>{ar ? "تحديد الراتب" : "Set salary"}</BaseerButton>} />}</BaseerCard></div><div className="hr-employee-profile__snapshot"><BaseerCard><h3>{ar ? "لقطة السجل" : "Record snapshot"}</h3><div className="hr-employee-profile__stats"><span><small>{ar ? "مسيرات" : "Payroll runs"}</small><strong>{payroll.length}</strong></span><span><small>{ar ? "سلف مفتوحة" : "Open advances"}</small><strong>{openAdvanceCount}</strong></span><span><small>{ar ? "إجازات" : "Leaves"}</small><strong>{leaves.length}</strong></span><span><small>{ar ? "خدمات" : "Services"}</small><strong>{detail.services.length}</strong></span></div></BaseerCard><BaseerNotice tone="info" title={ar ? "ملف موحد" : "One governed file"}>{ar ? "الخدمات والمستندات والرواتب والسلف والإجازات والمخالصات مرتبطة هنا بالموظف نفسه." : "Services, documents, payroll, advances, leaves, and settlements are connected here to this employee."}</BaseerNotice></div></div> : null}
    {tab === "employment" ? <Suspense fallback={<BaseerCard>{ar ? "جارٍ تحميل المسار الوظيفي…" : "Loading employment history…"}</BaseerCard>}><HrEmployeePromotionsPanel employeeId={employeeId} language={language} salary={salary} onError={onError} onChanged={onChanged} /></Suspense> : null}
    {tab === "compensation" ? <div className="hr-employee-profile__stack"><BaseerCard><header className="baseer-card__header"><div><h3>{ar ? "الراتب والبدلات" : "Salary and allowances"}</h3><p>{ar ? "الزيادة أو التخفيض ينشئان سجلاً مؤرخاً جديداً، ولا يغيران أي مسير سابق." : "Increases and decreases create a new dated record and never change past payroll."}</p></div><div className="baseer-inline-actions">{salary ? <><BaseerButton type="button" onClick={() => setSalaryAdjustment("INCREASE")}>{ar ? "زيادة راتب" : "Increase salary"}</BaseerButton><BaseerButton type="button" variant="secondary" onClick={() => setSalaryAdjustment("DECREASE")}>{ar ? "تخفيض راتب" : "Decrease salary"}</BaseerButton></> : null}<BaseerButton type="button" variant="secondary" onClick={onManageCompensation}>{salary ? (ar ? "تعديل الراتب" : "Edit salary") : (ar ? "تحديد الراتب" : "Set salary")}</BaseerButton></div></header>{salary ? <dl className="administration-details"><div><dt>{ar ? "الإجمالي الشهري" : "Monthly total"}</dt><dd><BaseerMoney value={salary.monthlyGross} language={language} /></dd></div><div><dt>{ar ? "الراتب الأساسي" : "Basic salary"}</dt><dd><BaseerMoney value={(Number(salary.monthlyGross) - Number(salary.foodAllowance) - Number(salary.housingAllowance) - Number(salary.transportAllowance) - Number(salary.otherAllowance)).toFixed(4)} language={language} /></dd></div><div><dt>{ar ? "بدل السكن" : "Housing allowance"}</dt><dd><BaseerMoney value={salary.housingAllowance} language={language} /></dd></div><div><dt>{ar ? "بدل المواصلات" : "Transport allowance"}</dt><dd><BaseerMoney value={salary.transportAllowance} language={language} /></dd></div><div><dt>{ar ? "بدل الأكل" : "Food allowance"}</dt><dd><BaseerMoney value={salary.foodAllowance} language={language} /></dd></div><div><dt>{ar ? "بدلات أخرى" : "Other allowances"}</dt><dd><BaseerMoney value={salary.otherAllowance} language={language} /></dd></div></dl> : <BaseerEmptyState title={ar ? "لم يُحدد راتب بعد" : "Salary not set"} />}</BaseerCard><ProfileTable rows={salaryHistory} columns={salaryHistoryColumns} rowKey={(row) => row.id} empty={ar ? "لا توجد تغييرات راتب مسجلة." : "No salary changes recorded."} label={ar ? "سجل تغييرات الراتب" : "Salary change history"} /></div> : null}
    {tab === "payroll" ? <PayrollSettlementLedger language={language} sections={sections} onMore={payrollCursor ? async () => { const session = activeSession(); if (!session) return; const receipt = await listHrEmployeePayrollHistory(session, employeeId, { cursor: payrollCursor, pageSize: 25 }); setPayroll((rows) => [...rows, ...receipt.lines]); setPayrollCursor(receipt.nextCursor); } : undefined} /> : null}
    {tab === "time" ? <ProfileTable rows={leaves} columns={leaveColumns} rowKey={(row) => row.id} empty={ar ? "لا توجد إجازات." : "No leaves."} label={ar ? "إجازات الموظف" : "Employee leaves"} onMore={leaveCursor ? async () => { const session = activeSession(); if (!session) return; const receipt = await listHrEmployeeLeaves(session, { employeeId, cursor: leaveCursor, pageSize: 50 }); setLeaves((rows) => [...rows, ...receipt.leaves]); setLeaveCursor(receipt.nextCursor); } : undefined} /> : null}
    {tab === "compliance" ? <ProfileTable rows={detail.services} columns={serviceColumns} rowKey={(row) => row.id} empty={ar ? "لا توجد خدمات أو سجلات امتثال." : "No services or compliance records."} label={ar ? "خدمات الموظف وامتثاله" : "Employee services & compliance"} /> : null}
    {tab === "documents" ? <div className="hr-employee-profile__stack"><Suspense fallback={<BaseerCard>{ar ? "جارٍ تحميل المستندات…" : "Loading documents…"}</BaseerCard>}><HrEmployeeDocumentsPanel employeeId={employeeId} language={language} onError={onError} onChanged={onChanged} /></Suspense><Suspense fallback={<BaseerCard>{ar ? "جارٍ تحميل الخطابات…" : "Loading letters…"}</BaseerCard>}><HrEmployeeLettersPanel employeeId={employeeId} language={language} hasCurrentCompensation={Boolean(salary)} onManageCompensation={onManageCompensation} onError={onError} onChanged={onChanged} /></Suspense></div> : null}
    {tab === "financial" ? <ProfileTable rows={detail.movements} columns={movementColumns} rowKey={(row) => row.id} empty={ar ? "لا توجد حركات مالية." : "No financial movements."} label={ar ? "الحركات المالية المرتبطة بالموظف" : "Employee-linked financial movements"} onMore={detail.hasMoreMovements ? onLoadMoreMovements : undefined} /> : null}
  </BaseerBatchPanel></section></BaseerDialog>{salaryAdjustment && salary ? <Suspense fallback={null}><HrSalaryAdjustmentDialog open language={language} employee={detail.employee} profile={salary} mode={salaryAdjustment} onClose={() => setSalaryAdjustment(null)} onSaved={onChanged} onError={onError} /></Suspense> : null}{payrollRunId ? <Suspense fallback={null}><HrPayrollDetailDialog runId={payrollRunId} language={language} onClose={() => setPayrollRunId(null)} onChanged={onChanged} onError={onError} /></Suspense> : null}{finalSettlementOpen ? <BaseerDialog open title={ar ? `نهاية خدمة ${name}` : `End of service — ${name}`} size="wide" language={language} onClose={() => { setFinalSettlementOpen(false); void onChanged(); }}><Suspense fallback={<BaseerCard>{ar ? "جارٍ تحميل المخالصة…" : "Loading settlement…"}</BaseerCard>}><HrFinalSettlementWorkspace language={language} employee={detail.employee} /></Suspense></BaseerDialog> : null}</>;
}

function ProfileTable<T>({ rows, columns, rowKey, empty, label, onMore }: { rows: readonly T[]; columns: readonly any[]; rowKey: (row: T) => string; empty: string; label: string; onMore?: () => void | Promise<void> }) {
  return <section className="hr-profile-table"><header><h3>{label}</h3></header>{rows.length ? <DataTable ariaLabel={label} caption={label} rows={rows} columns={columns} rowKey={rowKey} /> : <BaseerEmptyState title={empty} />}{onMore ? <BaseerButton type="button" variant="secondary" onClick={() => void onMore()}>تحميل المزيد / Load more</BaseerButton> : null}</section>;
}

function PayrollSettlementLedger({ language, sections, onMore }: { language: Language; sections: readonly LedgerSection[]; onMore?: () => void | Promise<void> }) {
  const ar = language === "ar";
  return <section className="hr-payroll-settlements" aria-label={ar ? "الرواتب والتسويات" : "Payroll and settlements"}><header><div><h3>{ar ? "الرواتب والتسويات" : "Payroll & settlements"}</h3><p>{ar ? "سجل موحد للرواتب والمخالصات والسلف والخصومات الخاصة بهذا الموظف." : "A unified record of this employee's payroll, settlements, advances, and deductions."}</p></div></header><div className="hr-payroll-settlements__scroll"><table><thead><tr><th>{ar ? "المرجع" : "Reference"}</th><th>{ar ? "التاريخ" : "Date"}</th><th>{ar ? "البيان" : "Description"}</th><th>{ar ? "الإجمالي" : "Gross"}</th><th>{ar ? "التسوية / المسدد" : "Settled / applied"}</th><th>{ar ? "الصافي / المتبقي" : "Net / remaining"}</th><th>{ar ? "الحالة" : "Status"}</th></tr></thead><tbody>{sections.map((section) => <Fragment key={section.id}><tr className="hr-payroll-settlements__section"><th colSpan={7}><span>{section.title}</span><small>{section.rows.length}</small></th></tr>{section.rows.length ? section.rows.map((row) => <tr key={row.id}><td>{row.reference}</td><td dir="ltr">{row.date}</td><td>{row.description}</td><td className="hr-payroll-settlements__amount">{row.gross}</td><td className="hr-payroll-settlements__amount">{row.adjustments}</td><td className="hr-payroll-settlements__amount hr-payroll-settlements__balance">{row.balance}</td><td>{row.status}</td></tr>) : <tr className="hr-payroll-settlements__empty"><td colSpan={7}>{section.empty}</td></tr>}</Fragment>)}</tbody></table></div>{onMore ? <BaseerButton type="button" variant="secondary" onClick={() => void onMore()}>{ar ? "تحميل مسيرات أقدم" : "Load older payroll runs"}</BaseerButton> : null}</section>;
}
