import { useMemo, useState } from "react";

import { presentBaseerApiError } from "./baseer-api-error";
import { BaseerButton } from "./baseer-button";
import { BaseerDialog } from "./baseer-dialog";
import { BaseerMoney } from "./baseer-money";
import { BaseerNotice } from "./baseer-workspace";
import { activeSession, api, requestId } from "./daily-sales-client";
import { setHrEmployeeCompensation } from "./hr-client";
import { HrJobTitleSuggestions } from "./hr-job-titles";

type Language = "ar" | "en";
type Draft = { nameAr: string; nameEn: string; jobTitle: string; hireDate: string; iqamaNumber: string; phone: string; email: string; effectiveMonth: string; basicSalary: string; housingAllowance: string; transportAllowance: string; foodAllowance: string; otherAllowance: string; scheduledHoursPerDay: string; scheduledWorkDays: string; workSchedule: string; notes: string };
const today = () => new Date().toISOString().slice(0, 10);
const empty = (): Draft => ({ nameAr: "", nameEn: "", jobTitle: "", hireDate: today(), iqamaNumber: "", phone: "", email: "", effectiveMonth: today().slice(0, 7), basicSalary: "", housingAllowance: "0", transportAllowance: "0", foodAllowance: "0", otherAllowance: "0", scheduledHoursPerDay: "8", scheduledWorkDays: "26", workSchedule: "", notes: "" });
const number = (value: string) => { const parsed = Number(value || "0"); return Number.isFinite(parsed) && parsed >= 0 ? parsed : 0; };

/** Guided onboarding keeps the pleasant single form while persisting an effective-dated agreement. */
export function HrEmployeeOnboardingDialog({ open, language, onClose, onSaved, onError }: { open: boolean; language: Language; onClose: () => void; onSaved: () => Promise<void>; onError: (message: string) => void }) {
  const ar = language === "ar";
  const [draft, setDraft] = useState<Draft>(empty);
  const [busy, setBusy] = useState(false);
  const total = useMemo(() => number(draft.basicSalary) + number(draft.housingAllowance) + number(draft.transportAllowance) + number(draft.foodAllowance) + number(draft.otherAllowance), [draft]);
  const set = <K extends keyof Draft>(key: K, value: Draft[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const close = () => { if (busy) return; setDraft(empty()); onClose(); };
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); const session = activeSession(); if (!session || busy || total <= 0 || number(draft.basicSalary) <= 0) return;
    setBusy(true);
    try {
      const employee = await api<{ id: string }>(session, "/hr/employees", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ nameAr: draft.nameAr, nameEn: draft.nameEn || undefined, jobTitle: draft.jobTitle || undefined, phone: draft.phone || undefined, email: draft.email || undefined, workSchedule: draft.workSchedule || undefined, hireDate: draft.hireDate, notes: draft.notes || undefined, idempotencyKey: requestId() }) });
      await setHrEmployeeCompensation(session, { employeeId: employee.id, effectiveFrom: `${draft.effectiveMonth}-01`, monthlyGross: total.toFixed(4), compensationMethod: "FIXED_MONTHLY", foodAllowance: number(draft.foodAllowance).toFixed(4), housingAllowance: number(draft.housingAllowance).toFixed(4), transportAllowance: number(draft.transportAllowance).toFixed(4), otherAllowance: number(draft.otherAllowance).toFixed(4), scheduledHoursPerDay: Number(draft.scheduledHoursPerDay), scheduledWorkDays: Number(draft.scheduledWorkDays), idempotencyKey: requestId() });
      if (draft.iqamaNumber.trim()) await api(session, "/hr/services", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ employeeId: employee.id, serviceType: "IQAMA_ISSUANCE", referenceNumber: draft.iqamaNumber.trim(), issueDate: draft.hireDate, idempotencyKey: requestId() }) });
      await onSaved(); setDraft(empty()); onClose();
    } catch (error) { onError(presentBaseerApiError(error, language, ar ? "إضافة الموظف" : "Adding employee")); }
    finally { setBusy(false); }
  };
  return <BaseerDialog open={open} title={ar ? "إضافة موظف" : "Add employee"} size="wide" language={language} busy={busy} onClose={close} footer={<><BaseerButton type="button" variant="secondary" disabled={busy} onClick={close}>{ar ? "إلغاء" : "Cancel"}</BaseerButton><BaseerButton type="submit" form="hr-employee-onboarding" disabled={busy || total <= 0 || number(draft.basicSalary) <= 0}>{ar ? "إضافة الموظف وحفظ الاتفاق" : "Add employee & save agreement"}</BaseerButton></>}>
    <form id="hr-employee-onboarding" className="hr-onboarding" onSubmit={(event) => void submit(event)}>
      <BaseerNotice tone="info" title={ar ? "رقم موظف تلقائي" : "Automatic employee number"}>{ar ? "سيُنشئ النظام الرقم EMP بالتسلسل عند الحفظ. اتفاق الراتب أدناه مؤرّخ من شهر التعيين ولا يغيّر أي سجل تاريخي لاحقاً." : "The system assigns the next EMP number on save. The agreement below is effective-dated from the hiring month and never rewrites history."}</BaseerNotice>
      <section className="hr-onboarding__section"><header><span>01</span><div><h3>{ar ? "الهوية والتعيين" : "Identity & employment"}</h3><p>{ar ? "البيانات الأساسية التي ستظهر في ملف الموظف." : "The core information shown in the employee file."}</p></div></header><div className="hr-onboarding__grid"><label>{ar ? "الاسم الكامل" : "Full name"}<em>*</em><input required autoFocus value={draft.nameAr} placeholder={ar ? "الاسم الكامل" : "Full name"} onChange={(event) => set("nameAr", event.target.value)} /></label><label>{ar ? "الاسم بالإنجليزية" : "Name (English)"}<input value={draft.nameEn} placeholder="Employee name in English" onChange={(event) => set("nameEn", event.target.value)} /></label><label>{ar ? "المسمى الوظيفي" : "Job title"}<input list="hr-onboarding-job-titles" value={draft.jobTitle} placeholder={ar ? "اختر من القائمة أو اكتب مسمى آخر" : "Choose a title or enter another"} onChange={(event) => set("jobTitle", event.target.value)} /><HrJobTitleSuggestions id="hr-onboarding-job-titles" language={language} /></label><label>{ar ? "تاريخ التعيين" : "Hire date"}<em>*</em><input required type="date" max={today()} value={draft.hireDate} onChange={(event) => set("hireDate", event.target.value)} /></label><label>{ar ? "رقم الإقامة" : "Iqama number"}<input inputMode="numeric" value={draft.iqamaNumber} placeholder="1234567890" onChange={(event) => set("iqamaNumber", event.target.value)} /></label><label>{ar ? "رقم الجوال" : "Phone"}<input inputMode="tel" value={draft.phone} onChange={(event) => set("phone", event.target.value)} /></label><label>{ar ? "البريد الإلكتروني" : "Email"}<input type="email" value={draft.email} onChange={(event) => set("email", event.target.value)} /></label><label>{ar ? "نظام العمل" : "Work schedule"}<input value={draft.workSchedule} placeholder={ar ? "مثال: الأحد إلى الخميس" : "Example: Sunday to Thursday"} onChange={(event) => set("workSchedule", event.target.value)} /></label></div></section>
      <section className="hr-onboarding__section"><header><span>02</span><div><h3>{ar ? "الاتفاق المالي الأول" : "Initial compensation agreement"}</h3><p>{ar ? "تفصيل واضح للراتب والبدلات، محفوظ كاتفاق مؤرّخ." : "A clear salary breakdown, stored as an effective-dated agreement."}</p></div></header><div className="hr-onboarding__grid"><label>{ar ? "شهر سريان الاتفاق" : "Agreement effective month"}<em>*</em><input required type="month" value={draft.effectiveMonth} onChange={(event) => set("effectiveMonth", event.target.value)} /></label><label>{ar ? "الراتب الأساسي" : "Basic salary"}<em>*</em><input required min="0.01" inputMode="decimal" value={draft.basicSalary} onChange={(event) => set("basicSalary", event.target.value)} /></label><label>{ar ? "بدل السكن" : "Housing allowance"}<input inputMode="decimal" value={draft.housingAllowance} onChange={(event) => set("housingAllowance", event.target.value)} /></label><label>{ar ? "بدل المواصلات" : "Transport allowance"}<input inputMode="decimal" value={draft.transportAllowance} onChange={(event) => set("transportAllowance", event.target.value)} /></label><label>{ar ? "بدل الأكل" : "Food allowance"}<input inputMode="decimal" value={draft.foodAllowance} onChange={(event) => set("foodAllowance", event.target.value)} /></label><label>{ar ? "بدلات أخرى" : "Other allowances"}<input inputMode="decimal" value={draft.otherAllowance} onChange={(event) => set("otherAllowance", event.target.value)} /></label><label>{ar ? "ساعات العمل يومياً" : "Daily working hours"}<input required type="number" min="1" max="12" value={draft.scheduledHoursPerDay} onChange={(event) => set("scheduledHoursPerDay", event.target.value)} /></label><label>{ar ? "أيام العمل شهرياً" : "Monthly working days"}<input required type="number" min="1" max="31" value={draft.scheduledWorkDays} onChange={(event) => set("scheduledWorkDays", event.target.value)} /></label><div className="hr-onboarding__total"><span>{ar ? "إجمالي الراتب الشهري" : "Total monthly salary"}</span><BaseerMoney value={total} language={language} /></div></div></section>
      <section className="hr-onboarding__section"><header><span>03</span><div><h3>{ar ? "ملاحظات" : "Notes"}</h3><p>{ar ? "اختياري؛ خاص بملف الموظف." : "Optional; stored in the employee file."}</p></div></header><label className="hr-onboarding__notes">{ar ? "ملاحظات الموظف" : "Employee notes"}<textarea value={draft.notes} onChange={(event) => set("notes", event.target.value)} /></label></section>
    </form>
  </BaseerDialog>;
}
