import { useCallback, useEffect, useMemo, useState } from "react";

import { presentBaseerApiError } from "./baseer-api-error";
import { BaseerButton } from "./baseer-button";
import { BaseerCard } from "./baseer-card";
import { BaseerDialog } from "./baseer-dialog";
import { BaseerFilterBar } from "./baseer-filter-bar";
import { BaseerSearchSelect } from "./baseer-search-select";
import { BaseerSummaryMetric, BaseerSummaryMetricGrid } from "./baseer-summary-metric";
import { DataTable, type DataTableColumn } from "./data-table";
import { activeSession, api, requestId, type ActiveSession } from "./daily-sales-client";
import { DailySalesSignIn } from "./daily-sales-sign-in";
import { cancelHrEmployeeService, createHrEmployeeService, getHrEmployeeService, issueHrEmployeeServiceCost, listHrEmployeeServices, listHrEmployees, renewHrEmployeeService, updateHrEmployeeService, type HrEmployee, type HrEmployeeServiceComplianceStatus, type HrEmployeeServiceRecord, type HrService } from "./hr-services-client";

type Language = "ar" | "en";
type ServiceForm = { employeeId: string; serviceType: HrService["serviceType"]; referenceNumber: string; issueDate: string; expiryDate: string; supplierId: string; categoryId: string; visaDurationMonths: string; notes: string };
type CostForm = { serviceId: string; businessDate: string; grossAmount: string; isTaxable: boolean; vaultId: string; supplierInvoiceNumber: string; supplierInvoiceMissingReason: string; supplierInvoiceDate: string; notes: string };
type FinanceConfiguration = { suppliers: Array<{ id: string; nameAr: string; nameEn: string | null; status: "ACTIVE" | "ARCHIVED" }>; categories: Array<{ id: string; nameAr: string; nameEn: string; kind: "PURCHASE" | "EXPENSE" | "SALE"; status: "ACTIVE" | "ARCHIVED"; isPosting: boolean }>; vaults: Array<{ id: string; nameAr: string; nameEn: string; status: "ACTIVE" | "ARCHIVED"; isPaymentDestination: boolean }> };

const today = () => new Date().toISOString().slice(0, 10);
const inDays = (days: number) => { const date = new Date(); date.setDate(date.getDate() + days); return date.toISOString().slice(0, 10); };
const emptyService = (employeeId = ""): ServiceForm => ({ employeeId, serviceType: "IQAMA_RENEWAL", referenceNumber: "", issueDate: today(), expiryDate: "", supplierId: "", categoryId: "", visaDurationMonths: "", notes: "" });
const emptyCost = (serviceId = "", vaultId = ""): CostForm => ({ serviceId, businessDate: today(), grossAmount: "", isTaxable: true, vaultId, supplierInvoiceNumber: "", supplierInvoiceMissingReason: "", supplierInvoiceDate: today(), notes: "" });

function employeeLabel(language: Language, employee: Pick<HrEmployee, "employeeNumber" | "nameAr" | "nameEn">) { return `${employee.employeeNumber} · ${language === "ar" ? employee.nameAr : employee.nameEn ?? employee.nameAr}`; }

export function HrServicesWorkspace({ language }: { language: Language }) {
  const ar = language === "ar";
  const [session, setSession] = useState<ActiveSession | null>(activeSession());
  const [services, setServices] = useState<HrEmployeeServiceRecord[]>([]);
  const [employees, setEmployees] = useState<HrEmployee[]>([]);
  const [configuration, setConfiguration] = useState<FinanceConfiguration | null>(null);
  const [search, setSearch] = useState("");
  const [employeeFilter, setEmployeeFilter] = useState("");
  const [typeFilter, setTypeFilter] = useState<"" | HrService["serviceType"]>("");
  const [complianceFilter, setComplianceFilter] = useState<"" | HrEmployeeServiceComplianceStatus>("");
  const [expiryFilter, setExpiryFilter] = useState<"" | "EXPIRED" | "DUE_30" | "DUE_60" | "DUE_90" | "NO_EXPIRY">("");
  const [nextCursor, setNextCursor] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [createOpen, setCreateOpen] = useState(false);
  const [editOpen, setEditOpen] = useState(false);
  const [renewOpen, setRenewOpen] = useState(false);
  const [cancelOpen, setCancelOpen] = useState(false);
  const [costOpen, setCostOpen] = useState(false);
  const [detail, setDetail] = useState<HrEmployeeServiceRecord | null>(null);
  const [actionService, setActionService] = useState<HrEmployeeServiceRecord | null>(null);
  const [serviceForm, setServiceForm] = useState<ServiceForm>(emptyService());
  const [cancelReason, setCancelReason] = useState("");
  const [costForm, setCostForm] = useState<CostForm>(emptyCost());

  const loadConfiguration = useCallback(async () => {
    const current = activeSession(); if (!current) return null;
    const result = await api<FinanceConfiguration>(current, "/finance/configuration"); setConfiguration(result); return result;
  }, []);
  const load = useCallback(async (cursor?: string, append = false) => {
    const current = activeSession(); setSession(current); if (!current) { setLoading(false); return; }
    if (!append) setLoading(true);
    try {
      const [serviceReceipt, employeeReceipt] = await Promise.all([listHrEmployeeServices(current, { employeeId: employeeFilter || undefined, serviceType: typeFilter || undefined, complianceStatus: complianceFilter || undefined, cursor, pageSize: 100 }), append ? Promise.resolve(null) : listHrEmployees(current)]);
      setServices((previous) => append ? [...previous, ...serviceReceipt.services] : serviceReceipt.services);
      setNextCursor(serviceReceipt.nextCursor);
      if (employeeReceipt) setEmployees(employeeReceipt.employees);
    } catch (error) { setMessage(presentBaseerApiError(error, language, ar ? "تحميل خدمات الموظفين" : "Loading employee services")); }
    finally { setLoading(false); }
  }, [ar, complianceFilter, employeeFilter, language, typeFilter]);
  useEffect(() => { void load(); }, [load]);

  const serviceTypeLabel = (value: HrService["serviceType"]) => ({ IQAMA_ISSUANCE: ar ? "إصدار إقامة" : "Iqama issuance", IQAMA_RENEWAL: ar ? "تجديد إقامة" : "Iqama renewal", SPONSORSHIP_TRANSFER: ar ? "نقل كفالة" : "Sponsorship transfer", EXIT_REENTRY_VISA: ar ? "خروج وعودة" : "Exit/re-entry visa", FLIGHT_TICKET: ar ? "تذكرة سفر" : "Flight ticket", MEDICAL_INSURANCE: ar ? "تأمين طبي" : "Medical insurance", HEALTH_CERTIFICATE: ar ? "شهادة صحية" : "Health certificate", OTHER: ar ? "خدمة أخرى" : "Other service" })[value];
  const complianceLabel = (value: HrEmployeeServiceComplianceStatus) => ({ ACTIVE: ar ? "سارية" : "Active", RENEWED: ar ? "مجددة" : "Renewed", CANCELLED: ar ? "ملغاة" : "Cancelled" })[value];
  const expiryState = (service: HrEmployeeServiceRecord): "EXPIRED" | "DUE_30" | "DUE_60" | "DUE_90" | "NO_EXPIRY" | "VALID" => {
    if (!service.expiryDate) return "NO_EXPIRY";
    if (service.expiryDate < today()) return "EXPIRED";
    if (service.expiryDate <= inDays(30)) return "DUE_30";
    if (service.expiryDate <= inDays(60)) return "DUE_60";
    if (service.expiryDate <= inDays(90)) return "DUE_90";
    return "VALID";
  };
  const expiryLabel = (value: ReturnType<typeof expiryState>) => ({ EXPIRED: ar ? "منتهية" : "Expired", DUE_30: ar ? "تنتهي خلال 30 يوماً" : "Due within 30 days", DUE_60: ar ? "تنتهي خلال 60 يوماً" : "Due within 60 days", DUE_90: ar ? "تنتهي خلال 90 يوماً" : "Due within 90 days", NO_EXPIRY: ar ? "بلا تاريخ انتهاء" : "No expiry", VALID: ar ? "صالحة" : "Valid" })[value];
  const statusLabel = (value: HrService["status"]) => value === "DRAFT" ? (ar ? "مسودة" : "Draft") : value === "ISSUED" ? (ar ? "مصدرة" : "Issued") : (ar ? "ملغاة" : "Cancelled");
  const activeEmployees = useMemo(() => employees.filter((employee) => employee.status === "ACTIVE" || employee.status === "ON_LEAVE"), [employees]);
  const activeSuppliers = configuration?.suppliers.filter((supplier) => supplier.status === "ACTIVE") ?? [];
  const activeCategories = configuration?.categories.filter((category) => category.status === "ACTIVE" && category.kind === "EXPENSE" && category.isPosting) ?? [];
  const activeVaults = configuration?.vaults.filter((vault) => vault.status === "ACTIVE" && vault.isPaymentDestination) ?? [];
  const visibleServices = useMemo(() => { const needle = search.trim().toLowerCase(); return services.filter((service) => (!expiryFilter || expiryState(service) === expiryFilter) && (!needle || [service.employee.employeeNumber, service.employee.nameAr, service.employee.nameEn, service.referenceNumber, service.serviceType, service.expiryDate, service.complianceStatus].filter(Boolean).join(" ").toLowerCase().includes(needle))); }, [expiryFilter, search, services]);
  const expirySummary = useMemo(() => ({ expired: services.filter((service) => expiryState(service) === "EXPIRED").length, due30: services.filter((service) => expiryState(service) === "DUE_30").length, due90: services.filter((service) => expiryState(service) === "DUE_60" || expiryState(service) === "DUE_90").length }), [services]);
  const loadDetail = async (service: HrEmployeeServiceRecord) => { const current = activeSession(); if (!current) return; try { setDetail((await getHrEmployeeService(current, service.id)).service); } catch (error) { setMessage(presentBaseerApiError(error, language, ar ? "تفاصيل الخدمة" : "Service details")); } };
  const prepareService = async (mode: "create" | "edit" | "renew", service?: HrEmployeeServiceRecord) => { try { await loadConfiguration(); setActionService(service ?? null); setServiceForm(service ? { employeeId: service.employeeId, serviceType: service.serviceType, referenceNumber: service.referenceNumber ?? "", issueDate: mode === "renew" ? today() : service.issueDate ?? "", expiryDate: service.expiryDate ?? "", supplierId: service.supplier?.id ?? "", categoryId: service.category?.id ?? "", visaDurationMonths: service.visaDurationMonths?.toString() ?? "", notes: service.notes ?? "" } : emptyService()); setDetail(null); if (mode === "create") setCreateOpen(true); if (mode === "edit") setEditOpen(true); if (mode === "renew") setRenewOpen(true); } catch (error) { setMessage(presentBaseerApiError(error, language, ar ? "إعداد الخدمة" : "Preparing service")); } };
  const serviceFields = () => ({ serviceType: serviceForm.serviceType, referenceNumber: serviceForm.referenceNumber || undefined, issueDate: serviceForm.issueDate || undefined, expiryDate: serviceForm.expiryDate || undefined, supplierId: serviceForm.supplierId || undefined, categoryId: serviceForm.categoryId || undefined, visaDurationMonths: serviceForm.visaDurationMonths ? Number(serviceForm.visaDurationMonths) : undefined, notes: serviceForm.notes || undefined, idempotencyKey: requestId() });
  const saveCreate = async (event: React.FormEvent) => { event.preventDefault(); const current = activeSession(); if (!current || busy) return; setBusy(true); try { await createHrEmployeeService(current, { employeeId: serviceForm.employeeId, ...serviceFields() }); setCreateOpen(false); setMessage(ar ? "تم حفظ خدمة الموظف." : "Employee service saved."); await load(); } catch (error) { setMessage(presentBaseerApiError(error, language, ar ? "حفظ الخدمة" : "Saving service")); } finally { setBusy(false); } };
  const saveEdit = async (event: React.FormEvent) => { event.preventDefault(); const current = activeSession(); if (!current || busy || !actionService) return; setBusy(true); try { await updateHrEmployeeService(current, { serviceId: actionService.id, ...serviceFields() }); setEditOpen(false); setActionService(null); setMessage(ar ? "تم تحديث الخدمة." : "Service updated."); await load(); } catch (error) { setMessage(presentBaseerApiError(error, language, ar ? "تحديث الخدمة" : "Updating service")); } finally { setBusy(false); } };
  const saveRenew = async (event: React.FormEvent) => { event.preventDefault(); const current = activeSession(); if (!current || busy || !actionService) return; setBusy(true); try { await renewHrEmployeeService(current, { serviceId: actionService.id, ...serviceFields() }); setRenewOpen(false); setActionService(null); setMessage(ar ? "تم إنشاء تجديد الخدمة." : "Service renewal created."); await load(); } catch (error) { setMessage(presentBaseerApiError(error, language, ar ? "تجديد الخدمة" : "Renewing service")); } finally { setBusy(false); } };
  const saveCancel = async (event: React.FormEvent) => { event.preventDefault(); const current = activeSession(); if (!current || busy || !actionService) return; setBusy(true); try { await cancelHrEmployeeService(current, { serviceId: actionService.id, reason: cancelReason, idempotencyKey: requestId() }); setCancelOpen(false); setActionService(null); setMessage(ar ? "تم إلغاء الخدمة مع حفظ السبب." : "Service cancelled and reason recorded."); await load(); } catch (error) { setMessage(presentBaseerApiError(error, language, ar ? "إلغاء الخدمة" : "Cancelling service")); } finally { setBusy(false); } };
  const openCost = async (service: HrEmployeeServiceRecord) => { if (!service.supplier || !service.category) { setMessage(ar ? "اختر المورد والبند المالي للخدمة قبل إصدار تكلفتها." : "Select the supplier and financial category before issuing the cost."); return; } try { const next = configuration ?? await loadConfiguration(); setCostForm(emptyCost(service.id, next?.vaults.find((vault) => vault.status === "ACTIVE" && vault.isPaymentDestination)?.id ?? "")); setCostOpen(true); } catch (error) { setMessage(presentBaseerApiError(error, language, ar ? "إعداد التكلفة" : "Preparing cost")); } };
  const saveCost = async (event: React.FormEvent) => { event.preventDefault(); const current = activeSession(); if (!current || busy) return; setBusy(true); try { await issueHrEmployeeServiceCost(current, { serviceId: costForm.serviceId, businessDate: costForm.businessDate, grossAmount: costForm.grossAmount, isTaxable: costForm.isTaxable, supplierInvoiceNumber: costForm.supplierInvoiceNumber || undefined, supplierInvoiceMissingReason: costForm.supplierInvoiceMissingReason || undefined, supplierInvoiceDate: costForm.supplierInvoiceDate || undefined, notes: costForm.notes || undefined, allocations: [{ vaultId: costForm.vaultId, grossAmount: costForm.grossAmount }], idempotencyKey: requestId() }); setCostOpen(false); setDetail(null); setMessage(ar ? "تم إصدار تكلفة الخدمة وربطها بسجل الموظف." : "The service cost was posted and linked to the employee record."); await load(); } catch (error) { setMessage(presentBaseerApiError(error, language, ar ? "إصدار التكلفة" : "Issuing cost")); } finally { setBusy(false); } };
  const appliedFilters = [{ id: "employee", value: employeeFilter, label: employees.find((employee) => employee.id === employeeFilter) ? employeeLabel(language, employees.find((employee) => employee.id === employeeFilter)!) : "", clear: () => setEmployeeFilter("") }, { id: "type", value: typeFilter, label: typeFilter ? serviceTypeLabel(typeFilter) : "", clear: () => setTypeFilter("") }, { id: "compliance", value: complianceFilter, label: complianceFilter ? complianceLabel(complianceFilter) : "", clear: () => setComplianceFilter("") }, { id: "expiry", value: expiryFilter, label: expiryFilter ? expiryLabel(expiryFilter) : "", clear: () => setExpiryFilter("") }].filter((item) => item.value).map((item) => ({ id: item.id, label: item.label, onRemove: item.clear }));
  const columns: readonly DataTableColumn<HrEmployeeServiceRecord>[] = [
    { id: "employee", header: ar ? "الموظف" : "Employee", cell: (row) => <BaseerButton variant="quiet" type="button" onClick={() => void loadDetail(row)}>{employeeLabel(language, row.employee)}</BaseerButton>, sort: (row) => ar ? row.employee.nameAr : row.employee.nameEn ?? row.employee.nameAr },
    { id: "service", header: ar ? "الخدمة" : "Service", cell: (row) => serviceTypeLabel(row.serviceType), sort: (row) => row.serviceType, width: "10rem" },
    { id: "reference", header: ar ? "المرجع" : "Reference", cell: (row) => row.referenceNumber ?? "—", sort: (row) => row.referenceNumber ?? "", width: "10rem" },
    { id: "expiry", header: ar ? "الانتهاء" : "Expiry", cell: (row) => row.expiryDate ?? "—", sort: (row) => row.expiryDate ?? "", width: "9rem" },
    { id: "compliance", header: ar ? "الانتهاء" : "Expiry state", cell: (row) => expiryLabel(expiryState(row)), sort: (row) => row.expiryDate ?? "", width: "12rem" },
    { id: "status", header: ar ? "الحالة" : "Status", cell: (row) => statusLabel(row.status), sort: (row) => row.status, width: "8rem" },
  ];
  const serviceTypes: readonly HrService["serviceType"][] = ["IQAMA_ISSUANCE", "IQAMA_RENEWAL", "SPONSORSHIP_TRANSFER", "EXIT_REENTRY_VISA", "FLIGHT_TICKET", "MEDICAL_INSURANCE", "HEALTH_CERTIFICATE", "OTHER"];
  if (!session) return <DailySalesSignIn language={language} />;
  const serviceFormBody = (id: string, submit: (event: React.FormEvent) => void, employeeLocked = false) => <form id={id} className="administration-form" onSubmit={(event) => void submit(event)}><label>{ar ? "الموظف" : "Employee"}<BaseerSearchSelect required disabled={employeeLocked} label={ar ? "الموظف" : "Employee"} value={serviceForm.employeeId} placeholder={ar ? "اختر الموظف" : "Select employee"} options={activeEmployees.map((employee) => ({ id: employee.id, label: employeeLabel(language, employee) }))} onChange={(employeeId) => setServiceForm((value) => ({ ...value, employeeId }))} /></label><label>{ar ? "نوع الخدمة" : "Service type"}<BaseerSearchSelect searchable={false} required label={ar ? "نوع الخدمة" : "Service type"} value={serviceForm.serviceType} placeholder={ar ? "اختر النوع" : "Select type"} options={serviceTypes.map((type) => ({ id: type, label: serviceTypeLabel(type) }))} onChange={(serviceType) => setServiceForm((value) => ({ ...value, serviceType: serviceType as HrService["serviceType"] }))} /></label><label>{ar ? "المورد" : "Supplier"}<BaseerSearchSelect label={ar ? "المورد" : "Supplier"} value={serviceForm.supplierId} placeholder={ar ? "اختياري" : "Optional"} options={activeSuppliers.map((supplier) => ({ id: supplier.id, label: ar ? supplier.nameAr : supplier.nameEn ?? supplier.nameAr }))} onChange={(supplierId) => setServiceForm((value) => ({ ...value, supplierId }))} /></label><label>{ar ? "البند المالي" : "Financial category"}<BaseerSearchSelect label={ar ? "البند المالي" : "Financial category"} value={serviceForm.categoryId} placeholder={ar ? "اختياري" : "Optional"} options={activeCategories.map((category) => ({ id: category.id, label: ar ? category.nameAr : category.nameEn }))} onChange={(categoryId) => setServiceForm((value) => ({ ...value, categoryId }))} /></label><label>{ar ? "الرقم المرجعي" : "Reference number"}<input value={serviceForm.referenceNumber} onChange={(event) => setServiceForm((value) => ({ ...value, referenceNumber: event.target.value }))} /></label><label>{ar ? "تاريخ الإصدار" : "Issue date"}<input type="date" max={today()} value={serviceForm.issueDate} onChange={(event) => setServiceForm((value) => ({ ...value, issueDate: event.target.value }))} /></label><label>{ar ? "تاريخ الانتهاء" : "Expiry date"}<input type="date" min={serviceForm.issueDate || undefined} value={serviceForm.expiryDate} onChange={(event) => setServiceForm((value) => ({ ...value, expiryDate: event.target.value }))} /></label>{serviceForm.serviceType === "EXIT_REENTRY_VISA" ? <label>{ar ? "المدة بالأشهر" : "Duration in months"}<input min="1" max="36" inputMode="numeric" value={serviceForm.visaDurationMonths} onChange={(event) => setServiceForm((value) => ({ ...value, visaDurationMonths: event.target.value }))} /></label> : null}<label>{ar ? "ملاحظات" : "Notes"}<textarea value={serviceForm.notes} onChange={(event) => setServiceForm((value) => ({ ...value, notes: event.target.value }))} /></label></form>;
  return <section className="administration-panel" aria-label={ar ? "خدمات الموظفين والامتثال" : "Employee services and compliance"}>
    <header className="administration-section-heading"><div><h2>{ar ? "خدمات الموظفين والامتثال" : "Employee services & compliance"}</h2><p>{ar ? "تسجيل الخدمات ومتابعة انتهائها؛ تصبح عملية مالية فقط عند إصدار تكلفتها." : "Record services and track expiry; they become financial only when their cost is issued."}</p></div><BaseerButton type="button" onClick={() => void prepareService("create")}>{ar ? "إضافة خدمة" : "Add service"}</BaseerButton></header>
    <BaseerSummaryMetricGrid ariaLabel={ar ? "ملخص الامتثال" : "Compliance summary"}><BaseerSummaryMetric label={ar ? "منتهية" : "Expired"} value={expirySummary.expired} /><BaseerSummaryMetric label={ar ? "تنتهي خلال 30 يوماً" : "Due within 30 days"} value={expirySummary.due30} /><BaseerSummaryMetric label={ar ? "تنتهي خلال 60–90 يوماً" : "Due within 60–90 days"} value={expirySummary.due90} /></BaseerSummaryMetricGrid>
    <BaseerFilterBar language={language} search={search} searchLabel={ar ? "البحث في خدمات الموظفين" : "Search employee services"} searchPlaceholder={ar ? "ابحث بالموظف أو الرقم المرجعي" : "Search employee or reference"} onSearchChange={setSearch} controlsPresentation="menu" controls={<><BaseerSearchSelect label={ar ? "الموظف" : "Employee"} value={employeeFilter} placeholder={ar ? "كل الموظفين" : "All employees"} options={employees.map((employee) => ({ id: employee.id, label: employeeLabel(language, employee) }))} onChange={setEmployeeFilter} /><label>{ar ? "النوع" : "Type"}<select value={typeFilter} onChange={(event) => setTypeFilter(event.target.value as typeof typeFilter)}><option value="">{ar ? "كل الأنواع" : "All types"}</option>{serviceTypes.map((type) => <option key={type} value={type}>{serviceTypeLabel(type)}</option>)}</select></label><label>{ar ? "السجل التشغيلي" : "Operational status"}<select value={complianceFilter} onChange={(event) => setComplianceFilter(event.target.value as typeof complianceFilter)}><option value="">{ar ? "كل الحالات" : "All statuses"}</option>{(["ACTIVE", "RENEWED", "CANCELLED"] as const).map((status) => <option key={status} value={status}>{complianceLabel(status)}</option>)}</select></label><label>{ar ? "الانتهاء" : "Expiry"}<select value={expiryFilter} onChange={(event) => setExpiryFilter(event.target.value as typeof expiryFilter)}><option value="">{ar ? "كل الفترات" : "All periods"}</option>{(["EXPIRED", "DUE_30", "DUE_60", "DUE_90", "NO_EXPIRY"] as const).map((status) => <option key={status} value={status}>{expiryLabel(status)}</option>)}</select></label></>} appliedFilters={appliedFilters} onClear={() => { setEmployeeFilter(""); setTypeFilter(""); setComplianceFilter(""); setExpiryFilter(""); }} />
    {message ? <p className="daily-sales-message error">{message}</p> : null}
    {loading ? <BaseerCard>{ar ? "جارٍ تحميل خدمات الموظفين…" : "Loading employee services…"}</BaseerCard> : visibleServices.length ? <DataTable ariaLabel={ar ? "سجل خدمات الموظفين" : "Employee services register"} caption={ar ? "سجل خدمات الموظفين" : "Employee services register"} columns={columns} rows={visibleServices} rowKey={(row) => row.id} /> : <BaseerCard>{ar ? "لا توجد خدمات مطابقة لهذه الشركة." : "No matching employee services for this company."}</BaseerCard>}
    {nextCursor ? <BaseerButton type="button" variant="secondary" disabled={loading} onClick={() => void load(nextCursor, true)}>{ar ? "تحميل المزيد" : "Load more"}</BaseerButton> : null}
    <BaseerDialog open={createOpen} title={ar ? "إضافة خدمة موظف" : "Add employee service"} language={language} busy={busy} onClose={() => setCreateOpen(false)} footer={<><BaseerButton type="button" variant="secondary" onClick={() => setCreateOpen(false)}>{ar ? "إلغاء" : "Cancel"}</BaseerButton><BaseerButton type="submit" form="hr-service-create" disabled={busy}>{ar ? "حفظ" : "Save"}</BaseerButton></>}>{serviceFormBody("hr-service-create", saveCreate)}</BaseerDialog>
    <BaseerDialog open={editOpen} title={ar ? "تعديل الخدمة" : "Edit service"} language={language} busy={busy} onClose={() => setEditOpen(false)} footer={<><BaseerButton type="button" variant="secondary" onClick={() => setEditOpen(false)}>{ar ? "إلغاء" : "Cancel"}</BaseerButton><BaseerButton type="submit" form="hr-service-edit" disabled={busy}>{ar ? "حفظ التعديل" : "Save changes"}</BaseerButton></>}>{serviceFormBody("hr-service-edit", saveEdit, true)}</BaseerDialog>
    <BaseerDialog open={renewOpen} title={ar ? "تجديد الخدمة" : "Renew service"} language={language} busy={busy} onClose={() => setRenewOpen(false)} footer={<><BaseerButton type="button" variant="secondary" onClick={() => setRenewOpen(false)}>{ar ? "إلغاء" : "Cancel"}</BaseerButton><BaseerButton type="submit" form="hr-service-renew" disabled={busy}>{ar ? "إنشاء التجديد" : "Create renewal"}</BaseerButton></>}>{serviceFormBody("hr-service-renew", saveRenew, true)}</BaseerDialog>
    <BaseerDialog open={cancelOpen} title={ar ? "إلغاء الخدمة" : "Cancel service"} language={language} busy={busy} onClose={() => setCancelOpen(false)} footer={<><BaseerButton type="button" variant="secondary" onClick={() => setCancelOpen(false)}>{ar ? "رجوع" : "Back"}</BaseerButton><BaseerButton type="submit" form="hr-service-cancel" disabled={busy}>{ar ? "تأكيد الإلغاء" : "Confirm cancellation"}</BaseerButton></>}><form id="hr-service-cancel" className="administration-form" onSubmit={(event) => void saveCancel(event)}><label>{ar ? "سبب الإلغاء" : "Cancellation reason"}<textarea required value={cancelReason} onChange={(event) => setCancelReason(event.target.value)} /></label></form></BaseerDialog>
    <BaseerDialog open={costOpen} title={ar ? "إصدار تكلفة الخدمة" : "Issue service cost"} language={language} busy={busy} onClose={() => setCostOpen(false)} footer={<><BaseerButton type="button" variant="secondary" onClick={() => setCostOpen(false)}>{ar ? "إلغاء" : "Cancel"}</BaseerButton><BaseerButton type="submit" form="hr-service-cost" disabled={busy}>{ar ? "إصدار التكلفة" : "Issue cost"}</BaseerButton></>}><form id="hr-service-cost" className="administration-form" onSubmit={(event) => void saveCost(event)}><label>{ar ? "التاريخ" : "Date"}<input required type="date" max={today()} value={costForm.businessDate} onChange={(event) => setCostForm((value) => ({ ...value, businessDate: event.target.value }))} /></label><label>{ar ? "المبلغ الإجمالي" : "Gross amount"}<input required inputMode="decimal" value={costForm.grossAmount} onChange={(event) => setCostForm((value) => ({ ...value, grossAmount: event.target.value }))} /></label><label>{ar ? "الخزينة" : "Vault"}<BaseerSearchSelect required label={ar ? "الخزينة" : "Vault"} value={costForm.vaultId} placeholder={ar ? "اختر الخزينة" : "Select vault"} options={activeVaults.map((vault) => ({ id: vault.id, label: ar ? vault.nameAr : vault.nameEn }))} onChange={(vaultId) => setCostForm((value) => ({ ...value, vaultId }))} /></label><label>{ar ? "رقم فاتورة المورد" : "Supplier invoice number"}<input value={costForm.supplierInvoiceNumber} onChange={(event) => setCostForm((value) => ({ ...value, supplierInvoiceNumber: event.target.value }))} /></label><label>{ar ? "سبب عدم وجود الفاتورة" : "Invoice missing reason"}<input value={costForm.supplierInvoiceMissingReason} onChange={(event) => setCostForm((value) => ({ ...value, supplierInvoiceMissingReason: event.target.value }))} /></label><label>{ar ? "تاريخ الفاتورة" : "Invoice date"}<input type="date" max={costForm.businessDate} value={costForm.supplierInvoiceDate} onChange={(event) => setCostForm((value) => ({ ...value, supplierInvoiceDate: event.target.value }))} /></label><label><input type="checkbox" checked={costForm.isTaxable} onChange={(event) => setCostForm((value) => ({ ...value, isTaxable: event.target.checked }))} /> {ar ? "خاضعة للضريبة" : "Taxable"}</label><label>{ar ? "ملاحظات" : "Notes"}<textarea value={costForm.notes} onChange={(event) => setCostForm((value) => ({ ...value, notes: event.target.value }))} /></label></form></BaseerDialog>
    <BaseerDialog open={Boolean(detail)} title={detail ? serviceTypeLabel(detail.serviceType) : ar ? "تفاصيل الخدمة" : "Service details"} language={language} busy={busy} onClose={() => setDetail(null)} footer={detail ? <><BaseerButton type="button" variant="secondary" disabled={busy || detail.status !== "DRAFT"} onClick={() => void prepareService("edit", detail)}>{ar ? "تعديل" : "Edit"}</BaseerButton><BaseerButton type="button" variant="secondary" disabled={busy || detail.status === "CANCELLED"} onClick={() => void prepareService("renew", detail)}>{ar ? "تجديد" : "Renew"}</BaseerButton>{detail.status === "DRAFT" ? <BaseerButton type="button" disabled={busy} onClick={() => void openCost(detail)}>{ar ? "إصدار التكلفة" : "Issue cost"}</BaseerButton> : null}<BaseerButton type="button" variant="quiet" disabled={busy || detail.status !== "DRAFT"} onClick={() => { setCancelReason(""); setActionService(detail); setDetail(null); setCancelOpen(true); }}>{ar ? "إلغاء الخدمة" : "Cancel service"}</BaseerButton></> : undefined}>{detail ? <dl className="administration-details"><div><dt>{ar ? "الموظف" : "Employee"}</dt><dd>{employeeLabel(language, detail.employee)}</dd></div><div><dt>{ar ? "نوع الخدمة" : "Service type"}</dt><dd>{serviceTypeLabel(detail.serviceType)}</dd></div><div><dt>{ar ? "الرقم المرجعي" : "Reference"}</dt><dd>{detail.referenceNumber ?? "—"}</dd></div><div><dt>{ar ? "الفترة" : "Period"}</dt><dd>{`${detail.issueDate ?? "—"} — ${detail.expiryDate ?? "—"}`}</dd></div><div><dt>{ar ? "الحالة التشغيلية" : "Operational status"}</dt><dd>{complianceLabel(detail.complianceStatus)}</dd></div><div><dt>{ar ? "حالة الانتهاء" : "Expiry state"}</dt><dd>{expiryLabel(expiryState(detail))}</dd></div><div><dt>{ar ? "الحالة" : "Status"}</dt><dd>{statusLabel(detail.status)}</dd></div><div><dt>{ar ? "العملية المالية" : "Financial transaction"}</dt><dd>{detail.outflowDocumentId ?? (ar ? "لم تُصدر" : "Not issued")}</dd></div>{detail.notes ? <div><dt>{ar ? "ملاحظات" : "Notes"}</dt><dd>{detail.notes}</dd></div> : null}</dl> : null}</BaseerDialog>
  </section>;
}
