import { lazy, Suspense, useCallback, useEffect, useState, type ComponentProps } from 'react';

import { BaseerButton } from './baseer-button';
import { BaseerDialog } from './baseer-dialog';
import { BaseerFilterBar } from './baseer-filter-bar';
import { defaultBaseerPeriodRange, type BaseerPeriodRange } from './baseer-period-values';
import { DailySalesSignIn } from './daily-sales-sign-in';
import { activeSession, api, type ActiveSession } from './daily-sales-client';
import { presentBaseerApiError } from './baseer-api-error';
import { ReportDocumentActions } from './report-document-actions';
import './reports-workspace.css';

const LazyBaseerPeriodFilter = lazy(async () => ({ default: (await import('./baseer-period-filter')).BaseerPeriodFilter }));
function BaseerPeriodFilter(props: ComponentProps<typeof LazyBaseerPeriodFilter>) { return <Suspense fallback={<span className="baseer-period-filter" aria-busy="true" />}><LazyBaseerPeriodFilter {...props} /></Suspense>; }

type Language = 'ar' | 'en';
type Money = Readonly<{ raw: string; display: string; sign: 'positive' | 'negative' | 'zero' }>;
type Row = Readonly<{ code: 'output_vat' | 'input_vat' | 'vat_paid' | 'vat_refunded'; labelAr: string; labelEn: string; amount: Money; eventCount: number }>;
type Metadata = Readonly<{ reportRunId: string; selectedPeriod: { from: string; to: string; months?: readonly string[] } }>;
type Result = Readonly<{ state: 'NOT_READY'; messageAr: string }> | (Metadata & Readonly<{ state: 'NO_DATA'; messageAr: string; rows: readonly []; netVat: Money }>) | (Metadata & Readonly<{ state: 'READY'; rows: readonly Row[]; netVat: Money }>);
type Evidence = Readonly<{ reportRunId: string; rowCode: Row['code']; nextCursor: string | null; items: readonly { lineId: string; businessDate: string; amount: Money; reference: string; labelAr: string; labelEn: string }[] }>;
type Source = Readonly<{ journalEntry: { sourceReference: string; businessDate: string; description: string | null; lines: readonly { id: string; lineNumber: number; accountCode: string; accountNameAr: string; accountNameEn: string; debitAmount: string; creditAmount: string }[] } }>;
const copy = { ar: { title: 'التقرير الضريبي الداخلي', amount: 'المبلغ', net: 'صافي ضريبة الفترة', loading: 'يتم تحميل التقرير الضريبي…', details: 'تفصيل الرقم', source: 'القيد المصدر', openSource: 'فتح القيد المصدر', back: 'العودة للتفصيل', more: 'تحميل المزيد', close: 'إغلاق', noData: 'لا توجد حركات ضريبية مؤهلة ضمن الفترة المحددة.', retry: 'إعادة المحاولة', debit: 'مدين', credit: 'دائن' }, en: { title: 'Internal VAT report', amount: 'Amount', net: 'Net VAT for period', loading: 'Loading VAT report…', details: 'Amount details', source: 'Source journal', openSource: 'Open source journal', back: 'Back to details', more: 'Load more', close: 'Close', noData: 'There are no eligible VAT movements in the selected period.', retry: 'Retry', debit: 'Debit', credit: 'Credit' } } as const;

export function InternalVatReportWorkspace({ language }: { language: Language }) {
  const text = copy[language]; const [session, setSession] = useState<ActiveSession | null>(activeSession); const [period, setPeriod] = useState<BaseerPeriodRange>(defaultBaseerPeriodRange); const [report, setReport] = useState<Result | null>(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(() => activeSession() !== null); const [selected, setSelected] = useState<Row | null>(null); const [evidence, setEvidence] = useState<Evidence | null>(null); const [source, setSource] = useState<Source | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const current = activeSession(); setSession(current); if (!current) { setLoading(false); return; } setLoading(true); setMessage(''); try { const query = new URLSearchParams({ from: period.from, to: period.to }); if (period.preset === 'MONTH' && period.months.length > 1) query.set('months', period.months.join(',')); setReport(await api<Result>(current, `/reports/internal-vat?${query}`)); } catch (error) { setReport(null); setMessage(presentBaseerApiError(error, language, text.title)); } finally { setLoading(false); } }, [language, period.from, period.months, period.preset, period.to, text.title]);
  useEffect(() => { void load(); }, [load]);
  const openEvidence = async (row: Row, cursor?: string) => { if (report?.state !== 'READY') return; const current = activeSession(); if (!current) return; if (!cursor) { setSelected(row); setEvidence(null); setSource(null); } setBusy(true); try { const query = new URLSearchParams({ rowCode: row.code, ...(cursor ? { cursor } : {}) }); const next = await api<Evidence>(current, `/reports/internal-vat/${report.reportRunId}/evidence?${query}`); setEvidence((previous) => cursor && previous ? { ...next, items: [...previous.items, ...next.items] } : next); } catch (error) { setMessage(presentBaseerApiError(error, language, text.details)); } finally { setBusy(false); } };
  const openSource = async (lineId: string) => { if (report?.state !== 'READY') return; const current = activeSession(); if (!current) return; setBusy(true); try { setSource(await api<Source>(current, `/reports/internal-vat/${report.reportRunId}/evidence/${lineId}/source`)); } catch (error) { setMessage(presentBaseerApiError(error, language, text.source)); } finally { setBusy(false); } };
  const label = (row: Row) => language === 'ar' ? row.labelAr : row.labelEn;
  if (!session) return <DailySalesSignIn language={language} />;
  return <section className="reports-prototype reports-workspace" aria-label={text.title}><header className="reports-prototype__intro"><div><h2>{text.title}</h2></div></header><section className="reports-prototype__canvas" dir={language === 'ar' ? 'rtl' : 'ltr'}><div className="reports-prototype__toolbar reports-prototype__toolbar--with-actions"><BaseerFilterBar language={language} controls={<BaseerPeriodFilter language={language} value={period} onChange={setPeriod} presets={['MONTH', 'QUARTER', 'YEAR', 'RANGE']} />} />{!loading && report?.state === 'READY' ? <ReportDocumentActions session={session} reportRunId={report.reportRunId} language={language} /> : null}</div>{message ? <><p className="reports-prototype__notice is-error">{message}</p><div className="reports-prototype__retry"><BaseerButton type="button" variant="secondary" onClick={() => void load()}>{text.retry}</BaseerButton></div></> : null}{loading ? <p className="reports-prototype__notice">{text.loading}</p> : null}{!loading && report && report.state !== 'READY' ? <p className="reports-prototype__notice">{report.messageAr || text.noData}</p> : null}{!loading && report?.state === 'READY' ? <div className="reports-prototype__table-shell"><table className="reports-prototype__table"><caption>{text.title}</caption><thead><tr><th scope="col">{text.title}</th><th scope="col" className="reports-prototype__amount">{text.amount}</th></tr></thead><tbody>{report.rows.map((row) => <tr key={row.code} className="reports-prototype__row reports-prototype__row--line"><th scope="row"><button type="button" className="reports-prototype__row-label-button" onClick={() => void openEvidence(row)}>{label(row)}</button></th><td><MoneyButton money={row.amount} label={label(row)} onClick={() => void openEvidence(row)} /></td></tr>)}<tr className="reports-prototype__row reports-prototype__row--result"><th scope="row">{text.net}</th><td><bdi className={`reports-prototype__number${report.netVat.sign === 'negative' ? ' is-negative' : ''}`} dir="ltr">{report.netVat.sign === 'negative' ? '−' : ''}{report.netVat.display}</bdi></td></tr></tbody></table></div> : null}</section><BaseerDialog open={selected !== null} size="wide" language={language} title={source ? text.source : selected ? `${text.details} — ${label(selected)}` : text.details} busy={busy} onClose={() => { setSelected(null); setEvidence(null); setSource(null); }} footer={<BaseerButton type="button" onClick={() => { setSelected(null); setEvidence(null); setSource(null); }}>{text.close}</BaseerButton>}>{source ? <SourceView source={source} language={language} onBack={() => setSource(null)} /> : selected ? <EvidenceView evidence={evidence} selected={selected} language={language} text={text} onSource={openSource} onMore={() => evidence?.nextCursor && void openEvidence(selected, evidence.nextCursor)} /> : null}</BaseerDialog></section>;
}
function MoneyButton({ money, label, onClick }: { money: Money; label: string; onClick: () => void }) { return <button type="button" className={`reports-prototype__number${money.sign === 'negative' ? ' is-negative' : ''}`} dir="ltr" aria-label={label} onClick={onClick}>{money.sign === 'negative' ? '−' : ''}{money.display}</button>; }
function EvidenceView({ evidence, selected, language, text, onSource, onMore }: { evidence: Evidence | null; selected: Row; language: Language; text: typeof copy[Language]; onSource: (lineId: string) => void; onMore: () => void }) { return <div className="reports-prototype__detail" dir={language === 'ar' ? 'rtl' : 'ltr'}><div className="reports-prototype__drawer-total"><span>{language === 'ar' ? selected.labelAr : selected.labelEn}</span><bdi dir="ltr">{selected.amount.sign === 'negative' ? '−' : ''}{selected.amount.display}</bdi></div>{!evidence ? <p>{text.loading}</p> : evidence.items.length ? <><ul className="reports-prototype__source-list">{evidence.items.map((item) => <li key={item.lineId}><div><span>{language === 'ar' ? item.labelAr : item.labelEn}</span><strong dir="ltr">{item.reference}</strong><small>{item.businessDate}</small></div><div className="reports-prototype__source-value"><bdi dir="ltr">{item.amount.sign === 'negative' ? '−' : ''}{item.amount.display}</bdi><button type="button" onClick={() => onSource(item.lineId)}>{text.openSource}</button></div></li>)}</ul>{evidence.nextCursor ? <BaseerButton type="button" variant="secondary" onClick={onMore}>{text.more}</BaseerButton> : null}</> : <p>{text.noData}</p>}</div>; }
function SourceView({ source, language, onBack }: { source: Source; language: Language; onBack: () => void }) { const text = copy[language]; const journal = source.journalEntry; return <div className="reports-prototype__detail" dir={language === 'ar' ? 'rtl' : 'ltr'}><BaseerButton type="button" variant="secondary" onClick={onBack}>{text.back}</BaseerButton><div className="reports-prototype__source-journal"><p><strong dir="ltr">{journal.sourceReference}</strong> · {journal.businessDate}</p>{journal.description ? <p>{journal.description}</p> : null}<table><thead><tr><th>#</th><th>{text.source}</th><th>{text.debit}</th><th>{text.credit}</th></tr></thead><tbody>{journal.lines.map((line) => <tr key={line.id}><td>{line.lineNumber}</td><td>{line.accountCode} · {language === 'ar' ? line.accountNameAr : line.accountNameEn}</td><td dir="ltr">{line.debitAmount}</td><td dir="ltr">{line.creditAmount}</td></tr>)}</tbody></table></div></div>; }
