import { useEffect, useMemo } from "react";

import { BaseerCombobox } from "./baseer-combobox";
import { BaseerDatePicker } from "./baseer-date-picker";
import { BaseerFormDialog } from "./baseer-form-dialog";
import { BaseerMoneyInput, BaseerTextArea, BaseerTextInput } from "./baseer-form-fields";
import { useBaseerForm, z } from "./baseer-form-state";
import { campaignPlatformLabel, campaignStatusLabel, type Campaign, type CampaignCopy, type CampaignDraft, type Language } from "./marketing-campaigns-workspace";

const platforms: Campaign["platform"][] = ["MANUAL", "GOOGLE_ADS", "META", "TIKTOK", "SNAPCHAT", "OTHER"];
const statuses: Exclude<Campaign["status"], "ARCHIVED">[] = ["DRAFT", "PLANNED", "ACTIVE", "COMPLETED", "CANCELLED"];
function schema(ar: boolean) { return z.object({ titleAr: z.string().trim().min(1, ar ? "اسم الحملة بالعربية مطلوب." : "Arabic campaign title is required.").max(160), titleEn: z.string().max(160), platform: z.enum(platforms), startsOn: z.string(), endsOn: z.string(), status: z.enum(statuses), objective: z.string().max(500), notes: z.string().max(2000), externalReference: z.string().max(160), plannedCost: z.string().regex(/^$|^\d+(\.\d{1,4})?$/, ar ? "أدخل مبلغاً صحيحاً حتى 4 منازل عشرية." : "Enter a valid amount with up to 4 decimals.") }).refine((value) => !value.startsOn || !value.endsOn || value.startsOn <= value.endsOn, { path: ["endsOn"], message: ar ? "تاريخ النهاية لا يسبق البداية." : "Campaign end cannot precede its start." }); }

export function MarketingCampaignMutationDialog({ dialog, language, busy, editing, initial, copy, campaign, error, onClose, onSubmit, onArchive, onStop }: { dialog: "create" | "edit" | "archive" | "stop"; language: Language; busy: boolean; editing: boolean; initial: CampaignDraft; copy: CampaignCopy; campaign: Campaign | null; error: string | null; onClose: () => void; onSubmit: (values: CampaignDraft) => Promise<void>; onArchive: (reason: string) => Promise<void>; onStop: (values: { stoppedOn: string; reason: string }) => Promise<void> }) {
  if (dialog === "archive") return <ArchiveDialog language={language} busy={busy} copy={copy} error={error} onClose={onClose} onSubmit={onArchive} />;
  if (dialog === "stop") return <StopDialog language={language} campaign={campaign} busy={busy} error={error} onClose={onClose} onSubmit={onStop} />;
  return <CampaignDialog language={language} busy={busy} editing={editing} initial={initial} copy={copy} error={error} onClose={onClose} onSubmit={onSubmit} />;
}

function CampaignDialog({ language, busy, editing, initial, copy, error, onClose, onSubmit }: { language: Language; busy: boolean; editing: boolean; initial: CampaignDraft; copy: CampaignCopy; error: string | null; onClose: () => void; onSubmit: (values: CampaignDraft) => Promise<void> }) {
  const ar = language === "ar"; const form = useBaseerForm<CampaignDraft>({ values: initial, schema: useMemo(() => schema(ar), [ar]), shouldFocusError: true }); const value = form.watch(); const set = (key: keyof CampaignDraft, next: string) => form.setValue(key, next as never, { shouldDirty: true, shouldValidate: true }); const fieldError = (name: keyof CampaignDraft) => form.formState.errors[name]?.message;
  return <BaseerFormDialog open title={editing ? copy.editTitle : copy.createTitle} language={language} formId="marketing-campaign-form" submitLabel={copy.save} onClose={onClose} busy={busy} error={error} size="wide"><form id="marketing-campaign-form" data-baseer-rhf-form="true" className="marketing-campaign-form" noValidate onSubmit={form.handleSubmit((values) => void onSubmit(values))}><label>{copy.titleAr}<BaseerTextInput aria-invalid={Boolean(fieldError("titleAr"))} {...form.register("titleAr")} autoFocus /></label>{fieldError("titleAr") ? <small className="baseer-field-error" role="alert">{fieldError("titleAr")}</small> : null}<label>{copy.titleEn}<BaseerTextInput {...form.register("titleEn")} /></label><label>{copy.platform}<BaseerCombobox label={copy.platform} placeholder={ar ? "اختر المنصة" : "Select platform"} value={value.platform} options={platforms.map((item) => ({ id: item, label: campaignPlatformLabel(item, ar) }))} onChange={(next) => set("platform", next)} /></label><div className="marketing-campaign-form__dates"><label>{copy.from}<BaseerDatePicker language={language} label={copy.from} value={value.startsOn} onChange={(next) => set("startsOn", next)} /></label><label>{copy.to}<BaseerDatePicker language={language} label={copy.to} value={value.endsOn} onChange={(next) => set("endsOn", next)} /></label></div>{fieldError("endsOn") ? <small className="baseer-field-error" role="alert">{fieldError("endsOn")}</small> : null}<label>{copy.lifecycle}<BaseerCombobox label={copy.lifecycle} placeholder={ar ? "اختر الحالة" : "Select status"} value={value.status} options={statuses.map((item) => ({ id: item, label: campaignStatusLabel(item, ar) }))} onChange={(next) => set("status", next)} /></label><label>{ar ? "التكلفة المخططة (ر.س، اختيارية)" : "Planned cost (SAR, optional)"}<BaseerMoneyInput value={value.plannedCost} onValueChange={(next) => set("plannedCost", next)} /></label><label>{copy.objective}<BaseerTextArea {...form.register("objective")} /></label><label>{copy.notes}<BaseerTextArea {...form.register("notes")} /></label><label>{copy.ref}<BaseerTextInput {...form.register("externalReference")} /></label></form></BaseerFormDialog>;
}

function ArchiveDialog({ language, busy, copy, error, onClose, onSubmit }: { language: Language; busy: boolean; copy: CampaignCopy; error: string | null; onClose: () => void; onSubmit: (reason: string) => Promise<void> }) {
  const ar = language === "ar"; const form = useBaseerForm<{ reason: string }>({ defaultValues: { reason: "" }, schema: useMemo(() => z.object({ reason: z.string().trim().min(1, ar ? "سبب الأرشفة مطلوب." : "An archive reason is required.").max(500) }), [ar]), shouldFocusError: true }); useEffect(() => form.reset({ reason: "" }), [form]); const reasonError = form.formState.errors.reason?.message;
  return <BaseerFormDialog open title={copy.archiveTitle} language={language} formId="marketing-archive-form" submitLabel={copy.archiveConfirm} onClose={onClose} busy={busy} error={error} size="compact"><form id="marketing-archive-form" data-baseer-rhf-form="true" className="marketing-campaign-form" noValidate onSubmit={form.handleSubmit(({ reason }) => void onSubmit(reason))}><p>{copy.archiveText}</p><label>{copy.reason}<BaseerTextArea compact aria-invalid={Boolean(reasonError)} {...form.register("reason")} autoFocus /></label>{reasonError ? <small className="baseer-field-error" role="alert">{reasonError}</small> : null}</form></BaseerFormDialog>;
}

function StopDialog({ language, campaign, busy, error, onClose, onSubmit }: { language: Language; campaign: Campaign | null; busy: boolean; error: string | null; onClose: () => void; onSubmit: (values: { stoppedOn: string; reason: string }) => Promise<void> }) {
  const ar = language === "ar"; const form = useBaseerForm<{ stoppedOn: string; reason: string }>({ defaultValues: { stoppedOn: "", reason: "" }, schema: useMemo(() => z.object({ stoppedOn: z.string().date(ar ? "اختر تاريخ إيقاف صحيحاً." : "Choose a valid stop date."), reason: z.string().trim().min(1, ar ? "سبب الإيقاف مطلوب." : "A stop reason is required.").max(500) }), [ar]), shouldFocusError: true }); useEffect(() => { form.reset({ stoppedOn: campaign?.endsOn ?? new Date().toISOString().slice(0, 10), reason: "" }); }, [campaign?.endsOn, form]); const stoppedOnError = form.formState.errors.stoppedOn?.message; const reasonError = form.formState.errors.reason?.message;
  return <BaseerFormDialog open title={ar ? "إيقاف الحملة" : "Stop campaign"} language={language} formId="marketing-campaign-stop-form" submitLabel={ar ? "تأكيد الإيقاف" : "Confirm stop"} onClose={onClose} busy={busy} error={error} size="compact"><form id="marketing-campaign-stop-form" data-baseer-rhf-form="true" className="marketing-campaign-form" noValidate onSubmit={form.handleSubmit((values) => void onSubmit(values))}><p>{ar ? "يحفظ الإيقاف كسياق زمني للحملة ويجعل هذا التاريخ نهاية الفترة الفعلية. لا يثبت الإيقاف سبب أي تغير في المبيعات." : "The stop is retained as campaign timing context and becomes the effective end date. It never proves the cause of a sales change."}</p><label>{ar ? "تاريخ الإيقاف" : "Stop date"}<BaseerDatePicker language={language} label={ar ? "تاريخ الإيقاف" : "Stop date"} value={form.watch("stoppedOn")} onChange={(next) => form.setValue("stoppedOn", next, { shouldDirty: true, shouldValidate: true })} /></label>{stoppedOnError ? <small className="baseer-field-error" role="alert">{stoppedOnError}</small> : null}<label>{ar ? "سبب الإيقاف" : "Stop reason"}<BaseerTextArea compact aria-invalid={Boolean(reasonError)} {...form.register("reason")} autoFocus /></label>{reasonError ? <small className="baseer-field-error" role="alert">{reasonError}</small> : null}</form></BaseerFormDialog>;
}
