import './nurix-migration-workspace.css';

import { useEffect, useState } from 'react';
import { BaseerApiError } from './baseer-api-error';
import { BaseerButton } from './baseer-button';
import { BaseerCard } from './baseer-card';
import { BaseerStatusBadge } from './baseer-status-badge';
import { BaseerEmptyState, BaseerNotice, BaseerSectionHeader, BaseerWorkspace } from './baseer-workspace';
import { activeSession, type ActiveSession } from './daily-sales-client';
import { DailySalesSignIn } from './daily-sales-sign-in';
import { formatCount, formatDateTime } from './number-format';
import { acknowledgeNurixMigrationException, approveNurixCompanyMaps, approveNurixDirectCandidates, createCommercialNurixCounterparty, createCommercialNurixCounterpartyReviewGroup, createNurixProvisionalSuppliers, loadNurixCounterpartyQueue, loadNurixCounterpartyReviewGroups, loadNurixCounterpartySuggestions, loadNurixMigrationReview, loadNurixMigrationRuns, resolveNurixCounterparty, resolveNurixCounterpartyReviewGroup, type NurixCounterpartyQueue, type NurixCounterpartyReviewGroups, type NurixCounterpartySuggestions, type NurixMigrationReview, type NurixMigrationRun } from './nurix-migration-client';

type Language = 'ar' | 'en';
const copy = {
  ar: { eyebrow: 'الإدارة / الترحيل', title: 'بوابة مراجعة ترحيل نوركس', description: 'اعتماد موثق للخرائط التقنية المباشرة فقط. لا تنقل هذه الصفحة أي سجلات مالية أو موظفين أو ملفات.', load: 'تحميل جولات الترحيل…', noRuns: 'لا توجد جولات نوركس في هذا المستأجر.', direct: 'خرائط مباشرة مرشّحة', counterparties: 'مطابقات هوية صريحة', intelligence: 'مساعد المراجعة الذكي', intelligenceHelp: 'اقتراحات محافظة بالاسم والتكرار ونوع الجهة. لا يُسجل أو ينشئ أي شيء حتى تضغط تطبيق الاقتراح.', suggestion: 'الاقتراح', suggestionMatch: 'الربط بالهوية القائمة', suggestionCreate: 'إنشاء هوية تجارية موحّدة', suggestionReview: 'مراجعة يدوية', high: 'ثقة عالية', medium: 'ثقة متوسطة', low: 'تحتاج مراجعة', applySuggestion: 'تطبيق الاقتراح', manualReview: 'مراجعة يدوية مطلوبة', repeatedNames: 'أسماء متطابقة عبر شركات', repeatedNamesHelp: 'الدفعة الواحدة تضم الاسم المتطابق بعد التطبيع المحافظ فقط؛ اختيارك ينشئ قرارات منفصلة قابلة للتدقيق لكل سجل في المجموعة.', supplierQueue: 'مراجعة الموردين غير المحسومين', supplierQueueHelp: 'اختيار هوية قائمة يسجل الاسم البديل صراحة لتلك الهوية؛ أو أنشئ هوية تجارية جديدة. القرار لا ينشئ مورد شركة ولا أي حركة مالية.', searchIdentity: 'ابحث في الهويات القائمة', chooseIdentity: 'اختر هوية قائمة…', resolve: 'تسجيل قرار الهوية', createCommercial: 'إنشاء هوية تجارية مستقلة', createCommercialGroup: 'إنشاء هوية تجارية موحّدة للمجموعة', next: 'إظهار الدفعة التالية', noCandidates: 'لا توجد أسماء غير محسومة في هذه الدفعة.', blockers: 'عوائق', review: 'تحتاج مراجعة', warnings: 'تنبيهات', reason: 'سبب اعتماد الخرائط أو الإقرار', reasonHelp: 'يُحفظ السبب في سجل تدقيق غير قابل للتعديل. أسباب قرارات الموردين تُكتب داخل بطاقة كل مورد.', supplierReason: 'سبب قرار هذا المورد', supplierReasonHelp: 'اكتب سببًا واضحًا من ثلاثة أحرف على الأقل؛ سيُحفظ مع هذا المورد فقط في سجل التدقيق.', approve: 'اعتماد الخرائط المباشرة', approved: 'معتمدة', acknowledge: 'إقرار بالمراجعة', acknowledged: 'تم الإقرار', exceptions: 'العوائق والمراجعات', audit: 'آخر قرارات المراجعة', noActions: 'لا توجد قرارات مسجلة بعد.', safeTitle: 'حدود الحماية', safe: 'لا يمكن من هذه الشاشة اعتماد الموردين أو الخزائن أو الفواتير أو القيود. تظهر تلك البنود كعوائق حتى تُعرّف قواعد تحويل معتمدة ثم تُشغّل تجربة dry-run.', select: 'اختيار جولة الترحيل', reload: 'تحديث', failed: 'تعذّر تنفيذ الطلب. تحقق من صلاحية مالك المستأجر واتصال الخادم.', stage: 'الحالة: مراجعة قبل التجربة' },
  en: { eyebrow: 'Administration / Migration', title: 'Noorix migration review gate', description: 'Auditable approval for direct technical candidates only. This page moves no financial, employee, or file records.', load: 'Loading migration runs…', noRuns: 'No Noorix migration runs exist in this tenant.', direct: 'Direct candidates', counterparties: 'Explicit identity matches', intelligence: 'Intelligent review assistant', intelligenceHelp: 'Conservative suggestions from names, repetition, and entity type. Nothing is recorded or created until you apply a suggestion.', suggestion: 'Suggestion', suggestionMatch: 'Link to the existing identity', suggestionCreate: 'Create one commercial identity', suggestionReview: 'Manual review', high: 'High confidence', medium: 'Medium confidence', low: 'Needs review', applySuggestion: 'Apply suggestion', manualReview: 'Manual review required', repeatedNames: 'Exact names across companies', repeatedNamesHelp: 'A batch contains only one conservatively normalized exact name; your choice creates a separately auditable decision for each record in the group.', supplierQueue: 'Unresolved supplier review', supplierQueueHelp: 'Selecting an existing identity registers this name as its explicit alias; or create a separate commercial identity. The decision creates neither a company supplier nor a financial movement.', searchIdentity: 'Search existing identities', chooseIdentity: 'Select an existing identity…', resolve: 'Record identity decision', createCommercial: 'Create separate commercial identity', createCommercialGroup: 'Create one commercial identity for the group', next: 'Show next batch', noCandidates: 'No unresolved names are in this batch.', blockers: 'Blockers', review: 'Review', warnings: 'Warnings', reason: 'Map approval or acknowledgement reason', reasonHelp: 'The reason is retained in an immutable audit record. Supplier decision reasons are entered inside each supplier card.', supplierReason: 'Reason for this supplier decision', supplierReasonHelp: 'Enter a clear reason of at least three characters; it will be retained only with this supplier decision.', approve: 'Approve direct candidates', approved: 'Approved', acknowledge: 'Acknowledge review', acknowledged: 'Acknowledged', exceptions: 'Blockers and reviews', audit: 'Latest review decisions', noActions: 'No decisions recorded yet.', safeTitle: 'Safety boundary', safe: 'This page cannot approve suppliers, vaults, invoices, or journals. Those remain blockers until approved transform rules exist and a dry-run is executed.', select: 'Select migration run', reload: 'Refresh', failed: 'The request could not be completed. Check tenant-owner access and server connectivity.', stage: 'Status: review before dry-run' },
} as const;

export function NurixMigrationWorkspace({ language }: { language: Language }) {
  const [session] = useState<ActiveSession | null>(activeSession);
  if (!session) return <DailySalesSignIn language={language} />;
  return <NurixMigrationContent language={language} session={session} />;
}

function NurixMigrationContent({ language, session }: { language: Language; session: ActiveSession }) {
  const text = copy[language];
  const supplierGate = language === 'ar'
    ? { unresolved: 'هويات مركزية مؤجلة', provisional: 'موردون مبدئيون داخل الشركات', vaults: 'خزائن مبدئية', title: 'إنشاء الموردين المبدئيين', blocked: 'إنشاء الموردين مقفل إلى أن تعتمد خرائط الشركات والحسابات والفئات المباشرة أولًا.', ready: 'يمكن الآن نسخ كل اسم مورد إلى شركته المستهدفة مع حفظ المصدر. لن تُستورد فواتير أو أرصدة أو قيود، ويمكن ربط المورد بهوية مركزية أو تعديل تصنيفه لاحقًا.', create: 'إنشاء الموردين المبدئيين', complete: 'أُنشئت جميع الموردين المبدئيين' }
    : { unresolved: 'Central identities deferred', provisional: 'Company provisional suppliers', vaults: 'Provisional vaults', title: 'Create provisional suppliers', blocked: 'Supplier creation is locked until company, direct-account, and direct-category maps are approved.', ready: 'Every supplier name can now be copied to its target company with provenance. No invoices, balances, or journals are imported, and central identity linkage or classification can be refined later.', create: 'Create provisional suppliers', complete: 'All provisional suppliers created' };
  const companyMaps = language === 'ar'
    ? { label: 'خرائط الشركات المخططة', approve: 'اعتماد خرائط الشركات', approved: 'معتمدة للموجة التالية' }
    : { label: 'Planned company maps', approve: 'Approve company maps', approved: 'Approved for the next wave' };
  const [runs, setRuns] = useState<NurixMigrationRun[]>([]);
  const [review, setReview] = useState<NurixMigrationReview | null>(null);
  const [counterpartyQueue, setCounterpartyQueue] = useState<NurixCounterpartyQueue | null>(null);
  const [counterpartyGroups, setCounterpartyGroups] = useState<NurixCounterpartyReviewGroups | null>(null);
  const [counterpartySuggestions, setCounterpartySuggestions] = useState<NurixCounterpartySuggestions | null>(null);
  const [identitySelections, setIdentitySelections] = useState<Record<string, string>>({});
  const [identitySearches, setIdentitySearches] = useState<Record<string, string>>({});
  const [counterpartyReasons, setCounterpartyReasons] = useState<Record<string, string>>({});
  const [selectedRunId, setSelectedRunId] = useState('');
  const [reason, setReason] = useState('');
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');

  const load = async (runId?: string) => {
    setLoading(true); setMessage('');
    try {
      const receipt = await loadNurixMigrationRuns(session);
      setRuns(receipt.runs);
      // An empty state value is not a selected run. Fall back to the first
      // available run so the initial page load shows its review gate rather
      // than only the selector.
      const nextId = runId || selectedRunId || receipt.runs[0]?.id || '';
      setSelectedRunId(nextId);
      const [nextReview, nextQueue, nextGroups, nextSuggestions] = nextId ? await Promise.all([loadNurixMigrationReview(session, nextId), loadNurixCounterpartyQueue(session, nextId), loadNurixCounterpartyReviewGroups(session, nextId), loadNurixCounterpartySuggestions(session, nextId)]) : [null, null, null, null];
      setReview(nextReview);
      setCounterpartyQueue(nextQueue);
      setCounterpartyGroups(nextGroups);
      setCounterpartySuggestions(nextSuggestions);
      setIdentitySelections({});
      setIdentitySearches({});
      setCounterpartyReasons({});
    } catch (error) { setMessage(error instanceof BaseerApiError ? text.failed : text.failed); }
    finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, []);
  const chooseRun = async (runId: string) => { setSelectedRunId(runId); await load(runId); };
  const command = async (operation: () => Promise<unknown>, auditReason: string, afterSuccess: () => void) => {
    if (auditReason.length < 3) { setMessage(language === 'ar' ? 'أدخل سببًا من ثلاثة أحرف على الأقل قبل التسجيل.' : 'Enter a reason of at least three characters before recording.'); return; }
    setBusy(true); setMessage('');
    try { await operation(); afterSuccess(); await load(selectedRunId); }
    catch (error) { setMessage(error instanceof BaseerApiError ? error.message : text.failed); }
    finally { setBusy(false); }
  };
  const tone = (severity: 'BLOCKER' | 'REVIEW' | 'WARNING') => severity === 'BLOCKER' ? 'danger' : severity === 'REVIEW' ? 'warning' : 'info';
  const directLabel = (kind: string) => kind === 'CATEGORY_DIRECT' ? (language === 'ar' ? 'فئات متطابقة مباشرة' : 'Direct category matches') : (language === 'ar' ? 'حسابات متطابقة بالرمز والنوع' : 'Account code/type matches');
  const counterpartyReason = (key: string) => counterpartyReasons[key]?.trim() ?? '';
  const visibleIdentities = (key: string, identities: NurixCounterpartyReviewGroups['identities']) => {
    const query = (identitySearches[key] ?? '').trim().toLocaleLowerCase();
    return query ? identities.filter((identity) => `${identity.canonicalNameAr} ${identity.kind}`.toLocaleLowerCase().includes(query)) : identities;
  };
  const clearCounterpartyReason = (key: string) => setCounterpartyReasons((current) => { const next = { ...current }; delete next[key]; return next; });
  const applyCounterpartySuggestion = (suggestion: NurixCounterpartySuggestions['suggestions'][number]) => {
    if (suggestion.action === 'MATCH_EXISTING_IDENTITY' && suggestion.identity) return command(() => resolveNurixCounterpartyReviewGroup(session, review!.run.id, suggestion.groupKey, suggestion.identity!.id, suggestion.reasonAr), suggestion.reasonAr, () => undefined);
    if (suggestion.action === 'CREATE_COMMERCIAL_GROUP') return command(() => createCommercialNurixCounterpartyReviewGroup(session, review!.run.id, suggestion.groupKey, suggestion.reasonAr), suggestion.reasonAr, () => undefined);
  };
  const suggestionLabel = (suggestion: NurixCounterpartySuggestions['suggestions'][number]) => {
    if (suggestion.action === 'MATCH_EXISTING_IDENTITY' && suggestion.identity) return `${text.suggestionMatch}: ${suggestion.identity.canonicalNameAr}`;
    return suggestion.action === 'CREATE_COMMERCIAL_GROUP' ? text.suggestionCreate : text.suggestionReview;
  };
  const loadNextCounterpartyBatch = async () => {
    if (!counterpartyQueue?.nextCursor || !review) return;
    setBusy(true); setMessage('');
    try { setCounterpartyQueue(await loadNurixCounterpartyQueue(session, review.run.id, counterpartyQueue.nextCursor)); setIdentitySelections({}); setIdentitySearches({}); setCounterpartyReasons({}); }
    catch { setMessage(text.failed); }
    finally { setBusy(false); }
  };

  if (loading && !review) return <section className="module-page__placeholder">{text.load}</section>;
  return <BaseerWorkspace className="nurix-migration-workspace">
    <BaseerSectionHeader eyebrow={text.eyebrow} title={text.title} description={text.description} actions={<BaseerStatusBadge tone="warning">{text.stage}</BaseerStatusBadge>} />
    <BaseerNotice tone="warning" title={text.safeTitle}>{text.safe}</BaseerNotice>
    {message ? <BaseerNotice tone="danger">{message}</BaseerNotice> : null}
    {runs.length === 0 ? <BaseerEmptyState title={text.noRuns} /> : <>
      <BaseerCard className="nurix-migration-selector"><label>{text.select}<select value={selectedRunId} onChange={(event) => void chooseRun(event.target.value)} disabled={busy}>{runs.map((run) => <option value={run.id} key={run.id}>{run.sourceSystem} · {run.transformVersion} · {run.sourceFingerprintPrefix}</option>)}</select></label><BaseerButton type="button" onClick={() => void load(selectedRunId)} disabled={loading || busy}>{text.reload}</BaseerButton></BaseerCard>
      {review ? <>
        <section className="nurix-migration-metrics" aria-label={text.title}>
          <Metric label={text.direct} value={String(review.run.directCandidates.reduce((sum, item) => sum + item.count, 0))} tone="success" />
          <Metric label={text.counterparties} value={String(review.run.counterpartyResolutions.explicitAlias)} tone="success" />
          <Metric label={supplierGate.unresolved} value={String(review.run.supplierReadiness.unresolved)} tone={review.run.supplierReadiness.unresolved ? "warning" : "success"} />
          <Metric label={supplierGate.provisional} value={String(review.run.supplierReadiness.provisionalSuppliers)} tone={review.run.supplierReadiness.provisionalSuppliers === review.run.supplierReadiness.candidates ? "success" : "warning"} />
          <Metric label={supplierGate.vaults} value={String(review.run.supplierReadiness.provisionalVaults)} tone={review.run.supplierReadiness.provisionalVaults ? "success" : "warning"} />
          <Metric label={text.blockers} value={String(review.run.exceptionCounts.blockers)} tone="danger" />
          <Metric label={text.review} value={String(review.run.exceptionCounts.review)} tone="warning" />
          <Metric label={text.warnings} value={String(review.run.exceptionCounts.warnings)} tone="info" />
        </section>
        <BaseerNotice tone={review.run.supplierReadiness.canCreateProvisionalSuppliers ? "success" : "warning"} title={supplierGate.title}>{review.run.supplierReadiness.canCreateProvisionalSuppliers ? supplierGate.ready : supplierGate.blocked}</BaseerNotice>
        {counterpartySuggestions ? <section className="nurix-migration-section"><header><div><h3>{text.intelligence}</h3><p>{text.intelligenceHelp}</p></div></header><div className="nurix-migration-ai-summary"><BaseerStatusBadge tone="success">{text.high}: {formatCount(counterpartySuggestions.summary.high, language)}</BaseerStatusBadge><BaseerStatusBadge tone="warning">{text.medium}: {formatCount(counterpartySuggestions.summary.medium, language)}</BaseerStatusBadge><BaseerStatusBadge tone="neutral">{text.low}: {formatCount(counterpartySuggestions.summary.low, language)}</BaseerStatusBadge></div><div className="nurix-migration-exception-list">{counterpartySuggestions.suggestions.filter((suggestion) => suggestion.confidence !== 'LOW').slice(0, 50).map((suggestion) => <BaseerCard key={suggestion.groupKey} padding="compact" className="nurix-migration-suggestion"><div><strong>{suggestion.nameAr}</strong><small>{formatCount(suggestion.count, language)} · {formatCount(suggestion.companyCount, language)}</small><p className="nurix-migration-suggestion-label"><b>{text.suggestion}:</b> {suggestionLabel(suggestion)}</p><p>{suggestion.reasonAr}</p></div><div><BaseerStatusBadge tone={suggestion.confidence === 'HIGH' ? 'success' : 'warning'}>{suggestion.confidence === 'HIGH' ? text.high : text.medium}</BaseerStatusBadge>{suggestion.action === 'REVIEW_MANUALLY' ? <BaseerStatusBadge tone="neutral">{text.manualReview}</BaseerStatusBadge> : <BaseerButton type="button" variant="primary" disabled={busy} onClick={() => void applyCounterpartySuggestion(suggestion)}>{text.applySuggestion}</BaseerButton>}</div></BaseerCard>)}</div></section> : null}
        <BaseerCard className="nurix-migration-reason"><label htmlFor="nurix-review-reason">{text.reason}</label><textarea id="nurix-review-reason" value={reason} onChange={(event) => setReason(event.target.value)} maxLength={500} disabled={busy} /><small>{text.reasonHelp}</small></BaseerCard>
        <section className="nurix-migration-section"><header><div><h3>{text.direct}</h3><p>{language === 'ar' ? 'هذه الخرائط لا تُحوّل السجلات؛ هي شهادة مراجعة مسبقة فقط.' : 'These maps do not transform records; this is a review attestation only.'}</p></div></header><div className="nurix-migration-candidate-list"><BaseerCard padding="compact" className="nurix-migration-candidate"><div><strong>{companyMaps.label}</strong><span>{formatCount(review.run.supplierReadiness.approvedCompanyMaps, language)} / {formatCount(review.run.supplierReadiness.companyMaps, language)}</span></div>{review.run.supplierReadiness.approvedCompanyMaps === review.run.supplierReadiness.companyMaps && review.run.supplierReadiness.companyMaps > 0 ? <BaseerStatusBadge tone="success">{companyMaps.approved}</BaseerStatusBadge> : <BaseerButton type="button" variant="primary" disabled={busy || review.run.supplierReadiness.companyMaps === 0} onClick={() => void command(() => approveNurixCompanyMaps(session, review.run.id, reason.trim()), reason.trim(), () => setReason(''))}>{companyMaps.approve}</BaseerButton>}</BaseerCard>{review.run.directCandidates.map((candidate) => <BaseerCard key={candidate.kind} padding="compact" className="nurix-migration-candidate"><div><strong>{directLabel(candidate.kind)}</strong><span>{formatCount(candidate.count, language)}</span></div>{candidate.approved ? <BaseerStatusBadge tone="success">{text.approved}</BaseerStatusBadge> : <BaseerButton type="button" variant="primary" disabled={busy || candidate.count === 0} onClick={() => void command(() => approveNurixDirectCandidates(session, review.run.id, candidate.kind, reason.trim()), reason.trim(), () => setReason(''))}>{text.approve}</BaseerButton>}</BaseerCard>)}</div></section>
        <section className="nurix-migration-section"><header><div><h3>{supplierGate.title}</h3><p>{language === 'ar' ? 'يُنشأ مورد مستقل لكل مورد مصدر داخل الشركة المعتمدة، ويحفظ ربط مصدر غير قابل للتكرار. النوع Expense مبدئي فقط إلى أن تحدد مرحلة تحويل المستندات التصنيف الصحيح.' : 'A separate supplier is created in each approved company with non-duplicable source provenance. Expense is a temporary starter type until document transformation determines the correct classification.'}</p></div></header><div className="nurix-migration-candidate-list"><BaseerCard padding="compact" className="nurix-migration-candidate"><div><strong>{supplierGate.provisional}</strong><span>{formatCount(review.run.supplierReadiness.provisionalSuppliers, language)} / {formatCount(review.run.supplierReadiness.candidates, language)}</span></div>{review.run.supplierReadiness.provisionalSuppliers === review.run.supplierReadiness.candidates && review.run.supplierReadiness.candidates > 0 ? <BaseerStatusBadge tone="success">{supplierGate.complete}</BaseerStatusBadge> : <BaseerButton type="button" variant="primary" disabled={busy || !review.run.supplierReadiness.canCreateProvisionalSuppliers} onClick={() => { const auditReason = reason.trim() || (language === 'ar' ? 'إنشاء الموردين المبدئيين من نوركس بعد اعتماد خرائط المراجعة.' : 'Create Noorix provisional suppliers after map review approval.'); void command(() => createNurixProvisionalSuppliers(session, review.run.id, auditReason), auditReason, () => setReason('')); }}>{supplierGate.create}</BaseerButton>}</BaseerCard></div></section>
        {(counterpartyGroups?.groups.filter((group) => group.count > 1).length ?? 0) > 0 ? <section className="nurix-migration-section"><header><div><h3>{text.repeatedNames}</h3><p>{text.repeatedNamesHelp}</p></div></header><div className="nurix-migration-exception-list">{counterpartyGroups?.groups.filter((group) => group.count > 1).map((group) => <BaseerCard key={group.key} padding="compact" className="nurix-migration-exception"><div><strong>{group.nameAr}</strong><small>{formatCount(group.count, language)} · {formatCount(group.companyCount, language)}</small></div><div className="nurix-migration-counterparty-actions"><label className="nurix-migration-counterparty-reason"><span>{text.supplierReason}</span><textarea value={counterpartyReasons[group.key] ?? ''} onChange={(event) => setCounterpartyReasons((current) => ({ ...current, [group.key]: event.target.value }))} maxLength={500} disabled={busy} /><small>{text.supplierReasonHelp}</small></label><label className="nurix-migration-identity-search"><span>{text.searchIdentity}</span><input type="search" value={identitySearches[group.key] ?? ''} onChange={(event) => setIdentitySearches((current) => ({ ...current, [group.key]: event.target.value }))} disabled={busy} /></label><select aria-label={text.chooseIdentity} value={identitySelections[group.key] ?? ''} disabled={busy} onChange={(event) => setIdentitySelections((current) => ({ ...current, [group.key]: event.target.value }))}><option value="">{text.chooseIdentity}</option>{visibleIdentities(group.key, counterpartyGroups.identities).map((identity) => <option key={identity.id} value={identity.id}>{identity.canonicalNameAr} · {identity.kind}</option>)}</select><BaseerButton type="button" variant="quiet" disabled={busy || !identitySelections[group.key] || counterpartyReason(group.key).length < 3} onClick={() => void command(() => resolveNurixCounterpartyReviewGroup(session, review.run.id, group.key, identitySelections[group.key]!, counterpartyReason(group.key)), counterpartyReason(group.key), () => clearCounterpartyReason(group.key))}>{text.resolve}</BaseerButton><BaseerButton type="button" variant="quiet" disabled={busy || counterpartyReason(group.key).length < 3} onClick={() => void command(() => createCommercialNurixCounterpartyReviewGroup(session, review.run.id, group.key, counterpartyReason(group.key)), counterpartyReason(group.key), () => clearCounterpartyReason(group.key))}>{text.createCommercialGroup}</BaseerButton></div></BaseerCard>)}</div></section> : null}
        <section className="nurix-migration-section"><header><div><h3>{text.supplierQueue}</h3><p>{text.supplierQueueHelp}</p></div></header>{counterpartyQueue?.candidates.length ? <div className="nurix-migration-exception-list">{counterpartyQueue.candidates.map((candidate) => <BaseerCard key={candidate.id} padding="compact" className="nurix-migration-exception"><div><strong>{candidate.nameAr}</strong>{candidate.nameEn ? <p>{candidate.nameEn}</p> : null}<small>{candidate.sourceCompanyId} · {candidate.sourceSupplierId}</small></div><div className="nurix-migration-counterparty-actions"><label className="nurix-migration-counterparty-reason"><span>{text.supplierReason}</span><textarea value={counterpartyReasons[candidate.id] ?? ''} onChange={(event) => setCounterpartyReasons((current) => ({ ...current, [candidate.id]: event.target.value }))} maxLength={500} disabled={busy} /><small>{text.supplierReasonHelp}</small></label><label className="nurix-migration-identity-search"><span>{text.searchIdentity}</span><input type="search" value={identitySearches[candidate.id] ?? ''} onChange={(event) => setIdentitySearches((current) => ({ ...current, [candidate.id]: event.target.value }))} disabled={busy} /></label><select aria-label={text.chooseIdentity} value={identitySelections[candidate.id] ?? ''} disabled={busy} onChange={(event) => setIdentitySelections((current) => ({ ...current, [candidate.id]: event.target.value }))}><option value="">{text.chooseIdentity}</option>{visibleIdentities(candidate.id, counterpartyQueue.identities).map((identity) => <option key={identity.id} value={identity.id}>{identity.canonicalNameAr} · {identity.kind}</option>)}</select><BaseerButton type="button" variant="quiet" disabled={busy || !identitySelections[candidate.id] || counterpartyReason(candidate.id).length < 3} onClick={() => void command(() => resolveNurixCounterparty(session, review.run.id, candidate.id, identitySelections[candidate.id]!, counterpartyReason(candidate.id)), counterpartyReason(candidate.id), () => clearCounterpartyReason(candidate.id))}>{text.resolve}</BaseerButton><BaseerButton type="button" variant="quiet" disabled={busy || counterpartyReason(candidate.id).length < 3} onClick={() => void command(() => createCommercialNurixCounterparty(session, review.run.id, candidate.id, counterpartyReason(candidate.id)), counterpartyReason(candidate.id), () => clearCounterpartyReason(candidate.id))}>{text.createCommercial}</BaseerButton></div></BaseerCard>)}</div> : <BaseerEmptyState title={text.noCandidates} />}{counterpartyQueue?.nextCursor ? <BaseerButton type="button" variant="quiet" disabled={busy} onClick={() => void loadNextCounterpartyBatch()}>{text.next}</BaseerButton> : null}</section>
        <section className="nurix-migration-section"><header><div><h3>{text.exceptions}</h3><p>{language === 'ar' ? 'الإقرار لا يحل العائق ولا يفتح الاستيراد؛ إنه يثبت المراجعة فقط.' : 'Acknowledgement does not resolve a blocker or unlock import; it only proves review.'}</p></div></header><div className="nurix-migration-exception-list">{review.exceptions.map((item) => <BaseerCard key={item.id} padding="compact" className="nurix-migration-exception"><div><BaseerStatusBadge tone={tone(item.severity)}>{item.severity}</BaseerStatusBadge><strong>{item.code}</strong><p>{item.message}</p></div>{item.acknowledged ? <BaseerStatusBadge tone="neutral">{text.acknowledged}</BaseerStatusBadge> : <BaseerButton type="button" variant="quiet" disabled={busy} onClick={() => void command(() => acknowledgeNurixMigrationException(session, review.run.id, item.id, reason.trim()), reason.trim(), () => setReason(''))}>{text.acknowledge}</BaseerButton>}</BaseerCard>)}</div></section>
        <section className="nurix-migration-section"><header><h3>{text.audit}</h3></header>{review.actions.length ? <ol className="nurix-migration-audit">{review.actions.map((action) => <li key={action.id}><strong>{action.kind}</strong><span>{action.reason}</span><time dateTime={action.createdAt}>{formatDateTime(action.createdAt, language, 'Asia/Riyadh')}</time></li>)}</ol> : <BaseerEmptyState title={text.noActions} />}</section>
      </> : null}
    </>}
  </BaseerWorkspace>;
}

function Metric({ label, value, tone }: { label: string; value: string; tone: 'success' | 'danger' | 'warning' | 'info' }) { return <BaseerCard padding="compact" className="nurix-migration-metric"><span>{label}</span><strong>{value}</strong><BaseerStatusBadge tone={tone}>{tone}</BaseerStatusBadge></BaseerCard>; }
