import { api, baseerApiBaseUrl, requestId, type ActiveSession } from './daily-sales-client';

export type NurixDirectCandidate = { kind: 'CATEGORY_DIRECT' | 'ACCOUNT_CODE_TYPE'; count: number; approved: boolean };
export type NurixMigrationRun = {
  id: string; sourceSystem: 'NOORIX_POSTGRES_ARCHIVE'; sourceFingerprintPrefix: string; transformVersion: string;
  status: string; companyCount: number; directCandidates: NurixDirectCandidate[];
  counterpartyResolutions: { explicitAlias: number; manual: number };
  supplierReadiness: { candidates: number; resolved: number; unresolved: number; companyMaps: number; approvedCompanyMaps: number; categoryCandidatesApproved: boolean; accountCandidatesApproved: boolean; provisionalSuppliers: number; provisionalVaults: number; canCreateProvisionalSuppliers: boolean; canStage: boolean };
  exceptionCounts: { blockers: number; review: number; warnings: number }; createdAt: string;
};
export type NurixMigrationException = { id: string; severity: 'BLOCKER' | 'REVIEW' | 'WARNING'; code: string; message: string; sourceEntity: string | null; acknowledged: boolean; createdAt: string };
export type NurixMigrationReview = { run: NurixMigrationRun; exceptions: NurixMigrationException[]; actions: Array<{ id: string; kind: string; actionKey: string; reason: string; createdAt: string }> };
export type NurixCounterpartyIdentity = { id: string; canonicalKey: string; canonicalNameAr: string; kind: 'COMMERCIAL_SUPPLIER' | 'GOVERNMENT_AUTHORITY' | 'GOVERNMENT_PLATFORM' | 'UTILITY_PROVIDER' | 'OTHER' };
export type NurixCounterpartyCandidate = { id: string; sourceCompanyId: string; sourceSupplierId: string; nameAr: string; nameEn: string | null; kind: 'EXPLICIT_ALIAS' | 'REVIEW_REQUIRED'; resolution: { kind: 'EXPLICIT_ALIAS' | 'MANUAL'; identity: NurixCounterpartyIdentity } | null };
export type NurixCounterpartyQueue = { candidates: NurixCounterpartyCandidate[]; identities: NurixCounterpartyIdentity[]; nextCursor: string | null };
export type NurixCounterpartyReviewGroup = { key: string; nameAr: string; count: number; companyCount: number };
export type NurixCounterpartyReviewGroups = { groups: NurixCounterpartyReviewGroup[]; identities: NurixCounterpartyIdentity[] };
export type NurixCounterpartySuggestion = { groupKey: string; nameAr: string; count: number; companyCount: number; action: 'MATCH_EXISTING_IDENTITY' | 'CREATE_COMMERCIAL_GROUP' | 'REVIEW_MANUALLY'; confidence: 'HIGH' | 'MEDIUM' | 'LOW'; reasonAr: string; identity: NurixCounterpartyIdentity | null };
export type NurixCounterpartySuggestions = { suggestions: NurixCounterpartySuggestion[]; summary: { high: number; medium: number; low: number } };
export type NurixExcelImportTemplate = { templateVersion: 'nurix-excel-package/v3'; sourceSystem: 'NOORIX_EXCEL_EXPORT'; sheets: Array<{ name: string; requiredColumns: string[] }> };
type NurixExcelMasterCounts = { suppliers: number; accounts: number; categories: number; vaults: number; employees: number };
export type NurixExcelMasterDataExecution = { executionId: string; status: 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED'; created: { accounts: number; categories: number; employees: number }; reused: { accounts: number; categories: number; employees: number }; reviewRequired: { accounts: number; categories: number; employees: number }; processed: number; remaining: number; completed: boolean; waves: number; financialWrites: 0 };
export type NurixExcelImportPreflight = { mode: 'PREFLIGHT_DRY_RUN'; status: 'PENDING_WORKBOOK_PARSER' | 'PARSED_DRY_RUN' | 'REJECTED'; templateVersion: 'nurix-excel-package/v3'; sourceCompanyId: string; targetCompanyId: string; financialWrites: 0; parsedRows: number; acceptedRows: number; rejectedRows: number; canStage: false; stagingPackageId: string | null; checks: Array<{ code: string; passed: boolean; messageAr: string }>; reconciliation: { passed: boolean; counts: Array<{ key: string; sheet: string; declaredRows: number; parsedRows: number; matches: boolean }>; totals: Array<{ key: string; sheet: string; column: string; declaredAmount: string; parsedAmount: string; matches: boolean }> }; masterDataReadiness: { availability: 'READ_ONLY_ANALYZED' | 'PENDING_TARGET_READ'; exactMatches: NurixExcelMasterCounts; createCandidates: NurixExcelMasterCounts; reviewRequired: NurixExcelMasterCounts; canWrite: false }; rowIssues: Array<{ sheet: string; rowNumber: number; code: string }> };
export type NurixHistoricalPayrollEvidence = { companyId: string; runs: Array<{ sourceRunNumber: string; payrollMonth: string; sourceAccruedAt: string; employeeCount: number; lineCount: number; grossAmount: string; deductionsAmount: string; sourceAdvancesAmount: string; appliedAdvancesAmount: string; advanceCarryoverEvidenceAmount: string; netAmount: string; paymentEvidenceKind: 'NONE' | 'AMOUNT_ONLY'; paymentEvidenceAmount: string | null; status: 'EVIDENCE_ONLY' }> };

const json = () => ({ 'Content-Type': 'application/json', 'X-Request-Id': requestId() });

export const loadNurixMigrationRuns = (session: ActiveSession) => api<{ runs: NurixMigrationRun[] }>(session, '/nurix-migration/runs');
export const loadNurixMigrationReview = (session: ActiveSession, runId: string) => api<NurixMigrationReview>(session, `/nurix-migration/runs/${runId}/review`);
export const loadNurixCounterpartyQueue = (session: ActiveSession, runId: string, cursor?: string) => api<NurixCounterpartyQueue>(session, `/nurix-migration/runs/${runId}/counterparties${cursor ? `?cursor=${encodeURIComponent(cursor)}` : ''}`);
export const loadNurixCounterpartyReviewGroups = (session: ActiveSession, runId: string) => api<NurixCounterpartyReviewGroups>(session, `/nurix-migration/runs/${runId}/counterparty-review-groups`);
export const loadNurixCounterpartySuggestions = (session: ActiveSession, runId: string) => api<NurixCounterpartySuggestions>(session, `/nurix-migration/runs/${runId}/counterparty-suggestions`);
export const approveNurixDirectCandidates = (session: ActiveSession, runId: string, kind: NurixDirectCandidate['kind'], reason: string) => api(session, `/nurix-migration/runs/${runId}/direct-candidates/approve`, { method: 'POST', headers: json(), body: JSON.stringify({ kind, reason }) });
export const approveNurixCompanyMaps = (session: ActiveSession, runId: string, reason: string) => api(session, `/nurix-migration/runs/${runId}/company-maps/approve`, { method: 'POST', headers: json(), body: JSON.stringify({ reason }) });
export const createNurixProvisionalSuppliers = (session: ActiveSession, runId: string, reason: string) => api<{ created: number; reused: number; linkedToExistingIdentity: number; total: number; processed: number; remaining: number; completed: boolean; waves: number }>(session, `/nurix-migration/runs/${runId}/provisional-suppliers`, { method: 'POST', headers: json(), body: JSON.stringify({ reason }) });
export const acknowledgeNurixMigrationException = (session: ActiveSession, runId: string, exceptionId: string, reason: string) => api(session, `/nurix-migration/runs/${runId}/exceptions/${exceptionId}/acknowledge`, { method: 'POST', headers: json(), body: JSON.stringify({ reason }) });
export const resolveNurixCounterparty = (session: ActiveSession, runId: string, candidateId: string, identityId: string, reason: string) => api(session, `/nurix-migration/runs/${runId}/counterparties/${candidateId}/resolve`, { method: 'POST', headers: json(), body: JSON.stringify({ identityId, reason }) });
export const createCommercialNurixCounterparty = (session: ActiveSession, runId: string, candidateId: string, reason: string) => api(session, `/nurix-migration/runs/${runId}/counterparties/${candidateId}/create-commercial-identity`, { method: 'POST', headers: json(), body: JSON.stringify({ reason }) });
export const resolveNurixCounterpartyReviewGroup = (session: ActiveSession, runId: string, groupKey: string, identityId: string, reason: string) => api(session, `/nurix-migration/runs/${runId}/counterparty-review-groups/${groupKey}/resolve`, { method: 'POST', headers: json(), body: JSON.stringify({ identityId, reason }) });
export const createCommercialNurixCounterpartyReviewGroup = (session: ActiveSession, runId: string, groupKey: string, reason: string) => api(session, `/nurix-migration/runs/${runId}/counterparty-review-groups/${groupKey}/create-commercial-identity`, { method: 'POST', headers: json(), body: JSON.stringify({ reason }) });

/** This dry-run never writes financial records. A technically verified workbook
 * may be retained encrypted solely to resume its review after an interruption. */
export const loadNurixExcelImportTemplate = (session: ActiveSession) => api<NurixExcelImportTemplate>(session, '/nurix-migration/excel-import/template');
export const loadNurixHistoricalPayrollEvidence = (session: ActiveSession, companyId: string) => api<NurixHistoricalPayrollEvidence>(session, `/nurix-migration/excel-import/historical-payroll?companyId=${encodeURIComponent(companyId)}`);
export const startNurixExcelImportPreflight = (session: ActiveSession, body: { targetCompanyId: string; sourceCompanyId: string; templateVersion: 'nurix-excel-package/v3'; workbook: { fileName: string; mimeType: string; sha256?: string; byteSize: number; exportedAt: string; contentsBase64: string } }) => api<NurixExcelImportPreflight>(session, '/nurix-migration/excel-import/packages/dry-run', { method: 'POST', headers: { 'Content-Type': 'application/vnd.baseer-erp.nurix-excel+json', 'X-Request-Id': requestId() }, body: JSON.stringify(body) });
export const executeNurixExcelMasterData = (session: ActiveSession, packageId: string) => api<NurixExcelMasterDataExecution>(session, `/nurix-migration/excel-import/packages/${packageId}/master-data`, { method: 'POST', headers: json(), body: JSON.stringify({ waveSize: 500 }) });
