import { useBaseerForm, z } from "./baseer-form-state";
import { useEffect, useMemo } from "react";

import { BaseerFormDialog } from "./baseer-form-dialog";
import type { ItemForm } from "./operations-catalog-workspace";

type Unit = { id: string; nameAr: string; nameEn: string | null; isActive: boolean };
type Section = { id: string; nameAr: string; nameEn: string | null; isActive: boolean };
const empty = (): ItemForm => ({ code: "", nameAr: "", nameEn: "", kind: "RAW_MATERIAL", sectionId: "", baseUnitId: "", unitIds: [], salePrice: "" });
function schema(ar: boolean) { return z.object({ code: z.string().trim().min(1, ar ? "أدخل رمز الصنف." : "Enter an item code."), nameAr: z.string().trim().min(1, ar ? "أدخل اسم الصنف بالعربية." : "Enter the Arabic item name."), nameEn: z.string(), kind: z.enum(["RAW_MATERIAL", "MENU_PRODUCT"]), sectionId: z.string(), baseUnitId: z.string().min(1, ar ? "اختر وحدة الأساس." : "Choose a base unit."), unitIds: z.array(z.string()).min(1, ar ? "اختر وحدة واحدة على الأقل." : "Choose at least one unit."), salePrice: z.string() }).superRefine((value, ctx) => { if (value.kind === "MENU_PRODUCT" && !value.sectionId) ctx.addIssue({ code: "custom", path: ["sectionId"], message: ar ? "اختر قسم التسجيل." : "Choose a registration section." }); if (value.baseUnitId && !value.unitIds.includes(value.baseUnitId)) ctx.addIssue({ code: "custom", path: ["unitIds"], message: ar ? "يجب أن تكون وحدة الأساس ضمن وحدات الصنف." : "The base unit must be included in the item units." }); if (value.salePrice && !/^\d+(?:\.\d{1,4})?$/.test(value.salePrice)) ctx.addIssue({ code: "custom", path: ["salePrice"], message: ar ? "أدخل سعر بيع صحيحاً." : "Enter a valid sale price." }); }); }

export function OperationsCatalogItemCreateDialog({ open, language, busy, value, units, sections, onClose, onSubmit }: { open: boolean; language: "ar" | "en"; busy: boolean; value: ItemForm; units: readonly Unit[]; sections: readonly Section[]; onClose: () => void; onSubmit: (value: ItemForm) => Promise<void> | void }) {
  const ar = language === "ar"; const t = ar ? { title: "إضافة مادة أولية", save: "حفظ", code: "الرمز", nameAr: "الاسم بالعربية", nameEn: "الاسم بالإنجليزية", kind: "نوع الصنف", raw: "مادة أولية", menu: "منتج منيو", section: "قسم التسجيل", base: "الوحدة الأساسية", sale: "سعر بيع المنيو", units: "وحدات الصنف" } : { title: "Add raw material", save: "Save", code: "Code", nameAr: "Arabic name", nameEn: "English name", kind: "Item type", raw: "Raw material", menu: "Menu product", section: "Registration section", base: "Base unit", sale: "Menu sale price", units: "Item units" };
  const validation = useMemo(() => schema(ar), [ar]); const form = useBaseerForm<ItemForm>({ defaultValues: value, schema: validation, shouldFocusError: true });
  const kind = form.watch("kind"); const baseUnitId = form.watch("baseUnitId"); const unitIds = form.watch("unitIds");
  useEffect(() => { if (open) form.reset(value.code || value.nameAr || value.baseUnitId ? value : empty()); }, [form, open, value]);
  const name = (item: { nameAr: string; nameEn: string | null }) => ar ? item.nameAr : item.nameEn ?? item.nameAr;
  const toggleUnit = (id: string) => { const next = unitIds.includes(id) ? unitIds.filter((item) => item !== id) : [...unitIds, id]; form.setValue("unitIds", next, { shouldDirty: true, shouldValidate: true }); if (baseUnitId === id && !next.includes(id)) form.setValue("baseUnitId", "", { shouldDirty: true, shouldValidate: true }); };
  return <BaseerFormDialog open={open} title={t.title} language={language} formId="operations-item" submitLabel={t.save} busy={busy} onClose={onClose}><form id="operations-item" className="administration-form" data-baseer-rhf-form="true" noValidate onSubmit={form.handleSubmit((next) => void onSubmit(next))}>
    <label>{t.code}<input autoFocus aria-invalid={Boolean(form.formState.errors.code)} {...form.register("code")} />{form.formState.errors.code ? <small role="alert">{form.formState.errors.code.message}</small> : null}</label>
    <label>{t.nameAr}<input aria-invalid={Boolean(form.formState.errors.nameAr)} {...form.register("nameAr")} />{form.formState.errors.nameAr ? <small role="alert">{form.formState.errors.nameAr.message}</small> : null}</label><label>{t.nameEn}<input {...form.register("nameEn")} /></label>
    <label>{t.kind}<select {...form.register("kind")} onChange={(event) => { form.setValue("kind", event.target.value as ItemForm["kind"], { shouldDirty: true }); form.setValue("sectionId", "", { shouldDirty: true }); }}><option value="RAW_MATERIAL">{t.raw}</option><option value="MENU_PRODUCT">{t.menu}</option></select></label>
    {kind === "MENU_PRODUCT" ? <label>{t.section}<select aria-invalid={Boolean(form.formState.errors.sectionId)} {...form.register("sectionId")}><option value="">—</option>{sections.filter((section) => section.isActive).map((section) => <option key={section.id} value={section.id}>{name(section)}</option>)}</select>{form.formState.errors.sectionId ? <small role="alert">{form.formState.errors.sectionId.message}</small> : null}</label> : null}
    <label>{t.base}<select aria-invalid={Boolean(form.formState.errors.baseUnitId)} {...form.register("baseUnitId")} onChange={(event) => { const next = event.target.value; form.setValue("baseUnitId", next, { shouldDirty: true, shouldValidate: true }); if (next && !unitIds.includes(next)) form.setValue("unitIds", [...unitIds, next], { shouldDirty: true, shouldValidate: true }); }}><option value="">—</option>{units.filter((unit) => unit.isActive).map((unit) => <option key={unit.id} value={unit.id}>{name(unit)}</option>)}</select>{form.formState.errors.baseUnitId ? <small role="alert">{form.formState.errors.baseUnitId.message}</small> : null}</label>
    {kind === "MENU_PRODUCT" ? <label>{t.sale}<input inputMode="decimal" aria-invalid={Boolean(form.formState.errors.salePrice)} {...form.register("salePrice")} />{form.formState.errors.salePrice ? <small role="alert">{form.formState.errors.salePrice.message}</small> : null}</label> : null}
    <fieldset><legend>{t.units}</legend>{units.filter((unit) => unit.isActive).map((unit) => <label key={unit.id}><input type="checkbox" checked={unitIds.includes(unit.id)} onChange={() => toggleUnit(unit.id)} /> {name(unit)}</label>)}{form.formState.errors.unitIds ? <small role="alert">{form.formState.errors.unitIds.message}</small> : null}</fieldset>
  </form></BaseerFormDialog>;
}
