import { lazy, Suspense, useCallback, useEffect, useState } from 'react';

import { presentBaseerApiError } from './baseer-api-error';
import { BaseerButton } from './baseer-button';
import { BaseerCard } from './baseer-card';
import { DailySalesSignIn } from './daily-sales-sign-in';
import { activeSession, api, requestId, type ActiveSession } from './daily-sales-client';
import { formatDate, formatMoney } from './number-format';
import type { AssetRegistrationForm } from './operations-asset-register-dialog';

type Language = 'ar' | 'en';
type QueueItem = { documentId: string; documentNumber: string; kind: 'PURCHASE' | 'EXPENSE'; businessDate: string; grossAmount: string; supplierNameAr: string | null; supplierNameEn: string | null; supplierInvoiceNumber: string | null; supplierInvoiceDate: string | null; assetCount: number };
type Asset = { id: string; sourceDocumentId: string; nameAr: string; nameEn: string | null; serialNumber: string | null; location: string | null; supplierNameSnapshot: string | null; invoiceNumberSnapshot: string | null; invoiceDateSnapshot: string | null; acquisitionAmount: string; warrantyProvider: string | null; warrantyTerms: string | null; warrantyStartsAt: string | null; warrantyEndsAt: string | null; status: 'ACTIVE' | 'ARCHIVED'; lines: Array<{ id: string; description: string; serialNumber: string | null; warrantyEndsAt: string | null }> };
type Workspace = { queue: QueueItem[]; assets: Asset[] };
const LazyOperationsAssetRegisterDialog = lazy(() => import('./operations-asset-register-dialog').then((module) => ({ default: module.OperationsAssetRegisterDialog })));

export function OperationsAssetsWarrantyWorkspace({ language }: { language: Language }) {
  const ar = language === 'ar'; const t = ar ? { title: 'الأصول والضمانات', queue: 'بانتظار التسجيل', assets: 'سجل الأصول', register: 'تسجيل أصل', emptyQueue: 'لا توجد مستندات معلّمة للمتابعة.', emptyAssets: 'لا توجد أصول مسجلة.', name: 'اسم الأصل', serial: 'الرقم التسلسلي', location: 'الموقع', provider: 'مزود الضمان', start: 'بداية الضمان', end: 'نهاية الضمان', terms: 'شروط الضمان', lines: 'بنود الضمان', save: 'حفظ السجل', archive: 'أرشفة', cancel: 'إلغاء', source: 'المستند المصدر', amount: 'قيمة الشراء المرجعية', saved: 'تم تسجيل الأصل.', fail: 'تعذر تنفيذ العملية.', active: 'نشط', archived: 'مؤرشف' } : { title: 'Assets & warranties', queue: 'Awaiting registration', assets: 'Asset register', register: 'Register asset', emptyQueue: 'No documents are marked for follow-up.', emptyAssets: 'No assets are registered.', name: 'Asset name', serial: 'Serial number', location: 'Location', provider: 'Warranty provider', start: 'Warranty start', end: 'Warranty end', terms: 'Warranty terms', lines: 'Warranty items', save: 'Save record', archive: 'Archive', cancel: 'Cancel', source: 'Source document', amount: 'Reference purchase amount', saved: 'Asset registered.', fail: 'The operation could not be completed.', active: 'Active', archived: 'Archived' };
  const [session, setSession] = useState<ActiveSession | null>(activeSession()); const [data, setData] = useState<Workspace | null>(null); const [target, setTarget] = useState<QueueItem | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { const current = activeSession(); setSession(current); if (!current) return; try { setData(await api<Workspace>(current, '/operations/assets-warranty')); } catch (error) { setMessage(presentBaseerApiError(error, language, t.fail)); } }, [language, t.fail]);
  useEffect(() => { void load(); }, [load]); if (!session) return <DailySalesSignIn language={language} />;
  const submit = async (form: AssetRegistrationForm) => { if (!target || busy) return; const lines = form.lines.split('\n').map((description) => description.trim()).filter(Boolean).map((description) => ({ description })); setBusy(true); setMessage(null); try { await api(session, '/operations/assets-warranty', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sourceDocumentId: target.documentId, nameAr: form.nameAr, ...(form.nameEn.trim() ? { nameEn: form.nameEn } : {}), ...(form.serialNumber.trim() ? { serialNumber: form.serialNumber } : {}), ...(form.location.trim() ? { location: form.location } : {}), ...(form.warrantyProvider.trim() ? { warrantyProvider: form.warrantyProvider } : {}), ...(form.warrantyTerms.trim() ? { warrantyTerms: form.warrantyTerms } : {}), ...(form.warrantyStartsAt ? { warrantyStartsAt: form.warrantyStartsAt } : {}), ...(form.warrantyEndsAt ? { warrantyEndsAt: form.warrantyEndsAt } : {}), ...(lines.length ? { lines } : {}), idempotencyKey: requestId() }) }); setTarget(null); setMessage(t.saved); await load(); } catch (error) { setMessage(presentBaseerApiError(error, language, t.fail)); } finally { setBusy(false); } };
  const archive = async (asset: Asset) => { if (busy) return; setBusy(true); try { await api(session, '/operations/assets-warranty/archive', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ assetId: asset.id, idempotencyKey: requestId() }) }); await load(); } catch (error) { setMessage(presentBaseerApiError(error, language, t.fail)); } finally { setBusy(false); } };
  return <section className="daily-sales-workspace" dir={ar ? 'rtl' : 'ltr'}><header className="administration-section-heading"><div><p className="eyebrow">Operations</p></div><BaseerButton type="button" variant="secondary" onClick={() => void load()} disabled={busy}>{ar ? 'تحديث' : 'Refresh'}</BaseerButton></header>{message ? <p className="daily-sales-message">{message}</p> : null}<BaseerCard><h3>{t.queue}</h3>{data?.queue.length ? <div className="administration-list">{data.queue.map((item) => <article key={item.documentId}><strong dir="ltr">{item.documentNumber}</strong><span>{item.supplierNameAr ?? '—'} · <bdi dir="ltr">{formatDate(item.businessDate, language)}</bdi> · <bdi dir="ltr">{formatMoney(item.grossAmount, 'SAR', language)}</bdi></span><BaseerButton type="button" onClick={() => setTarget(item)}>{t.register}</BaseerButton></article>)}</div> : <p>{t.emptyQueue}</p>}</BaseerCard><BaseerCard><h3>{t.assets}</h3>{data?.assets.length ? <div className="administration-list">{data.assets.map((asset) => <article key={asset.id}><strong>{ar ? asset.nameAr : asset.nameEn ?? asset.nameAr}</strong><span>{t.source}: <bdi dir="ltr">{asset.invoiceNumberSnapshot ?? asset.sourceDocumentId}</bdi> · {t.amount}: <bdi dir="ltr">{formatMoney(asset.acquisitionAmount, 'SAR', language)}</bdi></span><span><bdi dir="ltr">{asset.serialNumber ?? '—'}</bdi> · {asset.location ?? '—'} · <bdi dir="ltr">{formatDate(asset.warrantyEndsAt, language)}</bdi></span><span>{asset.status === 'ACTIVE' ? t.active : t.archived}</span>{asset.status === 'ACTIVE' ? <BaseerButton type="button" variant="secondary" onClick={() => void archive(asset)}>{t.archive}</BaseerButton> : null}</article>)}</div> : <p>{t.emptyAssets}</p>}</BaseerCard><Suspense fallback={null}><LazyOperationsAssetRegisterDialog open={target !== null} language={language} busy={busy} sourceDocumentNumber={target?.documentNumber ?? ''} onClose={() => setTarget(null)} onSubmit={submit} /></Suspense></section>;
}
