import { useCallback, useEffect, useState } from "react";

import { presentBaseerApiError } from "./baseer-api-error";
import { BaseerButton } from "./baseer-button";
import { BaseerCard } from "./baseer-card";
import { BaseerFilterBar } from "./baseer-filter-bar";
import { BaseerPeriodFilter, defaultBaseerPeriodRange, type BaseerPeriodRange } from "./baseer-period-filter";
import { DataTable, type DataTableColumn } from "./data-table";
import { DailySalesSignIn } from "./daily-sales-sign-in";
import { activeSession, api, type ActiveSession } from "./daily-sales-client";

type Language = "ar" | "en";
type MaterialRow = { rawMaterialItemId: string; materialNameAr: string; materialNameEn: string | null; unitId: string; unitNameAr: string; unitNameEn: string | null; quantity: string; amount: string; weightedActualUnitPrice: string };
type MaterialsReport = { totals: { materialCount: number; quantity: string; amount: string }; materials: MaterialRow[] };
type CustodyMonth = { month: string; openingBalance: string; funding: string; purchases: string; returns: string; reversals: string; closingBalance: string };
type CustodyReport = { representativeName: string | null; months: CustodyMonth[] };

export function OperationsReportsWorkspace({ language }: { language: Language }) {
  const ar = language === "ar";
  const t = ar ? { title: "تقارير المشتريات والعهدة", description: "تعرض هذه التقارير الشراء الفعلي وحركات العهدة فقط؛ لا تدخل خطط الطلبات في الأرقام.", refresh: "تحديث", materials: "المواد المستلمة", material: "المادة", unit: "الوحدة", quantity: "الكمية", amount: "القيمة الفعلية", average: "متوسط السعر الفعلي", materialCount: "عدد المواد", totalQuantity: "إجمالي الكمية", totalAmount: "إجمالي القيمة", custody: "كشف عهدة المندوب الشهري", representative: "المندوب", month: "الشهر", opening: "الرصيد الافتتاحي", funding: "العهدة المسلّمة", purchases: "المشتريات الفعلية", returns: "المرتجع", reversals: "تصحيحات", closing: "الرصيد الختامي", failed: "تعذر تحميل التقرير.", noData: "لا توجد حركات ضمن الفترة." } : { title: "Purchasing & custody reports", description: "These reports use actual purchases and custody movements only; purchase plans are excluded.", refresh: "Refresh", materials: "Received materials", material: "Material", unit: "Unit", quantity: "Quantity", amount: "Actual value", average: "Actual unit average", materialCount: "Materials", totalQuantity: "Total quantity", totalAmount: "Total value", custody: "Monthly representative custody", representative: "Representative", month: "Month", opening: "Opening balance", funding: "Funding", purchases: "Actual purchases", returns: "Returns", reversals: "Corrections", closing: "Closing balance", failed: "Could not load the report.", noData: "No movements in this period." };
  const [session, setSession] = useState<ActiveSession | null>(activeSession()); const [period, setPeriod] = useState<BaseerPeriodRange>(defaultBaseerPeriodRange()); const [materials, setMaterials] = useState<MaterialsReport | null>(null); const [custody, setCustody] = useState<CustodyReport | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { const current = activeSession(); setSession(current); if (!current) return; setBusy(true); setMessage(null); try { const query = new URLSearchParams({ from: period.from, to: period.to }); const [materialData, custodyData] = await Promise.all([api<MaterialsReport>(current, `/operations/reports/materials-received?${query}`), api<CustodyReport>(current, `/operations/reports/custody-monthly?${query}`)]); setMaterials(materialData); setCustody(custodyData); } catch (error) { setMessage(presentBaseerApiError(error, language, t.failed)); } finally { setBusy(false); } }, [language, period, t.failed]);
  useEffect(() => { void load(); }, [load]);
  if (!session) return <DailySalesSignIn language={language} />;
  const materialColumns: readonly DataTableColumn<MaterialRow>[] = [{ id: "material", header: t.material, cell: (row) => ar ? row.materialNameAr : row.materialNameEn ?? row.materialNameAr }, { id: "unit", header: t.unit, cell: (row) => ar ? row.unitNameAr : row.unitNameEn ?? row.unitNameAr }, { id: "quantity", header: t.quantity, numeric: true, cell: (row) => row.quantity }, { id: "average", header: t.average, numeric: true, cell: (row) => row.weightedActualUnitPrice }, { id: "amount", header: t.amount, numeric: true, cell: (row) => row.amount }];
  const custodyColumns: readonly DataTableColumn<CustodyMonth>[] = [{ id: "month", header: t.month, cell: (row) => row.month }, { id: "opening", header: t.opening, numeric: true, cell: (row) => row.openingBalance }, { id: "funding", header: t.funding, numeric: true, cell: (row) => row.funding }, { id: "purchases", header: t.purchases, numeric: true, cell: (row) => row.purchases }, { id: "returns", header: t.returns, numeric: true, cell: (row) => row.returns }, { id: "reversals", header: t.reversals, numeric: true, cell: (row) => row.reversals }, { id: "closing", header: t.closing, numeric: true, cell: (row) => row.closingBalance }];
  return <section className="daily-sales-workspace" dir={ar ? "rtl" : "ltr"}><header className="administration-section-heading"><div><p className="eyebrow">Operations</p><h3>{t.title}</h3><p>{t.description}</p></div><BaseerButton type="button" variant="secondary" disabled={busy} onClick={() => void load()}>{t.refresh}</BaseerButton></header><BaseerFilterBar language={language} controls={<BaseerPeriodFilter language={language} value={period} onChange={setPeriod} presets={["MONTH", "QUARTER", "YEAR", "RANGE"]} allowNonContiguousMonths={false} />} />{message ? <p className="daily-sales-message error">{message}</p> : null}<BaseerCard><h3>{t.materials}</h3>{materials ? <><div className="baseer-card-grid"><BaseerCard><strong>{t.materialCount}</strong><p>{materials.totals.materialCount}</p></BaseerCard><BaseerCard><strong>{t.totalQuantity}</strong><p>{materials.totals.quantity}</p></BaseerCard><BaseerCard><strong>{t.totalAmount}</strong><p>{materials.totals.amount}</p></BaseerCard></div>{materials.materials.length ? <DataTable ariaLabel={t.materials} caption={t.materials} rows={materials.materials} rowKey={(row) => `${row.rawMaterialItemId}-${row.unitId}`} columns={materialColumns} /> : <p>{t.noData}</p>}</> : null}</BaseerCard><BaseerCard><h3>{t.custody}</h3><p>{t.representative}: <strong>{custody?.representativeName ?? "—"}</strong></p>{custody?.months.length ? <DataTable ariaLabel={t.custody} caption={t.custody} rows={custody.months} rowKey={(row) => row.month} columns={custodyColumns} /> : <p>{t.noData}</p>}</BaseerCard></section>;
}
