import { useCallback, useEffect, useMemo, useState } from "react";

import { BaseerButton } from "./baseer-button";
import { BaseerCard } from "./baseer-card";
import { BaseerDatePicker } from "./baseer-date-picker";
import { OutflowBatchEntryTable } from "./outflow-batch-entry-table";
import { formatMoney } from "./number-format";
import { presentBaseerApiError } from "./baseer-api-error";
import { DailySalesSignIn } from "./daily-sales-sign-in";
import { activeSession, api, requestId, type ActiveSession } from "./daily-sales-client";
import { displayName } from "./baseer-localization";
import { financeText } from "./finance-copy";
import { useDialogFocusTrap } from "./use-dialog-focus-trap";

type Configuration = { profile: { vatAccountingEnabled: boolean; vatRateBasisPoints: number } | null; vaults: Array<{ id: string; nameAr: string; nameEn: string; type: "CASH" | "BANK" | "APP"; status: "ACTIVE" | "ARCHIVED"; isPaymentDestination: boolean }>; categories: Array<{ id: string; nameAr: string; nameEn: string; kind: "PURCHASE" | "EXPENSE"; status: "ACTIVE"; isPosting?: boolean }>; suppliers: Array<{ id: string; nameAr: string; nameEn: string | null; status: "ACTIVE"; categoryId: string | null }> };
type Document = { id: string; documentNumber: string; kind: "PURCHASE" | "EXPENSE"; settlementKind: "PAID" | "PAYABLE"; status: "POSTED" | "CANCELLED"; businessDate: string; grossAmount: string; batchNumber: string | null; supplierNameAr: string | null; supplierNameEn: string | null; categoryNameAr: string; categoryNameEn: string };
type CreditWorkspace = { companyId: string; asOfBusinessDate: string; openSupplierCount: number; openInvoiceCount: number; originalAmount: string; paidAmount: string; remainingAmount: string; suppliers: Array<{ supplierId: string; supplierNameAr: string; supplierNameEn: string | null; invoiceCount: number; originalAmount: string; paidAmount: string; remainingAmount: string; dues: Array<{ id: string; documentNumber: string; kind: "PURCHASE" | "EXPENSE"; businessDate: string; dueDate: string | null; categoryNameAr: string | null; categoryNameEn: string | null; originalAmount: string; paidAmount: string; remainingAmount: string }> }> };
type BatchRow = { id: string; kind: "PURCHASE" | "EXPENSE"; settlementKind: "PAID" | "PAYABLE"; categoryId: string; supplierId: string; invoiceNumber: string; missingReason: string; supplierInvoiceDate: string; grossAmount: string; isTaxable: boolean; vaultId: string; notes: string };

const newRow = (): BatchRow => ({ id: requestId(), kind: "PURCHASE", settlementKind: "PAID", categoryId: "", supplierId: "", invoiceNumber: "", missingReason: "", supplierInvoiceDate: "", grossAmount: "", isTaxable: true, vaultId: "", notes: "" });
const initialRows = () => Array.from({ length: 3 }, newRow);
const rowHasValue = (row: BatchRow) => Boolean(row.categoryId || row.supplierId || row.invoiceNumber || row.missingReason || row.supplierInvoiceDate || row.grossAmount || row.vaultId || row.notes);

export function PurchaseExpenseWorkspace({ language }: { language: "ar" | "en" }) {
  const text = financeText(language);
  const [session, setSession] = useState<ActiveSession | null>(activeSession);
  const [configuration, setConfiguration] = useState<Configuration | null>(null);
  const [documents, setDocuments] = useState<Document[]>([]);
  const [credit, setCredit] = useState<CreditWorkspace | null>(null);
  const [tab, setTab] = useState<"entry" | "credit">("entry");
  const [businessDate, setBusinessDate] = useState("");
  const [lastReceipt, setLastReceipt] = useState<{ grossAmount: string; netAmount: string; vatAmount: string; documentCount: number } | null>(null);
  const [batchNotes, setBatchNotes] = useState("");
  const [rows, setRows] = useState<BatchRow[]>(initialRows);
  const [message, setMessage] = useState<{ kind: "idle" | "success" | "error"; text: string }>({ kind: "idle", text: "" });
  const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { const current = activeSession(); setSession(current); if (!current) return; const [nextConfiguration, nextDocuments] = await Promise.all([api<Configuration>(current, "/finance/configuration"), api<{ documents: Document[] }>(current, "/finance/purchase-expense-documents")]); setConfiguration(nextConfiguration); setDocuments(nextDocuments.documents); }, []);
  const loadCredit = useCallback(async () => { const current = activeSession(); if (!current) return; const snapshot = await api<CreditWorkspace>(current, "/finance/purchase-expense-documents/credit-workspace"); setCredit(snapshot); setBusinessDate((currentDate) => currentDate || snapshot.asOfBusinessDate.slice(0, 10)); }, []);
  useEffect(() => { void load().catch((error) => setMessage({ kind: "error", text: presentBaseerApiError(error, language, text.loadingPurchaseData) })); }, [language, load, text.loadingPurchaseData]);
  useEffect(() => { if (tab === "credit") void loadCredit().catch((error) => setMessage({ kind: "error", text: presentBaseerApiError(error, language, text.credit) })); }, [language, loadCredit, tab, text.credit]);

  const categories = useMemo(() => configuration?.categories.filter((item) => item.status === "ACTIVE" && item.isPosting !== false) ?? [], [configuration]);
  const suppliers = useMemo(() => configuration?.suppliers.filter((item) => item.status === "ACTIVE") ?? [], [configuration]);
  const paymentVaults = useMemo(() => configuration?.vaults.filter((item) => item.status === "ACTIVE" && item.isPaymentDestination) ?? [], [configuration]);
  const enteredRows = useMemo(() => rows.filter(rowHasValue), [rows]);
  const change = <K extends keyof BatchRow>(rowId: string, key: K, value: BatchRow[K]) => setRows((current) => current.map((row) => row.id !== rowId ? row : key === "kind" ? { ...row, kind: value as BatchRow["kind"], categoryId: "" } : { ...row, [key]: value }));
  const chooseSupplier = (rowId: string, supplierId: string) => setRows((current) => current.map((row) => { if (row.id !== rowId) return row; const supplier = suppliers.find((item) => item.id === supplierId); const categoryId = supplier?.categoryId && categories.some((category) => category.id === supplier.categoryId && category.kind === row.kind) ? supplier.categoryId : row.categoryId; return { ...row, supplierId, categoryId }; }));
  const remove = (rowId: string) => setRows((current) => current.length === 1 ? current : current.filter((row) => row.id !== rowId));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const current = activeSession(); if (!current || saving) return; if (!businessDate) { setMessage({ kind: "error", text: text.selectDate }); return; } if (!enteredRows.length) { setMessage({ kind: "error", text: text.atLeastOneRow }); return; } for (const [index, row] of enteredRows.entries()) { if (!row.categoryId || !row.grossAmount || !Number.isFinite(Number(row.grossAmount)) || Number(row.grossAmount) <= 0 || (!row.invoiceNumber.trim() && !row.missingReason.trim()) || (row.invoiceNumber.trim() && row.missingReason.trim()) || (row.settlementKind === "PAYABLE" && !row.supplierId) || (row.settlementKind === "PAID" && !row.vaultId)) { setMessage({ kind: "error", text: text.invoiceValidation(index + 1) }); return; } } setSaving(true); setMessage({ kind: "idle", text: "" }); try { const receipt = await api<{ documentCount: number; grossAmount: string; netAmount: string; vatAmount: string }>(current, "/finance/purchase-expense-documents/batch", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ businessDate, ...(batchNotes.trim() ? { notes: batchNotes.trim() } : {}), items: enteredRows.map((row) => ({ kind: row.kind, settlementKind: row.settlementKind, categoryId: row.categoryId, ...(row.supplierId ? { supplierId: row.supplierId } : {}), ...(row.invoiceNumber.trim() ? { supplierInvoiceNumber: row.invoiceNumber.trim() } : { supplierInvoiceMissingReason: row.missingReason.trim() }), ...(row.supplierInvoiceDate ? { supplierInvoiceDate: row.supplierInvoiceDate } : {}), grossAmount: row.grossAmount, isTaxable: row.isTaxable, allocations: row.settlementKind === "PAID" ? [{ vaultId: row.vaultId, grossAmount: row.grossAmount }] : [], ...(row.notes.trim() ? { notes: row.notes.trim() } : {}) })), idempotencyKey: requestId() }) }); setRows(initialRows()); setBatchNotes(""); setLastReceipt(receipt); setMessage({ kind: "success", text: text.batchSaved(receipt.documentCount) }); await Promise.all([load(), loadCredit()]); } catch (error) { setMessage({ kind: "error", text: presentBaseerApiError(error, language, text.saveBatch) }); } finally { setSaving(false); } };
  if (!session) return <DailySalesSignIn language={language} />;
  return <section className="daily-sales-workspace purchase-batch-workspace" aria-label={text.purchases}>
    <header className="administration-section-heading"><div><h3>{text.batchEntry}</h3></div></header>
    <nav className="baseer-section-tabs" aria-label={text.purchases} role="tablist"><BaseerButton id="purchase-tab-entry" role="tab" aria-selected={tab === "entry"} aria-controls="purchase-panel-entry" type="button" variant={tab === "entry" ? "primary" : "secondary"} onClick={() => setTab("entry")}>{text.entry}</BaseerButton><BaseerButton id="purchase-tab-credit" role="tab" aria-selected={tab === "credit"} aria-controls="purchase-panel-credit" type="button" variant={tab === "credit" ? "primary" : "secondary"} onClick={() => setTab("credit")}>{text.credit}</BaseerButton></nav>
    {message.kind !== "idle" && <p className={`daily-sales-message ${message.kind}`}>{message.text}</p>}
    {!configuration ? <BaseerCard><p>{text.loadingCompanySetup}</p></BaseerCard> : <div id={`purchase-panel-${tab}`} role="tabpanel" aria-labelledby={`purchase-tab-${tab}`}>{tab === "entry" ? <>
      {!configuration.profile && <p className="daily-sales-message error">{text.setupRequired}</p>}
      <BaseerCard><form onSubmit={(event) => void submit(event)} className="purchase-batch-form"><div className="purchase-batch-header"><label>{text.batchDate}<BaseerDatePicker plain presentation="popover" language={language} label={text.batchDate} value={businessDate} onChange={setBusinessDate} /></label><label>{text.batchNotes}<input value={batchNotes} placeholder={text.optional} onChange={(event) => setBatchNotes(event.target.value)} /></label></div><OutflowBatchEntryTable language={language} text={text} ariaLabel={text.batchEntry} rows={rows} categories={categories} suppliers={suppliers} vaults={paymentVaults} vatEnabled={Boolean(configuration.profile?.vatAccountingEnabled)} vatRateBasisPoints={configuration.profile?.vatRateBasisPoints ?? 1500} allowedKinds={["PURCHASE", "EXPENSE"]} maxInvoiceDate={businessDate || undefined} onChange={change} onSupplierChange={chooseSupplier} onRemove={remove} /><footer className="purchase-batch-footer"><div className="purchase-batch-total">{lastReceipt ? <><span>{text.net} <strong>{formatMoney(lastReceipt.netAmount)}</strong></span><span>{text.tax} <strong>{formatMoney(lastReceipt.vatAmount)}</strong></span><span>{text.lastBatchTotal} <strong>{formatMoney(lastReceipt.grossAmount)}</strong></span></> : null}</div><div><BaseerButton aria-label={text.addRow} type="button" variant="icon" onClick={() => setRows((current) => [...current, newRow()])}>+</BaseerButton><BaseerButton variant="primary" disabled={saving || !configuration.profile}>{saving ? text.saving : text.saveInvoiceCount(enteredRows.length)}</BaseerButton></div></footer></form></BaseerCard>
      <BaseerCard><div className="administration-section-heading"><div><h3>{text.invoiceHistory}</h3></div><span>{documents.length} {text.invoiceCount}</span></div>{documents.length ? <div className="administration-list">{documents.map((document) => <article key={document.id}><strong>{document.documentNumber}</strong><span>{document.kind === "PURCHASE" ? text.purchaseInvoice : text.expenseInvoice} · {document.businessDate.slice(0, 10)}</span><span>{displayName(language, { nameAr: document.categoryNameAr, nameEn: document.categoryNameEn })}{document.supplierNameAr ? ` · ${displayName(language, { nameAr: document.supplierNameAr, nameEn: document.supplierNameEn })}` : ""}</span><strong>{formatMoney(document.grossAmount)}</strong></article>)}</div> : <p className="empty-results">{text.noInvoices}</p>}</BaseerCard>
    </> : <CreditPanel credit={credit} language={language} vaults={paymentVaults} reload={loadCredit} />}</div>}
  </section>;
}

function CreditPanel({ credit, language, vaults, reload }: { credit: CreditWorkspace | null; language: "ar" | "en"; vaults: ReadonlyArray<{ id: string; nameAr: string; nameEn: string }>; reload: () => Promise<void> }) {
  const text = financeText(language); const [target, setTarget] = useState<CreditWorkspace["suppliers"][number]["dues"][number] | null>(null); const [message, setMessage] = useState("");
  if (!credit) return <BaseerCard><p>{text.loading}</p></BaseerCard>;
  return <><div className="baseer-card-grid" aria-label={text.credit}><BaseerCard><p>{text.openCreditSuppliers}</p><strong>{credit.openSupplierCount}</strong></BaseerCard><BaseerCard><p>{text.openCreditInvoices}</p><strong>{credit.openInvoiceCount}</strong></BaseerCard><BaseerCard><p>{text.creditOutstanding}</p><strong>{formatMoney(credit.remainingAmount)}</strong></BaseerCard></div>{message ? <p className="daily-sales-message success">{message}</p> : null}<BaseerCard><div className="administration-section-heading"><div><h3>{text.credit}</h3><p>{text.creditAsOf} {credit.asOfBusinessDate.slice(0, 10)}</p></div></div>{credit.suppliers.length ? credit.suppliers.map((supplier) => <details key={supplier.supplierId}><summary><strong>{displayName(language, { nameAr: supplier.supplierNameAr, nameEn: supplier.supplierNameEn })}</strong> · {supplier.invoiceCount} · {formatMoney(supplier.remainingAmount)}</summary><div className="administration-list">{supplier.dues.map((due) => <article key={due.id}><strong>{due.documentNumber}</strong><span>{due.kind === "PURCHASE" ? text.purchaseInvoice : text.expenseInvoice} · {due.businessDate.slice(0, 10)}</span><span>{displayName(language, { nameAr: due.categoryNameAr ?? "—", nameEn: due.categoryNameEn ?? "—" })}</span><strong>{formatMoney(due.remainingAmount)}</strong><BaseerButton type="button" variant="secondary" onClick={() => setTarget(due)}>{text.recordSettlement}</BaseerButton></article>)}</div></details>) : <p className="empty-results">{text.noCreditInvoices}</p>}</BaseerCard><CreditPaymentDialog language={language} due={target} vaults={vaults} defaultBusinessDate={credit.asOfBusinessDate.slice(0, 10)} onClose={() => setTarget(null)} onSaved={async () => { setTarget(null); setMessage(text.repaymentSaved); await reload(); }} /></>;
}

function CreditPaymentDialog({ language, due, vaults, defaultBusinessDate, onClose, onSaved }: { language: "ar" | "en"; due: CreditWorkspace["suppliers"][number]["dues"][number] | null; vaults: ReadonlyArray<{ id: string; nameAr: string; nameEn: string }>; defaultBusinessDate: string; onClose: () => void; onSaved: () => Promise<void> }) {
  const text = financeText(language); const [vaultId, setVaultId] = useState(""); const [amount, setAmount] = useState(""); const [businessDate, setBusinessDate] = useState(defaultBusinessDate); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const dialogRef = useDialogFocusTrap({ open: due !== null, saving, onClose });
  useEffect(() => { if (due) { setVaultId(""); setAmount(due.remainingAmount); setBusinessDate(defaultBusinessDate); setError(""); } }, [defaultBusinessDate, due]);
  if (!due) return null;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const current = activeSession(); if (!current || saving) return; if (!vaultId || !amount || Number(amount) <= 0 || Number(amount) > Number(due.remainingAmount) || !businessDate) { setError(text.paymentValidation(1)); return; } setSaving(true); setError(""); try { await api(current, "/finance/supplier-dues/payments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ dueId: due.id, vaultId, businessDate, amount, idempotencyKey: requestId() }) }); await onSaved(); } catch (requestError) { setError(presentBaseerApiError(requestError, language, text.recordSettlement)); } finally { setSaving(false); } };
  return <div className="daily-sales-dialog-backdrop" role="presentation" onMouseDown={() => !saving && onClose()}><section ref={dialogRef} className="daily-sales-dialog" role="dialog" aria-modal="true" aria-labelledby="credit-payment-dialog-title" onMouseDown={(event) => event.stopPropagation()}><header className="daily-sales-dialog__header"><div><h3 id="credit-payment-dialog-title">{text.recordSettlement}</h3><p>{due.documentNumber} · {formatMoney(due.remainingAmount)}</p></div><button className="dialog-icon-button" type="button" aria-label={text.cancel} disabled={saving} onClick={onClose}>×</button></header><form className="daily-sales-dialog__form" onSubmit={(event) => void submit(event)}><label>{text.paymentDate}<BaseerDatePicker language={language} label={text.paymentDate} max={defaultBusinessDate} value={businessDate} onChange={setBusinessDate} /></label><label>{text.paymentChannel}<select required value={vaultId} onChange={(event) => setVaultId(event.target.value)}><option value="">{text.selectVault}</option>{vaults.map((vault) => <option key={vault.id} value={vault.id}>{displayName(language, vault)}</option>)}</select></label><label>{text.repaymentAmount} (SAR)<input required inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} /></label>{error ? <p className="daily-sales-message error">{error}</p> : null}<footer className="daily-sales-dialog__actions"><BaseerButton variant="primary" disabled={saving}>{saving ? text.saving : text.recordSettlement}</BaseerButton></footer></form></section></div>;
}
