import { BaseerButton } from "./baseer-button";
import { BaseerDialog } from "./baseer-dialog";
import { BaseerMoneyInput } from "./baseer-form-fields";
import { BaseerStaticSelect } from "./baseer-static-select";
import { formatMoney } from "./number-format";
import "./vat-simulation-workspace.css";

type Language = "ar" | "en";
type Draft = { salesTaxableAmount: string; outputVatAmount: string; purchasesTaxableAmount: string; inputVatAmount: string; paymentTarget: string | null };

export function VatSimulationEditorDialog({ open, language, title, quarter, year, selected, busy, draft, net, additionalPurchases, totalRequiredPurchases, copied, labels, onClose, onQuarterChange, onImport, onTaxableChange, onTargetChange, onCopy, onDelete, onSave }: { open: boolean; language: Language; title: string; quarter: number; year: number; selected: boolean; busy: "import" | "save" | "delete" | null; draft: Draft; net: number; additionalPurchases: number; totalRequiredPurchases: number; copied: boolean; labels: { add: string; delete: string; deleting: string; save: string; saving: string; inputs: string; quarter: string; import: string; importing: string; sales: string; purchases: string; beforeVat: string; target: string; results: string; vatAmount: string; net: string; additionalPurchases: string; totalPurchases: string; copyValue: string; copied: string }; onClose: () => void; onQuarterChange: (value: number) => void; onImport: () => void; onTaxableChange: (field: "salesTaxableAmount" | "purchasesTaxableAmount", value: string) => void; onTargetChange: (value: string) => void; onCopy: () => void; onDelete: () => void; onSave: () => void }) {
  return <BaseerDialog open={open} title={title} language={language} busy={busy !== null} onClose={onClose} size="wide" className="vat-simulation-workspace__dialog" footer={<>{selected ? <BaseerButton type="button" variant="danger" disabled={busy !== null} onClick={onDelete}>{busy === "delete" ? labels.deleting : labels.delete}</BaseerButton> : null}<BaseerButton type="button" variant="primary" disabled={busy !== null} onClick={onSave}>{busy === "save" ? labels.saving : labels.save}</BaseerButton></>}>
    <section className="vat-simulation-workspace__editor"><header className="vat-simulation-workspace__editor-header"><h3>Q{quarter} · {year}</h3></header><div className="vat-simulation-workspace__editor-columns"><section className="vat-simulation-workspace__input-panel"><header><h4>{labels.inputs}</h4><div className="vat-simulation-workspace__editor-actions"><label><span>{labels.quarter}</span><BaseerStaticSelect label={labels.quarter} value={quarter} onChange={(event) => onQuarterChange(Number(event.target.value))}>{([1, 2, 3, 4] as const).map((item) => <option key={item} value={item}>Q{item}</option>)}</BaseerStaticSelect></label><BaseerButton type="button" variant="secondary" className="vat-simulation-workspace__import-button" disabled={busy !== null} onClick={onImport}>{busy === "import" ? labels.importing : labels.import}</BaseerButton></div></header><div className="vat-simulation-workspace__form"><div className="vat-simulation-workspace__amount-grid"><label className="vat-simulation-workspace__amount-card"><span>{labels.sales}</span><small>{labels.beforeVat}</small><BaseerMoneyInput value={draft.salesTaxableAmount} onValueChange={(value) => onTaxableChange("salesTaxableAmount", value)} /></label><label className="vat-simulation-workspace__amount-card"><span>{labels.purchases}</span><small>{labels.beforeVat}</small><BaseerMoneyInput value={draft.purchasesTaxableAmount} onValueChange={(value) => onTaxableChange("purchasesTaxableAmount", value)} /></label></div><label className="vat-simulation-workspace__target"><span>{labels.target}</span><BaseerMoneyInput value={draft.paymentTarget ?? "0"} onValueChange={onTargetChange} /></label></div></section><section className="vat-simulation-workspace__result-panel"><header><h4>{labels.results}</h4></header><dl className="vat-simulation-workspace__result-list"><div><dt>{labels.sales} · {labels.vatAmount}</dt><dd dir="ltr">{formatMoney(Number(draft.outputVatAmount) || 0, "SAR", language)}</dd></div><div><dt>{labels.purchases} · {labels.vatAmount}</dt><dd dir="ltr">{formatMoney(Number(draft.inputVatAmount) || 0, "SAR", language)}</dd></div><div><dt>{labels.net}</dt><dd dir="ltr">{formatMoney(net, "SAR", language)}</dd></div></dl><dl className="vat-simulation-workspace__summary"><div className="vat-simulation-workspace__summary-primary"><dt>{labels.additionalPurchases}</dt><dd dir="ltr">{formatMoney(additionalPurchases, "SAR", language)}</dd></div><div><dt>{labels.totalPurchases}</dt><dd dir="ltr"><button type="button" className="vat-simulation-workspace__copy-value" onClick={onCopy} aria-label={labels.copyValue}><span>{formatMoney(totalRequiredPurchases, "SAR", language)}</span><small>{copied ? labels.copied : labels.copyValue}</small></button></dd></div></dl></section></div></section>
  </BaseerDialog>;
}
