export type AdministrationPermissionDefinition = Readonly<{
  code: string;
  module: string;
  nameAr: string;
  nameEn: string;
  risk: "standard" | "sensitive";
}>;

/**
 * The server owns this catalogue. Administrators can compose roles from these
 * stable capabilities, but they cannot invent permission keys in the UI.
 */
export const ADMINISTRATION_PERMISSION_CATALOG: readonly AdministrationPermissionDefinition[] = [
  { code: "administration.companies.read", module: "administration", nameAr: "عرض الشركات", nameEn: "View companies", risk: "standard" },
  { code: "administration.companies.manage", module: "administration", nameAr: "إدارة الشركات وإعداداتها", nameEn: "Manage companies and settings", risk: "sensitive" },
  { code: "administration.users.read", module: "administration", nameAr: "عرض المستخدمين", nameEn: "View users", risk: "standard" },
  { code: "administration.users.manage", module: "administration", nameAr: "إدارة المستخدمين", nameEn: "Manage users", risk: "sensitive" },
  { code: "administration.roles.read", module: "administration", nameAr: "عرض الأدوار والصلاحيات", nameEn: "View roles and permissions", risk: "standard" },
  { code: "administration.roles.manage", module: "administration", nameAr: "إدارة الأدوار والصلاحيات", nameEn: "Manage roles and permissions", risk: "sensitive" },

  { code: "backup.read", module: "backup", nameAr: "عرض حالة النسخ والاستعادة", nameEn: "View backup and recovery status", risk: "standard" },
  { code: "backup.create", module: "backup", nameAr: "إنشاء أرشيف شركة", nameEn: "Create company archive", risk: "sensitive" },
  { code: "backup.download", module: "backup", nameAr: "تنزيل أرشيفات بصير", nameEn: "Download Baseer archives", risk: "sensitive" },
  { code: "backup.schedule.manage", module: "backup", nameAr: "إدارة جدولة النسخ", nameEn: "Manage backup schedules", risk: "sensitive" },
  { code: "backup.restore.request", module: "backup", nameAr: "طلب استعادة شركة", nameEn: "Request company recovery", risk: "sensitive" },
  { code: "backup.restore.approve", module: "backup", nameAr: "اعتماد استعادة شركة", nameEn: "Approve company recovery", risk: "sensitive" },
  { code: "backup.restore.execute", module: "backup", nameAr: "تنفيذ استعادة شركة", nameEn: "Execute company recovery", risk: "sensitive" },
  { code: "backup.audit.view", module: "backup", nameAr: "مراجعة تدقيق النسخ", nameEn: "Review backup audit", risk: "standard" },

  { code: "finance.setup.write", module: "finance", nameAr: "تهيئة المالية للشركة", nameEn: "Initialize company finance", risk: "sensitive" },
  { code: "finance.configuration.read", module: "finance", nameAr: "عرض إعدادات المالية", nameEn: "View finance configuration", risk: "standard" },
  { code: "finance.periods.write", module: "finance", nameAr: "إدارة الفترات المالية", nameEn: "Manage fiscal periods", risk: "sensitive" },
  { code: "finance.vaults.read", module: "finance", nameAr: "عرض الخزائن", nameEn: "View vaults", risk: "standard" },
  { code: "finance.vaults.write", module: "finance", nameAr: "إدارة الخزائن", nameEn: "Manage vaults", risk: "sensitive" },
  { code: "finance.vaults.transfer", module: "finance", nameAr: "تحويل بين الخزائن", nameEn: "Transfer between vaults", risk: "sensitive" },
  { code: "finance.vaults.cancel", module: "finance", nameAr: "إلغاء تحويلات الخزائن", nameEn: "Cancel vault transfers", risk: "sensitive" },
  { code: "finance.vaults.reconcile", module: "finance", nameAr: "مطابقة البنوك والجرد النقدي", nameEn: "Reconcile banks and count cash", risk: "sensitive" },
  { code: "finance.foundation.write", module: "finance", nameAr: "نسخ وإعداد البيانات المالية الأساسية", nameEn: "Copy and initialize finance master data", risk: "sensitive" },
  { code: "finance.suppliers.read", module: "finance", nameAr: "عرض الموردين", nameEn: "View suppliers", risk: "standard" },
  { code: "finance.suppliers.write", module: "finance", nameAr: "إدارة الموردين", nameEn: "Manage suppliers", risk: "sensitive" },
  { code: "finance.categories.write", module: "finance", nameAr: "إدارة التصنيفات المالية", nameEn: "Manage financial categories", risk: "sensitive" },
  { code: "finance.supplier_dues.read", module: "finance", nameAr: "عرض ذمم الموردين", nameEn: "View supplier dues", risk: "standard" },
  { code: "finance.supplier_dues.write", module: "finance", nameAr: "إنشاء وسداد وعكس ذمم الموردين", nameEn: "Create, pay, and reverse supplier dues", risk: "sensitive" },
  { code: "finance.loans.read", module: "finance", nameAr: "عرض القروض والالتزامات", nameEn: "View inclusive loans and liabilities", risk: "standard" },
  { code: "finance.loans.write", module: "finance", nameAr: "إدارة القروض وسدادها", nameEn: "Manage inclusive loans and repayments", risk: "sensitive" },
  { code: "finance.purchase_expense.read", module: "finance", nameAr: "عرض مستندات المشتريات والمصروفات", nameEn: "View purchase and expense documents", risk: "standard" },
  { code: "finance.purchase_expense.create", module: "finance", nameAr: "إدخال مستندات المشتريات والمصروفات", nameEn: "Create purchase and expense documents", risk: "sensitive" },
  { code: "finance.purchase_expense.correct", module: "finance", nameAr: "تعديل مستندات المشتريات والمصروفات", nameEn: "Correct purchase and expense documents", risk: "sensitive" },
  { code: "finance.purchase_expense.cancel", module: "finance", nameAr: "إلغاء مستندات المشتريات والمصروفات", nameEn: "Cancel purchase and expense documents", risk: "sensitive" },
  { code: "reports.read", module: "reports", nameAr: "عرض التقارير", nameEn: "View reports", risk: "standard" },
  { code: "reports.cash_performance.activate", module: "reports", nameAr: "اعتماد بداية تغطية تقرير الأداء النقدي", nameEn: "Activate cash-performance report coverage", risk: "sensitive" },

  { code: "decision.metrics.read", module: "decision-intelligence", nameAr: "عرض القراءات الرسمية لمركز القرار", nameEn: "View official decision reads", risk: "standard" },
  { code: "decision.alerts.read", module: "decision-intelligence", nameAr: "عرض تنبيهات مركز القرار", nameEn: "View decision alerts", risk: "standard" },
  { code: "decision.alerts.manage", module: "decision-intelligence", nameAr: "إقرار وإغلاق تنبيهات مركز القرار", nameEn: "Manage decision alerts", risk: "sensitive" },
  { code: "decision.context.read", module: "decision-intelligence", nameAr: "عرض المناسبات والسياق", nameEn: "View decision context", risk: "standard" },
  { code: "decision.context.company.manage", module: "decision-intelligence", nameAr: "إدارة أحداث سياق الشركة", nameEn: "Manage company context events", risk: "sensitive" },
  { code: "decision.context.global.manage", module: "decision-intelligence", nameAr: "إدارة مصادر المناسبات العامة", nameEn: "Manage global context sources", risk: "sensitive" },
  { code: "decision.feedback.write", module: "decision-intelligence", nameAr: "تقديم تغذية راجعة للتحليل", nameEn: "Submit decision feedback", risk: "standard" },
  { code: "decision.policy.manage", module: "decision-intelligence", nameAr: "إدارة سياسات المقارنة والتنبيه", nameEn: "Manage decision policies", risk: "sensitive" },

  { code: "marketing.insights.read", module: "marketing", nameAr: "عرض الأداء التسويقي", nameEn: "View marketing performance", risk: "standard" },
  { code: "marketing.campaign.write", module: "marketing", nameAr: "إدارة سجل الحملات", nameEn: "Manage campaign register", risk: "sensitive" },
  { code: "marketing.reputation.policy.manage", module: "marketing", nameAr: "إدارة سياسة ردود السمعة", nameEn: "Manage reputation reply policy", risk: "sensitive" },
  { code: "marketing.google-connection.manage", module: "marketing", nameAr: "طلب وإدارة ربط Google للشركة", nameEn: "Request and manage the company Google connection", risk: "sensitive" },
  { code: "marketing.google-ads.reporting.read", module: "marketing", nameAr: "عرض تقارير Google Ads", nameEn: "View Google Ads reporting", risk: "standard" },
  { code: "marketing.google-business.profile.read", module: "marketing", nameAr: "عرض ملف Google Business", nameEn: "View Google Business Profile", risk: "standard" },
  { code: "marketing.google-business.publisher", module: "marketing", nameAr: "ناشر Google Business", nameEn: "Google Business Publisher", risk: "sensitive" },

  // This is deliberately absent from every company role template. The API
  // additionally requires a live tenant-owner assignment, so a company user
  // can neither discover nor query the central owner mailbox.
  { code: "inbound_evidence.owner_access", module: "inbound-evidence", nameAr: "الوصول إلى البريد والأدلة المركزي", nameEn: "Access the central inbound evidence hub", risk: "sensitive" },

  { code: "hr.employees.read", module: "hr", nameAr: "عرض الموظفين وملفاتهم", nameEn: "View employees and their files", risk: "standard" },
  { code: "hr.employees.write", module: "hr", nameAr: "إدارة الموظفين وخدماتهم", nameEn: "Manage employees and employee services", risk: "sensitive" },
  { code: "hr.advances.read", module: "hr", nameAr: "عرض سلف الموظفين", nameEn: "View employee advances", risk: "standard" },
  { code: "hr.advances.issue", module: "hr", nameAr: "إصدار سلف الموظفين", nameEn: "Issue employee advances", risk: "sensitive" },
  { code: "hr.advances.settle", module: "hr", nameAr: "تسوية سلف الموظفين", nameEn: "Settle employee advances", risk: "sensitive" },
  { code: "hr.advances.reverse", module: "hr", nameAr: "عكس سلف الموظفين", nameEn: "Reverse employee advances", risk: "sensitive" },
  { code: "hr.deductions.read", module: "hr", nameAr: "عرض خصومات الموظفين", nameEn: "View employee deductions", risk: "standard" },
  { code: "hr.deductions.manage", module: "hr", nameAr: "إدارة خصومات الموظفين", nameEn: "Manage employee deductions", risk: "sensitive" },
  { code: "hr.leaves.read", module: "hr", nameAr: "عرض إجازات الموظفين", nameEn: "View employee leaves", risk: "standard" },
  { code: "hr.leaves.manage", module: "hr", nameAr: "إدارة إجازات وعودة الموظفين", nameEn: "Manage employee leaves and returns", risk: "sensitive" },
  { code: "hr.payroll.read", module: "hr", nameAr: "عرض مسيرات الرواتب", nameEn: "View payroll runs", risk: "standard" },
  { code: "hr.payroll.create", module: "hr", nameAr: "إعداد مسيرات الرواتب والرواتب المعتمدة", nameEn: "Prepare payroll runs and compensation", risk: "sensitive" },
  { code: "hr.compensation.backdate", module: "hr", nameAr: "تسجيل الموظفين والرواتب بأثر رجعي", nameEn: "Backdate employee and salary records", risk: "sensitive" },
  { code: "hr.payroll.approve", module: "hr", nameAr: "اعتماد مسيرات الرواتب", nameEn: "Approve payroll runs", risk: "sensitive" },
  { code: "hr.payroll.pay", module: "hr", nameAr: "سداد مسيرات الرواتب", nameEn: "Pay payroll runs", risk: "sensitive" },
  { code: "hr.payroll.reverse", module: "hr", nameAr: "عكس مسيرات الرواتب", nameEn: "Reverse payroll runs", risk: "sensitive" },
  { code: "hr.employee_documents.read", module: "hr", nameAr: "عرض مستندات الموظفين", nameEn: "View employee documents", risk: "standard" },
  { code: "hr.employee_documents.write", module: "hr", nameAr: "إضافة وتعديل وإلغاء مستندات الموظفين", nameEn: "Manage employee documents", risk: "sensitive" },
  { code: "hr.employee_documents.revoke", module: "hr", nameAr: "إلغاء مستندات الموظفين", nameEn: "Revoke employee documents", risk: "sensitive" },
  { code: "hr.employee_documents.download", module: "hr", nameAr: "تنزيل مرفقات مستندات الموظفين", nameEn: "Download employee document attachments", risk: "sensitive" },
  { code: "hr.employee_letters.read", module: "hr", nameAr: "عرض خطابات الموظفين", nameEn: "View employee letters", risk: "standard" },
  { code: "hr.employee_letters.issue", module: "hr", nameAr: "إصدار خطابات الموظفين", nameEn: "Issue employee letters", risk: "sensitive" },
  { code: "hr.employee_letters.revoke", module: "hr", nameAr: "إلغاء خطابات الموظفين", nameEn: "Revoke employee letters", risk: "sensitive" },
  { code: "hr.final_settlements.read", module: "hr", nameAr: "عرض تسويات نهاية الخدمة", nameEn: "View final settlements", risk: "standard" },
  { code: "hr.final_settlements.create", module: "hr", nameAr: "إعداد تسويات نهاية الخدمة", nameEn: "Prepare final settlements", risk: "sensitive" },
  { code: "hr.final_settlements.verify", module: "hr", nameAr: "التحقق من أدلة تسويات نهاية الخدمة", nameEn: "Verify final-settlement evidence", risk: "sensitive" },
  { code: "hr.final_settlements.approve", module: "hr", nameAr: "اعتماد تسويات نهاية الخدمة", nameEn: "Approve final settlements", risk: "sensitive" },
  { code: "hr.final_settlements.pay", module: "hr", nameAr: "سداد تسويات نهاية الخدمة", nameEn: "Pay final settlements", risk: "sensitive" },
  { code: "hr.final_settlements.reverse", module: "hr", nameAr: "عكس تسويات نهاية الخدمة", nameEn: "Reverse final settlements", risk: "sensitive" },
  { code: "attendance.manage", module: "hr", nameAr: "إدارة الحضور والانصراف", nameEn: "Manage attendance and timekeeping", risk: "sensitive" },

  { code: "finance.daily_sales.read", module: "operations", nameAr: "عرض سجل المبيعات", nameEn: "View sales register", risk: "standard" },
  { code: "finance.daily_sales.history.read_all", module: "operations", nameAr: "عرض كامل سجل المبيعات", nameEn: "View full sales history", risk: "standard" },
  { code: "finance.daily_sales.create", module: "operations", nameAr: "إدخال تقفيل المبيعات", nameEn: "Enter sales closings", risk: "sensitive" },
  { code: "finance.daily_sales.correct", module: "operations", nameAr: "تصحيح تقفيل المبيعات", nameEn: "Correct sales closings", risk: "sensitive" },
  { code: "finance.daily_sales.reverse", module: "operations", nameAr: "عكس تقفيل المبيعات", nameEn: "Reverse sales closings", risk: "sensitive" },
  { code: "finance.operational_calendar.manage", module: "operations", nameAr: "توثيق أيام بدون عمل", nameEn: "Manage non-operating days", risk: "sensitive" },
  { code: "operations.catalog.read", module: "operations", nameAr: "عرض مواد ومنتجات العمليات", nameEn: "View operations materials and products", risk: "standard" },
  { code: "operations.catalog.manage", module: "operations", nameAr: "إدارة مواد ومنتجات العمليات", nameEn: "Manage operations materials and products", risk: "sensitive" },
  { code: "operations.conversions.publish", module: "operations", nameAr: "نشر تحويلات وحدات المواد", nameEn: "Publish material unit conversions", risk: "sensitive" },
  { code: "operations.recipe.read", module: "operations", nameAr: "عرض الرسبي وتكلفة التشغيل", nameEn: "View recipes and operational cost", risk: "standard" },
  { code: "operations.recipe.publish", module: "operations", nameAr: "نشر إصدارات الرسبي", nameEn: "Publish recipe versions", risk: "sensitive" },
  { code: "operations.inventory.read", module: "operations", nameAr: "عرض مخزون المواد وتكلفته", nameEn: "View material inventory and cost", risk: "sensitive" },
  { code: "operations.purchase_request.read", module: "operations", nameAr: "عرض طلبات المشتريات والعهدة", nameEn: "View purchase requests and custody", risk: "standard" },
  { code: "operations.purchase_request.create", module: "operations", nameAr: "إنشاء طلبات مشتريات", nameEn: "Create purchase requests", risk: "sensitive" },
  { code: "operations.purchase_request.receive", module: "operations", nameAr: "استلام طلبات المشتريات", nameEn: "Receive purchase requests", risk: "sensitive" },
  { code: "operations.purchase_request.cancel", module: "operations", nameAr: "إلغاء طلبات المشتريات المعلقة", nameEn: "Cancel pending purchase requests", risk: "sensitive" },
  { code: "operations.purchase_receipt.reverse", module: "operations", nameAr: "عكس استلام المشتريات", nameEn: "Reverse posted purchase receipts", risk: "sensitive" },
  { code: "operations.custody.read", module: "operations", nameAr: "عرض رصيد عهدة المندوب", nameEn: "View purchasing representative custody", risk: "sensitive" },
  { code: "operations.custody.return", module: "operations", nameAr: "تسجيل مرتجع عهدة", nameEn: "Record custody return", risk: "sensitive" },
  { code: "operations.internal_registration.create", module: "operations", nameAr: "تسجيل الإنتاج الداخلي بلا أسعار", nameEn: "Record internal output without prices", risk: "standard" },
  { code: "operations.internal_registration.read", module: "operations", nameAr: "عرض تقارير التسجيل الداخلي", nameEn: "View internal registration reports", risk: "standard" },
  { code: "operations.assets.read", module: "operations", nameAr: "عرض الأصول والضمانات", nameEn: "View assets and warranties", risk: "standard" },
  { code: "operations.assets.manage", module: "operations", nameAr: "إدارة الأصول والضمانات", nameEn: "Manage assets and warranties", risk: "sensitive" },
  { code: "operations.whatsapp_invoice_monitoring.read", module: "operations", nameAr: "عرض وارد فواتير واتساب", nameEn: "View WhatsApp invoice monitoring", risk: "standard" },
  { code: "operations.whatsapp_invoice_monitoring.review", module: "operations", nameAr: "مراجعة وتصحيح وارد فواتير واتساب", nameEn: "Review and correct WhatsApp invoice monitoring", risk: "sensitive" },
  // Compatibility only for roles created before the narrower daily-sales split.
  { code: "finance.daily_sales.write", module: "operations", nameAr: "إدخال وتقفيل مبيعات قديم", nameEn: "Legacy sales-closing write", risk: "sensitive" },

  { code: "platform.files.read", module: "platform", nameAr: "عرض الملفات", nameEn: "View files", risk: "standard" },
  { code: "platform.files.write", module: "platform", nameAr: "إضافة ملفات", nameEn: "Add files", risk: "sensitive" },
  { code: "platform.business-date.read", module: "platform", nameAr: "عرض تاريخ العمل", nameEn: "View business date", risk: "standard" },
  { code: "platform.observability.read", module: "platform", nameAr: "عرض حالة التشغيل", nameEn: "View operational health", risk: "standard" },
  { code: "platform.output.preview", module: "platform", nameAr: "معاينة الطباعة", nameEn: "Preview output", risk: "standard" },
  { code: "platform.output.export", module: "platform", nameAr: "تصدير التقارير", nameEn: "Export output", risk: "sensitive" },

  { code: "platform.ai.use", module: "ai", nameAr: "استخدام بصيرة ضمن المهارات المتاحة", nameEn: "Use Basira within available skills", risk: "standard" },
  { code: "platform.ai.configuration.read", module: "ai", nameAr: "عرض إعداد مزود الذكاء", nameEn: "View AI provider configuration", risk: "sensitive" },
  { code: "platform.ai.configuration.write", module: "ai", nameAr: "تعديل إعداد مزود الذكاء", nameEn: "Change AI provider configuration", risk: "sensitive" },
  { code: "platform.ai.provider.configure", module: "ai", nameAr: "تهيئة مزود الذكاء", nameEn: "Configure AI provider", risk: "sensitive" },
  { code: "platform.ai.identity.read", module: "ai", nameAr: "عرض هوية الذكاء للشركة", nameEn: "View company AI identity", risk: "standard" },
  { code: "platform.ai.identity.write", module: "ai", nameAr: "تعديل هوية الذكاء للشركة", nameEn: "Change company AI identity", risk: "sensitive" },
  { code: "platform.ai.identity.create_version", module: "ai", nameAr: "إنشاء إصدار هوية الذكاء للشركة", nameEn: "Create company AI identity version", risk: "sensitive" },
  { code: "platform.ai.context.read", module: "ai", nameAr: "عرض سياق بصيرة المعتمد للشركة", nameEn: "View approved company Basira context", risk: "standard" },
  { code: "platform.ai.context.write", module: "ai", nameAr: "إدارة سياق بصيرة المنظم للشركة", nameEn: "Manage structured company Basira context", risk: "sensitive" },
  { code: "platform.ai.skills.read", module: "ai", nameAr: "عرض كتالوج مهارات بصيرة وحالتها", nameEn: "View Basira skill catalogue and status", risk: "standard" },
  { code: "platform.ai.skills.activate", module: "ai", nameAr: "اعتماد أو إيقاف مهارات بصيرة للشركة", nameEn: "Approve or suspend company Basira skills", risk: "sensitive" },
  { code: "platform.ai.receipts.read", module: "ai", nameAr: "عرض إيصالات تنفيذ بصيرة", nameEn: "View Basira execution receipts", risk: "sensitive" },
  { code: "platform.ai.evaluations.write", module: "ai", nameAr: "تقييم مخرجات بصيرة", nameEn: "Evaluate Basira outputs", risk: "standard" },
  { code: "platform.ai.evaluations.read", module: "ai", nameAr: "عرض تقييمات بصيرة", nameEn: "View Basira evaluations", risk: "sensitive" },
  { code: "platform.ai.system_identity.read", module: "ai", nameAr: "عرض هوية بصيرة المركزية", nameEn: "View central Baseerah identity", risk: "standard" },
  { code: "platform.ai.system_identity.write", module: "ai", nameAr: "تعديل هوية بصيرة المركزية", nameEn: "Change central Baseerah identity", risk: "sensitive" },
  { code: "platform.ai.system_identity.create_version", module: "ai", nameAr: "إنشاء إصدار هوية بصيرة المركزية", nameEn: "Create central Baseerah identity version", risk: "sensitive" },
  { code: "decision.human_insights.read", module: "decision", nameAr: "عرض التفسيرات المحفوظة والقرارات البشرية", nameEn: "View saved interpretations and human decisions", risk: "standard" },
  { code: "decision.human_insights.write", module: "decision", nameAr: "تسجيل واعتماد قرارات بشرية على التفسير", nameEn: "Record and approve human interpretation decisions", risk: "sensitive" },
] as const;

const DAILY_SALES_MANAGE = [
  "finance.daily_sales.create",
  "finance.daily_sales.correct",
  "finance.daily_sales.reverse",
  "finance.operational_calendar.manage",
] as const;

const COMPANY_MANAGER_PERMISSIONS = [
  // A company manager may create and take custody of the encrypted archive for
  // their own company. Recovery approval/execution stay deliberately split.
  "backup.read",
  "backup.create",
  "backup.download",
  "backup.schedule.manage",
  "backup.restore.request",
  "platform.ai.use",
  "platform.ai.context.read",
  "platform.ai.context.write",
  "platform.ai.skills.read",
  "platform.ai.skills.activate",
  "platform.ai.receipts.read",
  "platform.ai.evaluations.read",
  "platform.ai.evaluations.write",
  "decision.human_insights.read",
  "decision.human_insights.write",
  "finance.setup.write",
  "finance.configuration.read",
  "reports.read",
  "reports.cash_performance.activate",
  "decision.metrics.read",
  "decision.alerts.read",
  "decision.alerts.manage",
  "decision.context.read",
  "decision.context.company.manage",
  "decision.feedback.write",
  "marketing.insights.read",
  "marketing.campaign.write",
  "marketing.reputation.policy.manage",
  "marketing.google-connection.manage",
  "finance.periods.write",
  "finance.vaults.read",
  "finance.vaults.write",
  "finance.vaults.transfer",
  "finance.vaults.cancel",
  "finance.vaults.reconcile",
  "finance.foundation.write",
  "finance.suppliers.read",
  "finance.suppliers.write",
  "finance.categories.write",
  "finance.supplier_dues.read",
  "finance.supplier_dues.write",
  "finance.loans.read",
  "finance.loans.write",
  "finance.purchase_expense.read",
  "finance.purchase_expense.create",
  "finance.purchase_expense.correct",
  "finance.purchase_expense.cancel",
  "hr.employees.read",
  "hr.employees.write",
  "hr.advances.read",
  "hr.advances.issue",
  "hr.advances.settle",
  "hr.advances.reverse",
  "hr.deductions.read",
  "hr.deductions.manage",
  "hr.leaves.read",
  "hr.leaves.manage",
  "hr.payroll.read",
  "hr.payroll.create",
  "hr.compensation.backdate",
  "hr.payroll.approve",
  "hr.payroll.pay",
  "hr.payroll.reverse",
  "hr.employee_documents.read",
  "hr.employee_documents.write",
  "hr.employee_documents.revoke",
  "hr.employee_documents.download",
  "hr.employee_letters.read",
  "hr.employee_letters.issue",
  "hr.employee_letters.revoke",
  "hr.final_settlements.read",
  "hr.final_settlements.create",
  "hr.final_settlements.verify",
  "hr.final_settlements.approve",
  "hr.final_settlements.pay",
  "hr.final_settlements.reverse",
  "attendance.manage",
  "finance.daily_sales.read",
  "finance.daily_sales.history.read_all",
  ...DAILY_SALES_MANAGE,
  "operations.catalog.read",
  "operations.catalog.manage",
  "operations.conversions.publish",
  "operations.recipe.read",
  "operations.recipe.publish",
  "operations.inventory.read",
  "operations.purchase_request.read",
  "operations.purchase_request.create",
  "operations.purchase_request.receive",
  "operations.purchase_request.cancel",
  "operations.purchase_receipt.reverse",
  "operations.custody.read",
  "operations.custody.return",
  "operations.internal_registration.create",
  "operations.internal_registration.read",
  "operations.assets.read",
  "operations.assets.manage",
  "operations.whatsapp_invoice_monitoring.read",
  "operations.whatsapp_invoice_monitoring.review",
  "platform.files.read",
  "platform.files.write",
  "platform.business-date.read",
  "platform.output.preview",
  "platform.output.export",
] as const;

export const SYSTEM_ROLE_TEMPLATES = [
  { code: "BASEER_COMPANY_MANAGER", nameAr: "مدير الشركة", nameEn: "Company manager", permissions: COMPANY_MANAGER_PERMISSIONS },
  { code: "BASEER_BACKUP_AUDITOR", nameAr: "مراجع النسخ والاستعادة", nameEn: "Backup and recovery auditor", permissions: ["backup.read", "backup.audit.view"] },
  { code: "BASEER_FINANCE_ACCOUNTANT", nameAr: "محاسب", nameEn: "Accountant", permissions: ["platform.ai.use", "finance.configuration.read", "reports.read", "finance.vaults.read", "finance.vaults.transfer", "finance.vaults.cancel", "finance.vaults.reconcile", "finance.suppliers.read", "finance.supplier_dues.read", "finance.supplier_dues.write", "finance.loans.read", "finance.loans.write", "finance.purchase_expense.read", "finance.purchase_expense.create", "finance.purchase_expense.correct", "finance.purchase_expense.cancel", "finance.daily_sales.read", "finance.daily_sales.history.read_all", "operations.whatsapp_invoice_monitoring.read", "operations.whatsapp_invoice_monitoring.review", ...DAILY_SALES_MANAGE, "platform.files.read", "platform.files.write", "platform.business-date.read", "platform.output.preview", "platform.output.export"] },
  { code: "BASEER_SALES_SUPERVISOR", nameAr: "مشرف مبيعات", nameEn: "Sales supervisor", permissions: ["platform.ai.use", "finance.daily_sales.read", "finance.daily_sales.history.read_all", ...DAILY_SALES_MANAGE, "platform.business-date.read", "platform.output.preview"] },
  { code: "BASEER_CASHIER", nameAr: "كاشير", nameEn: "Cashier", permissions: ["platform.ai.use", "finance.daily_sales.read", "finance.daily_sales.create", "platform.business-date.read"] },
  { code: "BASEER_OPERATIONS_ENTRY", nameAr: "موظف تسجيل داخلي", nameEn: "Internal registration employee", permissions: ["operations.internal_registration.create"] },
  { code: "BASEER_READER", nameAr: "قارئ", nameEn: "Reader", permissions: ["platform.ai.use", "finance.daily_sales.read", "finance.configuration.read", "reports.read", "finance.suppliers.read", "finance.supplier_dues.read", "finance.loans.read", "finance.purchase_expense.read", "operations.whatsapp_invoice_monitoring.read", "platform.business-date.read"] },
] as const;

export function permissionCodesAreKnown(codes: readonly string[]): boolean {
  const known = new Set(ADMINISTRATION_PERMISSION_CATALOG.map((item) => item.code));
  return codes.length > 0 && codes.every((code) => known.has(code));
}
