import { createAdministrationCompanyRequestSchema, assignAdministrationMembershipRequestSchema, createAdministrationRoleRequestSchema, createAdministrationUserRequestSchema, administrationOverviewReceiptSchema, companyIdSchema, resetAdministrationUserPasswordRequestSchema, updateAdministrationCompanyRequestSchema, updateAdministrationUserStatusRequestSchema, userIdSchema, withdrawAdministrationMembershipRequestSchema } from "@baseer-erp/contracts";
import { BadRequestException, Body, Controller, Delete, Get, Headers, HttpCode, Param, Post, Put, UnauthorizedException } from "@nestjs/common";
import { AdministrationService } from "./administration.service.js";
import { TenantAdministrationContextService } from "./tenant-administration-context.service.js";

@Controller("administration")
export class AdministrationController {
  constructor(private readonly administration: AdministrationService, private readonly context: TenantAdministrationContextService) {}
  @Get("overview") async overview(@Headers("authorization") authorization?: string) { return administrationOverviewReceiptSchema.parse(await this.administration.overview(await this.context.authorize(this.accessToken(authorization)))); }
  @Post("companies") @HttpCode(201) async createCompany(@Body() body: unknown, @Headers("authorization") authorization?: string) { const request = createAdministrationCompanyRequestSchema.safeParse(body); if (!request.success) throw new BadRequestException("Invalid administration company request."); return this.administration.createCompany(await this.context.authorize(this.accessToken(authorization)), request.data); }
  @Post("roles") @HttpCode(201) async createRole(@Body() body: unknown, @Headers("authorization") authorization?: string) { const request = createAdministrationRoleRequestSchema.safeParse(body); if (!request.success) throw new BadRequestException("Invalid administration role request."); return this.administration.createRole(await this.context.authorize(this.accessToken(authorization)), request.data); }
  @Post("users") @HttpCode(201) async createUser(@Body() body: unknown, @Headers("authorization") authorization?: string) { const request = createAdministrationUserRequestSchema.safeParse(body); if (!request.success) throw new BadRequestException("Invalid administration user request."); return this.administration.createUser(await this.context.authorize(this.accessToken(authorization)), request.data); }
  @Put("memberships") async assignMembership(@Body() body: unknown, @Headers("authorization") authorization?: string) { const request = assignAdministrationMembershipRequestSchema.safeParse(body); if (!request.success) throw new BadRequestException("Invalid administration membership request."); return this.administration.assignMembership(await this.context.authorize(this.accessToken(authorization)), request.data); }
  @Put("companies/:companyId/settings") async updateCompany(@Param("companyId") companyId: string, @Body() body: unknown, @Headers("authorization") authorization?: string) { const id = companyIdSchema.safeParse(companyId); const request = updateAdministrationCompanyRequestSchema.safeParse(body); if (!id.success || !request.success) throw new BadRequestException("Invalid company settings request."); return this.administration.updateCompany(await this.context.authorize(this.accessToken(authorization)), id.data, request.data); }
@Put("users/:userId/status") async updateUserStatus(@Param("userId") userId: string, @Body() body: unknown, @Headers("authorization") authorization?: string) { const id = userIdSchema.safeParse(userId); const request = updateAdministrationUserStatusRequestSchema.safeParse(body); if (!id.success || !request.success) throw new BadRequestException("Invalid user status request."); return this.administration.updateUserStatus(await this.context.authorize(this.accessToken(authorization)), id.data, request.data); }
  @Post("users/:userId/reset-password") @HttpCode(200) async resetUserPassword(@Param("userId") userId: string, @Body() body: unknown, @Headers("authorization") authorization?: string) { const id = userIdSchema.safeParse(userId); const request = resetAdministrationUserPasswordRequestSchema.safeParse(body); if (!id.success || !request.success) throw new BadRequestException("Invalid password reset request."); return this.administration.resetUserPassword(await this.context.authorize(this.accessToken(authorization)), id.data, request.data); }
  @Delete("memberships/:userId/:companyId") async withdrawMembership(@Param("userId") userId: string, @Param("companyId") companyId: string, @Body() body: unknown, @Headers("authorization") authorization?: string) { const user = userIdSchema.safeParse(userId); const company = companyIdSchema.safeParse(companyId); const request = withdrawAdministrationMembershipRequestSchema.safeParse(body); if (!user.success || !company.success || !request.success) throw new BadRequestException("Invalid membership withdrawal request."); return this.administration.withdrawMembership(await this.context.authorize(this.accessToken(authorization)), user.data, company.data, request.data); }
  private accessToken(value?: string): string { const match = /^Bearer\s+(.+)$/i.exec(value ?? ""); if (!match?.[1]) throw new UnauthorizedException("Invalid authentication credentials."); return match[1]; }
}
