import { createAdministrationCompanyRequestSchema, assignAdministrationMembershipRequestSchema, createAdministrationRoleRequestSchema, createAdministrationUserRequestSchema, administrationOverviewReceiptSchema, companyIdSchema, resetAdministrationUserPasswordRequestSchema, replaceAdministrationUserAccessRequestSchema, updateAdministrationCompanyRequestSchema, updateAdministrationRoleRequestSchema, updateAdministrationUserLoginRequestSchema, updateAdministrationUserDisplayNameRequestSchema, deleteAdministrationRoleRequestSchema, updateAdministrationCompanyStatusRequestSchema, uploadAdministrationCompanyLogoRequestSchema, updateAdministrationUserStatusRequestSchema, userIdSchema, withdrawAdministrationMembershipRequestSchema } from "@baseer-erp/contracts";
import { BadRequestException, Body, Controller, Delete, Get, Headers, HttpCode, Param, Post, Put, Res, UnauthorizedException, UseGuards } from "@nestjs/common";
import { SkipThrottle, Throttle, ThrottlerGuard } from "@nestjs/throttler";
import type { FastifyReply } from "fastify";
import { RouteConfig } from "@nestjs/platform-fastify";
import { AdministrationService } from "./administration.service.js";
import { TenantAdministrationContextService } from "./tenant-administration-context.service.js";

@Controller("administration")
export class AdministrationController {
  constructor(private readonly administration: AdministrationService, private readonly context: TenantAdministrationContextService) {}
  @Get("overview") async overview(@Headers("authorization") authorization?: string) { return administrationOverviewReceiptSchema.parse(await this.administration.overview(await this.context.authorize(this.accessToken(authorization)))); }
  @Post("companies") @HttpCode(201) async createCompany(@Body() body: unknown, @Headers("authorization") authorization?: string) { const request = createAdministrationCompanyRequestSchema.safeParse(body); if (!request.success) throw new BadRequestException("Invalid administration company request."); return this.administration.createCompany(await this.context.authorize(this.accessToken(authorization)), request.data); }
  @Post("roles") @HttpCode(201) async createRole(@Body() body: unknown, @Headers("authorization") authorization?: string) { const request = createAdministrationRoleRequestSchema.safeParse(body); if (!request.success) throw new BadRequestException("Invalid administration role request."); return this.administration.createRole(await this.context.authorize(this.accessToken(authorization)), request.data); }
  @Put("roles/:roleId") async updateRole(@Param("roleId") roleId: string, @Body() body: unknown, @Headers("authorization") authorization?: string) { const id = companyIdSchema.safeParse(roleId); const request = updateAdministrationRoleRequestSchema.safeParse(body); if (!id.success || !request.success) throw new BadRequestException("Invalid administration role update."); return this.administration.updateRole(await this.context.authorize(this.accessToken(authorization)), id.data, request.data); }
  @Delete("roles/:roleId") async deleteRole(@Param("roleId") roleId: string, @Body() body: unknown, @Headers("authorization") authorization?: string) { const id = companyIdSchema.safeParse(roleId); const request = deleteAdministrationRoleRequestSchema.safeParse(body ?? {}); if (!id.success || !request.success) throw new BadRequestException("Invalid administration role deletion."); return this.administration.deleteRole(await this.context.authorize(this.accessToken(authorization)), id.data); }
  @Post("users") @HttpCode(201) async createUser(@Body() body: unknown, @Headers("authorization") authorization?: string) { const request = createAdministrationUserRequestSchema.safeParse(body); if (!request.success) throw new BadRequestException("Invalid administration user request."); return this.administration.createUser(await this.context.authorize(this.accessToken(authorization)), request.data); }
  @Put("memberships") async assignMembership(@Body() body: unknown, @Headers("authorization") authorization?: string) { const request = assignAdministrationMembershipRequestSchema.safeParse(body); if (!request.success) throw new BadRequestException("Invalid administration membership request."); return this.administration.assignMembership(await this.context.authorize(this.accessToken(authorization)), request.data); }
  @Put("users/:userId/access") async replaceUserAccess(@Param("userId") userId: string, @Body() body: unknown, @Headers("authorization") authorization?: string) { const id = userIdSchema.safeParse(userId); const request = replaceAdministrationUserAccessRequestSchema.safeParse(body); if (!id.success || !request.success) throw new BadRequestException("Invalid administration user access request."); return this.administration.replaceUserAccess(await this.context.authorize(this.accessToken(authorization)), id.data, request.data); }
  @Put("users/:userId/login") async updateUserLogin(@Param("userId") userId: string, @Body() body: unknown, @Headers("authorization") authorization?: string) { const id = userIdSchema.safeParse(userId); const request = updateAdministrationUserLoginRequestSchema.safeParse(body); if (!id.success || !request.success) throw new BadRequestException("Invalid administration user login request."); return this.administration.updateUserLogin(await this.context.authorize(this.accessToken(authorization)), id.data, request.data); }
  @Put("users/:userId/display-name") async updateUserDisplayName(@Param("userId") userId: string, @Body() body: unknown, @Headers("authorization") authorization?: string) { const id = userIdSchema.safeParse(userId); const request = updateAdministrationUserDisplayNameRequestSchema.safeParse(body); if (!id.success || !request.success) throw new BadRequestException("Invalid administration user display name request."); return this.administration.updateUserDisplayName(await this.context.authorize(this.accessToken(authorization)), id.data, request.data); }
  @Post("companies/:companyId/logo") @HttpCode(201) @RouteConfig({ bodyLimit: 1024 * 1024 }) @UseGuards(ThrottlerGuard) @SkipThrottle({ authIp: true, authIdentity: true, report: true, output: true }) @Throttle({ fileWrite: { limit: 12, ttl: 60_000, blockDuration: 60_000 } }) async uploadCompanyLogo(@Param("companyId") companyId: string, @Body() body: unknown, @Headers("authorization") authorization?: string) { const id = companyIdSchema.safeParse(companyId); const request = uploadAdministrationCompanyLogoRequestSchema.safeParse(body); if (!id.success || !request.success) throw new BadRequestException("Invalid company logo request."); return this.administration.uploadCompanyLogo(await this.context.authorize(this.accessToken(authorization)), id.data, request.data); }
  @Get("companies/:companyId/logo") async companyLogo(@Param("companyId") companyId: string, @Headers("authorization") authorization: string | undefined, @Res() reply: FastifyReply) { const id = companyIdSchema.safeParse(companyId); if (!id.success) throw new BadRequestException("Invalid company identifier."); const logo = await this.administration.readCompanyLogo(await this.context.authorize(this.accessToken(authorization)), id.data); return reply.header("Cache-Control", "private, max-age=300").type(logo.mimeType).send(logo.bytes); }
  @Put("companies/:companyId/settings") async updateCompany(@Param("companyId") companyId: string, @Body() body: unknown, @Headers("authorization") authorization?: string) { const id = companyIdSchema.safeParse(companyId); const request = updateAdministrationCompanyRequestSchema.safeParse(body); if (!id.success || !request.success) throw new BadRequestException("Invalid company settings request."); return this.administration.updateCompany(await this.context.authorize(this.accessToken(authorization)), id.data, request.data); }
@Put("companies/:companyId/status") async updateCompanyStatus(@Param("companyId") companyId: string, @Body() body: unknown, @Headers("authorization") authorization?: string) { const id = companyIdSchema.safeParse(companyId); const request = updateAdministrationCompanyStatusRequestSchema.safeParse(body); if (!id.success || !request.success) throw new BadRequestException("Invalid company status request."); return this.administration.updateCompanyStatus(await this.context.authorize(this.accessToken(authorization)), id.data, request.data); }
  @Put("users/:userId/status") async updateUserStatus(@Param("userId") userId: string, @Body() body: unknown, @Headers("authorization") authorization?: string) { const id = userIdSchema.safeParse(userId); const request = updateAdministrationUserStatusRequestSchema.safeParse(body); if (!id.success || !request.success) throw new BadRequestException("Invalid user status request."); return this.administration.updateUserStatus(await this.context.authorize(this.accessToken(authorization)), id.data, request.data); }
  @Post("users/:userId/reset-password") @HttpCode(200) async resetUserPassword(@Param("userId") userId: string, @Body() body: unknown, @Headers("authorization") authorization?: string) { const id = userIdSchema.safeParse(userId); const request = resetAdministrationUserPasswordRequestSchema.safeParse(body); if (!id.success || !request.success) throw new BadRequestException("Invalid password reset request."); return this.administration.resetUserPassword(await this.context.authorize(this.accessToken(authorization)), id.data, request.data); }
  @Delete("memberships/:userId/:companyId") async withdrawMembership(@Param("userId") userId: string, @Param("companyId") companyId: string, @Body() body: unknown, @Headers("authorization") authorization?: string) { const user = userIdSchema.safeParse(userId); const company = companyIdSchema.safeParse(companyId); const request = withdrawAdministrationMembershipRequestSchema.safeParse(body); if (!user.success || !company.success || !request.success) throw new BadRequestException("Invalid membership withdrawal request."); return this.administration.withdrawMembership(await this.context.authorize(this.accessToken(authorization)), user.data, company.data, request.data); }
  private accessToken(value?: string): string { const match = /^Bearer\s+(.+)$/i.exec(value ?? ""); if (!match?.[1]) throw new UnauthorizedException("Invalid authentication credentials."); return match[1]; }
}
