import { BadRequestException, Body, Controller, Get, Headers, HttpCode, Param, ParseUUIDPipe, Post, Query, UseGuards } from '@nestjs/common';
import { SkipThrottle, Throttle, ThrottlerGuard } from '@nestjs/throttler';
import { approveAttendanceRosterRequestSchema, archiveAttendanceScheduleTemplateRequestSchema, assignAttendanceEmployeeScheduleRequestSchema, assignAttendanceEmployeesScheduleRequestSchema, attendanceAlertQuerySchema, attendanceAlertsReceiptSchema, attendanceBranchSchema, attendanceCompanySettingsSchema, attendanceCoverageQuerySchema, attendanceCoverageReceiptSchema, attendanceDashboardQuerySchema, attendanceDashboardReceiptSchema, attendanceEffectiveEmployeeScheduleQuerySchema, attendanceEffectiveEmployeeScheduleSchema, attendanceEmployeeComplianceQuerySchema, attendanceEmployeeComplianceReceiptSchema, attendanceEmployeePinDisplayReceiptSchema, attendanceEmployeePortalScopeReceiptSchema, attendanceEmployeePortalSessionReceiptSchema, attendanceEmployeePortalSessionRequestSchema, attendanceEmployeeRecordReceiptSchema, attendanceEmployeeRecordRequestSchema, attendanceEmployeeScheduleListQuerySchema, attendanceEmployeeScheduleListReceiptSchema, attendanceEmployeeScheduleSchema, attendanceOpenSessionsQuerySchema, attendanceOpenSessionsReceiptSchema, attendanceReportQuerySchema, attendanceReportReceiptSchema, attendanceRosterQuerySchema, attendanceRosterReceiptSchema, attendanceScheduleTemplateSchema, attendanceScheduleWorkspaceQuerySchema, attendanceScheduleWorkspaceReceiptSchema, closeAttendanceSessionReceiptSchema, closeAttendanceSessionRequestSchema, configureAttendanceEmployeeScheduleRequestSchema, createAttendanceBranchRequestSchema, createAttendanceScheduleExceptionRequestSchema, createAttendanceScheduleTemplateRequestSchema, createAttendanceScheduleVersionRequestSchema, decideAttendanceScheduleExceptionRequestSchema, saveAttendanceRosterDraftRequestSchema, setAttendanceEmployeePinRequestSchema, setAttendanceEmployeeWeeklyAdjustmentRequestSchema, updateAttendanceBranchRequestSchema, updateAttendanceCompanySettingsRequestSchema, updateAttendanceScheduleTemplateRequestSchema } from '@baseer-erp/contracts';
import { CompanyContextService } from '../company-context/company-context.service.js';
import { AttendanceService } from './attendance.service.js';

const MANAGE = ['attendance.manage'] as const;
@Controller('attendance')
export class AttendanceController {
  constructor(private readonly companyContext: CompanyContextService, private readonly attendance: AttendanceService) {}
  @Get('company-settings') async companySettings(@Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { return attendanceCompanySettingsSchema.parse(await this.attendance.companySettings(await this.authorize(authorization, companyId))); }
  @Post('company-settings') @HttpCode(200) async updateCompanySettings(@Body() body: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = updateAttendanceCompanySettingsRequestSchema.safeParse(body); if (!input.success) throw new BadRequestException('Invalid attendance company settings request.'); return attendanceCompanySettingsSchema.parse(await this.attendance.updateCompanySettings(await this.authorize(authorization, companyId), input.data)); }
  @Get('branches') async list(@Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const context = await this.authorize(authorization, companyId); return { branches: attendanceBranchSchema.array().parse(await this.attendance.listBranches(context)) }; }
  @Post('branches') @HttpCode(201) async create(@Body() body: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = createAttendanceBranchRequestSchema.safeParse(body); if (!input.success) throw new BadRequestException('Invalid attendance branch request.'); return this.attendance.createBranch(await this.authorize(authorization, companyId), input.data); }
  @Post('branches/update') async update(@Body() body: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = updateAttendanceBranchRequestSchema.safeParse(body); if (!input.success) throw new BadRequestException('Invalid attendance branch update.'); return this.attendance.updateBranch(await this.authorize(authorization, companyId), input.data); }
  @Post('employees/pin') async pin(@Body() body: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = setAttendanceEmployeePinRequestSchema.safeParse(body); if (!input.success) throw new BadRequestException('Invalid attendance PIN request.'); return this.attendance.setEmployeePin(await this.authorize(authorization, companyId), input.data); }
  @Get('employees/:employeeId/pin') async employeePin(@Param('employeeId', ParseUUIDPipe) employeeId: string, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { return attendanceEmployeePinDisplayReceiptSchema.parse(await this.attendance.employeePinDisplay(await this.authorize(authorization, companyId), employeeId)); }
  @Get('branches/:branchId/qr') async qr(@Param('branchId', ParseUUIDPipe) branchId: string, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { return this.attendance.issueQr(await this.authorize(authorization, companyId), branchId); }
  @Get('employee-portal-scope') async employeePortalScope(@Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const context = await this.authorize(authorization, companyId); return attendanceEmployeePortalScopeReceiptSchema.parse({ tenantId: context.tenantId, companyId: context.companyId }); }
  @Get('dashboard') async dashboard(@Query() query: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = attendanceDashboardQuerySchema.safeParse(query); if (!input.success) throw new BadRequestException('Invalid attendance dashboard query.'); return attendanceDashboardReceiptSchema.parse(await this.attendance.dashboard(await this.authorize(authorization, companyId), input.data.date)); }
  @Get('report') async report(@Query() query: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = attendanceReportQuerySchema.safeParse(query); if (!input.success || input.data.from > input.data.to) throw new BadRequestException('Invalid attendance report query.'); return attendanceReportReceiptSchema.parse(await this.attendance.report(await this.authorize(authorization, companyId), input.data)); }
  @Get('coverage') async coverage(@Query() query: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = attendanceCoverageQuerySchema.safeParse(query); if (!input.success) throw new BadRequestException('Invalid attendance coverage query.'); return attendanceCoverageReceiptSchema.parse(await this.attendance.coverage(await this.authorize(authorization, companyId), input.data.date)); }
  @Get('roster') async roster(@Query() query: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = attendanceRosterQuerySchema.safeParse(query); if (!input.success) throw new BadRequestException('Invalid attendance roster query.'); return attendanceRosterReceiptSchema.parse(await this.attendance.roster(await this.authorize(authorization, companyId), input.data.weekStart)); }
  @Post('roster/draft') async saveRosterDraft(@Body() body: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = saveAttendanceRosterDraftRequestSchema.safeParse(body); if (!input.success) throw new BadRequestException('Invalid attendance roster draft.'); return attendanceRosterReceiptSchema.parse(await this.attendance.saveRosterDraft(await this.authorize(authorization, companyId), input.data)); }
  @Post('roster/approve') async approveRoster(@Body() body: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = approveAttendanceRosterRequestSchema.safeParse(body); if (!input.success) throw new BadRequestException('Invalid attendance roster approval.'); return attendanceRosterReceiptSchema.parse(await this.attendance.approveRoster(await this.authorize(authorization, companyId), input.data)); }
  @Get('alerts') async alerts(@Query() query: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = attendanceAlertQuerySchema.safeParse(query); if (!input.success) throw new BadRequestException('Invalid attendance alerts query.'); return attendanceAlertsReceiptSchema.parse(await this.attendance.alerts(await this.authorize(authorization, companyId), input.data.date)); }
  @Get('schedule-templates') async scheduleTemplates(@Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { return { templates: attendanceScheduleTemplateSchema.array().parse(await this.attendance.listScheduleTemplates(await this.authorize(authorization, companyId))) }; }
  @Get('schedule-workspace') async scheduleWorkspace(@Query() query: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = attendanceScheduleWorkspaceQuerySchema.safeParse(query); if (!input.success) throw new BadRequestException('Invalid attendance schedule workspace query.'); return attendanceScheduleWorkspaceReceiptSchema.parse(await this.attendance.scheduleWorkspace(await this.authorize(authorization, companyId), input.data.date)); }
  @Post('schedule-templates') @HttpCode(201) async createScheduleTemplate(@Body() body: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = createAttendanceScheduleTemplateRequestSchema.safeParse(body); if (!input.success) throw new BadRequestException('Invalid attendance schedule template request.'); return this.attendance.createScheduleTemplate(await this.authorize(authorization, companyId), input.data); }
  @Post('schedule-templates/update') async updateScheduleTemplate(@Body() body: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = updateAttendanceScheduleTemplateRequestSchema.safeParse(body); if (!input.success) throw new BadRequestException('Invalid attendance schedule template update.'); return this.attendance.updateScheduleTemplate(await this.authorize(authorization, companyId), input.data); }
  @Post('schedule-templates/version') @HttpCode(201) async createScheduleVersion(@Body() body: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = createAttendanceScheduleVersionRequestSchema.safeParse(body); if (!input.success) throw new BadRequestException('Invalid attendance schedule version request.'); return this.attendance.createScheduleVersion(await this.authorize(authorization, companyId), input.data); }
  @Post('schedule-templates/archive') async archiveScheduleTemplate(@Body() body: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = archiveAttendanceScheduleTemplateRequestSchema.safeParse(body); if (!input.success) throw new BadRequestException('Invalid attendance schedule archive request.'); return this.attendance.archiveScheduleTemplate(await this.authorize(authorization, companyId), input.data); }
  @Post('employees/schedule-assignment') @HttpCode(201) async assignSchedule(@Body() body: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = assignAttendanceEmployeeScheduleRequestSchema.safeParse(body); if (!input.success) throw new BadRequestException('Invalid employee schedule assignment request.'); return this.attendance.assignEmployeeSchedule(await this.authorize(authorization, companyId), input.data); }
  @Post('employees/schedule-assignments') @HttpCode(201) async assignSchedules(@Body() body: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = assignAttendanceEmployeesScheduleRequestSchema.safeParse(body); if (!input.success) throw new BadRequestException('Invalid employee schedule assignments request.'); return this.attendance.assignEmployeesSchedule(await this.authorize(authorization, companyId), input.data); }
  @Post('employees/schedule-setup') @HttpCode(201) async configureSchedule(@Body() body: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = configureAttendanceEmployeeScheduleRequestSchema.safeParse(body); if (!input.success) throw new BadRequestException('Invalid employee work schedule setup request.'); return this.attendance.configureEmployeeSchedule(await this.authorize(authorization, companyId), input.data); }
  @Post('employees/weekly-adjustment') @HttpCode(201) async weeklyAdjustment(@Body() body: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = setAttendanceEmployeeWeeklyAdjustmentRequestSchema.safeParse(body); if (!input.success) throw new BadRequestException('Invalid employee weekly adjustment request.'); return this.attendance.setEmployeeWeeklyAdjustment(await this.authorize(authorization, companyId), input.data); }
  @Get('employees/schedules') async employeeSchedules(@Query() query: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = attendanceEmployeeScheduleListQuerySchema.safeParse(query); if (!input.success) throw new BadRequestException('Invalid attendance schedule list query.'); return attendanceEmployeeScheduleListReceiptSchema.parse(await this.attendance.employeeSchedules(await this.authorize(authorization, companyId), input.data)); }
  @Get('employees/:employeeId/schedule') async employeeSchedule(@Param('employeeId', ParseUUIDPipe) employeeId: string, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { return attendanceEmployeeScheduleSchema.parse(await this.attendance.employeeSchedule(await this.authorize(authorization, companyId), employeeId)); }
  @Get('employees/:employeeId/schedule/effective') async effectiveEmployeeSchedule(@Param('employeeId', ParseUUIDPipe) employeeId: string, @Query() query: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = attendanceEffectiveEmployeeScheduleQuerySchema.safeParse(query); if (!input.success) throw new BadRequestException('Invalid effective attendance schedule query.'); return attendanceEffectiveEmployeeScheduleSchema.parse(await this.attendance.effectiveEmployeeSchedule(await this.authorize(authorization, companyId), employeeId, input.data.date)); }
  @Get('employees/:employeeId/compliance') async employeeCompliance(@Param('employeeId', ParseUUIDPipe) employeeId: string, @Query() query: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = attendanceEmployeeComplianceQuerySchema.safeParse(query); if (!input.success) throw new BadRequestException('Invalid attendance compliance query.'); return attendanceEmployeeComplianceReceiptSchema.parse(await this.attendance.employeeCompliance(await this.authorize(authorization, companyId), employeeId, input.data)); }
  @Post('schedule-exceptions') @HttpCode(201) async createScheduleException(@Body() body: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = createAttendanceScheduleExceptionRequestSchema.safeParse(body); if (!input.success) throw new BadRequestException('Invalid attendance schedule exception request.'); return this.attendance.createScheduleException(await this.authorize(authorization, companyId), input.data); }
  @Post('schedule-exceptions/decide') async decideScheduleException(@Body() body: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = decideAttendanceScheduleExceptionRequestSchema.safeParse(body); if (!input.success) throw new BadRequestException('Invalid attendance schedule exception decision.'); return this.attendance.decideScheduleException(await this.authorize(authorization, companyId), input.data); }
  @Post('sessions/close') async closeOpenSession(@Body() body: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = closeAttendanceSessionRequestSchema.safeParse(body); if (!input.success) throw new BadRequestException('Invalid administrative attendance checkout request.'); return closeAttendanceSessionReceiptSchema.parse(await this.attendance.closeOpenSession(await this.authorizeManagerClose(authorization, companyId), input.data)); }
  @Get('sessions/open') async openSessionsForManager(@Query() query: unknown, @Headers('authorization') authorization?: string, @Headers('x-baseer-company-id') companyId?: string) { const input = attendanceOpenSessionsQuerySchema.safeParse(query); if (!input.success) throw new BadRequestException('Invalid open attendance-sessions query.'); return attendanceOpenSessionsReceiptSchema.parse(await this.attendance.openSessionsForManager(await this.authorizeManagerClose(authorization, companyId), input.data)); }
  // Employee access is protected solely by the dedicated PIN policy. Without
  // these skips, the generic ERP-login budgets also count every PWA request
  // and can lock a valid employee out after unrelated admin sign-in attempts.
  @Post('record') @HttpCode(201) @UseGuards(ThrottlerGuard) @SkipThrottle({ authIp: true, authIdentity: true, report: true, output: true, fileWrite: true }) @Throttle({ attendancePin: { limit: 12, ttl: 60_000, blockDuration: 15 * 60_000 } }) async record(@Body() body: unknown) { const input = attendanceEmployeeRecordRequestSchema.safeParse(body); if (!input.success) throw new BadRequestException('Invalid attendance record.'); return attendanceEmployeeRecordReceiptSchema.parse(await this.attendance.recordFromEmployee(input.data)); }
  @Post('portal/session') @HttpCode(201) @UseGuards(ThrottlerGuard) @SkipThrottle({ authIp: true, authIdentity: true, report: true, output: true, fileWrite: true }) @Throttle({ attendancePin: { limit: 6, ttl: 60_000, blockDuration: 15 * 60_000 } }) async employeePortalSession(@Body() body: unknown) { const input = attendanceEmployeePortalSessionRequestSchema.safeParse(body); if (!input.success) throw new BadRequestException('Invalid employee portal access.'); return attendanceEmployeePortalSessionReceiptSchema.parse(await this.attendance.createEmployeePortalSession(input.data)); }
  @Get('portal/profile') @UseGuards(ThrottlerGuard) @SkipThrottle({ authIp: true, authIdentity: true, report: true, output: true, fileWrite: true }) @Throttle({ attendancePin: { limit: 30, ttl: 60_000, blockDuration: 60_000 } }) async employeePortalProfile(@Headers('authorization') authorization?: string) { const accessToken = /^Bearer\s+(.+)$/i.exec(authorization ?? '')?.[1]; if (!accessToken) throw new BadRequestException('Employee portal access token is required.'); return attendanceEmployeePortalSessionReceiptSchema.shape.profile.parse(await this.attendance.employeePortalProfile(accessToken)); }
  private async authorize(authorization: string | undefined, companyId: string | undefined) {
    // HTTP clients send `Authorization: Bearer <token>`, whereas the company
    // context verifies the raw signed token. Passing the whole header made
    // every attendance request look unauthenticated and triggered the web
    // client's expired-session recovery.
    const accessToken = /^Bearer\s+(.+)$/i.exec(authorization ?? '')?.[1];
    const access = await this.companyContext.authorize({
      accessToken: accessToken ?? '',
      companyId: companyId ?? '',
      requiredCapabilities: MANAGE,
    });
    const context = {
      tenantId: access.principal.tenantId,
      companyId: access.company.id,
      actorUserId: access.principal.userId,
    };
    await this.attendance.assertManagementAuthority(context);
    return context;
  }
  private async authorizeManagerClose(authorization: string | undefined, companyId: string | undefined) {
    const accessToken = /^Bearer\s+(.+)$/i.exec(authorization ?? '')?.[1];
    const access = await this.companyContext.authorize({ accessToken: accessToken ?? '', companyId: companyId ?? '', requiredCapabilities: MANAGE });
    const context = { tenantId: access.principal.tenantId, companyId: access.company.id, actorUserId: access.principal.userId };
    await this.attendance.assertManagerCloseAuthority(context);
    return context;
  }
}
